/* Generated by cgen, seed=112 */

int g0;
int g1 = 48;
unsigned long g2 = 3772;

unsigned long f0(void);

unsigned long f0(void)
{
    int v0_0;
    int v0_1;
    int v0_2;
    int v0_3;
    v0_0 = 0;
    v0_1 = 1;
    v0_2 = -2;
    v0_3 = 0;

    {
        int _w0;
        _w0 = 0;
        while (_w0 < 10) {
            _w0++;
            v0_2 %= ((((v0_1 ? "world"[2] : '7'), ((int)sizeof(unsigned char) < g1)) ^ ((g2 % ((int)sizeof(int) | 1)) - (83 | g0))) | 1);
        }
    }
    if ((((-42 == (int)sizeof(int)) > (-19 ^ 0)) >> (2))) {
        v0_1 |= (((v0_1 ^ 9748) % ((g2 | 6) | 1)) != ((1804 < "world"[4]) != ("barY"[2] || g1)));
    }
    return (v0_2);
}

int main(void)
{
    int result;
    unsigned long m0;
    unsigned char m1;
    long m2;
    unsigned long m3;
    unsigned long m4;
    unsigned int m5;
    long m6;
    unsigned int m7;
    result = 0;
    m0 = 1;
    m1 = 1;
    m2 = 1;
    m3 = 65;
    m4 = 1202;
    m5 = 1;
    m6 = 0;
    m7 = 0;

    {
        int _f1;
        for (_f1 = 0; _f1 < 1; _f1++) {
            m7 &= (((m1 + 68) << (3)) << (14));
        }
    }
    switch ((f0() == ((62 && g1) ? (result && m7) : f0()))) {
    case 1:
        {
            if ((m4 * m7)) {
                m3 += (result == 4563);
            }
            f0();
        }
        break;
    default:
        m3 |= f0();
        break;
    }
    {
        m3 /= ((((45 ? 1741 : -39) ? ('Y' >> (8)) : (g2 || "barY"[1])) != ((m2 - 'e') >> (0))) | 1);
        m1 /= ((((m4 != 55) << (1)), f0()) | 1);
    }

    result = 0;
    result += (int)(m2);
    result += (int)f0();

    return (result >= 0 ? result : -result) & 255;
}
