/* Generated by cgen, seed=99 */

struct S0 {
    char m0;
    char m1;
    int m2;
    unsigned long m3;
    unsigned int m4;
    unsigned int m5;
};

struct S1 {
    unsigned char m0;
    int m1;
    unsigned int m2;
    unsigned long m3;
    unsigned long m4;
    unsigned int m5;
};

struct S2 {
    unsigned char m0;
    char m1;
};

int g0[8];

unsigned int f0(char p0);
char f1(unsigned char p0, long p1, char p2, int p3);
unsigned long f2(void);
int f3(void);

unsigned int f0(char p0)
{
    char * v0_0;
    v0_0 = 0;

    {
        int _w0;
        _w0 = 0;
        while (_w0 < 10) {
            _w0++;
            {
                int _f1;
                for (_f1 = 0; _f1 < 10; _f1++) {
                    p0 *= ((g0[7] ^ 0) / (((int)sizeof(unsigned int) ? p0 : p0) | 1));
                }
            }
        }
    }
    switch ((((p0 % ('p' | 1)) != (86, -17)) >> (3))) {
    case 4:
        p0 -= (((p0 << (25)) ^ (1 && 26)) != (('0' ? p0 : ',') << (0)));
        break;
    case 5:
        {
            int _d2;
            _d2 = 0;
            do {
                _d2++;
                if ((65 > p0)) {
                    p0 &= (g0[3] > 13);
                } else {
                    p0 /= ((p0 / (p0 | 1)) | 1);
                    if (p0) {
                        p0 -= 'f';
                        p0 %= ('L' | 1);
                    } else {
                        p0 /= (p0 | 1);
                        p0 %= (p0 | 1);
                    }
                    p0 *= ((int)sizeof(unsigned long) / ((int)sizeof(long) | 1));
                }
                {
                    int _d3;
                    _d3 = 0;
                    do {
                        _d3++;
                        if (-21) {
                            p0 %= (g0[4] | 1);
                            p0 &= (int)sizeof(unsigned char);
                        }
                        p0 %= ((p0 ? p0 : g0[7]) | 1);
                    } while (_d3 < 3);
                }
            } while (_d2 < 3);
        }
        break;
    }
    v0_0 = &p0;
    *v0_0 = ((((p0 - 5670) ? (p0 > 1) : (p0 % (g0[4] | 1))) ^ ((1, 24), (p0 < -20))), (((-2 ? 53 : p0) ? (g0[0], g0[5]) : (1761 != 0)) && ((g0[7] % ("fooX"[3] | 1)) == (p0 + g0[7]))));
    p0 %= ((((((int)sizeof(unsigned int) | p0) ^ (p0 ? p0 : 7025)) << (16)) % (((((int)sizeof(char) ? p0 : 34) != (p0 ? p0 : "world"[0])) % ((((int)sizeof(long), -48), (240 < g0[5])) | 1)) | 1)) | 1);
    v0_0 = &p0;
    *v0_0 = ((((g0[4] ? p0 : p0) ? (p0 != '`') : (p0 ? p0 : 0)) < ((g0[7], p0) && (1 % (23 | 1)))) ^ (((g0[0] / ("barY"[0] | 1)) || (p0 || g0[4])), ((p0 % (1 | 1)) ? ((int)sizeof(char) | 11) : (-40 ^ p0))));
    {
        int _f4;
        for (_f4 = 0; _f4 < 2; _f4++) {
            {
                int _f5;
                for (_f5 = 0; _f5 < 4; _f5++) {
                    p0 |= ((p0 & g0[5]) - (41 == 5377));
                }
            }
            p0 = ((("hello"[0] % ("world"[2] | 1)), ((int)sizeof(char) > 92)) ? ((p0 * p0) > (p0 && p0)) : ((p0 / (p0 | 1)) ? ('i' ? p0 : 79) : ("fooX"[0], "test"[2])));
            (((p0 - p0) | (p0 | p0)), ((p0 % ((int)sizeof(int) | 1)), (96 + (int)sizeof(long))));
        }
    }
    {
        int _f6;
        for (_f6 = 0; _f6 < 4; _f6++) {
            {
                int _d7;
                _d7 = 0;
                do {
                    _d7++;
                    v0_0 = &p0;
                } while (_d7 < 7);
            }
        }
    }
    p0 %= (((((117 ? (int)sizeof(unsigned int) : 1) << (18)) ^ ((p0 * p0) | ((int)sizeof(unsigned long) ? g0[3] : (int)sizeof(int)))) - ((('{' | g0[3]) ? (1 < 78) : (p0 ^ -29)) & (("fooX"[3] % ('k' | 1)) / ((p0 | 1) | 1)))) | 1);
    {
        int _d8;
        _d8 = 0;
        do {
            _d8++;
            p0 += ((("barY"[0] / (p0 | 1)) != (p0 % (173 | 1))) + (("abcd"[1] >> (12)) << (20)));
        } while (_d8 < 3);
    }
    p0 -= (((('"' * 8368) != (1 || 'c')) ? ((197, (int)sizeof(char)) % ((p0 || p0) | 1)) : ((p0 == 'Q') > (1 + g0[7]))) / ((((p0 >> (26)), (p0 ^ "hello"[3])) * ((0 + -19), (p0 ? g0[7] : p0))) | 1));
    return (p0);
}

char f1(unsigned char p0, long p1, char p2, int p3)
{
    int v1_0;
    v1_0 = 5999;

    p3 /= (((((v1_0 % (p2 | 1)), (-20 + p0)), (((int)sizeof(unsigned int) >> (23)) * (g0[1], v1_0))) / ((f0((p3 | -34)) * ((p3, v1_0) ? (158 ? p2 : ']') : (48 ^ 67))) | 1)) | 1);
    {
        int _f9;
        for (_f9 = 0; _f9 < 10; _f9++) {
            (f0((g0[1] | p2)) ? f0((249 ? p2 : p0)) : ((g0[7] >> (8)) ? ("hello"[4] + g0[1]) : (g0[7] == p2)));
        }
    }
    f0((((p0 < v1_0) ^ ("fooX"[1] || '6')) ^ ((p3 > p3), (p1 == g0[7]))));
    {
        {
            int _d10;
            _d10 = 0;
            do {
                _d10++;
                v1_0 &= ((p3 ? -21 : p0), (v1_0 ? "abc123"[0] : '1'));
            } while (_d10 < 9);
        }
    }
    v1_0 *= (((('G' ? p2 : "abcd"[1]), (v1_0 & 0)), ((v1_0 ^ p2) > (v1_0 % (p3 | 1)))) == (((v1_0 ? (int)sizeof(unsigned int) : p2) && (g0[7], p1)) < (f0(g0[0]) * (p1 ? p1 : '`'))));
    return (p3);
}

unsigned long f2(void)
{
    unsigned int v2_0;
    char v2_1[9];
    int v2_2[9];
    unsigned int v2_3;
    v2_0 = 200;
    v2_1[0] = 4233;
    v2_2[0] = 0;
    v2_3 = 96;

    v2_0 *= ((((-43 % (v2_3 | 1)) < ("barY"[1] - 1)) ? ((g0[7] | v2_0) - ("world"[3] * v2_3)) : (("fooX"[1], 4078) ? (0 ? v2_0 : 0) : (-37 << (14)))) < (((v2_0 * g0[1]) % (("test"[0] / (v2_3 | 1)) | 1)) - (f0('A') < (1 < v2_3))));
    v2_0 /= (((((v2_0 & v2_3), ('V', v2_3)) ? ((v2_1[7] ? v2_0 : (int)sizeof(int)) % ((-30 & -30) | 1)) : (f1(12, "fooX"[0], -47, (int)sizeof(unsigned char)) & (v2_3, g0[2]))) && (((v2_0 == v2_0) ? (v2_3 * v2_0) : ((int)sizeof(int), (int)sizeof(unsigned int))) > f1((216 ? v2_2[0] : 1), (v2_3 ^ 14), ((int)sizeof(long) ? v2_1[4] : v2_0), (-34 / (v2_0 | 1))))) | 1);
    v2_1[4] = (((f1(v2_0, 1, v2_3, 60) != ((int)sizeof(long) & g0[1])) >> (16)) ? ((((int)sizeof(char) ? 7899 : v2_0) / (f0('6') | 1)) - ((v2_3, 0) - (v2_3 | 85))) : ((f1(2294, v2_1[7], g0[2], v2_3) == (59, "world"[3])) + (('[' - v2_0) ^ ("test"[3] > v2_2[7]))));
    v2_1[5] = ((f0((v2_0 > 0)) * ((5287 ? 'j' : 8344) ? (v2_3 > v2_3) : (v2_3 & 0))) > ((((int)sizeof(unsigned long) + (int)sizeof(char)) - (v2_3, v2_3)) != (((int)sizeof(char), '8') + (0 * "abc123"[0]))));
    v2_2[8] = (f0(((v2_0, -45), ("abcd"[0] > '@'))) ? (f1(f1('j', 252, 0, v2_3), (43 != '0'), ('o' < 33), (v2_3 * "abcd"[0])) ? (f1(v2_2[2], "abc123"[1], v2_3, 'H') < ((int)sizeof(unsigned int) + "wxyz"[1])) : (("abcd"[1], (int)sizeof(unsigned char)) ? (7348 ? 14 : 93) : (v2_0 << (29)))) : (((22 << (21)) | f1('V', (int)sizeof(unsigned char), "test"[1], (int)sizeof(long))) << (4)));
    return (v2_3);
}

int f3(void)
{
    unsigned int v3_0;
    v3_0 = 0;

    goto _lbl11;
    _lbl11:
    v3_0 |= ((((v3_0 - v3_0) ? (v3_0 + 'Y') : (0, 4345)) != ((-37 != 1) > f1(g0[2], (int)sizeof(int), 4804, v3_0))) < (((g0[0] && v3_0) ? (v3_0 % ((int)sizeof(long) | 1)) : (v3_0 / (v3_0 | 1))) ? ((0 ? 15 : v3_0) != ((int)sizeof(char) > 1)) : f0(f2())));
    return (v3_0);
}

int main(void)
{
    int result;
    int * m0;
    unsigned char m1;
    char m2[7];
    int m3;
    result = 0;
    m0 = 0;
    m1 = 91;
    m2[0] = 0;
    m3 = 1;

    g0[6] = ((((22 & -25) | f1(result, "fooX"[0], "hello"[1], 68)), f0((m1 && m1))) ? (((190 == 75) * ("barY"[1], "abcd"[1])) > ((m1 - g0[6]) > (0 ? m1 : m1))) : (((m2[3] - m1) || ((int)sizeof(unsigned char), -48)) / (((-23 ? 67 : 'n') < f1(1, (int)sizeof(long), m2[1], "barY"[0])) | 1)));
    m1 -= (((("abc123"[1] % (m3 | 1)) / (("world"[1] < 'W') | 1)) ? ((m1 - (int)sizeof(unsigned int)), ("abcd"[0] == (int)sizeof(unsigned long))) : ((1 % (m3 | 1)), f1(m2[1], m3, result, 0))) == ((((int)sizeof(char) || (int)sizeof(int)) && (g0[5] < 't')) + (('4' << (14)) ? ('z' ^ 0) : (m2[5] == 'h'))));
    m3 *= (((((int)sizeof(long) ? "hello"[4] : 1) << (6)) > ((1 || m3) && (m3 + result))) - ((f0(-42) % ((1 == m1) | 1)) != (f0(m1) % (((int)sizeof(long) == result) | 1))));
    m1 /= (((((m1 | result) + f2()) ? (('=' | -32) == f3()) : (("wxyz"[0] / ('e' | 1)) ? (m3 != "test"[3]) : f1('D', m3, m3, m1))) ^ ((((int)sizeof(char) - 5192) == (result % (result | 1))) - f2())) | 1);
    {
        int _w12;
        _w12 = 0;
        while (_w12 < 2) {
            _w12++;
            m2[6] = ((("wxyz"[2] > g0[2]), (result + result)) == ((192 * m1) * f0(1)));
        }
    }
    m3 &= (f2() / (((("wxyz"[0] >> (27)) < (1 % (1 | 1))) & ((m3, "world"[1]) / (('(' / (result | 1)) | 1))) | 1));
    switch (f1(((result + -15) == (71 ? 'H' : (int)sizeof(long))), ((-5 >> (8)) == (m3 | '+')), f2(), (f1(-49, 1, m2[3], m3) ^ (m3 & m3)))) {
    case 3:
        m2[6] = ((f2() ? f1(m1, (int)sizeof(unsigned long), -18, result) : ((int)sizeof(unsigned char) | m3)) / (((70 + '%') ^ f2()) | 1));
        break;
    case 8:
        {
            int _f13;
            for (_f13 = 0; _f13 < 3; _f13++) {
                m2[1] = (((int)sizeof(unsigned char) < -4) ^ (m1 % (m2[1] | 1)));
            }
        }
        break;
    case 13:
        {
            int _f14;
            for (_f14 = 0; _f14 < 2; _f14++) {
                {
                    int _w15;
                    _w15 = 0;
                    while (_w15 < 5) {
                        _w15++;
                        m1 *= (0 || 87);
                    }
                }
                m0 = &result;
                *m0 = ((m2[0] - m1) / ((21 && 1) | 1));
            }
        }
        switch (f0(((int)sizeof(unsigned char) ^ '@'))) {
        case 4:
            switch (f2()) {
            case 1:
                m1 /= (('"' << (4)) | 1);
                break;
            case 8:
                result *= f1(m1, m3, m3, '*');
                m1 -= (result < 7867);
                break;
            case 10:
                switch (result) {
                case 2:
                    m3 = result;
                    break;
                case 8:
                    result += '4';
                    break;
                case 14:
                    result -= "fooX"[0];
                    break;
                }
                break;
            case 18:
                m1 /= (f1(result, -8, "hello"[3], m1) | 1);
                break;
            }
            break;
        case 5:
            m0 = &m3;
            break;
        case 13:
            {
                int _d16;
                _d16 = 0;
                do {
                    _d16++;
                    m3 += (m2[3] != 151);
                } while (_d16 < 4);
            }
            break;
        default:
            switch (('i' ? 'A' : m3)) {
            case 0:
                result |= f2();
                break;
            case 5:
                if (0) {
                    m1 /= ('"' | 1);
                }
                break;
            case 13:
                m3 = (m3 & m2[6]);
                break;
            }
            break;
        }
        break;
    default:
        goto _lbl17;
        _lbl17:
        break;
    }
    goto _lbl18;
    _lbl18:
    if (f0((('5' << (2)), f1((int)sizeof(unsigned char), -34, 9111, result)))) {
        {
            int _f19;
            for (_f19 = 0; _f19 < 2; _f19++) {
                {
                    int _d20;
                    _d20 = 0;
                    do {
                        _d20++;
                        result = (m2[2] ? m3 : m2[5]);
                    } while (_d20 < 1);
                }
            }
        }
        {
            int _d21;
            _d21 = 0;
            do {
                _d21++;
                {
                    int _w22;
                    _w22 = 0;
                    while (_w22 < 5) {
                        _w22++;
                        result %= ((-39 << (1)) | 1);
                        if (m2[2]) {
                            result /= (m2[3] | 1);
                        } else {
                            m1 -= m1;
                            m1 += m3;
                        }
                    }
                }
                ((3525 == result) % ((m3 + m3) | 1));
            } while (_d21 < 8);
        }
    }

    result = 0;
    result += (int)(m1);
    result += (int)f2();
    result += (int)f0(((140 == 1) * (result ? -19 : m3)));

    return (result >= 0 ? result : -result) & 255;
}
