/* Generated by cgen, seed=343 */

struct S0 {
    char m0;
    unsigned char m1;
    unsigned char m2;
    unsigned int m3;
    unsigned int m4;
    unsigned char m5;
};

struct S1 {
    char m0;
    unsigned char m1;
};

struct S2 {
    unsigned long m0;
    unsigned char m1;
};

struct S3 {
    unsigned char m0;
    char m1;
    unsigned char m2;
};

struct S4 {
    unsigned long m0;
    long m1;
};

long g0;
int g1[2];
char g2 = 6177;
unsigned int g3 = 74;
int g4 = 1596;

unsigned int f0(long p0, unsigned long p1, int p2, unsigned char p3);
long f1(char p0);
unsigned long f2(char p0, unsigned int p1, char p2);
char f3(int p0, int p1, unsigned long p2);
int f4(char p0, unsigned long p1, unsigned long p2, unsigned char p3, unsigned int p4);
char f5(void);

unsigned int f0(long p0, unsigned long p1, int p2, unsigned char p3)
{
    int v0_0;
    int v0_1[3];
    int * v0_2;
    long v0_3;
    char v0_4[16];
    v0_0 = 0;
    v0_1[0] = 0;
    v0_2 = 0;
    v0_3 = 1;
    v0_4[0] = 1;

    v0_2 = &p0;
    ((((g0 * "fooX"[3]) / (((int)sizeof(unsigned char), g3) | 1)) > (("world"[0] + v0_3), (0 & g1[0]))) | ((((int)sizeof(char) - g2) && ('y' >> (13))) ? (((int)sizeof(unsigned int) ^ "world"[4]) % ((p3 || "abcd"[0]) | 1)) : ((105 ^ v0_0) - (0 / (1 | 1)))));
    v0_1[0] = ((((0 >> (11)) << (8)) + ((p0 != p1) > (1 >> (20)))) << (26));
    goto _lbl0;
    _lbl0:
    p0 += ((((1 - p1) ? (0 ? v0_0 : g1[1]) : (13 ^ 9032)), ((v0_0 ? v0_3 : p2) - (v0_0 == v0_3))) < (((g1[1] - 29) * (1 || g0)) + ((59 || "hello"[3]) >> (6))));
    switch ((((v0_3, p1) < (0 ? p3 : p0)) / (((0 == v0_1[0]), ("fooX"[1] ? 91 : g0)) | 1))) {
    case 2:
        v0_1[2] = (((g1[1] || v0_4[13]) || ('B' << (11))) ? ((g2 | g4) >> (14)) : (("world"[3] ^ 93) / (('o' ? '?' : v0_1[0]) | 1)));
        break;
    }
    return (g2);
}

long f1(char p0)
{
    char * v1_0;
    int v1_1[11];
    long v1_2;
    char * v1_3;
    v1_0 = 0;
    v1_1[0] = 22;
    v1_2 = 9454;
    v1_3 = 0;

    v1_0 = &g4;
    *v1_0 = ((((18 + 9), ((int)sizeof(char) && g3)) ? (("world"[3] & 0) << (8)) : (((int)sizeof(unsigned char) / ('X' | 1)) ^ (197 ? v1_1[5] : p0))) == (f0((1 ? g4 : (int)sizeof(char)), (']' % (v1_1[1] | 1)), ("abcd"[2] % (0 | 1)), (1 ? -14 : "abc123"[4])) * f0(f0(v1_2, 0, g0, "abcd"[1]), f0(g2, g4, 51, (int)sizeof(unsigned int)), (p0, p0), (1 * g4))));
    {
        int _d1;
        _d1 = 0;
        do {
            _d1++;
            v1_0 = &g4;
        } while (_d1 < 3);
    }
    return (g0);
}

unsigned long f2(char p0, unsigned int p1, char p2)
{
    unsigned int v2_0;
    char * v2_1;
    v2_0 = 0;
    v2_1 = 0;

    g4 -= ((((v2_0 < 85) || (' ', p2)) ? (('H' * (int)sizeof(long)) << (13)) : ((-35 ^ 'P') == ((int)sizeof(char), (int)sizeof(char)))) / (((f1(g4) < (8060 < g3)) + ((g1[1] > -17) % ((p2 + 6369) | 1))) | 1));
    v2_1 = &v2_0;
    *v2_1 = (((((int)sizeof(int) != 1) / ((g2 == g4) | 1)) % ((('H' + g0) >> (10)) | 1)) || (((11 ^ "wxyz"[3]) * ('m' % (0 | 1))), ((0, 33) || (3172 >> (22)))));
    return (g4);
}

char f3(int p0, int p1, unsigned long p2)
{
    unsigned char v3_0;
    struct S2 v3_1;
    int * v3_2;
    v3_0 = 45;
    v3_1.m0 = 1;
    v3_1.m1 = 0;
    v3_2 = 0;

    goto _lbl2;
    _lbl2:
    g1[1] = ((((v3_0 ? "abc123"[5] : '+') ? ("abc123"[2] ? 1 : 6131) : (v3_0 ^ 't')) * ((-30 != p1) / ((g1[0] ? g3 : 1) | 1))) % ((((p2 ? (int)sizeof(long) : "barY"[1]), (-27 % ("wxyz"[3] | 1))), ((p0 < "abc123"[2]) ? ('N', 1) : (47 && 'x'))) | 1));
    switch (((f1(p1) / ((7325 ^ 0) | 1)) != ((g4, "test"[1]) / ((p2, "test"[0]) | 1)))) {
    case 2:
        v3_0 |= (((g4 != (int)sizeof(int)) ? ("hello"[4] > 0) : (0 * g1[1])) ? ((0 << (23)) & ('E' ? g1[0] : g0)) : ((-13 ? 67 : p1) ? (p1, 1) : ('?' | g2)));
        break;
    case 7:
        if ((('u' != "test"[2]) > (-25 - g4))) {
            g0 &= ((g3 || g1[1]) | (v3_0 > 1));
            {
                int _f3;
                for (_f3 = 0; _f3 < 1; _f3++) {
                    g4 |= (-18 == 38);
                }
            }
        } else {
            switch ((g1[0] && g2)) {
            case 2:
                g2 -= (g3, p2);
                break;
            }
        }
        break;
    }
    p2 += f1(f0((('E' > ' ') + (8860 ? 242 : 156)), (('n' & p1) ? ('-' - "hello"[2]) : (g3 == 'o')), ((-29 ? '~' : "hello"[2]) ? (g1[0] % (g1[0] | 1)) : (53 * g1[0])), ((38 >> (8)) ? (g3 | (int)sizeof(int)) : (g0 + -37))));
    return (p0);
}

int f4(char p0, unsigned long p1, unsigned long p2, unsigned char p3, unsigned int p4)
{
    long v4_0;
    unsigned int v4_1;
    char * v4_2;
    struct S1 v4_3;
    v4_0 = 0;
    v4_1 = 89;
    v4_2 = 0;
    v4_3.m0 = -35;
    v4_3.m1 = -6;

    (((((int)sizeof(char) >> (12)) | (g4 < 167)) || ((-6 * g3) == (1 | (int)sizeof(long)))) >> (30));
    return (p1);
}

char f5(void)
{
    unsigned char v5_0;
    unsigned int v5_1;
    v5_0 = 91;
    v5_1 = 0;

    g4 *= (((((int)sizeof(unsigned long) ^ g4) * (g0 ^ v5_1)) != (("fooX"[0] ? g3 : -23) && (2730 && -9))) - f3(f2((g1[0] | 1), (g1[0] / ('+' | 1)), (g0 > g2)), ((75 && (int)sizeof(long)) & (g0 % (7407 | 1))), ((87, (int)sizeof(long)) ? (g2 ^ v5_1) : (v5_0 ? g3 : v5_1))));
    g3 &= ((f4((g2 || (int)sizeof(long)), (g3, 21), f1(g3), (v5_0 ? "abcd"[2] : 1), (g3 > 194)) ? (((int)sizeof(char), 6678) ? ("abc123"[5] != (int)sizeof(unsigned int)) : ((int)sizeof(unsigned char), 1)) : ((v5_0 >> (6)) < (0 * (int)sizeof(unsigned int)))) < (((g3 | g4) > (52 ^ v5_0)) > ((1 == g4) - ((int)sizeof(unsigned int) - g1[0]))));
    goto _lbl4;
    _lbl4:
    g0 %= (((((v5_1 != (int)sizeof(unsigned long)) ? (g1[0] ^ v5_1) : (g3, g2)) * ((1 && 36) << (16))) && (((44 + v5_1) ? (g4 + v5_1) : (16 == '{')) != ((4160, g1[1]) < (g4 ? v5_0 : 'T')))) | 1);
    goto _lbl5;
    _lbl5:
    return (g0);
}

int main(void)
{
    int result;
    unsigned int m0;
    result = 0;
    m0 = 8146;

    g3 -= (((("test"[1] | 1) != (m0 << (30))) - (("fooX"[3] || ']') < (g0 % (m0 | 1)))) != ((f1(')') < ('{', g4)), ((result ? m0 : "abc123"[3]) / ((g4 % (result | 1)) | 1))));
    {
        int _f6;
        for (_f6 = 0; _f6 < 10; _f6++) {
            (((-34 >> (12)) / (f2(g4, -17, result) | 1)) == f4((26 != 99), ('V' ? 0 : "abc123"[5]), (m0 >> (9)), (result ? "world"[3] : g4), (g0 / (g0 | 1))));
        }
    }
    result -= ((f0(((int)sizeof(int) - "hello"[3]), ("world"[3] / ("world"[1] | 1)), f2(m0, g3, 949), (g0 > g1[0])), ((0 < (int)sizeof(int)) != (-30 > 1))) >> (0));

    result = 0;
    result += (int)(g3);
    result += (int)(g4);
    result += (int)(g2);
    result += (int)f2((f5() - (result == 0)), (("wxyz"[2] & 9879) * (result | g4)), (f3((int)sizeof(int), (int)sizeof(unsigned int), 4840) << (15)));

    return (result >= 0 ? result : -result) & 255;
}
