/* Generated by cgen, seed=419 */

int g0[7];
int g1[7];
int g2[9];

unsigned char f0(char p0, unsigned long p1, unsigned char p2);

unsigned char f0(char p0, unsigned long p1, unsigned char p2)
{
    char v0_0;
    v0_0 = 7406;

    {
        p2 += ((('5' != p0) == (-39 - 0)) - ((p0 / (p2 | 1)) || ("fooX"[2] || '7')));
        p0 %= ((((1 < "abcd"[2]) != (p1 != g2[5])) | ((2916 / (v0_0 | 1)) & (-27 & p2))) | 1);
    }
    switch ((((v0_0 != -5) | (p2 - p2)) | (((int)sizeof(unsigned long) != '|') > (p0 % (197 | 1))))) {
    case 1:
        if (((p0 << (23)) ? ((int)sizeof(unsigned int) ? p1 : "abcd"[3]) : ('a' | p2))) {
            p0 -= ((-14 && -47) || (p2 - 1));
        }
        break;
    }
    p1 *= ((((p1, p2), (122 % ('~' | 1))) ? ((p2, '*') & (-40, "abcd"[3])) : ((0, v0_0) * (426 != 7994))) ? ((((int)sizeof(unsigned long) + p2), ('t' < "hello"[2])) | ((7761, 1) & (p1 || p0))) : (((p2 - 2050) == (p2 > g0[3])) / (((v0_0 >> (1)) & (1489 & -40)) | 1)));
    return (v0_0);
}

int main(void)
{
    int result;
    unsigned long m0;
    int m1;
    unsigned char m2;
    int m3;
    char * m4;
    char * m5;
    result = 0;
    m0 = 100;
    m1 = 117;
    m2 = 6746;
    m3 = 24;
    m4 = 0;
    m5 = 0;

    result &= ((((result ^ '^') ^ f0(m0, "fooX"[1], g2[5])) ? ((g1[3] && 28) ? ((int)sizeof(unsigned int) | 1714) : (1 & g0[1])) : (("abcd"[1] >> (28)) | (8481 ? 4 : (int)sizeof(long)))) - f0(((m1 ? 232 : 3464) == (-7 - result)), f0(((int)sizeof(unsigned long) < (int)sizeof(long)), (g2[4] % ("test"[0] | 1)), (g0[1] << (30))), (("abcd"[0] * m2) - f0(m3, m1, "abcd"[3]))));

    result = 0;
    result += (int)(m3);
    result += (int)f0(((result ^ m3) ^ (m0 & 1)), (('G' >> (13)) && (m0 & m1)), (("world"[1] | g0[6]) ? ('Z' == m0) : (m1 != g2[0])));
    result += (int)f0((f0((int)sizeof(unsigned int), ']', m1), ('W' == -47)), (("fooX"[0] << (12)) == ((int)sizeof(int) < m1)), ((m3 ^ m2), ((int)sizeof(char) / ((int)sizeof(long) | 1))));

    return (result >= 0 ? result : -result) & 255;
}
