/* Generated by cgen, seed=396 */

struct S0 {
    int m0;
    unsigned char m1;
    unsigned char m2;
    long m3;
    unsigned int m4;
    long m5;
};

struct S1 {
    char m0;
    int m1;
    unsigned long m2;
    unsigned long m3;
    unsigned char m4;
};

struct S2 {
    char m0;
    unsigned int m1;
};

struct S3 {
    unsigned int m0;
    long m1;
    unsigned long m2;
};

struct S4 {
    int m0;
    unsigned int m1;
    char m2;
    unsigned int m3;
    unsigned char m4;
};

struct S5 {
    unsigned long m0;
    char m1;
    unsigned char m2;
};

struct S6 {
    unsigned int m0;
    unsigned long m1;
};

unsigned int g0;

unsigned int f0(unsigned long p0, int p1, int p2, unsigned long p3);
char f1(unsigned long p0, unsigned long p1, long p2);
char f2(long p0, unsigned long p1);
unsigned int f3(long p0, unsigned char p1, unsigned char p2);
unsigned char f4(void);
unsigned long f5(unsigned int p0);
unsigned long f6(unsigned char p0, char p1);
unsigned long f7(void);

unsigned int f0(unsigned long p0, int p1, int p2, unsigned long p3)
{
    unsigned int v0_0;
    v0_0 = 0;

    {
        int _f0;
        for (_f0 = 0; _f0 < 5; _f0++) {
            g0 |= (((2246 | 41) ? ((int)sizeof(long) / (-36 | 1)) : ((int)sizeof(unsigned int) << (3))) * (("abcd"[1] & v0_0) > (95, 3847)));
            p3 /= ((((113 / (-40 | 1)) ? (38 & g0) : (158 ? 'G' : g0)) & ((-29 ? (int)sizeof(int) : 164) ? ("abcd"[3] < g0) : (p0 > g0))) | 1);
        }
    }
    g0 %= ((((('+' + -19) >> (0)) & ((p2 - -6) & (37 ? (int)sizeof(unsigned char) : "world"[1]))) ^ (((1 | 1) || (p3 < 52)) ? ((p1 % (v0_0 | 1)) ? (p1 != 'N') : (p3 ^ 0)) : ((0 ^ 'x') << (4)))) | 1);
    p1 &= ((((-35 && p3), (p0 % ((int)sizeof(unsigned long) | 1))) << (22)) / ((((p2 ? "hello"[0] : 1) * (p0 | v0_0)) - ((v0_0 != (int)sizeof(unsigned char)) ? ("fooX"[3] ? p2 : p2) : (p0 - 222))) | 1));
    goto _lbl1;
    _lbl1:
    g0 %= (((((p0 ^ 4053) && (9799 ? 'G' : g0)) && ((p1 || '?') - (51 ? 71 : p1))) ? ((("barY"[1] >> (18)) ? (93 ? 48 : (int)sizeof(unsigned int)) : ('2' ? 156 : 1)) >> (15)) : (((g0 / (v0_0 | 1)) ^ ('_' != g0)) != ((g0 < (int)sizeof(int)) ? (g0 < g0) : (1 ? 151 : 66)))) | 1);
    {
        int _f2;
        for (_f2 = 0; _f2 < 5; _f2++) {
            {
                int _w3;
                _w3 = 0;
                while (_w3 < 2) {
                    _w3++;
                    p3 = ((v0_0 < g0) + (p3 < p0));
                    p3 *= ((p0 % ('2' | 1)), (1 || 'V'));
                    {
                        p2 -= ("wxyz"[2] - 8531);
                        if ((int)sizeof(char)) {
                            p1 &= 1;
                        }
                    }
                }
            }
        }
    }
    g0 %= (((((1 ? p3 : p1) / (("hello"[0], 0) | 1)) > (("hello"[2], (int)sizeof(unsigned char)) > (v0_0 - p3))) - (((57 / (',' | 1)), (-37 * 31)) << (27))) | 1);
    goto _lbl4;
    _lbl4:
    {
        int _d5;
        _d5 = 0;
        do {
            _d5++;
            p1 *= ((("world"[2] >> (9)) != (1441 < p2)) % ((((int)sizeof(long) ? "abcd"[3] : "wxyz"[0]), (p2 & 'x')) | 1));
        } while (_d5 < 3);
    }
    p3 = (((((int)sizeof(long) << (28)) < (-1 ? (int)sizeof(char) : "wxyz"[0])) | ((0 / (v0_0 | 1)) ^ (g0 & 1))), (((p3 % (p0 | 1)) % ((p3 || p3) | 1)) && ((1 + 23), (g0 ? p3 : 31))));
    p3 = ((((p0 / (p2 | 1)) != (1 ? 0 : p1)) ? ((v0_0, 0) >> (12)) : ((-43 ? g0 : g0) < (v0_0 >> (5)))) ? ((("fooX"[3] ? 1 : (int)sizeof(unsigned long)) > (p2 != p2)) > ((p1 >> (23)) ? (45 ? p0 : 0) : ((int)sizeof(unsigned char) % ((int)sizeof(unsigned char) | 1)))) : (((-23 + (int)sizeof(long)), ((int)sizeof(unsigned long) > 5656)) | ((p0 & '7') ? ('q' == p3) : ("wxyz"[3] >> (17)))));
    goto _lbl6;
    _lbl6:
    g0 = (((('+' | -35) ? (p1, 1) : (p3 & -42)) + ((p3 >> (23)) ? (p3 > 1) : (-16, p3))) ^ (((v0_0 % ((int)sizeof(long) | 1)) ? (-22 && v0_0) : (97 / (0 | 1))) * ((209 && p1) > (6723 - p3))));
    if ((((1 == -5) & (p1 != 0)) && ((32 && p3) << (12)))) {
        p0 = (((v0_0, 7576) ? (1 & 'x') : (']' ? 0 : p0)) | ((1 + 80) + (p2 != p2)));
    }
    return (p1);
}

char f1(unsigned long p0, unsigned long p1, long p2)
{
    char v1_0;
    v1_0 = 78;

    g0 %= (f0((((0 & '$') & (2051 && 213)) & (("abc123"[1], p0) ? (47 ^ 0) : f0(g0, p1, 'w', p2))), f0(((83 != 1), (p1 == '8')), f0(('o' + -23), ("hello"[4] + g0), (g0 || '+'), (-37 - g0)), ((-17 & p1) != f0(-4, -46, 7966, 1)), ((57 | ']') - ("abcd"[1] << (8)))), (((-45 ? (int)sizeof(long) : g0) & (p1 == -12)) == ((78 ? ',' : p1) == (p1 * p0))), ((f0(p2, -30, (int)sizeof(long), 189) || (p2 > p1)) > (((int)sizeof(long), p1) != (p2 >> (17))))) | 1);
    return (p1);
}

char f2(long p0, unsigned long p1)
{
    int v2_0;
    v2_0 = 1;

    g0 -= f1(f0(((p1 && 23) ^ f0(46, p1, p0, (int)sizeof(int))), ((v2_0, p1) >> (14)), ((0 * 127) >> (27)), ((g0 && g0) != (0 / (v2_0 | 1)))), (((98 == g0) == ('n' ? 0 : 1)) | (("abcd"[3] ? -20 : 1), ('i' ^ -24))), (f0((g0 & p1), ((int)sizeof(char) && 422), (252 ? 7420 : '8'), f0(p1, v2_0, 'x', 0)) || f1((1 >> (23)), (g0, p1), (p0 & (int)sizeof(long)))));
    return (v2_0);
}

unsigned int f3(long p0, unsigned char p1, unsigned char p2)
{
    unsigned int v3_0;
    unsigned int v3_1;
    char * v3_2;
    long v3_3;
    int v3_4;
    v3_0 = 0;
    v3_1 = 1;
    v3_2 = 0;
    v3_3 = 7283;
    v3_4 = -7;

    v3_2 = &v3_3;
    v3_3 *= (((('9' % (0 | 1)), (2329 % (v3_0 | 1))) % ((f2(p2, v3_3) | ((int)sizeof(unsigned char) & '+')) | 1)) * f2(((-47 ^ v3_1) >> (0)), ((193 >> (28)) + ((int)sizeof(unsigned char) && v3_4))));
    return (g0);
}

unsigned char f4(void)
{
    unsigned char v4_0;
    int v4_1[8];
    v4_0 = 0;
    v4_1[0] = 0;

    v4_0 /= ((f2((('.' ^ v4_1[0]) ? (' ' | g0) : ('c' || 45)), (((int)sizeof(unsigned int), "abcd"[3]) ? (1, (int)sizeof(unsigned char)) : (g0 << (24)))) % ((((1 - "fooX"[0]) && (v4_0, g0)) ? ((0 ? -14 : g0) % ((v4_1[4] * v4_0) | 1)) : f3((0, "wxyz"[0]), ((int)sizeof(char) ? (int)sizeof(int) : -42), (g0 < -31))) | 1)) | 1);
    g0 &= f1((((v4_1[1], 327) >> (0)) ? ((v4_0 ^ 45) - ("hello"[0] & 8819)) : f1((v4_0 != 141), (1 > 'u'), (0 >> (16)))), ((('/' ? v4_0 : v4_1[2]) + (g0 & v4_1[2])) ? ((-9 != 53), (1 >> (28))) : (f1('1', v4_0, 1) != (v4_0 - v4_0))), (f0((v4_1[7] > 1), (253 << (14)), (g0 | 11), (1 % (4379 | 1))) >> (7)));
    if (((("fooX"[0] ? (int)sizeof(char) : v4_0) - (g0 >> (19))) & (((int)sizeof(long), g0) + (v4_0 == 'G')))) {
        {
            {
                int _d7;
                _d7 = 0;
                do {
                    _d7++;
                    if (v4_0) {
                        v4_0 = g0;
                        g0 |= v4_0;
                    } else {
                        v4_0 |= "abc123"[3];
                        v4_0 += "abcd"[0];
                    }
                } while (_d7 < 5);
            }
        }
        {
            int _f8;
            for (_f8 = 0; _f8 < 3; _f8++) {
                {
                    int _d9;
                    _d9 = 0;
                    do {
                        _d9++;
                        g0 /= ((g0 == 4322) | 1);
                    } while (_d9 < 2);
                }
                ((v4_0 ? -1 : 1), f0('d', '.', (int)sizeof(char), g0));
            }
        }
        v4_1[5] = ((("test"[0], g0) == (v4_0 < "barY"[3])) ^ ((v4_0 >> (2)) - (g0 ? "test"[0] : 0)));
    } else {
        {
            int _w10;
            _w10 = 0;
            while (_w10 < 5) {
                _w10++;
                {
                    int _d11;
                    _d11 = 0;
                    do {
                        _d11++;
                        g0 &= ("fooX"[1] > v4_0);
                    } while (_d11 < 2);
                }
            }
        }
    }
    if (((('`' + 49) ? (g0 ? "fooX"[1] : v4_0) : (1 != v4_0)), ((v4_1[6] >> (7)) ? (1960 ? g0 : v4_1[0]) : (g0, g0)))) {
        {
            int _d12;
            _d12 = 0;
            do {
                _d12++;
                g0 |= ((0 && v4_0) % ((80 != v4_0) | 1));
                v4_0 &= f0((v4_0 - v4_0), ((int)sizeof(unsigned int), g0), f0('b', -24, 185, (int)sizeof(long)), (g0, "fooX"[1]));
            } while (_d12 < 4);
        }
    } else {
        if ((('U' != "hello"[2]) && ('R' == (int)sizeof(unsigned long)))) {
            goto _lbl13;
            _lbl13:
            if (((int)sizeof(long) ? v4_0 : v4_0)) {
                v4_0 &= (-24 * v4_1[1]);
            } else {
                g0 %= (((int)sizeof(unsigned int) < (int)sizeof(int)) | 1);
                v4_0 -= ((int)sizeof(char) ? g0 : '#');
            }
        } else {
            v4_1[1] = ((25 >> (10)) & ((int)sizeof(int), "wxyz"[3]));
        }
        {
            int _d14;
            _d14 = 0;
            do {
                _d14++;
                if (('Y' != g0)) {
                    v4_0 *= (-38 / (v4_1[2] | 1));
                    switch (v4_0) {
                    case 1:
                        g0 += v4_0;
                        v4_0 %= (1 | 1);
                        break;
                    case 9:
                        v4_0 &= (int)sizeof(int);
                        break;
                    case 12:
                        g0 -= v4_0;
                        break;
                    case 15:
                        g0 *= g0;
                        break;
                    case 21:
                        v4_0 /= (g0 | 1);
                        break;
                    default:
                        v4_0 += v4_0;
                        break;
                    }
                    v4_0 -= f2(6841, v4_0);
                } else {
                    switch (g0) {
                    case 3:
                        g0 *= 5343;
                        g0 += v4_0;
                        break;
                    case 6:
                        g0 += 70;
                        break;
                    case 14:
                        v4_0 &= 8511;
                        break;
                    default:
                        v4_0 |= "fooX"[3];
                        break;
                    }
                }
            } while (_d14 < 4);
        }
    }
    return (g0);
}

unsigned long f5(unsigned int p0)
{
    unsigned long v5_0;
    int v5_1;
    v5_0 = -35;
    v5_1 = 23;

    goto _lbl15;
    _lbl15:
    v5_1 |= ((((v5_1 >> (0)) != (v5_1 != "abc123"[2])) + f3((v5_1 << (24)), (2 ? (int)sizeof(int) : v5_1), (-6 & (int)sizeof(unsigned long)))) + (((1 ^ 'n') | ('0' % (p0 | 1))) * ((-3 % (1 | 1)) % ((v5_1 ^ '2') | 1))));
    switch ((((0 ? (int)sizeof(unsigned int) : 'q'), ((int)sizeof(int), g0)) % (((0 + v5_1) | ("barY"[0] ^ p0)) | 1))) {
    case 2:
        {
            int _f16;
            for (_f16 = 0; _f16 < 8; _f16++) {
                g0 |= f4();
            }
        }
        break;
    case 5:
        p0 += (((245 < 'G') & (v5_0, v5_0)) == ((v5_0 == v5_0) & (26 ? "wxyz"[3] : 0)));
        v5_0 |= (((g0 | (int)sizeof(int)) << (22)) < ((-27 | '@') ? (29 > g0) : (9799 | v5_0)));
        break;
    case 12:
        {
            int _f17;
            for (_f17 = 0; _f17 < 5; _f17++) {
                {
                    v5_1 *= (1, p0);
                }
            }
        }
        break;
    default:
        {
            int _d18;
            _d18 = 0;
            do {
                _d18++;
                {
                    int _d19;
                    _d19 = 0;
                    do {
                        _d19++;
                        g0 -= ("fooX"[0] && 138);
                    } while (_d19 < 1);
                }
            } while (_d18 < 7);
        }
        v5_1 &= (((50 << (16)), ('8' ^ (int)sizeof(unsigned long))), (f2('H', 170) + (p0, p0)));
        break;
    }
    g0 |= (((('3' + v5_1) % ((v5_1 ? p0 : 'x') | 1)) ? f4() : (('~' << (10)) < ('%' != '^'))) ? f1(((0 % (g0 | 1)) << (21)), (f0(p0, v5_1, v5_1, v5_1) != ((int)sizeof(unsigned char) != "test"[1])), f3(("hello"[4] && g0), (-44 > (int)sizeof(long)), (p0 || g0))) : (((p0 | (int)sizeof(long)) && f2(-48, 31)) | ((v5_0 ? 7101 : -36) * (100 ^ 'I'))));
    return (v5_0);
}

unsigned long f6(unsigned char p0, char p1)
{
    char v6_0[7];
    unsigned long v6_1;
    unsigned long v6_2;
    struct S3 v6_3;
    int v6_4;
    v6_0[0] = -10;
    v6_1 = 2;
    v6_2 = 0;
    v6_3.m0 = -33;
    v6_3.m1 = 5675;
    v6_3.m2 = 39;
    v6_4 = 82;

    p1 %= (((((v6_2 < (int)sizeof(int)) | f3("abc123"[3], 0, 0)), (('^' ? -50 : 6518) | (0 ? p1 : 1))) & (f4() % (((v6_4 ? 1 : 60) - f4()) | 1))) | 1);
    switch (f1(f1((v6_1 >> (9)), (0 | (int)sizeof(char)), ((int)sizeof(unsigned char) >> (18))), ((0, p1), (v6_0[5] | "hello"[3])), ((v6_4, p1) | (g0 % (126 | 1))))) {
    case 3:
        (f0(("barY"[0] != "fooX"[1]), f3(p0, 0, v6_1), ("wxyz"[1] << (22)), (g0 << (27))) >> (7));
        break;
    }
    v6_4 = ((((2522, '/') ^ (v6_2 && g0)) > f2((-27 >> (17)), (v6_4 << (9)))) >> (19));
    {
        int _w20;
        _w20 = 0;
        while (_w20 < 5) {
            _w20++;
            (((1 ? v6_4 : v6_0[4]) & (117 ? (int)sizeof(unsigned long) : 0)) * f4());
            v6_4 &= ((("hello"[0] ? v6_0[3] : v6_1) ? ("hello"[1] == -21) : (1 ? v6_2 : '-')) < ((1 ? "abc123"[0] : 'N') ? (v6_2, g0) : (v6_1 == p1)));
        }
    }
    v6_3.m0 = ((((v6_2 + 1), (v6_2 / (p1 | 1))) < ((g0 ? 'W' : 161) * (-10 || v6_4))), ((("hello"[2] || 1) / (f1(-20, p0, p0) | 1)) ? ((v6_0[3], v6_2) % (('7' % (p1 | 1)) | 1)) : (f2(v6_4, '3') < (4520 && 'R'))));
    v6_0[0] = ((((-35 % ('A' | 1)) > (1 || g0)) == ((v6_1 ? v6_0[2] : p1) * f0(39, 54, "abc123"[0], -5))) ? ((("test"[1] ? 'X' : -43) << (9)) ? (("abc123"[5] & p0) / (((int)sizeof(long) * 1) | 1)) : ((0 * 28) / ((1 >> (2)) | 1))) : (f1(("abc123"[4] | v6_2), ("abc123"[3] == 0), ('}' << (30))) < (('J' / (p1 | 1)) & (1 != p0))));
    v6_1 &= ((((v6_2 | p0) << (26)) + f1((214 ? v6_0[1] : v6_4), (6342, 170), ((int)sizeof(unsigned char) == 'm'))) ? (((1 || "wxyz"[1]) == (v6_4 > 1)) * ((1 ? v6_2 : "world"[0]) + (107, v6_4))) : (f4() ? ((61, (int)sizeof(unsigned long)) & ((int)sizeof(int), 1)) : ((38 << (23)) >> (6))));
    v6_4 += ((((1 == p1) | (v6_2 ^ 1)) != (f2(g0, v6_1) ^ (v6_0[2] || (int)sizeof(unsigned long)))) && (((g0 - '*') / (('o' != 8825) | 1)) ^ ((135 ? p0 : '?') ? (1 || 7402) : f0(p0, v6_2, "wxyz"[2], -26))));
    p1 += ((((p0 && (int)sizeof(int)) > ("wxyz"[0] ? (int)sizeof(unsigned int) : p1)) * f5((p0 ? 0 : p0))) & (((v6_2 ? 84 : v6_1) | (v6_0[6] ? p1 : 'g')) ? (('A' - -14) ? ((int)sizeof(unsigned char) & v6_2) : f0(v6_0[5], (int)sizeof(int), p0, 'S')) : (("barY"[2], p0) % ((0 ? (int)sizeof(int) : v6_4) | 1))));
    return (v6_1);
}

unsigned long f7(void)
{
    int v7_0;
    int v7_1[2];
    struct S0 v7_2;
    int * v7_3;
    int * v7_4;
    v7_0 = 11;
    v7_1[0] = 42;
    v7_2.m0 = -17;
    v7_2.m1 = 67;
    v7_2.m2 = 16;
    v7_2.m3 = 6018;
    v7_2.m4 = 68;
    v7_2.m5 = 0;
    v7_3 = 0;
    v7_4 = 0;

    v7_2.m5 = (((((int)sizeof(char) & "abcd"[2]) / (f6('8', "fooX"[3]) | 1)) < ((g0 / ((int)sizeof(unsigned int) | 1)) && (0 & v7_0))), ((((int)sizeof(unsigned long) ? 1 : 'j') + (129 << (9))) > (('J' >> (18)) << (10))));
    return (v7_0);
}

int main(void)
{
    int result;
    unsigned int m0;
    struct S5 m1;
    struct S2 m2;
    unsigned char m3;
    int * m4;
    int m5;
    result = 0;
    m0 = 2;
    m1.m0 = 0;
    m1.m1 = 6656;
    m1.m2 = 1;
    m2.m0 = -16;
    m2.m1 = 68;
    m3 = 1;
    m4 = 0;
    m5 = 21;

    m5 -= ((f5((235 ? -41 : 1)), ((1, "abc123"[0]) == ('2' ? m5 : g0))) ? ((f6(-12, result) * ('a' % (m0 | 1))) / (((0 << (5)) * (g0 | g0)) | 1)) : f6(((m5, 0) || f0(0, (int)sizeof(char), 1, "fooX"[1])), f0((1 > 0), (0 ? 7633 : 0), f2(1, g0), (-25 ? 904 : (int)sizeof(unsigned int)))));

    result = 0;
    result += (int)(m3);
    result += (int)f3(((m3 & (int)sizeof(long)) | (47 ? m5 : m5)), (((int)sizeof(unsigned char) ? 1 : -33) ? (result ^ (int)sizeof(unsigned long)) : (1 << (0))), (('5' && 0) || (g0 >> (20))));
    result += (int)f3(((0 & 1) || ("hello"[3] ? "world"[1] : 188)), ((g0 + 148) >> (18)), ((17 > 1) ^ (g0 != (int)sizeof(long))));

    return (result >= 0 ? result : -result) & 255;
}
