/* Generated by cgen, seed=33 */

struct S0 {
    unsigned long m0;
    long m1;
    char m2;
    char m3;
    int m4;
    long m5;
};

char g0;
long g1;
int g2 = 1;
unsigned char g3 = -16;
unsigned long g4 = 1;
unsigned char g5;
char g6 = 9711;
unsigned long g7;

int f0(unsigned long p0, int p1, long p2, int p3);
unsigned int f1(unsigned long p0, int p1, int p2, long p3);

int f0(unsigned long p0, int p1, long p2, int p3)
{
    unsigned char v0_0;
    struct S0 v0_1;
    v0_0 = 0;
    v0_1.m0 = 0;
    v0_1.m1 = 9;
    v0_1.m2 = -19;
    v0_1.m3 = 1;
    v0_1.m4 = 0;
    v0_1.m5 = 0;

    if (((('a' && 8139) + ("fooX"[1] ? "world"[4] : p3)) ? ((160 - (int)sizeof(unsigned char)) ? (2783 ? g6 : 73) : (-42, g5)) : ((-42 ^ g1) == (g7 & (int)sizeof(char))))) {
        g1 -= (((31 * 1) ? (g5 - g3) : (p2 ? -23 : (int)sizeof(unsigned int))) >> (6));
    }
    g5 *= (((('Z' && 5588), (p2, g3)) || ((2516 ? g3 : v0_0) ^ (g5 == (int)sizeof(unsigned int)))) ? (((v0_0 || p3) % ((-18 > "barY"[2]) | 1)) * ((g3 / (1 | 1)) < (v0_0 ? 0 : g4))) : (((-40 / (1 | 1)) & (-4 + g2)) == (("fooX"[2] << (30)) && (0, 99))));
    g4 |= ((((0 - "abc123"[3]) << (14)) / (((g3 && 'G') * (g2 != "test"[2])) | 1)) + (((p2 || g3) ^ (p3 < p1)) & ((116 | 0) && ("abc123"[0] && -16))));
    g6 *= ((((g0 / (-46 | 1)) * ((int)sizeof(long) < p2)), (('4' - 'V') ? (g3 / (g3 | 1)) : (1 < g6))) & (((4 / (6384 | 1)) ? (p1 << (3)) : (0 * -24)) - ((5325 < (int)sizeof(unsigned char)) && (0 ? 0 : 1))));
    g0 = (((((int)sizeof(unsigned long), (int)sizeof(unsigned char)) ^ ('x' > 4)) >> (18)) >> (2));
    {
        int _w0;
        _w0 = 0;
        while (_w0 < 5) {
            _w0++;
            (((g7 ? p1 : p0) / ((0 == "wxyz"[2]) | 1)) ^ ((23 | g6) > (1 && 1)));
        }
    }
    {
        int _d1;
        _d1 = 0;
        do {
            _d1++;
            v0_1.m5 = (((-41 || g2) != ('J' + 7996)) ? (('(' ? g0 : 2087) / ((g4 << (29)) | 1)) : ((p3 % ("fooX"[3] | 1)), (g6 || g3)));
        } while (_d1 < 4);
    }
    p2 |= (((('A' & v0_0) < (g2 & g4)) + ((3752 ? p0 : p0) - (42 & g1))), ((((int)sizeof(unsigned long) + g5) > (0 ^ g3)) ? ((p0 * 72) ^ (1 ? 1 : g3)) : (((int)sizeof(unsigned char), "barY"[1]) && (g5 << (22)))));
    return (p0);
}

unsigned int f1(unsigned long p0, int p1, int p2, long p3)
{
    int v1_0[7];
    int * v1_1;
    long v1_2;
    int v1_3;
    v1_0[0] = 0;
    v1_1 = 0;
    v1_2 = 749;
    v1_3 = 134;

    {
        int _w2;
        _w2 = 0;
        while (_w2 < 1) {
            _w2++;
            g5 -= f0((f0((int)sizeof(int), g7, (int)sizeof(long), 177) && f0((int)sizeof(char), p0, g6, g2)), ((p1 | v1_0[5]) ? ("hello"[2] ^ g0) : (1 + v1_0[0])), ((0 >> (27)) + (g2 >> (8))), f0((p1 * (int)sizeof(unsigned long)), (g5 != g4), ("hello"[0] || 34), ("hello"[2] + 1)));
        }
    }
    return (p1);
}

int main(void)
{
    int result;
    int m0[15];
    char m1;
    char m2;
    unsigned long m3;
    int m4;
    int m5;
    int * m6;
    result = 0;
    m0[0] = 205;
    m1 = 0;
    m2 = 170;
    m3 = -10;
    m4 = 0;
    m5 = 1;
    m6 = 0;

    {
        int _d3;
        _d3 = 0;
        do {
            _d3++;
            (f1((m1 >> (6)), f0(-42, m2, g7, m1), (m3, "wxyz"[0]), (m0[2] << (2))) * ((m0[3] ^ "abcd"[3]) == (m1 ^ 'Y')));
        } while (_d3 < 2);
    }
    f0((((-29 >> (18)) == (191 == g2)) >> (9)), (((-42 - m0[11]) + (4 > (int)sizeof(unsigned int))) == (f0(63, 157, 67, g5) ? ("world"[0] ? g4 : m2) : f1(m0[5], 3845, 0, m4))), ((("world"[3] * g5), ((int)sizeof(int) > "abcd"[3])) ? (('4' * m1) << (1)) : ((1384 ? g6 : 'e') || (m3, m4))), (((g4 ^ "abc123"[2]) * (249 + g4)) << (14)));
    if ((((1 ? 'J' : m2), (165 + m4)) / (((0 ? 3254 : "barY"[3]) ? (g2 & m0[13]) : (0 == g0)) | 1))) {
        {
            int _f4;
            for (_f4 = 0; _f4 < 10; _f4++) {
                {
                    switch (9758) {
                    case 3:
                        m2 = g1;
                        break;
                    case 8:
                        m5 &= g7;
                        break;
                    case 11:
                        g6 &= m5;
                        break;
                    case 19:
                        m3 /= (m2 | 1);
                        break;
                    }
                }
            }
        }
    }
    goto _lbl5;
    _lbl5:
    (((('r' * m3) && ("fooX"[1] << (26))) % ((((int)sizeof(long) != m4) ? (m2 ? "world"[3] : 52) : ("test"[2] > -36)) | 1)) * ((((int)sizeof(long) || g5) / ((m5, m3) | 1)) % (((result ^ m1) / (f0(m1, "abc123"[3], 49, (int)sizeof(unsigned int)) | 1)) | 1)));
    switch ((((1 * (int)sizeof(int)), (m0[10] | "wxyz"[1])) >> (13))) {
    case 3:
        m3 /= ((((g2 == 9457), (result || g7)) ^ ((1 ? (int)sizeof(unsigned char) : '.') ? ("fooX"[1], "hello"[4]) : f1(1, 170, 9120, m4))) | 1);
        break;
    case 8:
        if (((m5 || 'L') % ((g3 ? 16 : 14) | 1))) {
            ((0 % (151 | 1)) / (f0(0, (int)sizeof(char), "fooX"[1], result) | 1));
        }
        break;
    case 13:
        if (((m0[5], m1) > f0(g0, g6, 7350, result))) {
            m5 %= (((result ? "world"[3] : g1) && (m0[13] & -15)) | 1);
            g6 %= ((("fooX"[2] << (5)) == (g7 - 'P')) | 1);
        } else {
            switch ((g0 * 111)) {
            case 0:
                g5 -= (m2 % ((int)sizeof(unsigned char) | 1));
                break;
            case 8:
                if (m5) {
                    g1 = m0[1];
                    g5 /= (g7 | 1);
                }
                if (85) {
                    m3 -= g4;
                }
                break;
            case 14:
                m1 /= ((m1 ? 27 : 'q') | 1);
                break;
            }
        }
        break;
    case 17:
        m0[12] = (((-27 / (m3 | 1)) ? (1 != g7) : ((int)sizeof(int) ? m0[10] : "barY"[2])), (('S', "world"[1]) - (m1, result)));
        break;
    case 24:
        {
            int _d6;
            _d6 = 0;
            do {
                _d6++;
                switch ((1 | m0[7])) {
                case 1:
                    g2 += (g3 >> (22));
                    break;
                case 7:
                    switch (g3) {
                    case 0:
                        g1 &= m5;
                        break;
                    case 9:
                        g3 = m4;
                        break;
                    }
                    break;
                default:
                    m4 -= (g5 + g4);
                    break;
                }
            } while (_d6 < 10);
        }
        goto _lbl7;
        _lbl7:
        break;
    default:
        switch (f0((180 != g6), ((int)sizeof(unsigned char) / (m3 | 1)), (1, (int)sizeof(long)), (g6 > 1))) {
        case 3:
            g5 |= (f1(g6, g7, "barY"[0], result) == (g2 ^ m0[6]));
            break;
        case 5:
            {
                int _d8;
                _d8 = 0;
                do {
                    _d8++;
                    result *= ((int)sizeof(int) ^ g0);
                } while (_d8 < 3);
            }
            break;
        default:
            {
                int _d9;
                _d9 = 0;
                do {
                    _d9++;
                    m2 %= ((g6 ? 5831 : (int)sizeof(unsigned long)) | 1);
                    m1 |= ("hello"[1] & 80);
                } while (_d9 < 4);
            }
            break;
        }
        {
            int _w10;
            _w10 = 0;
            while (_w10 < 9) {
                _w10++;
                goto _lbl11;
                _lbl11:
                m0[1] = ((36 == m5) << (18));
            }
        }
        break;
    }
    g6 = (f1(((g6 || 75) | (29 ? result : g3)), f0(f0((int)sizeof(int), m5, 'X', 1), (g5 ^ "test"[2]), (12 % (m5 | 1)), (4674 << (26))), f0((0 && (int)sizeof(unsigned char)), (m2, 3423), ("hello"[4] << (9)), (0 | '<')), ((7591 > "abcd"[0]) ? ((int)sizeof(int) << (20)) : (g2, m3))), (f0((0 - g2), ('Z', g4), (g1, g3), (g3, g7)) | (('Q' ? m0[9] : m5) + (m1 || 5583))));

    result = 0;
    result += (int)(m5);
    result += (int)(g4);
    result += (int)(m2);
    result += (int)(g3);
    result += (int)f1((f1(g5, -6, m2, "abc123"[1]) ? (79 ? "abc123"[1] : 1) : ("abcd"[0] ? m4 : g0)), f0((0 >> (3)), (g3 ? 1 : 66), f0(m4, 'Y', 0, '1'), ('v' ? ')' : (int)sizeof(unsigned int))), ((0 % (-10 | 1)) + (g6 / (20 | 1))), (("test"[3] < 8584) - (m3, m5)));
    result += (int)f0(((g5 ? -17 : g5), (m1 < result)), (f1('N', g3, g4, '@') || (g1 - 1)), ((-1 ? (int)sizeof(unsigned char) : g5) ? (g2 == 2042) : (g7 ? 48 : g5)), (f1(m1, 6121, 14, 58) - (m2 * 'f')));

    return (result >= 0 ? result : -result) & 255;
}
