/* Generated by cgen, seed=355 */

struct S0 {
    unsigned int m0;
    unsigned long m1;
    long m2;
};

int g0;
struct S0 gs1;
unsigned long g2;
char g3 = 0;
unsigned char g4 = 0;
long g5 = 0;
unsigned long g6;

char f0(long p0);
unsigned char f1(unsigned long p0, unsigned long p1, unsigned char p2, unsigned char p3);

char f0(long p0)
{
    int v0_0;
    unsigned int v0_1;
    v0_0 = 150;
    v0_1 = 3334;

    g0 -= (((("test"[1] - p0) | ("wxyz"[0] > '~')) ? ((p0 << (9)) / (((int)sizeof(char) ^ v0_0) | 1)) : ((g5 << (20)) | (1 == g6))) ? ((('X', 14) << (10)) & ((g2 + "wxyz"[2]) >> (17))) : (((g0 ? v0_1 : 'L'), (12 * (int)sizeof(unsigned char))) && ((33 ? (int)sizeof(unsigned char) : p0) * (g4 + -50))));
    return (g0);
}

unsigned char f1(unsigned long p0, unsigned long p1, unsigned char p2, unsigned char p3)
{
    int v1_0[8];
    char * v1_1;
    char v1_2[14];
    char * v1_3;
    v1_0[0] = 2926;
    v1_1 = 0;
    v1_2[0] = -6;
    v1_3 = 0;

    p3 *= ((((1 < g2) ? (17 | g6) : (v1_2[11] ? g6 : g5)), (('N', 728) / ((p3 | 0) | 1))) ^ ((f0("test"[1]) && ((int)sizeof(unsigned int) | g0)) | (f0(p0) % ((2445 ? g6 : g0) | 1))));
    gs1.m0 = ((((g5 << (5)) != ((int)sizeof(int) || "fooX"[1])), ((p2 ? 'k' : p1) << (8))) & ((("world"[1], g3) < f0(p1)) != (("hello"[0] / (p0 | 1)) ? f0(1) : (p3 != v1_2[9]))));
    if ((((65 + 132), (7005 ? g5 : "wxyz"[0])) / (((9062 != "wxyz"[2]), (p1 ^ 5082)) | 1))) {
        {
            int _f0;
            for (_f0 = 0; _f0 < 1; _f0++) {
                {
                    int _f1;
                    for (_f1 = 0; _f1 < 4; _f1++) {
                        p2 &= (0 ? v1_2[13] : 0);
                        g5 += (g4 - p0);
                    }
                }
            }
        }
        switch (((p2 || p1) >> (22))) {
        case 4:
            {
                int _w2;
                _w2 = 0;
                while (_w2 < 2) {
                    _w2++;
                    g3 /= ((p2 & 84) | 1);
                }
            }
            break;
        case 7:
            {
                int _f3;
                for (_f3 = 0; _f3 < 3; _f3++) {
                    g4 |= (v1_0[3] - '@');
                    g5 -= ((int)sizeof(char) / ((int)sizeof(unsigned char) | 1));
                }
            }
            break;
        }
    } else {
        {
            p1 %= ((('m' && p2) && (g2 ? g3 : 'f')) | 1);
        }
        {
            int _w4;
            _w4 = 0;
            while (_w4 < 4) {
                _w4++;
                {
                    int _f5;
                    for (_f5 = 0; _f5 < 1; _f5++) {
                        p3 |= (154 ^ 60);
                    }
                }
            }
        }
    }
    if ((((p0 || g6) | (55 | "abcd"[3])), ((7948 < g6) * (1 && v1_2[3])))) {
        {
            int _f6;
            for (_f6 = 0; _f6 < 2; _f6++) {
                {
                    int _w7;
                    _w7 = 0;
                    while (_w7 < 1) {
                        _w7++;
                        p0 %= (f0(-3) | 1);
                        g0 += (v1_2[5] ? v1_0[3] : "test"[1]);
                    }
                }
            }
        }
        p1 /= ((((194 - 0) || (g0 - p3)), f0(("abc123"[2] ? g6 : v1_2[2]))) | 1);
    }
    ((((1, g3) > (146 + p3)) ^ (('4' % ('K' | 1)) >> (10))), (((g0 || 1) ^ (1 != "abc123"[1])) - ((p3 < -42) == ("fooX"[1] / (p3 | 1)))));
    return (g0);
}

int main(void)
{
    int result;
    unsigned long m0;
    char m1;
    char m2[15];
    char m3;
    int * m4;
    char m5;
    result = 0;
    m0 = 253;
    m1 = 195;
    m2[0] = 0;
    m3 = 134;
    m4 = 0;
    m5 = 1;

    m2[2] = ((((-15 ? 0 : 1) << (10)) ^ ((3124 && m5) - ("hello"[0] ? m2[6] : "abcd"[3]))) | ((("test"[2] ? '5' : 0) == (g2 | 4800)) ? ((1 | 1374) ? (1 || (int)sizeof(int)) : (0, '*')) : (('r' ^ result) ? ('X' ? g2 : 0) : f1(g6, g5, "barY"[2], m2[8]))));
    {
        int _f8;
        for (_f8 = 0; _f8 < 2; _f8++) {
            g4 -= (((g4 ? (int)sizeof(long) : 1) ? f1(g0, '#', m3, (int)sizeof(char)) : (g6 << (15))) | ((m1 - m5) % ((m5, "hello"[4]) | 1)));
        }
    }
    gs1.m2 = ((f0(f1(result, 145, (int)sizeof(char), "world"[1])) ? (((int)sizeof(unsigned long) | g5), (m2[5] || m3)) : ((m0 - "abc123"[2]) | (1 % (m0 | 1)))) - (((m5 - m2[4]) - (-41 != 82)), f1(f1(0, 'h', "test"[2], m2[1]), (m5 * "wxyz"[0]), (result | (int)sizeof(int)), ("test"[0] > (int)sizeof(long)))));

    result = 0;
    result += (int)(m5);
    result += (int)(g0);
    result += (int)(g2);
    result += (int)(m5);
    result += (int)f0((f0(g6) ? ((int)sizeof(long), 4) : (g4 * "abc123"[4])));
    result += (int)f0((f0(0) || f0("abc123"[1])));
    result += (int)f1(((g2 * g5) ^ (g5 ? m1 : 0)), (f1(5, g5, 0, m3) ^ ('X' << (0))), ((7572 ? 84 : m3) > (15 % ('(' | 1))), ((1 - g6), f1(79, g6, g3, (int)sizeof(unsigned int))));

    return (result >= 0 ? result : -result) & 255;
}
