/* Generated by cgen, seed=295 */

struct S0 {
    int m0;
    unsigned char m1;
};

struct S1 {
    unsigned long m0;
    char m1;
    long m2;
    unsigned int m3;
};

struct S2 {
    char m0;
    unsigned long m1;
    char m2;
    char m3;
    unsigned long m4;
    unsigned char m5;
};

struct S3 {
    char m0;
    unsigned long m1;
    unsigned long m2;
    int m3;
    unsigned int m4;
    unsigned long m5;
};

struct S4 {
    int m0;
    unsigned char m1;
    long m2;
    int m3;
    long m4;
};

int g0[12];
char g1;
int g2[5];
int g3[8];
unsigned long g4;
unsigned char g5 = 5;
unsigned char g6;

unsigned int f0(char p0, char p1, unsigned char p2, unsigned char p3, int p4);
unsigned long f1(void);
char f2(long p0);
unsigned int f3(unsigned long p0, long p1);
unsigned int f4(unsigned long p0, unsigned int p1);
long f5(unsigned int p0, long p1);

unsigned int f0(char p0, char p1, unsigned char p2, unsigned char p3, int p4)
{
    int v0_0;
    v0_0 = 1;

    if ((((41 ^ g6) == ((int)sizeof(char) ^ "abcd"[2])) > ((g2[0] ? (int)sizeof(long) : g3[5]) + (37 && (int)sizeof(unsigned char))))) {
        p0 |= (((7 ? -42 : 0) + (p1 != "fooX"[2])) > ((g6 | '<') == (p1, 1)));
    }
    if ((((-47 >> (27)) ? ((int)sizeof(long), "fooX"[3]) : (9495 ^ 68)) && ((g4 >> (6)) ? (48, (int)sizeof(int)) : (0 == p1)))) {
        {
            g5 *= ((g2[0] ? 1 : g6) * (1 > p1));
            g2[2] = ((g4 | "barY"[3]) + (p2 && g2[1]));
        }
        {
            int _d0;
            _d0 = 0;
            do {
                _d0++;
                v0_0 |= (("world"[4] >> (13)) ? (p2, 1) : (1 ? g3[0] : "fooX"[1]));
            } while (_d0 < 10);
        }
    } else {
        {
            v0_0 -= (((int)sizeof(long) + g6) > (1 != 94));
        }
    }
    p4 /= (((((p2 != "wxyz"[2]) ? ('#' < p4) : (1 ? (int)sizeof(unsigned int) : g5)), ((p2 || 587) << (25))) > (((1 ^ p2) | (g2[4] & 10)) & (("abc123"[3] >> (8)) == ((int)sizeof(unsigned long) ? 41 : g6)))) | 1);
    g5 |= ((((g1 ? g2[4] : p1) ? ("world"[2] && (int)sizeof(unsigned long)) : (p4 == "barY"[1])) != (("test"[0] < 0) + (v0_0 == g4))) == (((-27 + 1) % ((0 & g2[4]) | 1)) % ((((int)sizeof(int) % (p2 | 1)) | (0 & g3[3])) | 1)));
    return (g6);
}

unsigned long f1(void)
{
    unsigned long v1_0;
    v1_0 = 41;

    v1_0 = (((("hello"[0] << (17)) << (29)), (((int)sizeof(unsigned long) ? g4 : g1), (g2[2] / ("test"[3] | 1)))) ? ((f0((int)sizeof(long), g4, (int)sizeof(unsigned char), (int)sizeof(unsigned long), v1_0) << (5)) << (6)) : f0(((-7 < 252) != (2784 >> (1))), ((1 * g4) ? (g2[0] + g6) : (g5 || v1_0)), (('-' > (int)sizeof(int)) / ((-16, g3[7]) | 1)), (f0(1, "hello"[1], 2, v1_0, -33) > (g6 - (int)sizeof(char))), (f0(g0[8], g2[2], '7', '|', g4) << (19))));
    return (g5);
}

char f2(long p0)
{
    struct S4 v2_0;
    v2_0.m0 = 1;
    v2_0.m1 = 1;
    v2_0.m2 = 1;
    v2_0.m3 = 0;
    v2_0.m4 = -34;

    g1 += f1();
    g4 |= ((((g6 ? g5 : 60) ? ('_' && p0) : (0, g5)) && ((g4 >> (12)) % ((g4, '=') | 1))) - ((("hello"[4] ^ g6) << (29)) && (((int)sizeof(unsigned long) ? g1 : "wxyz"[1]) % ((g5 != 163) | 1))));
    g2[3] = (((("hello"[4] - -22) ? ("world"[0], (int)sizeof(char)) : (g6 | (int)sizeof(char))) ? ((g5 || p0) > (g5 + 183)) : ((p0 % (g4 | 1)) / (f0(g6, '2', (int)sizeof(char), 'h', ':') | 1))) != ((('h' || g4) != ('4' == '5')) ? ((g5 % (g2[3] | 1)) != ("abcd"[3] % ("barY"[0] | 1))) : f1()));
    {
        int _f1;
        for (_f1 = 0; _f1 < 6; _f1++) {
            p0 *= (((3151, g1) >> (18)) << (26));
            {
                g6 /= ((((int)sizeof(unsigned long) & 'A') - (58 == "world"[4])) | 1);
            }
        }
    }
    g4 |= (f0(((p0 < 8631) << (27)), (("wxyz"[0] % (g3[5] | 1)) ^ (0 ? -43 : g4)), ((g2[1] ? g3[4] : g1) | ((int)sizeof(char) | 1)), ((7888, 1) ^ ("world"[4] || g4)), ((g1 || '+') / ((7192 * g4) | 1))) != (((5286 - g5) ? (9848 > 1) : (g5 + 27)) != (("world"[1] - 1) && (g5 << (19)))));
    g1 /= (((((-44 ? g5 : p0) ? (-37 ? "abcd"[1] : g5) : (g0[3] == g6)) + (("barY"[3] << (12)) / ((0 != -35) | 1))) & f0(((g1 || 'G') % ((g6 > p0) | 1)), (((int)sizeof(unsigned int) < g3[7]) | (p0, "fooX"[1])), (((int)sizeof(long) | '6') != (g1, (int)sizeof(int))), ((140 & 0) > (97 > g0[9])), ((p0 + 4834) < (141 * 0)))) | 1);
    {
        int _d2;
        _d2 = 0;
        do {
            _d2++;
            {
                g1 *= (f0(g4, g6, p0, 7169, "world"[3]) != ("barY"[3] != 'M'));
                ((-34 - (int)sizeof(unsigned char)), ("hello"[1] << (29)));
                (f0(-37, g1, p0, "test"[1], "wxyz"[0]) - f0((int)sizeof(unsigned int), g3[3], "abcd"[1], 8657, 100));
            }
            g5 = ((f1() / ((g4 == g6) | 1)) / ((f0(g0[2], "abcd"[2], "hello"[1], 254, g5), (309, -13)) | 1));
        } while (_d2 < 1);
    }
    goto _lbl3;
    _lbl3:
    return (g4);
}

unsigned int f3(unsigned long p0, long p1)
{
    int * v3_0;
    v3_0 = 0;

    {
        int _w4;
        _w4 = 0;
        while (_w4 < 7) {
            _w4++;
            (((1 != g2[3]), (p0 & 182)) ? ((g5 ? '!' : (int)sizeof(long)) - (g5 ? g4 : -42)) : ((44 & (int)sizeof(char)) != (188 / (g0[7] | 1))));
            g6 /= ((((g5 || 'f') ? (231 / (p1 | 1)) : (7258 > 74)), ((g4 < p1) || f0((int)sizeof(char), g1, g4, 'k', (int)sizeof(int)))) | 1);
            g6 -= (((g0[3] & 56) || ('2' != g1)) ? (("barY"[0] < p0) ? (2668 < 'e') : ('D' ^ g4)) : f2(f1()));
        }
    }
    switch (((("abc123"[3], g6) ? ("wxyz"[2] & g5) : f0(g2[3], "test"[0], 31, g0[9], g0[8])) == ((g1, g6) || (1, g3[2])))) {
    case 2:
        p0 -= (f1() ? ((g4 << (12)) && (1 == g0[8])) : ((g4, 89) && ("fooX"[2] != g4)));
        break;
    case 7:
        switch (((g0[7] & p1) * (22 ? "test"[3] : p0))) {
        case 4:
            g6 %= (((p1 % (6733 | 1)) ? (g0[2] * g4) : (g0[9] | g4)) | 1);
            break;
        }
        goto _lbl5;
        _lbl5:
        break;
    }
    ((((g1 < p0) ? (0 < g4) : (g6 ? p0 : p0)) ? ((g2[3] > g3[1]) + f1()) : ((105 - g2[1]) ? (1 != p0) : ("world"[0], p1))), (((0 > -23) | f1()) >> (22)));
    g0[6] = ((f2((70 ? (int)sizeof(unsigned char) : (int)sizeof(long))) << (20)) << (28));
    {
        int _w6;
        _w6 = 0;
        while (_w6 < 3) {
            _w6++;
            if (f1()) {
                g2[4] = ((g6 == g0[7]) * ('8' % (g6 | 1)));
                goto _lbl7;
                _lbl7:
                if ((g4 * 226)) {
                    if ("abcd"[1]) {
                        p0 = g2[3];
                        g1 &= g2[2];
                    } else {
                        g5 += (int)sizeof(unsigned char);
                    }
                }
            } else {
                goto _lbl8;
                _lbl8:
                if ((g1 ? g3[2] : '~')) {
                    switch (p0) {
                    case 0:
                        g4 /= (g5 | 1);
                        g4 -= g6;
                        break;
                    case 5:
                        g4 = '`';
                        break;
                    }
                }
            }
            g6 /= (((f1(), (g4 << (6))), ((g4 || 'F') * f0(64, g6, "world"[2], (int)sizeof(int), (int)sizeof(long)))) | 1);
        }
    }
    switch (((('#', "hello"[3]), (p0 * -47)) != ((p1 ^ g0[4]) >> (4)))) {
    case 0:
        g4 += ((((int)sizeof(char) - -31) < (g2[3] != (int)sizeof(long))) | (("wxyz"[0] - g4) - (g4 << (5))));
        break;
    }
    return (g6);
}

unsigned int f4(unsigned long p0, unsigned int p1)
{
    char v4_0;
    v4_0 = 237;

    goto _lbl9;
    _lbl9:
    g5 += (((("world"[1] ^ (int)sizeof(char)), (p1 - g4)) / (f3((g1 >> (1)), (p1 & -4)) | 1)) == f0((('F', 728) ? (-49 ^ "hello"[2]) : ('%' ? p1 : p1)), ((g1 < 'w') || (5763 && p1)), f0(('`' >> (30)), (-44 == 'f'), ((int)sizeof(int) ? 'E' : 1), (g2[3] % (g4 | 1)), (18 ? g6 : p1)), ((53 & 0) / (((int)sizeof(char) ? g6 : g0[8]) | 1)), (("barY"[0], p1) == (1, 0))));
    v4_0 += f3(((f2(g4) >> (30)) || (f1() * (g1 ? g5 : 0))), f1());
    p1 += (f0((((int)sizeof(long) || g6) % ((g2[0] << (7)) | 1)), ((g5 - g1) + (g4, 20)), ((g6 % (0 | 1)) ? (g4 - 899) : (1, g3[1])), ((g4 / (g4 | 1)) * (g4, 81)), ((p0 % (g0[4] | 1)) != (p0 << (27)))) >> (14));
    return (g6);
}

long f5(unsigned int p0, long p1)
{
    long v5_0;
    char * v5_1;
    int * v5_2;
    char v5_3[10];
    v5_0 = -49;
    v5_1 = 0;
    v5_2 = 0;
    v5_3[0] = -48;

    v5_0 *= ((((p0 << (13)) / ((28 != g6) | 1)) >> (8)) ? (((v5_0 < g4) ? ("world"[3], "world"[1]) : ("fooX"[1] - g4)) < f1()) : f4(((1 << (23)) ? (g6 ? g1 : p1) : f2(-10)), (("abc123"[3], 'Q') < f1())));
    v5_0 &= ((((g4 | g5) - (-24 < g4)) | f4((-18 | "world"[1]), f2(g0[11]))) == ((('^' < g6) / (("hello"[3] || "abc123"[1]) | 1)) && (((int)sizeof(int) - g6) * ((int)sizeof(unsigned char) || g3[6]))));
    g0[3] = ((((p0 ? 50 : p1) % ((v5_0 ^ (int)sizeof(int)) | 1)) != ((1128 & "hello"[2]) ? ('{' << (27)) : (g2[3], 83))), (f0((g4 % ("abcd"[1] | 1)), (g2[2] > v5_3[2]), f2(3819), f1(), (g1 % (p1 | 1))) / (((p1 > p0) ? f3(g2[1], (int)sizeof(char)) : (125 - g4)) | 1)));
    g6 = f3((((g1 ? 0 : g3[5]) < ("abc123"[4] << (18))) ? (('U' + 'i') && (g6 | p0)) : f0((g4 - g0[1]), (p0 | g6), (0 % ((int)sizeof(unsigned int) | 1)), (g1 << (8)), (7412 ^ p0))), (((g6 | 'z'), ((int)sizeof(unsigned char) * g6)) * f0((p0 >> (22)), (v5_0, 6885), (g5 != 4148), (-11, (int)sizeof(unsigned int)), f1())));
    {
        int _f10;
        for (_f10 = 0; _f10 < 5; _f10++) {
            {
                int _f11;
                for (_f11 = 0; _f11 < 2; _f11++) {
                    switch (("wxyz"[2] < "test"[2])) {
                    case 1:
                        v5_0 += f4(33, "abcd"[3]);
                        break;
                    case 8:
                        p0 /= ((v5_0 / (g0[7] | 1)) | 1);
                        v5_0 %= ((v5_0 ? g5 : 'T') | 1);
                        break;
                    case 14:
                        g5 = (g1 << (5));
                        break;
                    default:
                        if (p1) {
                            p0 -= 89;
                            p0 %= ("fooX"[3] | 1);
                        } else {
                            p1 -= p1;
                            g1 -= "fooX"[0];
                        }
                        g1 = (g6 >> (24));
                        break;
                    }
                    p1 = f0((p1 << (18)), f3(p0, 0), (p0 - 166), (99 ^ "abcd"[3]), (g1 % (g3[3] | 1)));
                }
            }
        }
    }
    switch ((((g1 | "fooX"[2]) || f2(476)) | ((0 == g6) != (-34 || p1)))) {
    case 1:
        g5 /= (((f0(g1, 68, g6, g4, g1) - ('R' + "world"[3])) & ((p0 ? 0 : 21), ("fooX"[1] & (int)sizeof(unsigned long)))) | 1);
        break;
    case 6:
        (((p1 / (v5_0 | 1)) << (1)) == (('}' ? g2[1] : g2[4]) % ((g1 ^ (int)sizeof(char)) | 1)));
        break;
    }
    {
        (((p1 && 1) << (1)) != ((5961 ? p0 : 191) < (1 | v5_3[3])));
        f3(((p1 ^ g4) % (f0(v5_3[8], g6, p0, (int)sizeof(char), "test"[2]) | 1)), (f0("test"[2], 135, g4, g5, -48) ^ (0 | 85)));
    }
    g6 += f3(((((int)sizeof(unsigned long) & v5_0) & (5475, 173)) & ((g6 >> (18)) ? ((int)sizeof(unsigned long) ? g6 : 47) : (g6 / ('5' | 1)))), f0(((3153 - (int)sizeof(unsigned long)) < (g5 | g3[0])), (((int)sizeof(char), 6255) == ('^' | 0)), (('<' + g5) % ((9343 * (int)sizeof(unsigned int)) | 1)), ((g5 & v5_0) - f3(1524, (int)sizeof(unsigned char))), f2(((int)sizeof(int) || '4'))));
    p0 &= (f2(((g6 + 5), (7 ? '5' : (int)sizeof(long)))) % (f3((('A' / (167 | 1)) == (g6 && g5)), ((-14 * -2), ('x' | -15))) | 1));
    return (g4);
}

int main(void)
{
    int result;
    int m0[5];
    unsigned char m1;
    result = 0;
    m0[0] = 25;
    m1 = 0;

    {
        int _d12;
        _d12 = 0;
        do {
            _d12++;
            {
                int _d13;
                _d13 = 0;
                do {
                    _d13++;
                    switch ((g0[5] ^ result)) {
                    case 2:
                        result &= (1 != "fooX"[2]);
                        break;
                    case 5:
                        g4 -= (m1 ? g6 : g0[3]);
                        break;
                    case 11:
                        g5 &= (241 > '$');
                        break;
                    }
                } while (_d13 < 6);
            }
            if (f4((m0[1] || result), (g4 || g3[1]))) {
                switch ((result << (11))) {
                case 1:
                    if (g0[1]) {
                        result = g0[10];
                    } else {
                        g5 %= ('+' | 1);
                    }
                    break;
                case 6:
                    m1 *= ("fooX"[0] != (int)sizeof(char));
                    break;
                case 13:
                    result *= ('$' == 99);
                    break;
                default:
                    g6 += (g6 ? m1 : g4);
                    break;
                }
            }
        } while (_d12 < 5);
    }
    result /= (((f5((m1 == -34), f0((int)sizeof(long), "barY"[2], -23, -21, "world"[4])) >> (19)) ? (((158 ? 77 : 1) ? f4(g4, (int)sizeof(unsigned long)) : ('q' * g1)), (('j' ? (int)sizeof(int) : m1), f3('a', g2[3]))) : ((((int)sizeof(unsigned int) % ('Q' | 1)) + (g2[0] + g5)) >> (25))) | 1);
    result /= (f4(((((int)sizeof(char) > g6) != (g3[3] / (g4 | 1))) * ((result << (5)) > ((int)sizeof(unsigned char) < g2[3]))), (((0 >> (16)) ? (g6 ? g6 : g1) : (m1 / (g0[9] | 1))) == ((g0[0] && '-') < ("wxyz"[1] >> (21))))) | 1);

    result = 0;
    result += (int)(g4);
    result += (int)(g4);
    result += (int)(g6);
    result += (int)f4(((g3[1] ? m0[0] : g1) != (m1 & g1)), (f2(result) << (3)));

    return (result >= 0 ? result : -result) & 255;
}
