/* Generated by cgen, seed=68 */

struct S0 {
    char m0;
    char m1;
    unsigned long m2;
    unsigned int m3;
    unsigned long m4;
    int m5;
};

struct S1 {
    long m0;
    long m1;
    char m2;
    unsigned int m3;
    long m4;
};

struct S2 {
    unsigned char m0;
    unsigned long m1;
    unsigned int m2;
    long m3;
    char m4;
    long m5;
};

struct S3 {
    long m0;
    unsigned char m1;
};

int g0[13];

unsigned long f0(char p0, unsigned long p1);
unsigned int f1(long p0);
long f2(int p0, char p1, long p2);
unsigned int f3(void);
unsigned int f4(int p0, unsigned long p1);

unsigned long f0(char p0, unsigned long p1)
{
    int v0_0;
    v0_0 = 109;

    {
        int _f0;
        for (_f0 = 0; _f0 < 10; _f0++) {
            p1 *= ((('g' ? g0[11] : 0) % ((g0[5] || 419) | 1)) ^ ((1 ? 'W' : 1) ? (p0 == 'W') : (1 >> (10))));
        }
    }
    return (p1);
}

unsigned int f1(long p0)
{
    char v1_0[2];
    unsigned int v1_1;
    struct S1 v1_2;
    int v1_3[10];
    v1_0[0] = 0;
    v1_1 = 1;
    v1_2.m0 = 1;
    v1_2.m1 = -13;
    v1_2.m2 = 1;
    v1_2.m3 = 1;
    v1_2.m4 = -32;
    v1_3[0] = 1;

    {
        int _w1;
        _w1 = 0;
        while (_w1 < 7) {
            _w1++;
            v1_2.m2 = (((g0[4] << (13)) < ('2', g0[1])) ? (('-' && v1_1) * (p0 / (v1_0[1] | 1))) : ((v1_1 - p0) != (p0 || 9113)));
            switch (((v1_0[1] < -49) ^ ('*', p0))) {
            case 3:
                v1_1 = (((int)sizeof(unsigned char) == '!') < (0 & g0[6]));
                break;
            }
            if ((((int)sizeof(long) == -10) ? ("abcd"[3] == (int)sizeof(int)) : (45 ^ "test"[1]))) {
                v1_1 &= ((v1_0[0] == p0) >> (0));
            } else {
                {
                    switch ('?') {
                    case 0:
                        p0 = 1;
                        break;
                    case 5:
                        v1_1 -= (int)sizeof(int);
                        break;
                    }
                    switch ("abc123"[3]) {
                    case 0:
                        v1_1 &= v1_1;
                        p0 &= v1_1;
                        break;
                    case 8:
                        p0 /= (p0 | 1);
                        break;
                    case 11:
                        p0 &= 187;
                        break;
                    case 19:
                        v1_1 /= (-48 | 1);
                        break;
                    }
                }
            }
        }
    }
    {
        int _w2;
        _w2 = 0;
        while (_w2 < 9) {
            _w2++;
            v1_2.m3 = (((32, v1_1) / ((v1_0[0] >> (29)) | 1)) ? ((-18 == (int)sizeof(unsigned int)) << (16)) : (('Q' != g0[3]) | (0 == '8')));
            goto _lbl3;
            _lbl3:
            if ((f0("hello"[0], 'g') || (p0 < 0))) {
                g0[2] = (f0(v1_1, p0) >> (18));
            } else {
                v1_1 %= ((("hello"[4] * "wxyz"[3]) || (p0 ? v1_1 : ')')) | 1);
            }
        }
    }
    return (v1_1);
}

long f2(int p0, char p1, long p2)
{
    struct S1 v2_0;
    v2_0.m0 = 30;
    v2_0.m1 = 7;
    v2_0.m2 = -33;
    v2_0.m3 = 187;
    v2_0.m4 = 19;

    p2 |= ((((p2 ? "wxyz"[3] : p1) + (p2 % (1 | 1))) % (((-27 % (p1 | 1)) ? (p2 ^ p2) : (g0[10] >> (21))) | 1)) > (f0(((int)sizeof(int) * 'H'), f1(p0)) % (((p1 >> (30)) != (255 ^ p0)) | 1)));
    if (f1(((1 ? p2 : 'U') ^ ((int)sizeof(char) ^ 1)))) {
        {
            int _f4;
            for (_f4 = 0; _f4 < 7; _f4++) {
                switch ((p0 | (int)sizeof(unsigned int))) {
                case 3:
                    p1 -= (g0[4] ^ (int)sizeof(unsigned long));
                    break;
                case 7:
                    if (231) {
                        p1 = 1479;
                    }
                    break;
                default:
                    switch (42) {
                    case 3:
                        p1 += "fooX"[0];
                        break;
                    case 7:
                        p0 &= p0;
                        break;
                    }
                    p2 += (1321 << (8));
                    break;
                }
                p1 -= ((p1 ? p0 : (int)sizeof(unsigned int)) % (f0(p2, "fooX"[0]) | 1));
            }
        }
    }
    p2 -= (((f0(-38, g0[11]) && ((int)sizeof(int), 'y')), ((p0 | '"') << (7))) || f0((((int)sizeof(unsigned long) >> (15)) | (183 + 55)), (('4' > 4600) / ((-40 > 1672) | 1))));
    {
        int _w5;
        _w5 = 0;
        while (_w5 < 10) {
            _w5++;
            p0 = (((p2 ? "abcd"[1] : 0) % ((70 > (int)sizeof(char)) | 1)) ? ((1417 ^ 1) ? ('%', "barY"[2]) : (p2 ? -6 : p1)) : ((p0 == 56) >> (9)));
        }
    }
    return (p1);
}

unsigned int f3(void)
{
    char * v3_0;
    v3_0 = 0;

    ((((g0[3] % (69 | 1)) ? ((int)sizeof(char) ? 136 : 176) : (64, 8387)) < ((0 ? g0[12] : 'p') && ("abcd"[1] / (255 | 1)))) ? (f1(((int)sizeof(char) % (1 | 1))) << (1)) : (((1181 || 1) | ('j' ^ 't')) ? ((9283 / (9705 | 1)) ^ (0 ^ 0)) : ((1, 0) || (198 >> (22)))));
    ((((0 & (int)sizeof(int)) || ((int)sizeof(unsigned char), 1)) << (5)) % ((f0((1 < 130), (115, 0)) ? (((int)sizeof(unsigned long) % (3342 | 1)), (1 % (52 | 1))) : ((1, "hello"[0]) / (("abc123"[2] == 220) | 1))) | 1));
    return 80;
}

unsigned int f4(int p0, unsigned long p1)
{
    struct S0 v4_0;
    v4_0.m0 = -47;
    v4_0.m1 = 9452;
    v4_0.m2 = 104;
    v4_0.m3 = 6;
    v4_0.m4 = 0;
    v4_0.m5 = -45;

    if ((((-2 >> (24)) < (p1 * p0)) ? ((1 - '^'), ((int)sizeof(unsigned long) | p0)) : (('<' < 0) ? (p1 & (int)sizeof(unsigned long)) : ((int)sizeof(unsigned char), p0)))) {
        {
            int _w6;
            _w6 = 0;
            while (_w6 < 1) {
                _w6++;
                {
                    int _d7;
                    _d7 = 0;
                    do {
                        _d7++;
                        p0 &= (p1 ^ (int)sizeof(unsigned long));
                    } while (_d7 < 5);
                }
                {
                    int _w8;
                    _w8 = 0;
                    while (_w8 < 3) {
                        _w8++;
                        switch ((int)sizeof(long)) {
                        case 2:
                            p0 = g0[10];
                            break;
                        case 9:
                            p1 %= ("world"[4] | 1);
                            p1 %= (g0[2] | 1);
                            break;
                        case 14:
                            p1 &= ')';
                            p0 %= (p0 | 1);
                            break;
                        case 17:
                            p0 += p1;
                            break;
                        case 23:
                            p0 &= p1;
                            break;
                        default:
                            p1 /= (166 | 1);
                            break;
                        }
                    }
                }
            }
        }
    } else {
        p1 = ((('V' == 100) % ((p1 ? -11 : p0) | 1)), ((p0 || "world"[4]), ("abcd"[0] ? 62 : "world"[2])));
        p0 *= f2(((g0[11] ? 1 : 'R') ^ ('*' | g0[7])), ((p1 < "abcd"[3]) != (8089 % (p1 | 1))), ((p1, g0[12]) * ("world"[4] != p0)));
        {
            int _w9;
            _w9 = 0;
            while (_w9 < 7) {
                _w9++;
                {
                    int _d10;
                    _d10 = 0;
                    do {
                        _d10++;
                        p0 += f0("abc123"[1], p1);
                    } while (_d10 < 4);
                }
            }
        }
    }
    {
        int _f11;
        for (_f11 = 0; _f11 < 6; _f11++) {
            g0[6] = ((((int)sizeof(long) ? p0 : p0) ? (g0[8] ? 0 : 22) : (p1 << (25))) != ((1 < 227), ("test"[0], p1)));
            switch (((0, p0) + (p1 & p1))) {
            case 1:
                {
                    int _f12;
                    for (_f12 = 0; _f12 < 5; _f12++) {
                        p0 &= (p1 / ((int)sizeof(unsigned int) | 1));
                    }
                }
                break;
            case 9:
                switch (('-' & 0)) {
                case 3:
                    p0 = (0 % (g0[2] | 1));
                    break;
                case 9:
                    p0 -= ((int)sizeof(char), g0[7]);
                    if ('e') {
                        p1 |= g0[0];
                    }
                    break;
                case 12:
                    p1 += (-49 && 121);
                    break;
                }
                break;
            default:
                p0 &= ((p0 != (int)sizeof(char)) | f2(p0, p0, p0));
                p1 += ((-24 >> (7)) - ("barY"[2] ? "fooX"[1] : p0));
                break;
            }
            p0 -= (((p0 ? p0 : 'J') != (p1 == p1)) || (f1(g0[5]) ? ("abcd"[0] ? g0[7] : 90) : (')' / (p1 | 1))));
        }
    }
    p0 %= (((((p1 < (int)sizeof(unsigned long)) < (59 == p1)) != ((66 ? 2549 : (int)sizeof(unsigned int)) << (0))) | (((p0 ^ 21) | (p0 ? 'Q' : p0)) - (f1(202) >> (0)))) | 1);
    return (p0);
}

int main(void)
{
    int result;
    unsigned int m0;
    int * m1;
    int m2;
    char m3[11];
    char m4[11];
    unsigned int m5;
    result = 0;
    m0 = 1;
    m1 = 0;
    m2 = 6940;
    m3[0] = 1;
    m4[0] = 1;
    m5 = 0;

    m5 |= ((((4150 || (int)sizeof(unsigned int)) >> (4)) ? f2((result ? m2 : 0), f2(result, 21, (int)sizeof(unsigned long)), ("fooX"[2] >> (10))) : (("fooX"[3], m5) ^ (1 ? m5 : m3[2]))), ((f0(-5, (int)sizeof(unsigned long)) << (30)) ? (("wxyz"[2] ? 8168 : 'h') / ((m0 ? m2 : 0) | 1)) : ((m2 & 476), (-22 ? 213 : m2))));
    m0 *= (f4((("fooX"[1] % (m4[8] | 1)) < (result / ("world"[3] | 1))), ((m5 | 4128) ? f2(m5, result, m0) : (m0 << (1)))) ? (((m3[10] * -46) | ('3' ? 'o' : "abcd"[1])) ? (f4(5544, m5) == ('4' + m5)) : (('=' | '|') & f0(5675, m3[4]))) : f2((((int)sizeof(long) * m0) | ('d' - result)), ((m5 % (90 | 1)) - (1 || result)), ((63 ? m5 : (int)sizeof(unsigned int)) ? (-26 && '!') : (m0 < result))));
    goto _lbl13;
    _lbl13:

    result = 0;
    result += (int)(m5);
    result += (int)(m2);
    result += (int)(m5);
    result += (int)(m2);
    result += (int)f3();
    result += (int)f4(((m2 ? '&' : 92) ? f4(m2, -49) : f0(m2, 'z')), (((int)sizeof(int) < 1), (0, result)));
    result += (int)f2(((m2 == m5) < (m3[4] != m2)), (f3() - ((int)sizeof(unsigned char), "world"[1])), f3());

    return (result >= 0 ? result : -result) & 255;
}
