/* Generated by cgen, seed=56 */

char g0 = -30;
long g1;
int g2[3];
int g3;
char g4 = 87;

char f0(unsigned long p0, char p1, unsigned long p2);

char f0(unsigned long p0, char p1, unsigned long p2)
{
    int v0_0;
    v0_0 = 23;

    v0_0 += ((((g4 != (int)sizeof(unsigned long)) || (g1 < "fooX"[3])) ? ((p2 < 1) < (g1 >> (9))) : ((p1 < v0_0) && ((int)sizeof(int), "abc123"[2]))), (((g2[2], p1) - ('T' << (6))), (((int)sizeof(char) << (16)) | (g4 == "test"[2]))));
    g0 |= ((((0 % (p0 | 1)) - (g2[1], (int)sizeof(long))) ? ((g2[1] % (p1 | 1)) == ((int)sizeof(long) < g2[1])) : ((199 * g1) - (g2[0], p0))) * (((1 == g2[2]) ^ (g1 || (int)sizeof(unsigned char))) + (('0' ? (int)sizeof(unsigned int) : g4) && (g4 << (17)))));
    return (p1);
}

int main(void)
{
    int result;
    unsigned char m0;
    unsigned long m1;
    int m2;
    char m3[12];
    int m4;
    unsigned char m5;
    result = 0;
    m0 = 1;
    m1 = -36;
    m2 = 1;
    m3[0] = 0;
    m4 = 29;
    m5 = 0;

    g2[0] = ((f0(("abc123"[2] & result), (m0 - '^'), (47 + "barY"[0])) > ((m0 & 1) | (result ? 0 : g0))) > ((f0(m2, m2, g0) || ((int)sizeof(long) >> (22))) ? (("abcd"[0] & 26) || ((int)sizeof(unsigned int) == 'd')) : (f0(result, g2[1], (int)sizeof(unsigned long)) > (m2 ? -19 : 149))));
    result &= ((f0(f0('R', "abcd"[1], 1), (result ? 40 : 1), (m3[0] == 1)), ((57 && g1) * (m5 | m3[0]))), (((g2[1] && g2[1]) % ((m5 ? (int)sizeof(unsigned long) : 1) | 1)) ^ (f0(57, g0, "fooX"[2]) ? (38 & 50) : ("wxyz"[1] ^ m0))));
    g0 -= (((("barY"[1] || -48) + (g2[0] << (24))) == ((g3 ? 'm' : "wxyz"[2]) > f0(m5, "abc123"[3], m4))) ? (((-23 >> (8)) || (m1 ? -8 : 1)) << (15)) : f0(((0, g2[2]) != (m2 > (int)sizeof(long))), ((-38 + 1) ? (-13 ? 81 : "abcd"[2]) : (m0 | 414)), ((m0 != m5) != (g0 | '%'))));
    g3 *= ((((g0 ? m4 : '7') ? f0(g0, m3[4], m5) : (m4, m1)) != f0((m2, g0), (m4 >> (3)), (1 % (g2[1] | 1)))) ? (((1 - 1) >> (0)) || ((g1 << (29)) + (g0 << (2)))) : (f0((-8 && 19), f0(g4, 40, 1), ('I' ? g4 : g3)) > ((1 - m5), (-43 - g2[0]))));
    (f0((((int)sizeof(int) * "fooX"[0]) >> (7)), ((-29 * 3070) << (15)), (("abcd"[2] | 'g') | ('1' * 'Q'))) & (((g2[1] || m4) / ((m0 % ("test"[3] | 1)) | 1)) * ((g0 == 77), (0 / (4644 | 1)))));
    {
        int _w0;
        _w0 = 0;
        while (_w0 < 9) {
            _w0++;
            {
                int _w1;
                _w1 = 0;
                while (_w1 < 2) {
                    _w1++;
                    m5 %= ((("abcd"[1] + 22) * (-11, g1)) | 1);
                    {
                        int _f2;
                        for (_f2 = 0; _f2 < 2; _f2++) {
                            switch (356) {
                            case 0:
                                m5 /= (result | 1);
                                break;
                            case 8:
                                m5 %= ('V' | 1);
                                break;
                            case 10:
                                g1 = g0;
                                break;
                            case 18:
                                g4 -= (int)sizeof(unsigned long);
                                break;
                            }
                        }
                    }
                }
            }
            m1 %= (((f0((int)sizeof(unsigned char), result, g3) >> (2)) - ((result != m1) / ((m2 || m3[1]) | 1))) | 1);
            {
                if ((result || 243)) {
                    m0 += (g1 | g2[0]);
                    m4 = (0, '9');
                } else {
                    g1 += (4482 && -39);
                }
            }
        }
    }
    m1 |= (f0((((int)sizeof(unsigned int) + g2[1]), (g3 << (30))), ((result > m4) >> (28)), ((result && "wxyz"[1]) | (g2[2] || 53))) < f0(((m2 || m5) ? (171 >> (30)) : (m0 || result)), ((-42 + (int)sizeof(long)), f0(result, g2[1], 9834)), ((m3[11] / ("world"[3] | 1)) == f0('U', '5', 1014))));
    {
        int _d3;
        _d3 = 0;
        do {
            _d3++;
            m5 -= (((4416 ? g1 : (int)sizeof(unsigned int)) | (g0 >> (28))) * ((m5 % (g1 | 1)) % ((m1 | 1) | 1)));
        } while (_d3 < 1);
    }
    g2[1] = ((((g0 << (27)) >> (17)) < ((g3 ? m3[11] : 30) / (('U' << (17)) | 1))) ^ (((m1 + m3[4]) != f0(result, g0, g3)) != f0((0 ^ m0), ("wxyz"[1] && -35), (m3[2] ? g2[0] : m2))));
    g4 %= (((((g3 / (36 | 1)), (1 - m4)), ((result, 26) ^ (g3 ? 102 : m2))) ? ((('g' % ('z' | 1)) >> (27)) << (26)) : (f0(('N' ? m5 : "fooX"[0]), f0('`', 0, -39), f0((int)sizeof(unsigned long), g1, 'R')), ((5839 & m1) != (89 * m4)))) | 1);

    result = 0;
    result += (int)(g3);
    result += (int)(g1);
    result += (int)(g4);
    result += (int)(g1);
    result += (int)(m0);
    result += (int)f0((("barY"[0], m0) != (m1 == -44)), (((int)sizeof(unsigned char) ? m5 : 43) & (m0 & m3[11])), f0((g4 ? "wxyz"[2] : m1), (m0 - (int)sizeof(unsigned int)), ((int)sizeof(int), 1)));

    return (result >= 0 ? result : -result) & 255;
}
