/* Generated by cgen, seed=345 */

struct S0 {
    int m0;
    char m1;
    unsigned char m2;
};

struct S1 {
    int m0;
    unsigned long m1;
    long m2;
    long m3;
    unsigned long m4;
};

struct S2 {
    int m0;
    unsigned char m1;
    int m2;
};

int g0[14];
unsigned char g1;
struct S2 gs2;
unsigned long g3;
char g4 = 6199;
unsigned char g5;
unsigned long g6;
unsigned int g7 = -48;
int g8[7];
int g9 = -24;

int f0(int p0, unsigned char p1, char p2);
unsigned int f1(int p0, unsigned char p1, int p2, unsigned char p3, int p4);
char f2(int p0);
unsigned char f3(unsigned int p0, char p1, int p2);

int f0(int p0, unsigned char p1, char p2)
{
    int v0_0;
    v0_0 = -46;

    gs2.m1 = ((((g4 && "barY"[3]) ^ (g8[5] ^ "barY"[0])) && (('[', 'M') > ('=', g4))) && (((g4 % (g8[1] | 1)) < (-21 ? 9 : '|')) && ((1, 1) & ("abcd"[2] + 125))));
    g5 %= (((((g5 >> (11)) % (((int)sizeof(unsigned char) - "fooX"[3]) | 1)) != ((p0, '`') >> (5))) ? ((((int)sizeof(long) != (int)sizeof(long)) ^ ('"' ? g8[0] : (int)sizeof(long))) ? ((0 > g8[4]) != ("test"[1] - (int)sizeof(unsigned int))) : (((int)sizeof(long) | g5) - (g0[11] ? 0 : g5))) : (((p1 % (0 | 1)) && ((int)sizeof(unsigned char) && -35)) > ((g0[2] && p1) != (g5 << (23))))) | 1);
    goto _lbl0;
    _lbl0:
    p0 |= ((((g8[4] - -5) != ((int)sizeof(unsigned int) & (int)sizeof(unsigned long))), (("wxyz"[3], '!') && (g1 | g7))) ? (((0 ? 3511 : 9137) != ("hello"[0] ^ g1)) | ((216 << (10)) ^ (g4 << (2)))) : (((p0 || g1) >> (20)) * ((p0 | g4) << (20))));
    ((((5904 - v0_0) - (3567 || 1)) ? ((g8[5] ^ -44) & (-47 << (2))) : ((p0 / ((int)sizeof(int) | 1)) << (5))) - (((g1 / (0 | 1)) ? ("fooX"[2] ? 1 : v0_0) : ('o' ^ 74)) ? ((v0_0 / ((int)sizeof(long) | 1)) || (g3 ^ '[')) : ((g4 < g6), (69 << (26)))));
    goto _lbl1;
    _lbl1:
    {
        int _w2;
        _w2 = 0;
        while (_w2 < 9) {
            _w2++;
            g3 -= (((g9 < g1) << (18)), ((g8[2] == g0[4]) > (1 * g5)));
        }
    }
    if ((((p1 ? 64 : g0[5]) - (1 | g7)) < (((int)sizeof(int) << (0)) | ('E' >> (7))))) {
        g8[4] = ((((int)sizeof(char), p1) ? (v0_0 & g9) : (g7 == g7)) + ((98 ? g4 : 'o') < (1 % (' ' | 1))));
        p2 /= ((((g3 ^ g0[4]) / (('(' < (int)sizeof(long)) | 1)) ? ((g6 & g3) + (g0[9] != g8[5])) : ((g6 % ("test"[0] | 1)) % ((p2 ? g8[0] : '^') | 1))) | 1);
    }
    return (p2);
}

unsigned int f1(int p0, unsigned char p1, int p2, unsigned char p3, int p4)
{
    unsigned int v1_0;
    int * v1_1;
    int * v1_2;
    v1_0 = 0;
    v1_1 = 0;
    v1_2 = 0;

    g8[0] = ((((g4, p4) == (56 << (12))) << (9)) ? (((0 * 97), ("abcd"[1] ? (int)sizeof(unsigned char) : 1)) / ((f0(g0[7], 0, g8[3]) ? (g4 >> (23)) : (-49 || -13)) | 1)) : ((((int)sizeof(int), g4) << (28)) && ((0 && -43) || (114 == 34))));
    {
        int _f3;
        for (_f3 = 0; _f3 < 8; _f3++) {
            {
                int _d4;
                _d4 = 0;
                do {
                    _d4++;
                    goto _lbl5;
                    _lbl5:
                    switch (f0(g3, g8[2], p1)) {
                    case 4:
                        p3 += ('|' ? g9 : -4);
                        break;
                    case 7:
                        v1_0 /= (("world"[3] % (p0 | 1)) | 1);
                        g7 += (p4 & g5);
                        break;
                    case 13:
                        g9 *= (g5 + 16);
                        break;
                    default:
                        g9 %= ((0 != p0) | 1);
                        break;
                    }
                } while (_d4 < 6);
            }
            p2 -= ((('J' * p1) ^ (p0 == 57)) % (((g5 ? p4 : 7910) != (1 || "abcd"[2])) | 1));
        }
    }
    goto _lbl6;
    _lbl6:
    switch ((((p4 & p1) ? (-15, 245) : (p0 >> (21))) ? ((g8[6] | g0[1]) << (23)) : ((84 >> (3)), (g1, g0[13])))) {
    case 4:
        {
            v1_2 = &g7;
            {
                int _f7;
                for (_f7 = 0; _f7 < 2; _f7++) {
                    g9 %= ((g7, 235) | 1);
                }
            }
        }
        break;
    case 9:
        if (f0(((int)sizeof(unsigned int) - g7), (g8[3] ^ "fooX"[1]), (v1_0 ? g1 : g6))) {
            v1_0 |= ((g3 > (int)sizeof(int)) / ((g6, 205) | 1));
            p4 |= f0(('g' ? "abcd"[2] : 67), (127 > 1), ("hello"[1] % (g3 | 1)));
        }
        break;
    default:
        g9 |= ((f0(g1, 4354, g9) ? (g7 - g4) : ("world"[4] ^ 76)) ^ (("test"[2] + g0[6]) == (7363 | 'N')));
        break;
    }
    v1_1 = &v1_0;
    return (p1);
}

char f2(int p0)
{
    int v2_0;
    unsigned long v2_1;
    v2_0 = 7426;
    v2_1 = 0;

    p0 -= (((("test"[1] % ('!' | 1)) ? (1 % (g6 | 1)) : (g8[3] ? (int)sizeof(unsigned int) : -3)) >> (29)) ^ (((g0[10] > g7), (v2_1 + g4)) && ((v2_1 % (g4 | 1)) ? (g5 != 169) : (g3 != 1))));
    return (g9);
}

unsigned char f3(unsigned int p0, char p1, int p2)
{
    struct S2 v3_0;
    v3_0.m0 = -13;
    v3_0.m1 = 1;
    v3_0.m2 = 0;

    g5 -= ((((-2 ? 2524 : p1) == (0 != 33)) * ((p2 ? g0[11] : "abc123"[4]) & (g3 ? 72 : g4))) ? ((('C' % (p1 | 1)) ? (g3 >> (0)) : (g5 != g6)) << (5)) : ((("world"[3] != g6) == (-10 == p1)), ((-36 + g1), f1(99, p0, (int)sizeof(long), "test"[0], (int)sizeof(char)))));
    g4 |= (((f2(g6) + (212 > "wxyz"[0])) / (f2(f2(g6)) | 1)) >> (19));
    return (g4);
}

int main(void)
{
    int result;
    int m0;
    unsigned char m1;
    int m2[12];
    char * m3;
    int m4;
    result = 0;
    m0 = 1;
    m1 = 1;
    m2[0] = 221;
    m3 = 0;
    m4 = 255;

    {
        int _w8;
        _w8 = 0;
        while (_w8 < 4) {
            _w8++;
            (((g7 & 'T') >> (17)) - f2((result ^ 0)));
        }
    }

    result = 0;
    result += (int)(g1);
    result += (int)(m1);
    result += (int)(g7);
    result += (int)(g3);
    result += (int)(m1);
    result += (int)f2(((g0[12] >> (10)) ? (m0, (int)sizeof(unsigned long)) : (g6 << (20))));
    result += (int)f2(((result / ("wxyz"[0] | 1)) ? (50 ^ 0) : f0((int)sizeof(int), g5, m0)));
    result += (int)f1(((g6 ? m0 : 2187) || ("hello"[0] % ("abc123"[1] | 1))), ((255 >> (18)) || (g4 < 225)), f3(((int)sizeof(unsigned long) ^ m1), (47 != g8[3]), (g1 / ((int)sizeof(unsigned char) | 1))), ((1 % (1 | 1)), f2("test"[2])), ((m4 < 1) > ('/' || (int)sizeof(unsigned int))));

    return (result >= 0 ? result : -result) & 255;
}
