/* Generated by cgen, seed=389 */

struct S0 {
    unsigned long m0;
    long m1;
    unsigned long m2;
    unsigned long m3;
};

struct S1 {
    int m0;
    long m1;
};

struct S2 {
    unsigned long m0;
    unsigned int m1;
    long m2;
    long m3;
};

struct S3 {
    char m0;
    unsigned long m1;
    int m2;
    unsigned long m3;
    char m4;
    unsigned char m5;
};

struct S4 {
    unsigned int m0;
    long m1;
};

struct S5 {
    int m0;
    char m1;
    unsigned long m2;
    unsigned char m3;
    unsigned char m4;
};

char g0 = 36;
unsigned long g1 = -12;
long g2;
long g3;
unsigned long g4 = 2682;
unsigned char g5 = 52;

int f0(long p0, char p1, unsigned char p2);
unsigned char f1(int p0, char p1, unsigned int p2);
long f2(unsigned long p0, int p1);
unsigned char f3(void);
long f4(void);
unsigned char f5(long p0, int p1, unsigned int p2, unsigned char p3, int p4);
unsigned char f6(unsigned long p0);

int f0(long p0, char p1, unsigned char p2)
{
    int v0_0;
    v0_0 = 75;

    {
        int _w0;
        _w0 = 0;
        while (_w0 < 9) {
            _w0++;
            g2 = (((-39 + 3945) == (143 != g1)) % (((113, p0) & (g0 ? '_' : '5')) | 1));
        }
    }
    return (p1);
}

unsigned char f1(int p0, char p1, unsigned int p2)
{
    char v1_0;
    char v1_1;
    unsigned int v1_2;
    v1_0 = 6678;
    v1_1 = 5435;
    v1_2 = 28;

    v1_2 *= ((((-19 ? g5 : g1) + ((int)sizeof(char) ? 147 : (int)sizeof(unsigned int))), ((7285 - 8) - f0(-33, 1, 1))) ? (((0, 1) | ('-' << (26))) / ((('t' == 162) | (g5 / (1 | 1))) | 1)) : (((p1 | 1) ? ("world"[0] / (v1_0 | 1)) : (1 == (int)sizeof(int))) ^ ((p1, 1) + (g5 - "fooX"[1]))));
    goto _lbl1;
    _lbl1:
    switch ((((5784 != 14) & (g2 ? p0 : -16)) != (('f' - (int)sizeof(long)) | (g1 & '9')))) {
    case 2:
        {
            int _w2;
            _w2 = 0;
            while (_w2 < 10) {
                _w2++;
                p2 %= (((v1_1, 240) == (g2 ? g0 : 2)) | 1);
                v1_0 %= (f0((v1_1, 233), ((int)sizeof(char) + 52), f0(p2, v1_2, g3)) | 1);
            }
        }
        p0 = (((g0 << (11)) ? (p1 - g1) : (1 / (v1_1 | 1))) + (f0(v1_1, v1_2, v1_2) ? (g4, (int)sizeof(unsigned int)) : f0(1, 26, g3)));
        break;
    default:
        goto _lbl3;
        _lbl3:
        {
            int _w4;
            _w4 = 0;
            while (_w4 < 8) {
                _w4++;
                p1 |= ((p0 != 0) ? (-2, 64) : (1 - 0));
            }
        }
        break;
    }
    p0 %= (f0((((p2 << (17)) & f0(g4, p0, (int)sizeof(unsigned int))) ? ((v1_0 ^ ':') / ((90 > g5) | 1)) : ((16 ? 253 : g2) - (0 != p2))), (((3127 % (g0 | 1)) || f0(v1_0, 1, (int)sizeof(int))), ((g3 >> (17)) * (-14 >> (17)))), f0(((v1_2 % (69 | 1)) != ((int)sizeof(unsigned char) | (int)sizeof(char))), f0((p0 / (p1 | 1)), f0(v1_0, "hello"[0], p0), (231 / (9752 | 1))), ((v1_1 ? (int)sizeof(unsigned long) : 58) && (g1, g5)))) | 1);
    {
        int _f5;
        for (_f5 = 0; _f5 < 8; _f5++) {
            if ((('v' | 86) << (5))) {
                p1 /= ((('H' * (int)sizeof(int)) & (0 % (0 | 1))) | 1);
                g4 += f0((1682 != p1), (-2 - '!'), (g1 && 7280));
                g3 = (("fooX"[3] == g1) ? (g5, -7) : (p2 ? '<' : -31));
            } else {
                {
                    int _f6;
                    for (_f6 = 0; _f6 < 4; _f6++) {
                        p0 += (17, g2);
                    }
                }
            }
            g5 &= (((94 == v1_0) % ((g3 ? g3 : (int)sizeof(int)) | 1)) + ((-3 & -15) < ((int)sizeof(long) * (int)sizeof(unsigned int))));
        }
    }
    goto _lbl7;
    _lbl7:
    if (((f0(p0, (int)sizeof(char), "barY"[0]) ? ("fooX"[1] ? p2 : "world"[3]) : (g1 ? 8 : 3587)) + ((55 == (int)sizeof(unsigned char)) * (p0 && 0)))) {
        v1_2 -= (((150 || 142) - (g4 && v1_0)) != ((1 == "abcd"[1]), (v1_1 + v1_0)));
    } else {
        if ((f0(11, v1_1, 1) ? f0(v1_1, g4, 8440) : (p0 && '5'))) {
            switch ((15 << (15))) {
            case 2:
                g5 -= (220 ? "wxyz"[2] : -24);
                break;
            case 5:
                p1 = ('W', v1_2);
                break;
            default:
                p1 = f0(-19, -20, 18);
                break;
            }
        }
        {
            int _f8;
            for (_f8 = 0; _f8 < 3; _f8++) {
                {
                    int _f9;
                    for (_f9 = 0; _f9 < 1; _f9++) {
                        g5 /= ((p2 || (int)sizeof(unsigned char)) | 1);
                        v1_0 *= (72 >> (16));
                    }
                }
                g5 = ((p1 || "test"[2]) ? (1 * g5) : f0(p1, -22, "world"[1]));
                g1 = ((v1_2, v1_2) > (1 | 1));
            }
        }
    }
    return (p2);
}

long f2(unsigned long p0, int p1)
{
    long v2_0;
    int v2_1;
    char v2_2;
    char v2_3;
    v2_0 = 236;
    v2_1 = 8548;
    v2_2 = 19;
    v2_3 = 1;

    g4 *= (((((int)sizeof(unsigned long) * g2) + ('f' & v2_3)) + ((7632 ? 146 : -20) & ('2' << (9)))) ? (((p1 & 0) % ((g5 == 95) | 1)), ((p1 > v2_3) << (7))) : (((v2_0 * 0) * (52 < g4)) >> (3)));
    {
        {
            int _f10;
            for (_f10 = 0; _f10 < 8; _f10++) {
                {
                    int _d11;
                    _d11 = 0;
                    do {
                        _d11++;
                        v2_1 %= ((g0 ^ p1) | 1);
                    } while (_d11 < 1);
                }
                if (("abc123"[3] ^ 87)) {
                    v2_3 %= ((g2, 1) | 1);
                    switch (132) {
                    case 0:
                        v2_1 *= "barY"[2];
                        break;
                    default:
                        g5 += '0';
                        break;
                    }
                } else {
                    g3 = (0, g5);
                }
            }
        }
        g0 = (((v2_0 ^ 0) * (0 ? g0 : g5)) > f0((0 && 0), f1(5205, (int)sizeof(long), 1), (g0 >> (19))));
    }
    switch ((((-20 << (28)) - (71 & "wxyz"[1])) < (('P' % ("hello"[0] | 1)) ? (-41 ? 1 : 10) : ((int)sizeof(char) - -5)))) {
    case 3:
        g5 &= (((0 != g4), (-6 - p1)) >> (19));
        break;
    }
    {
        int _w12;
        _w12 = 0;
        while (_w12 < 9) {
            _w12++;
            goto _lbl13;
            _lbl13:
            v2_1 *= ((('}' << (3)) ^ (g5 | 166)) << (18));
            p0 %= ((f1((70 == g3), ('O' ^ "fooX"[1]), f0((int)sizeof(long), 63, 846)) > (((int)sizeof(long) && "barY"[0]) << (13))) | 1);
        }
    }
    {
        int _d14;
        _d14 = 0;
        do {
            _d14++;
            {
                {
                    int _w15;
                    _w15 = 0;
                    while (_w15 < 5) {
                        _w15++;
                        g1 |= (1 | 1);
                    }
                }
            }
        } while (_d14 < 8);
    }
    return (p1);
}

unsigned char f3(void)
{
    unsigned long v3_0;
    int v3_1;
    v3_0 = 0;
    v3_1 = 0;

    (((f0((int)sizeof(char), "fooX"[3], g2), (g4 ? g1 : (int)sizeof(unsigned int))) & ((g4 ? g1 : 223), (v3_0 && g0))) << (10));
    if (((f2(g3, (int)sizeof(unsigned char)) ^ (v3_0, v3_0)) * (((int)sizeof(unsigned char) || "abc123"[2]) & ('h' ? 1 : v3_1)))) {
        g0 -= f1(((0 > g0), (-23 * 0)), f2((116 && g1), (6 ? 'Q' : 84)), (f2(1, 163) << (9)));
    } else {
        v3_0 += (((g5 - 68) | (g5 * g2)) != ((v3_1 < 77) && (g2 == g2)));
    }
    v3_0 &= ((((g1 - 31), (1, v3_0)) + f0((1 << (20)), ("fooX"[1] * 6413), (g4 ? 1340 : 'V'))) ? (f2((0 % (60 | 1)), (0, 'Z')) || (f1(-32, "wxyz"[0], 206) & (3618 + (int)sizeof(unsigned long)))) : ((("world"[4] && g4) + f1(v3_0, 13, 785)) % (((g5 < 0) ? f0(4434, g3, g3) : (v3_1 + g3)) | 1)));
    return (v3_0);
}

long f4(void)
{
    unsigned long v4_0;
    v4_0 = 1;

    g1 -= ((((1 ? '+' : 'P') && (55 % ("world"[2] | 1))), f0((-24 & "abc123"[5]), (g4 < ']'), (150, 1))) >> (1));
    return (g3);
}

unsigned char f5(long p0, int p1, unsigned int p2, unsigned char p3, int p4)
{
    int v5_0;
    v5_0 = 49;

    switch ((f3(), ((p3 || "barY"[0]), (g3 - p3)))) {
    case 2:
        v5_0 *= (((p3 / ((int)sizeof(unsigned long) | 1)) == f3()) % (f0((0 != 0), ('f' ? 'y' : g4), (-45, -2)) | 1));
        break;
    case 6:
        g5 += ((((int)sizeof(int) ? 'i' : 0) ? (10 | -36) : (7454 | 0)) ? (("abc123"[1], g3) & ('j' % (-20 | 1))) : f3());
        {
            int _w16;
            _w16 = 0;
            while (_w16 < 7) {
                _w16++;
                {
                    if (49) {
                        p3 -= g0;
                    } else {
                        p1 &= g4;
                    }
                }
            }
        }
        break;
    }
    {
        int _d17;
        _d17 = 0;
        do {
            _d17++;
            p4 -= (((7250 > '5') & f0(241, g1, '|')) << (10));
        } while (_d17 < 3);
    }
    g2 %= ((((('c' | '"') > (206 << (5))) | ((p1 || 0) != f4())) ^ f3()) | 1);
    {
        p0 -= (((g5, 1) || (p0 << (25))) & (f2(g2, 203) != ((int)sizeof(char) == g4)));
        p1 += (((p1 ^ v5_0) ^ ('b' & 1)) << (1));
    }
    return (g5);
}

unsigned char f6(unsigned long p0)
{
    unsigned int v6_0;
    v6_0 = 1;

    if ((((g1 - g0) << (16)) && ((g4 ^ g1) ? f4() : (0 | p0)))) {
        g1 /= (f5(((g4 % ("abc123"[0] | 1)) && (3 << (24))), (((int)sizeof(unsigned int) + g0) == (1 ? 0 : 76)), ((7982, g5) ? (1 + p0) : (g3 == 3788)), ((g4 || 'Y') ^ f4()), ((0 || 18) ? (1 * 0) : f5(58, g5, g5, g5, 8449))) | 1);
    }
    {
        int _d18;
        _d18 = 0;
        do {
            _d18++;
            switch (((0 & g3) % ((p0 > "wxyz"[1]) | 1))) {
            case 3:
                v6_0 |= ((-2 >> (30)) ? (v6_0 ^ g0) : ((int)sizeof(char), g1));
                break;
            case 8:
                g4 += (("barY"[2] + p0) && ("abc123"[2] && g4));
                break;
            }
        } while (_d18 < 10);
    }
    g4 += (f2(((p0 ^ 1) - (g2 * 16)), ((g2 % (-49 | 1)) != (g4 & '<'))) ? (((0 / (40 | 1)) ? ('j', 'd') : ((int)sizeof(unsigned int), 87)) ? f1((7720 ? 'd' : g4), f2(32, '#'), (1 * g0)) : (((int)sizeof(int) < 124) >> (2))) : (((7986, g3) << (1)) ? ((71 ? v6_0 : 29) - ("hello"[3] | 0)) : ((1 | (int)sizeof(unsigned int)) << (18))));
    {
        int _w19;
        _w19 = 0;
        while (_w19 < 1) {
            _w19++;
            p0 &= f1((f1(1, "world"[4], v6_0) | ((int)sizeof(long) && g5)), (f2(v6_0, 7953) > ("test"[0] / (119 | 1))), f5(("hello"[1] > "fooX"[0]), (0 == "abcd"[0]), (g0 ? 116 : 3691), ((int)sizeof(char) > "test"[1]), ('_' < 229)));
        }
    }
    g2 += (((('J' < '#'), (g5 || (int)sizeof(unsigned long))) & ((1 & "fooX"[2]) ? (-27 | g0) : ("abcd"[2] * 105))) ? f5(((g1 != 5) | (g0 ? g1 : g3)), ((0 > (int)sizeof(long)) % (f1((int)sizeof(long), "abcd"[1], '9') | 1)), ((g1, -3) != (g0 * -17)), ((-43 < g2), ((int)sizeof(char) ? p0 : 468)), ((1 ? -40 : g3) * (v6_0 < v6_0))) : ((('v' >> (11)) >> (23)), ((g0 ? g4 : v6_0) << (17))));
    {
        int _w20;
        _w20 = 0;
        while (_w20 < 2) {
            _w20++;
            p0 /= ((f4(), (((int)sizeof(unsigned int) | g1), (8471 ^ -38))) | 1);
        }
    }
    return (g1);
}

int main(void)
{
    int result;
    long m0;
    result = 0;
    m0 = 0;

    {
        result %= ((((1 ? 't' : 998) > (0 - '+')) + (((int)sizeof(unsigned int) && 154) ? ("hello"[4] < result) : (44 >> (11)))) | 1);
    }
    g3 -= f1(f2((((int)sizeof(unsigned int) > 156) > ((int)sizeof(unsigned int) > 0)), (("wxyz"[1] * 3211) ? ('W', result) : (g2 * g3))), ((("wxyz"[2] || 0) & (119 / ((int)sizeof(long) | 1))) ? ((35 < 6590) ? (g2 ? 41 : 66) : ("world"[1] / (m0 | 1))) : (((int)sizeof(unsigned long), (int)sizeof(unsigned int)) + ('+' && 1))), (((g5 ? 0 : (int)sizeof(unsigned char)) ^ (g4 > g5)) || ((0 ^ m0) || (g3 > m0))));
    switch ((((g4, g4) || ((int)sizeof(unsigned int) + result)) << (8))) {
    case 2:
        {
            int _w21;
            _w21 = 0;
            while (_w21 < 2) {
                _w21++;
                g3 = (f3() & (1 % ('X' | 1)));
            }
        }
        break;
    case 5:
        g1 -= (((result && -18) < (g4 && m0)) == ((g3 > g3) % ((3781, g4) | 1)));
        if (((6932, (int)sizeof(unsigned int)) && f3())) {
            goto _lbl22;
            _lbl22:
            if ((0 < 18)) {
                g2 %= ((g0, g3) | 1);
            }
        }
        break;
    default:
        switch (((1 < g3) / (((int)sizeof(long) ? -25 : 'B') | 1))) {
        case 1:
            {
                g1 |= f5(g1, 6, -35, g0, 1);
                g4 *= f5(573, "abc123"[1], 80, g1, result);
                if (1) {
                    g3 = g2;
                }
                result &= f3();
            }
            break;
        case 5:
            result %= (((g3 ? g5 : g4) / (f1(7299, g2, 157) | 1)) | 1);
            break;
        case 10:
            {
                result -= (g0 & g4);
                g3 %= (('?' - g5) | 1);
            }
            break;
        case 19:
            result &= ((29 != 1), f1(']', m0, 60));
            break;
        default:
            g3 %= ((("world"[3] ? "fooX"[2] : (int)sizeof(char)) ? (g2 ? g2 : m0) : (-39 ? 1 : 0)) | 1);
            break;
        }
        break;
    }
    {
        int _f23;
        for (_f23 = 0; _f23 < 10; _f23++) {
            g5 %= (((("world"[2] != -32) && ("abc123"[3] / ((int)sizeof(unsigned long) | 1))) % (((0 % (41 | 1)) + (result, g1)) | 1)) | 1);
        }
    }

    result = 0;
    result += (int)(g4);
    result += (int)(g3);
    result += (int)f6(f0((m0 >> (23)), (m0 ? "barY"[2] : (int)sizeof(long)), ("world"[1] + "abcd"[3])));
    result += (int)f6(f6(('b' << (22))));

    return (result >= 0 ? result : -result) & 255;
}
