/* Generated by cgen, seed=195 */

struct S0 {
    unsigned char m0;
    unsigned char m1;
    char m2;
    unsigned long m3;
    unsigned long m4;
};

struct S1 {
    unsigned char m0;
    long m1;
    int m2;
    long m3;
    unsigned char m4;
    char m5;
};

unsigned int g0 = 0;
unsigned long g1 = 0;
struct S0 gs2;

int f0(unsigned int p0, unsigned char p1, long p2, unsigned int p3);
char f1(void);
unsigned long f2(unsigned char p0, unsigned long p1, long p2);

int f0(unsigned int p0, unsigned char p1, long p2, unsigned int p3)
{
    int * v0_0;
    char * v0_1;
    v0_0 = 0;
    v0_1 = 0;

    {
        int _f0;
        for (_f0 = 0; _f0 < 1; _f0++) {
            {
                int _d1;
                _d1 = 0;
                do {
                    _d1++;
                    if ((p2 && (int)sizeof(char))) {
                        p0 = (6 & -41);
                    }
                } while (_d1 < 8);
            }
        }
    }
    g0 |= ((((p0 << (28)) / ((p0 | -12) | 1)) * ((p3 ? 74 : p0) % ((0 ^ p0) | 1))) / (((('O' ? (int)sizeof(unsigned int) : p0), (p3 ? 0 : 37)), ((p0 / (39 | 1)) == (119 ? p0 : 0))) | 1));
    v0_1 = &g0;
    return (g1);
}

char f1(void)
{
    struct S1 v1_0;
    v1_0.m0 = 1;
    v1_0.m1 = 10;
    v1_0.m2 = 122;
    v1_0.m3 = 31;
    v1_0.m4 = 1;
    v1_0.m5 = 213;

    goto _lbl2;
    _lbl2:
    g0 = f0((((g0, "abc123"[0]) < (33 >> (20))) < ((g1 ^ g1) == ((int)sizeof(unsigned int) ^ g1))), ((f0(g0, g1, -9, g1) ^ ('h' - 1)), ((g1 ? 225 : 58) == f0(g0, g0, -12, g0))), (((9786 - g0) == f0(10, '2', 8401, 67)) + (f0(-41, 75, -11, g1) != f0(g1, 9656, g1, 62))), ((("abc123"[5] >> (1)) - (g0 < g0)) || ((g1 ? "abcd"[0] : 3834) < (g0 > 0))));
    return (g0);
}

unsigned long f2(unsigned char p0, unsigned long p1, long p2)
{
    char * v2_0;
    int v2_1[8];
    v2_0 = 0;
    v2_1[0] = 54;

    ((((-50 ? 1 : '8') ? ('A' == (int)sizeof(int)) : (p1 << (30))), ((0 >> (22)) ? (v2_1[6], (int)sizeof(unsigned int)) : (g1 ? 'P' : 116))) < (((p1 ? "world"[4] : 1) ? (g1, p0) : (v2_1[4] != (int)sizeof(char))) ? ((g0 | "world"[1]) && (p2 + v2_1[2])) : ((p2 ? 0 : p2) ? (p1 < 6) : ('r' >> (8)))));
    v2_0 = &g1;
    *v2_0 = ((((g1 & p2) != (8527 - "abc123"[3])) ^ ((-34 ? g0 : p2) ? f0('*', 'l', g0, 1) : (0 == 122))) ? (((-4 || 6935), f1()) ^ (("hello"[1] - "barY"[0]) ? (v2_1[7] | p0) : (0 & '&'))) : f0(((']' & "hello"[4]) >> (30)), ((p0 ^ "hello"[1]) ^ (p0 || p1)), (('r' == 85) > ((int)sizeof(unsigned long) ? v2_1[0] : v2_1[0])), (('o' ? -14 : "barY"[2]), (g0 >> (25)))));
    return (g0);
}

int main(void)
{
    int result;
    char m0[3];
    unsigned long m1;
    long m2;
    char m3;
    result = 0;
    m0[0] = 6317;
    m1 = 8198;
    m2 = 94;
    m3 = -9;

    m1 %= ((f0((f0('*', m3, g0, m0[1]), (1 + "test"[2])), ((m3 % ("world"[0] | 1)) >> (29)), ((result && 97) << (29)), ((g1 % ("wxyz"[1] | 1)) - (g0 & 0))) == (f1() ^ ((96 ? 't' : 199) + ('P' ? m0[2] : m1)))) | 1);
    m2 &= ((((g1, g1) ? ((int)sizeof(unsigned int) > result) : (50 ? (int)sizeof(long) : result)), ((m2 ? g1 : m3) ? (194 | 0) : (g1 || m1))) ? (((m1 < 9820), (1 + g0)) == (f2(70, (int)sizeof(long), 1) ? (g0 && -42) : (m3 + g1))) : (((g1 << (13)) >> (6)), (f0('`', -13, g1, 1) % ((g0 >> (1)) | 1))));
    goto _lbl3;
    _lbl3:

    result = 0;
    result += (int)(m3);
    result += (int)(m1);
    result += (int)(m1);
    result += (int)f1();

    return (result >= 0 ? result : -result) & 255;
}
