/* Generated by cgen, seed=72 */

unsigned char g0 = 0;

unsigned char f0(int p0, unsigned long p1, char p2, unsigned int p3);

unsigned char f0(int p0, unsigned long p1, char p2, unsigned int p3)
{
    long v0_0;
    v0_0 = 1;

    p2 += ((((p1 ? v0_0 : (int)sizeof(unsigned char)) ? ("barY"[2] >> (7)) : (g0 ? g0 : p1)) && ((g0 || 29) * ((int)sizeof(unsigned long) / (3192 | 1)))) > (((2106 - v0_0) || (p3, p2)) * ((135 ? "barY"[2] : '@') | (p2 % (0 | 1)))));
    p3 &= (((('c' % (p1 | 1)) == (1, "abcd"[0])) << (12)) | ((((int)sizeof(int), -41) > (0 ? (int)sizeof(unsigned char) : p1)), ((v0_0, g0) || (g0 || -18))));
    {
        int _f0;
        for (_f0 = 0; _f0 < 8; _f0++) {
            switch ((("world"[0] / (1 | 1)) != (p3 ? p1 : 'U'))) {
            case 3:
                goto _lbl1;
                _lbl1:
                break;
            case 7:
                switch ((5817 / (6185 | 1))) {
                case 4:
                    g0 |= (p1 ? p0 : (int)sizeof(unsigned int));
                    if ("abc123"[0]) {
                        p0 *= 'C';
                        g0 /= ("test"[2] | 1);
                    }
                    break;
                case 7:
                    p0 -= (4638 & p0);
                    break;
                case 13:
                    g0 *= ((int)sizeof(unsigned long) >> (12));
                    break;
                default:
                    p2 %= ((72 / (0 | 1)) | 1);
                    p1 -= ((int)sizeof(unsigned int), g0);
                    break;
                }
                break;
            }
        }
    }
    {
        int _d2;
        _d2 = 0;
        do {
            _d2++;
            {
                int _d3;
                _d3 = 0;
                do {
                    _d3++;
                    (("wxyz"[2] - g0) % ((p1 >> (15)) | 1));
                    g0 = (("hello"[3] && 1) | ("test"[2] == p2));
                } while (_d3 < 3);
            }
        } while (_d2 < 10);
    }
    ((((p1 & 3315) != ("test"[1] - 175)) * ((v0_0 % (p2 | 1)) || (p2 == 84))), (((242 >> (24)) ? ("test"[1] << (8)) : ((int)sizeof(char) & "hello"[1])) && ((p1 & (int)sizeof(unsigned char)) && ('U' > 134))));
    if ((((p2 && 9545) || ((int)sizeof(char) != p2)) ? ((42 | p2) + ('Z' < 245)) : ((v0_0 % ((int)sizeof(unsigned char) | 1)) ? ("barY"[0], "hello"[4]) : (77 >> (25))))) {
        {
            int _d4;
            _d4 = 0;
            do {
                _d4++;
                v0_0 &= (('e' != (int)sizeof(long)) < (p2 < p0));
                p0 %= (((p1, p0) || (188 | p1)) | 1);
            } while (_d4 < 10);
        }
        v0_0 /= ((((240 ? v0_0 : 84) ? (v0_0 != p2) : (146 & 0)) << (24)) | 1);
        {
            int _w5;
            _w5 = 0;
            while (_w5 < 3) {
                _w5++;
                {
                    p0 *= (1 - (int)sizeof(unsigned long));
                }
                {
                    int _d6;
                    _d6 = 0;
                    do {
                        _d6++;
                        p2 /= ((-28 > (int)sizeof(long)) | 1);
                    } while (_d6 < 1);
                }
                v0_0 += ((p2, -1) | (1, -7));
            }
        }
    } else {
        p3 = ((("test"[0] == p0), (7959, (int)sizeof(int))) ? (("abcd"[1] & "test"[0]) ? ((int)sizeof(unsigned long) > '9') : (p3 + (int)sizeof(long))) : (((int)sizeof(char) & p0), ((int)sizeof(unsigned long) ? 'S' : p1)));
    }
    return (v0_0);
}

int main(void)
{
    int result;
    unsigned char m0;
    char m1;
    unsigned char m2;
    result = 0;
    m0 = 1;
    m1 = 234;
    m2 = -5;

    g0 %= (((((m1 << (21)) > (result & ':')) >> (6)) ? (f0(((int)sizeof(unsigned char) != 5389), ("abcd"[0] ^ m0), (g0 != 5448), (g0 ^ 'A')) > ((g0 ? m2 : m1) == (result > m0))) : ((f0(110, m0, 6230, 21) ? (0 && m1) : f0(m0, 1, result, 'x')) ^ ((g0 || "abcd"[0]) >> (1)))) | 1);
    m0 *= ((((m0 % (result | 1)) / (('E' > 1) | 1)) && ((m0 * m0) ? (-35 ? m1 : result) : (-20 && "wxyz"[0]))) || (f0((0 ? 6272 : 'O'), ((int)sizeof(long), g0), (0 < 5133), (226 & m1)), ((0 << (11)), ('E' << (2)))));

    result = 0;
    result += (int)(m0);
    result += (int)f0((f0(1, g0, 169, m0) > (0 ? "test"[2] : -24)), ((m0 && m2) / ((g0 / ("test"[2] | 1)) | 1)), (((int)sizeof(long), "world"[2]) ? (m2 >> (21)) : (-10 * 'Z')), f0((-6 | -4), f0(33, 39, m2, 0), f0(result, "abcd"[1], "hello"[3], m2), (m1 % (g0 | 1))));

    return (result >= 0 ? result : -result) & 255;
}
