/* Generated by cgen, seed=353 */

struct S0 {
    char m0;
    int m1;
    char m2;
    unsigned char m3;
    long m4;
    char m5;
};

struct S1 {
    int m0;
    char m1;
};

struct S2 {
    unsigned char m0;
    int m1;
    int m2;
    unsigned int m3;
    unsigned long m4;
    long m5;
};

int g0[8];
int g1 = 86;
long g2 = -32;
int g3[5];
unsigned int g4;
int g5 = 1;
int g6;
int g7[15];

unsigned long f0(long p0);
unsigned char f1(unsigned char p0, unsigned char p1, unsigned char p2);
int f2(unsigned char p0);
unsigned char f3(void);

unsigned long f0(long p0)
{
    struct S1 v0_0;
    char v0_1[5];
    unsigned char v0_2;
    unsigned int v0_3;
    int * v0_4;
    v0_0.m0 = -10;
    v0_0.m1 = 1;
    v0_1[0] = -18;
    v0_2 = 5246;
    v0_3 = 69;
    v0_4 = 0;

    {
        int _d0;
        _d0 = 0;
        do {
            _d0++;
            {
                int _d1;
                _d1 = 0;
                do {
                    _d1++;
                    g5 *= ((g1 == (int)sizeof(long)) * (g7[9], 'f'));
                    ((g4 & g2) < (0 < g5));
                } while (_d1 < 3);
            }
            g4 -= (((g6, g4) > (g2 & g7[12])) ^ ((0 ? 43 : 2) ? (g1 ? v0_3 : v0_3) : (-40 / (g2 | 1))));
        } while (_d0 < 9);
    }
    if (((("abcd"[0] % (p0 | 1)) ? (v0_1[0] < g2) : (g5 * v0_3)) ^ (("abcd"[0] ? v0_2 : v0_3) ? (p0 && 189) : (g7[12] * -32)))) {
        (((1 != "fooX"[1]) + (4918 ? -49 : 8544)) % ((("wxyz"[0] != 97) % ((g2 && g2) | 1)) | 1));
    }
    p0 += ((((g1 || 0) > (72 ? "abc123"[5] : "test"[3])) & ((2536 > g4), (g1 - 0))) & ((('_' || v0_2) | ('z' && g7[13])), ((75, v0_2) > (g1 == 1))));
    (((('*' + -10) ? (1 && "wxyz"[1]) : ("barY"[1] > "wxyz"[0])) - ((13 < v0_2) && (-43, v0_1[3]))) % ((((g2 < 0) ? (-35 ? 'A' : p0) : (v0_2 / (g2 | 1))) ? ((g5 != 'P') > (0 % (v0_3 | 1))) : ((5875 > g4) || (1 + "hello"[3]))) | 1));
    switch ((((1 | 'r') ? (1 ? "barY"[0] : (int)sizeof(unsigned long)) : (1 ? 8866 : 's')) == ((g6 ? g6 : g2) * (1 % ((int)sizeof(int) | 1))))) {
    case 3:
        g1 &= ((("hello"[1], g4) == (94 != g3[3])) || ((g5 ? g4 : -19) + (v0_3 < 0)));
        g1 = ((("barY"[3] - "abc123"[0]) ? (96 != g7[1]) : (g0[3], "test"[3])) < (((int)sizeof(char) ? g6 : g4) || (70 > v0_3)));
        break;
    case 9:
        g1 %= ((((v0_3 + g3[0]) ? (p0 << (17)) : (v0_3 ? 1 : p0)) ? ((g0[5] != 206), (g6 % (1 | 1))) : ((g6 || 'O') << (14))) | 1);
        break;
    case 14:
        {
            g2 -= (("abcd"[1] || g7[6]) || (g3[4] ^ 52));
            g6 /= ((('n' >> (22)) & (g2 & -23)) | 1);
            v0_3 &= ((7820 ? 0 : v0_3) ^ (v0_2 * 1));
        }
        g7[3] = (((p0 >> (24)), ("hello"[3], (int)sizeof(int))) / (((g2 ? g1 : g1) - (g7[6], 15)) | 1));
        break;
    case 18:
        switch (((v0_3 == 3725) ? (46 > 7944) : (v0_3 != v0_1[2]))) {
        case 0:
            ((g5 % (g2 | 1)) ? ((int)sizeof(char), 1) : (9084 == 83));
            break;
        default:
            g4 |= ((v0_1[2] + '}') != (2128 < g5));
            break;
        }
        p0 *= ((('1' * g4) < ((int)sizeof(unsigned char) - 90)) > ((g5 != 0) != ((int)sizeof(char) >> (3))));
        break;
    case 22:
        g7[11] = (((v0_1[2] % (6484 | 1)) != ('_' || 0)) && ((g5 != "wxyz"[0]) >> (30)));
        {
            {
                p0 *= (g1 & 44);
            }
            g2 *= ((-9 | g5) - (p0, 1));
        }
        break;
    }
    goto _lbl2;
    _lbl2:
    return (v0_2);
}

unsigned char f1(unsigned char p0, unsigned char p1, unsigned char p2)
{
    unsigned char v1_0;
    v1_0 = 0;

    p2 *= ((((g0[7] != 1) ? f0(p2) : (941 < 239)), (f0((int)sizeof(char)), (30 ? p0 : p1))) == (f0(((int)sizeof(unsigned char) || 213)) / (((g3[0] | 42) - f0(')')) | 1)));
    switch (((('7' / ((int)sizeof(long) | 1)) % (f0((int)sizeof(int)) | 1)) | (f0((int)sizeof(unsigned long)) || (6045 - g7[3])))) {
    case 0:
        p1 -= (((g7[9], 119) | f0(61)) << (21));
        g4 %= (f0(((61 / (70 | 1)) ? (g4 - (int)sizeof(unsigned char)) : (121 && p0))) | 1);
        break;
    case 7:
        g0[2] = f0(((1 ? "abc123"[5] : 'o') * (g1 || ',')));
        break;
    }
    (((f0('K') >> (1)) / ((('M' < g2) * ("wxyz"[0] < (int)sizeof(char))) | 1)) % ((((p0 ^ -9) > f0(0)) ? f0((g1 & p1)) : ((165 - 98) ^ (p2 * -35))) | 1));
    {
        p0 += f0(((8404, (int)sizeof(int)) * ("hello"[3] > g6)));
    }
    g4 %= (f0((((v1_0 >> (9)) > (g0[6] < -5)) > (f0(g5) >> (13)))) | 1);
    return (g2);
}

int f2(unsigned char p0)
{
    int v2_0[8];
    int v2_1;
    char v2_2[8];
    unsigned int v2_3;
    int v2_4;
    long v2_5;
    v2_0[0] = 0;
    v2_1 = 15;
    v2_2[0] = 7160;
    v2_3 = 0;
    v2_4 = 225;
    v2_5 = 0;

    switch (((((int)sizeof(int) ? 5185 : g3[3]) > (8728 ? "hello"[2] : g5)) ? f1((0 ? 85 : 40), (30 | g2), f1('U', p0, g1)) : ((g3[3] & p0) >> (6)))) {
    case 4:
        goto _lbl3;
        _lbl3:
        break;
    case 6:
        ((f1(v2_0[7], (int)sizeof(unsigned int), 'y') ? ('c' * (int)sizeof(long)) : (g5 + v2_4)) < (((int)sizeof(long) | "hello"[2]) >> (1)));
        break;
    case 11:
        {
            int _d4;
            _d4 = 0;
            do {
                _d4++;
                g2 = ((p0 >> (20)) > f1("barY"[3], -36, (int)sizeof(int)));
            } while (_d4 < 8);
        }
        break;
    case 17:
        g5 |= f1((f0(p0) != (v2_5 << (9))), ((p0 - g5), (g4 ? v2_3 : v2_3)), ((1, (int)sizeof(unsigned long)), ((int)sizeof(long) || v2_3)));
        break;
    case 21:
        if (((g6 ? g6 : v2_5) - (4054 | g3[3]))) {
            ((v2_0[7] % (173 | 1)) > ("barY"[1] | 689));
        }
        break;
    }
    {
        int _d5;
        _d5 = 0;
        do {
            _d5++;
            if ((f1(v2_1, "barY"[0], g4) | (5782 / ('J' | 1)))) {
                f1((g5 != v2_4), (v2_3, (int)sizeof(int)), (1 ? (int)sizeof(unsigned long) : '='));
            } else {
                {
                    int _d6;
                    _d6 = 0;
                    do {
                        _d6++;
                        v2_1 |= ((int)sizeof(long) ? v2_3 : (int)sizeof(unsigned long));
                    } while (_d6 < 3);
                }
            }
        } while (_d5 < 7);
    }
    return (v2_5);
}

unsigned char f3(void)
{
    char v3_0;
    v3_0 = 58;

    ((f0(('`' == 902)) || (('8' ? 1342 : '"') ? (g5 == g7[9]) : (g2 ? 1 : "abcd"[0]))) < f2(((9992 % ("hello"[1] | 1)) < f0(v3_0))));
    g2 /= (((((g2 ^ g4) ? (1 ? (int)sizeof(unsigned long) : 5427) : ("wxyz"[2] + 0)) && ((g0[6] || g5) || (-38 % (g6 | 1)))) % (((f1(153, g1, g5) + (v3_0 << (27))) < f0((-26 && '_'))) | 1)) | 1);
    g6 %= ((f0((f1(g0[2], g2, '9') * (g6 % (55 | 1)))) >> (25)) | 1);
    if (((('B' % ((int)sizeof(int) | 1)) == f1(g2, 'd', g3[4])) != f2(((int)sizeof(unsigned long) ? g3[2] : -37)))) {
        g5 /= ((f1(((int)sizeof(char) + 5768), ('>' - -40), (g6, g4)) || ((100 * "wxyz"[3]) < (0 ? g5 : 310))) | 1);
    }
    g4 %= (((((53 ? g7[8] : g6), ((int)sizeof(long) << (22))), ((175 << (29)) ? f1(g1, 57, g7[0]) : (1 ^ v3_0))) | ((f2('T') << (7)) - ((57 << (17)) && f0(1)))) | 1);
    g4 &= ((((1 > g4) && (g7[7] && 0)) & f0((v3_0 ? "hello"[2] : v3_0))) < (f1((v3_0 * g1), (-16 > g5), ((int)sizeof(long), 's')) < f1(f1('|', g0[6], (int)sizeof(unsigned int)), (1 >> (23)), f2(g7[2]))));
    g0[0] = ((((3047 > 3150) ? (g1, g2) : (g1 ? (int)sizeof(unsigned long) : g4)), (((int)sizeof(unsigned int) ? g2 : v3_0) ? (g4 % ("hello"[4] | 1)) : ((int)sizeof(unsigned long) != "world"[1]))) ^ (((v3_0 - "wxyz"[2]), ("abcd"[1], v3_0)) ? ((-27 != g6) ^ (g0[0] != 5)) : ((g0[1] | g4) ? (g6, g4) : f0(201))));
    g1 |= f0((f2(f0('7')) + (f1(g1, g4, g7[12]) << (20))));
    return (g2);
}

int main(void)
{
    int result;
    struct S0 m0;
    result = 0;
    m0.m0 = 210;
    m0.m1 = -38;
    m0.m2 = 43;
    m0.m3 = 7397;
    m0.m4 = -37;
    m0.m5 = 1;

    g7[8] = (((f1(-50, g5, g2), ('Y' & result)) & f2((g7[6] == g2))), (((83 + (int)sizeof(unsigned long)) == (1 - "hello"[2])) != (("test"[0], '8') ? ((int)sizeof(unsigned long) || 'm') : f1(g7[0], (int)sizeof(unsigned char), 2514))));
    (f3() ? ((("world"[4] ^ -28), (g1 << (15))), ((g2 >> (29)) * ('r' != 3))) : (((g1 == 173) ? (g6 < g4) : (g0[6] || 19)) ? ((6887 ? 232 : g3[2]) != f2(g6)) : ((g1, g1) ? (g2 ? 'e' : g6) : (0 ? g4 : result))));
    {
        int _f7;
        for (_f7 = 0; _f7 < 2; _f7++) {
            g7[12] = (((g1, g1) & f3()) >> (13));
        }
    }
    {
        int _d8;
        _d8 = 0;
        do {
            _d8++;
            g4 /= ((((g2 ? g3[2] : "wxyz"[0]) - (102 & g6)) / (((64 ? '?' : -15), (g6 / ('$' | 1))) | 1)) | 1);
        } while (_d8 < 7);
    }
    g1 *= (((('_', g5) ? (0, 'Q') : (g4 & 1)) * ((g1 ? (int)sizeof(long) : 69) ? ((int)sizeof(long) > g7[2]) : (result, g6))) ^ (((0 << (9)) / ((1 > result) | 1)) ? ((g4 && result) ? ("barY"[2] >> (4)) : (result != g0[7])) : (f2('*') >> (4))));
    g7[10] = ((((g7[13] < 0) && ("abcd"[3] ? result : result)) << (30)) * f1(f1((g1 * result), (144 ? 0 : (int)sizeof(unsigned char)), (g2 < "test"[2])), ((211 % (g1 | 1)) ? (result != (int)sizeof(int)) : ("wxyz"[2] < result)), (f3() ? f1((int)sizeof(unsigned long), -10, g4) : (3028 || g4))));
    g4 = (f0(((g5 ^ 0) + (g2, 5455))), (f0(f3()) ? (f3() != (result << (10))) : (f3() * f3())));
    m0.m3 = (((f3() ? (78 - 1) : (g5 ? (int)sizeof(unsigned int) : g2)) / ((((int)sizeof(unsigned char) || '-') % ((g2 > 97) | 1)) | 1)) >> (30));

    result = 0;
    result += (int)(g6);
    result += (int)(g6);
    result += (int)f2(((1 ? (int)sizeof(unsigned long) : 0) ? ("fooX"[2] > g7[1]) : (g5 ? g5 : g1)));
    result += (int)f3();
    result += (int)f0(f1((result / ("wxyz"[1] | 1)), ((int)sizeof(unsigned char) ? 7458 : (int)sizeof(long)), (g5 != 205)));

    return (result >= 0 ? result : -result) & 255;
}
