/* Generated by cgen, seed=241 */

char g0 = 1;
int g1;
char g2;
unsigned int g3;

unsigned int f0(long p0, unsigned char p1, unsigned long p2, unsigned long p3, char p4);

unsigned int f0(long p0, unsigned char p1, unsigned long p2, unsigned long p3, char p4)
{
    char v0_0[6];
    int v0_1;
    unsigned long v0_2;
    unsigned long v0_3;
    int * v0_4;
    long v0_5;
    v0_0[0] = 160;
    v0_1 = 1;
    v0_2 = 103;
    v0_3 = -33;
    v0_4 = 0;
    v0_5 = 0;

    p3 = ((((p4 % (g2 | 1)) & ((int)sizeof(unsigned char) ? 1 : 1)) != ((g1, p0) && ((int)sizeof(char) * g3))), ((('`' && (int)sizeof(char)) * ("fooX"[1] * 0)), (((int)sizeof(unsigned char) != p3) ^ ((int)sizeof(unsigned char) | 5540))));
    {
        int _d0;
        _d0 = 0;
        do {
            _d0++;
            v0_0[5] = (((-37 > v0_1) ^ (v0_1 | p2)) + (('}' && "fooX"[0]) / ((v0_1 * v0_2) | 1)));
        } while (_d0 < 6);
    }
    return (g0);
}

int main(void)
{
    int result;
    int m0[8];
    int m1;
    char m2[2];
    long m3;
    int * m4;
    int * m5;
    result = 0;
    m0[0] = 1;
    m1 = 1017;
    m2[0] = 1313;
    m3 = 1524;
    m4 = 0;
    m5 = 0;

    result /= ((((f0((int)sizeof(unsigned char), g3, m3, 0, (int)sizeof(char)), (1 + -39)) >> (8)) < (((m2[0] || 0) * (g3, m0[0])) << (6))) | 1);
    g1 %= ((((f0(m0[7], 'H', "test"[1], g2, result) | (235 || g1)) < (('M' != 'B') | (g3 - 24))) || (((m1 < 1) < ("abc123"[1] | 287)) ^ (f0(m0[3], -31, (int)sizeof(int), "world"[1], 1) ? (g1 == 1) : (m1 ? 'F' : g2)))) | 1);
    {
        int _f1;
        for (_f1 = 0; _f1 < 2; _f1++) {
            g2 |= ((("hello"[0] ? '%' : g1) + ("wxyz"[2] ^ "hello"[2])) || (((int)sizeof(char) << (6)) ? (7216 * m1) : (50 << (3))));
            result *= (((g2, g2) || f0((int)sizeof(int), g3, g0, '@', m0[2])) == f0((result == 'W'), (m3 * 0), (result ? m3 : result), f0("world"[4], m2[0], m3, (int)sizeof(unsigned int), (int)sizeof(unsigned int)), (g1 | "world"[2])));
        }
    }

    result = 0;
    result += (int)f0(((g2 != m0[0]) | f0(-19, 208, m0[2], m3, m1)), f0((result == "abc123"[2]), (2058 - g0), (80 >> (1)), f0((int)sizeof(int), 1, 83, 100, "world"[2]), (g1 < g2)), ((m2[1] + 78) && ('~' > m0[1])), ((result ^ 7336) > (23 * m1)), f0((g1 || g3), ("barY"[1] - g3), (result, (int)sizeof(unsigned char)), (g0 & m2[0]), ((int)sizeof(long) && 0)));
    result += (int)f0(((g0 ^ "abc123"[0]) ^ f0((int)sizeof(int), "test"[3], 7379, "abcd"[0], m3)), (('%' << (14)) || f0(m1, -17, result, ';', m2[1])), ((1 == '/') && (g1 - g0)), (("barY"[3] ? m1 : m0[3]) != (g0 ? g1 : g1)), f0(("barY"[0] >> (16)), (m1 ? g0 : 1312), ((int)sizeof(long) ? "fooX"[0] : 83), (g0, m0[3]), (m2[1] || "test"[3])));
    result += (int)f0((f0(1, 'n', m3, result, g3) ? (g2 ? m0[1] : 0) : (g0 >> (10))), ((g2 ^ 1) && (m2[1] > 66)), f0(('(' < m3), (g1 - g3), (126 != m1), (g0 % (8967 | 1)), (1 % (m3 | 1))), (("world"[1], 211), (m0[6] | result)), f0((result - g3), (g1 < "hello"[1]), ("barY"[1] && result), (g3 && g3), ((int)sizeof(long) % (m1 | 1))));

    return (result >= 0 ? result : -result) & 255;
}
