/* Generated by cgen, seed=32 */

long g0 = 224;
int g1[3];
int g2;

int f0(unsigned long p0, unsigned char p1, char p2, int p3);

int f0(unsigned long p0, unsigned char p1, char p2, int p3)
{
    int v0_0[2];
    v0_0[0] = 1;

    g0 = ((((p0 > g0) && ("abc123"[0] < "test"[0])) || ((40 >> (2)) != ('M' ? p1 : "hello"[4]))) == ((("hello"[1] && g0) != (p2 && "wxyz"[3])) ? (("test"[0] - -50) ? (8922 > 'a') : (g1[1] << (7))) : ((0 && g0) ? (4076 % ((int)sizeof(unsigned int) | 1)) : (0 << (3)))));
    {
        int _f0;
        for (_f0 = 0; _f0 < 7; _f0++) {
            switch ((('-' && 0) % (('A' % (1 | 1)) | 1))) {
            case 1:
                {
                    int _w1;
                    _w1 = 0;
                    while (_w1 < 2) {
                        _w1++;
                        p2 += (p0 ^ g0);
                        p1 *= (p0 > p3);
                    }
                }
                break;
            case 6:
                {
                    if (g2) {
                        g2 /= ("wxyz"[2] | 1);
                    }
                    if (1283) {
                        p0 %= ((int)sizeof(unsigned int) | 1);
                    }
                }
                break;
            case 13:
                p3 -= (('3' % (p0 | 1)) ^ (p2 || (int)sizeof(unsigned int)));
                break;
            case 16:
                ((v0_0[0] & v0_0[1]) * (v0_0[1] / ((int)sizeof(char) | 1)));
                break;
            }
        }
    }
    {
        int _w2;
        _w2 = 0;
        while (_w2 < 5) {
            _w2++;
            {
                int _w3;
                _w3 = 0;
                while (_w3 < 10) {
                    _w3++;
                    {
                        int _w4;
                        _w4 = 0;
                        while (_w4 < 4) {
                            _w4++;
                            p2 -= (p1 && g1[2]);
                        }
                    }
                }
            }
            p0 /= ((((g0 / (-29 | 1)) % ((0 < p3) | 1)) != ((p1 ? p0 : 159) ? ('9' + 114) : (1 / ("barY"[1] | 1)))) | 1);
            switch (((p3 >> (27)) ^ (g1[0] ^ (int)sizeof(unsigned char)))) {
            case 1:
                p3 *= ((p2 ? 'F' : p2) > (-35 ? (int)sizeof(char) : 33));
                break;
            case 5:
                g1[0] = ((g1[1] == "barY"[1]) & (p1 >> (11)));
                break;
            default:
                v0_0[1] = ((1 | 71), ((int)sizeof(unsigned long) == g1[1]));
                break;
            }
        }
    }
    p1 *= ((((p2 | 'l') * (-34 ^ g0)), ((p3 ? 'J' : p3), (0 || (int)sizeof(char)))) ? (((p1 < 'z') || (1816 || p3)) > ((v0_0[0] ? g2 : 2) + (g0 < p1))) : ((((int)sizeof(unsigned int) == "test"[1]) && (p1 << (15))) + (((int)sizeof(char) >> (7)) | (g0 - p3))));
    p1 += (((("barY"[2] % (p0 | 1)) ? ("hello"[3] ? p0 : 79) : (g1[1] | 1)), (((int)sizeof(char) / ('v' | 1)) >> (7))), (((v0_0[0] ? 0 : 0) && (g1[2], 105)) + ((-15 | p1) == (p0 && p2))));
    p1 -= (((('Y' ? p0 : p0) < (p3 == p2)) & ((0 + g1[0]) ^ (g2 ^ p2))) ? (((p3 * p3) * ((int)sizeof(long) / (g2 | 1))) + (((int)sizeof(unsigned char) ? p0 : p3) - (p0 || g2))) : (((19 + g0) ? (p1 << (26)) : (p2 ? 77 : g2)) & (((int)sizeof(unsigned char) / (g1[0] | 1)) < (p3 << (1)))));
    p3 /= (((((3 * v0_0[1]) * (p2 ? v0_0[0] : -28)) ? (("world"[0] - p1) > ("abcd"[3] > g2)) : ((3356 || 7850) ^ (p2 & 0))) + (((g2 ? "test"[0] : p1) - (']' < p1)) >> (9))) | 1);
    p0 %= (((((70 != -50) ? (p3 != 25) : (p3 ? g2 : p0)) & ((p0, 'O') ^ (0 + g0))) ^ (((p2 < 1) ^ ('O' << (21))) + ((g0 ? p1 : "abcd"[1]), (p1 / ('D' | 1))))) | 1);
    if (((("wxyz"[2] * 3815) > ('I' % (g0 | 1))) * (((int)sizeof(char) ? p3 : 1) != (p3 < 92)))) {
        {
            int _f5;
            for (_f5 = 0; _f5 < 6; _f5++) {
                g2 %= (((9566 ^ v0_0[1]), (1 + 0)) | 1);
            }
        }
        p2 |= (((0, p2) ? ('%' == g1[0]) : ((int)sizeof(unsigned int) ^ '5')) | ((p1 | p0) | ("test"[1] + v0_0[0])));
    }
    p3 *= ((((p0 * (int)sizeof(char)) != ((int)sizeof(unsigned char) ? g1[2] : p0)) ? ((g2 << (2)) ? ("hello"[2] / (70 | 1)) : (p0 != p3)) : (((int)sizeof(unsigned char) + 143), ('A' ? p0 : p0))) < ((("barY"[3] / ('P' | 1)) ? (p2 && g2) : (g1[1] / (-36 | 1))) != ((5728, v0_0[0]) != (p0 - p0))));
    switch ((((0 < 0) % (((int)sizeof(unsigned char) ^ p0) | 1)) & ((p1 / (g0 | 1)) ? (p3 + '4') : (p0 > 90)))) {
    case 4:
        {
            switch ((29 < (int)sizeof(long))) {
            case 0:
                p1 /= ((p3 ? p3 : 382) | 1);
                break;
            case 5:
                p3 = ("hello"[0] != ';');
                break;
            case 13:
                p1 += (p0 + 'W');
                break;
            default:
                switch (v0_0[1]) {
                case 0:
                    p1 = (int)sizeof(char);
                    break;
                default:
                    p1 *= 0;
                    p2 = p3;
                    break;
                }
                break;
            }
            g0 += (((int)sizeof(int) * 96) ? ((int)sizeof(unsigned int), g2) : (g2 << (22)));
            {
                int _d6;
                _d6 = 0;
                do {
                    _d6++;
                    g0 += (g1[0] & p3);
                } while (_d6 < 3);
            }
        }
        break;
    case 8:
        if ((("abc123"[1] ? '@' : p3) ^ (g0 + 22))) {
            p2 *= ((66 / (p3 | 1)) % (((int)sizeof(int) != 1) | 1));
        }
        {
            int _w7;
            _w7 = 0;
            while (_w7 < 1) {
                _w7++;
                {
                    p2 &= (v0_0[1] | 'v');
                    p0 = (p3 != 47);
                    g2 |= (50 - (int)sizeof(long));
                }
            }
        }
        break;
    case 13:
        if (((p1 << (19)) ? (v0_0[1] ? g1[1] : v0_0[1]) : (g1[1] | p2))) {
            g2 /= ((((int)sizeof(int) ^ -9), (3133 == p1)) | 1);
            if ((p3 && g1[0])) {
                g2 = ("fooX"[0] < p0);
            } else {
                g2 *= (g2 < p3);
            }
            {
                int _w8;
                _w8 = 0;
                while (_w8 < 4) {
                    _w8++;
                    g2 += ("wxyz"[2] / (p1 | 1));
                }
            }
        } else {
            p2 += (((int)sizeof(unsigned long), p3) >> (5));
            g2 &= ((5556 - "abcd"[2]) - ('O' >> (23)));
        }
        break;
    case 17:
        switch ((("world"[4] ? '+' : p1) == ("abcd"[3] % ((int)sizeof(long) | 1)))) {
        case 2:
            v0_0[0] = ((p1 ? p3 : g2), (p2 | p1));
            break;
        case 5:
            v0_0[1] = (((int)sizeof(long) != 0) * (133 & p0));
            break;
        case 14:
            p0 &= (("world"[2] || "abcd"[1]) * (p1 ? 0 : p2));
            break;
        case 17:
            switch ((1 * g2)) {
            case 3:
                p0 |= (g2 * p2);
                break;
            default:
                if (g2) {
                    p2 &= -28;
                } else {
                    p1 -= "world"[2];
                }
                break;
            }
            break;
        case 20:
            {
                int _f9;
                for (_f9 = 0; _f9 < 3; _f9++) {
                    g2 &= ("abc123"[1] < g1[0]);
                }
            }
            break;
        default:
            g0 += ((p0 ? '$' : g0), (g0 & 'f'));
            g0 &= ((p3 & p3) % ((g1[1] << (12)) | 1));
            break;
        }
        break;
    case 20:
        {
            int _d10;
            _d10 = 0;
            do {
                _d10++;
                p3 -= ((g2 | 3) / ((-17 ^ p2) | 1));
                p0 /= (((p2 - 189) ? (p1 > g0) : (8927 ^ (int)sizeof(int))) | 1);
            } while (_d10 < 6);
        }
        break;
    default:
        p0 *= (((v0_0[1], p3) - ("hello"[0] / (139 | 1))) || ((g1[0] % ('t' | 1)) || (0 % (6749 | 1))));
        break;
    }
    return (p1);
}

int main(void)
{
    int result;
    unsigned long m0;
    char m1;
    result = 0;
    m0 = 78;
    m1 = 6912;

    g1[2] = ((((8 % ((int)sizeof(unsigned int) | 1)) < (g1[1] % (g0 | 1))) >> (0)) | ((("abc123"[3] && m1) ? (85 && (int)sizeof(int)) : (g2 | 81)), (('`' != 550), (g0, g1[0]))));
    {
        int _d11;
        _d11 = 0;
        do {
            _d11++;
            g1[0] = ((f0(1, "wxyz"[1], 91, 303) << (12)) ^ ((g0, "fooX"[2]) - f0(result, 'V', g0, 'u')));
        } while (_d11 < 6);
    }
    g0 += ((((g0 & m0) >> (13)) >> (15)) - (((g2 + g0) / ((-39, m1) | 1)) % (((m0 | result) && ("abcd"[1] - "world"[0])) | 1)));

    result = 0;
    result += (int)(g0);
    result += (int)f0(f0((g0 == result), (m1 ? g1[2] : (int)sizeof(unsigned int)), (48 > g1[0]), (-36 || (int)sizeof(char))), ((g1[0] + -1) ^ (g2 < 0)), f0((m0 >> (4)), (m0, 0), f0(g2, '9', (int)sizeof(long), m1), f0((int)sizeof(unsigned char), g1[2], (int)sizeof(long), m0)), f0((1 + 30), (g2 - result), (-20 || 0), (64, g2)));
    result += (int)f0(((g0 == (int)sizeof(unsigned int)) | ((int)sizeof(unsigned char) == m0)), ((m1 ? 'B' : 0) && ('_' < g0)), ((-35 * m1) | ('U' / ("wxyz"[0] | 1))), ((100 != g2) + (7407 != m1)));

    return (result >= 0 ? result : -result) & 255;
}
