/* Generated by cgen, seed=161 */

int g0;
int g1[12];
char g2 = 6834;
int g3;

unsigned int f0(unsigned char p0);

unsigned int f0(unsigned char p0)
{
    int v0_0;
    v0_0 = 7;

    {
        int _d0;
        _d0 = 0;
        do {
            _d0++;
            goto _lbl1;
            _lbl1:
            switch ((((int)sizeof(int) - 1) | ((int)sizeof(unsigned char), g2))) {
            case 3:
                g1[9] = ((p0 | g0) != ("wxyz"[0] & v0_0));
                break;
            default:
                {
                    int _d2;
                    _d2 = 0;
                    do {
                        _d2++;
                        v0_0 *= (g1[8] | 156);
                        g3 *= (']' != -49);
                    } while (_d2 < 2);
                }
                break;
            }
        } while (_d0 < 7);
    }
    return (g2);
}

int main(void)
{
    int result;
    unsigned char m0;
    result = 0;
    m0 = 231;

    ((((-46 % (6355 | 1)) ? ("test"[1] * result) : (g0 + 'w')) * ((m0 ? -46 : 147) ^ f0(192))) >> (23));
    f0((((161 % (166 | 1)) > ((int)sizeof(char) % (0 | 1))) + ((74 & -46), ("abc123"[0] >> (0)))));
    {
        int _d3;
        _d3 = 0;
        do {
            _d3++;
            f0(f0(("abcd"[0] % (g1[10] | 1))));
            g3 += ((f0((int)sizeof(int)) || (1 ? "abc123"[1] : 153)), (('s' / ("test"[1] | 1)) - (g1[3] == g2)));
        } while (_d3 < 1);
    }
    result /= (((((g0 & g2) ? (g2 >> (19)) : ('"' - g0)) >> (10)) && f0((("wxyz"[0] != (int)sizeof(unsigned long)) % ((result != 0) | 1)))) | 1);

    result = 0;
    result += (int)(g3);
    result += (int)f0(((-48 - result) / ((1278 && 172) | 1)));
    result += (int)f0(f0((0 ? m0 : g1[10])));

    return (result >= 0 ? result : -result) & 255;
}
