/* Generated by cgen, seed=200 */

struct S0 {
    unsigned int m0;
    char m1;
    unsigned long m2;
};

unsigned long g0 = 33;

unsigned long f0(unsigned int p0);
unsigned int f1(unsigned char p0, unsigned int p1, unsigned int p2, long p3);

unsigned long f0(unsigned int p0)
{
    int v0_0;
    char v0_1;
    unsigned int v0_2;
    v0_0 = 83;
    v0_1 = -18;
    v0_2 = 41;

    v0_1 += (((("wxyz"[0] & 1) - (v0_1, (int)sizeof(char))) % (((1 | "hello"[3]) / ((v0_0 - g0) | 1)) | 1)) ? (((66 == 'r') ^ (1 ? 0 : "fooX"[2])) << (19)) : (((v0_1, v0_2) ? (1 != 4) : (7 || ' ')), ((87 + "abcd"[1]) || ((int)sizeof(char) < -45))));
    g0 -= ((((v0_1 != -36) / ((1, 0) | 1)) == ((v0_0 * 8191) ^ (-23 + v0_1))) | (((0 > 98) == (v0_2 % ('3' | 1))) - ((43 * (int)sizeof(unsigned char)) < (0, v0_1))));
    {
        int _w0;
        _w0 = 0;
        while (_w0 < 8) {
            _w0++;
            {
                int _d1;
                _d1 = 0;
                do {
                    _d1++;
                    v0_2 %= ((('@' << (14)) == (1 + 7840)) | 1);
                } while (_d1 < 4);
            }
            if (((v0_0 != -12) >> (7))) {
                {
                    v0_1 /= ((v0_2 ? p0 : "hello"[3]) | 1);
                }
            } else {
                v0_0 += ((79 ? (int)sizeof(unsigned long) : g0) || (p0, 4));
            }
        }
    }
    return (v0_0);
}

unsigned int f1(unsigned char p0, unsigned int p1, unsigned int p2, long p3)
{
    unsigned int v1_0;
    char v1_1[7];
    int v1_2;
    char v1_3;
    v1_0 = 94;
    v1_1[0] = 0;
    v1_2 = 147;
    v1_3 = 230;

    p0 &= f0((((15 ^ ']') << (15)) << (18)));
    {
        int _w2;
        _w2 = 0;
        while (_w2 < 5) {
            _w2++;
            {
                int _w3;
                _w3 = 0;
                while (_w3 < 2) {
                    _w3++;
                    {
                        int _w4;
                        _w4 = 0;
                        while (_w4 < 3) {
                            _w4++;
                            p0 += (p3 / (80 | 1));
                            p1 -= ("abcd"[2] << (15));
                        }
                    }
                    f0(('L' ? v1_2 : 0));
                }
            }
        }
    }
    return (g0);
}

int main(void)
{
    int result;
    unsigned int m0;
    char * m1;
    unsigned char m2;
    result = 0;
    m0 = 0;
    m1 = 0;
    m2 = 158;

    result -= (((f1(m0, "fooX"[1], g0, -7) != ((int)sizeof(long) << (8))) < (f1((int)sizeof(char), 29, result, m0) * ('G' + 0))) % ((((result | m2) == (m0 == 126)) == ((m2 + (int)sizeof(long)), ('X' << (12)))) | 1));
    m0 %= ((f0(((2175 * 31) & ("hello"[0] == g0))) ? ((("wxyz"[2] - m0) >> (15)), ((0 ? -1 : 125), (m0 ^ ';'))) : ((f1(g0, 'g', g0, "barY"[1]) ^ f0(g0)) ? (((int)sizeof(unsigned long) >> (30)) ^ (0 | 78)) : ((result, g0), (25 ? 1 : '@')))) | 1);
    (((("abcd"[1] ? "barY"[0] : 1) == ('#' % ((int)sizeof(long) | 1))) ? ((239 > 44) ? (-25 > 6190) : (m2 > 1)) : (((int)sizeof(long) + -15) == (197 % (g0 | 1)))) / (f1(((g0 / ('Q' | 1)) || ('y' - (int)sizeof(unsigned int))), ((result + result) % ((result % (m0 | 1)) | 1)), (((int)sizeof(unsigned int) || result) ? (m0 == (int)sizeof(int)) : f0(-41)), ((result >> (4)) ? ("world"[0], g0) : (m2, 245))) | 1));
    {
        int _w5;
        _w5 = 0;
        while (_w5 < 10) {
            _w5++;
            (((m2 * g0) > f0("hello"[0])) ? ((result == result) == ('m' > (int)sizeof(int))) : (('X' | -42) ? (m2, 0) : (m2 - g0)));
        }
    }

    result = 0;
    result += (int)(m2);
    result += (int)(m0);
    result += (int)(m2);
    result += (int)f0(f1((67 ^ 9), ("world"[1] ? 80 : g0), (m0 << (14)), (171 * 218)));
    result += (int)f1((f1(4901, 86, -36, 53) - ("abc123"[2] % (g0 | 1))), (((int)sizeof(unsigned char) ^ m2) ? (1 ? 'f' : 0) : (240 > 717)), ((1 / ('e' | 1)) % ((m0, "abcd"[3]) | 1)), (((int)sizeof(unsigned long) ^ '5') != (0 && 0)));
    result += (int)f0(((m0, 1), ((int)sizeof(unsigned int) - 61)));

    return (result >= 0 ? result : -result) & 255;
}
