/* Generated by cgen, seed=307 */

struct S0 {
    int m0;
    long m1;
    char m2;
    int m3;
};

long g0 = -6;

unsigned char f0(unsigned int p0, unsigned long p1, unsigned int p2, int p3);
long f1(void);

unsigned char f0(unsigned int p0, unsigned long p1, unsigned int p2, int p3)
{
    int v0_0;
    char v0_1[4];
    struct S0 v0_2;
    int v0_3;
    int v0_4;
    int v0_5;
    v0_0 = 76;
    v0_1[0] = 8507;
    v0_2.m0 = 930;
    v0_2.m1 = 1;
    v0_2.m2 = 1;
    v0_2.m3 = 1;
    v0_3 = 72;
    v0_4 = 89;
    v0_5 = 1;

    ((((v0_3 << (4)) < ((int)sizeof(unsigned char) && p1)) || (((int)sizeof(unsigned char) >> (7)), (-11 != "world"[4]))) + ((("wxyz"[0] & v0_3) == ((int)sizeof(unsigned char) ? p1 : g0)) & ((128 < -32) * (216 && v0_4))));
    v0_1[2] = ((((-46 ? (int)sizeof(char) : p1), (0, 61)) & ((p2 ? (int)sizeof(unsigned long) : "hello"[1]) + ('W' | (int)sizeof(unsigned long)))) | ((('X' / ("abc123"[2] | 1)), (v0_0 && p3)) ? (("fooX"[0] << (10)) ? (p1 * "abc123"[5]) : (v0_0 == "abc123"[5])) : ((82 | '3') == ("wxyz"[2] ^ 'C'))));
    {
        int _f0;
        for (_f0 = 0; _f0 < 5; _f0++) {
            switch (((v0_1[1] << (3)) - (p1 ? p3 : 0))) {
            case 4:
                {
                    int _w1;
                    _w1 = 0;
                    while (_w1 < 1) {
                        _w1++;
                        switch ((int)sizeof(int)) {
                        case 2:
                            v0_5 += 230;
                            p1 = p1;
                            break;
                        case 9:
                            g0 &= p2;
                            p0 |= g0;
                            break;
                        case 11:
                            p3 *= 0;
                            p2 = v0_0;
                            break;
                        default:
                            v0_0 *= v0_0;
                            break;
                        }
                        v0_4 |= (p2 * -31);
                        p3 = (v0_1[3], v0_3);
                    }
                }
                break;
            case 7:
                v0_0 -= ((v0_3 ? p1 : p1), ("barY"[3] / (106 | 1)));
                switch ((v0_1[0] && 0)) {
                case 2:
                    v0_3 += ((int)sizeof(unsigned char) << (25));
                    break;
                case 5:
                    switch ('l') {
                    case 2:
                        p1 -= v0_4;
                        v0_5 -= 1;
                        break;
                    }
                    break;
                case 12:
                    p3 |= (1 != 0);
                    break;
                case 15:
                    v0_5 &= (6027 << (19));
                    break;
                case 21:
                    v0_3 -= (v0_0, v0_1[2]);
                    break;
                }
                break;
            }
        }
    }
    v0_1[0] = ((((v0_1[2] - v0_4) + (p3 >> (4))) || ((183 ^ "world"[4]) != (40 % (g0 | 1)))) ? (((74 ? 1 : "wxyz"[0]) == (173 ? "wxyz"[0] : v0_1[2])) && ((0 << (8)) ? ((int)sizeof(unsigned int) >> (23)) : (1 / (42 | 1)))) : (((p2 == p0) % ((v0_0, 'd') | 1)) & ((g0 ? "wxyz"[2] : "test"[0]) % ((1 - p1) | 1))));
    (((((int)sizeof(char), v0_1[2]) << (17)), (((int)sizeof(unsigned long) == 51) ? (p1 >> (5)) : ('Q' == v0_5))), (((p0 < p1) || (0 == p2)) ? ((-30 < v0_1[0]) % ((v0_5 > (int)sizeof(unsigned char)) | 1)) : (("abcd"[3] && "world"[1]) ? (v0_0 == v0_1[2]) : ((int)sizeof(long), 251))));
    v0_2.m0 = ((((v0_1[3] + v0_4) ^ (p0 + -7)), ((8407 ? 'A' : 'z') == (p1, 'A'))) ^ (((0 == 82) && (v0_4, p0)) * (((int)sizeof(unsigned int) > p1) == (v0_1[1] ? v0_1[3] : 10))));
    {
        int _f2;
        for (_f2 = 0; _f2 < 4; _f2++) {
            {
                p2 &= (((int)sizeof(long) < 0) ? (9574 % (v0_5 | 1)) : (g0 + '1'));
            }
        }
    }
    p2 /= (((((p3 || 76) < (-31 || v0_5)) && (('4' & 1127) ? (46 << (11)) : (2011 ? 193 : v0_1[2]))) ? (((p2 & g0) > (217 - v0_5)) ? (('$' || p3) || (p2, -39)) : ((93 >> (23)) != (-50 | p1))) : (((p3 == v0_4) > ("hello"[1] || v0_1[1])), ((v0_0 ? 0 : "hello"[3]) & (v0_3 + v0_1[1])))) | 1);
    return (p3);
}

long f1(void)
{
    int v1_0;
    int v1_1[15];
    char v1_2;
    int v1_3[8];
    char * v1_4;
    char * v1_5;
    char v1_6;
    int v1_7;
    v1_0 = -33;
    v1_1[0] = 90;
    v1_2 = 84;
    v1_3[0] = 8;
    v1_4 = 0;
    v1_5 = 0;
    v1_6 = 1;
    v1_7 = 3489;

    ((((v1_6 ? g0 : 0) >> (15)) * ((v1_6 ? "world"[3] : v1_0) || (v1_6 ^ v1_3[3]))) * ((f0((int)sizeof(char), (int)sizeof(unsigned long), 1, v1_6) << (21)) ? ((v1_6 ? '@' : (int)sizeof(unsigned long)) | (g0 || g0)) : ((v1_0 && v1_7), (v1_0, g0))));
    switch ((((v1_2 + v1_0) + ("test"[1] - 5693)) >> (29))) {
    case 4:
        switch ((("hello"[3] ? v1_7 : v1_1[1]) ? (v1_3[5] >> (2)) : (0 >> (22)))) {
        case 1:
            v1_5 = &v1_6;
            break;
        case 6:
            {
                v1_6 |= f0(85, 161, 6391, v1_1[5]);
            }
            goto _lbl3;
            _lbl3:
            break;
        case 10:
            {
                int _w4;
                _w4 = 0;
                while (_w4 < 5) {
                    _w4++;
                    v1_0 |= ("world"[1] ? g0 : 2633);
                }
            }
            break;
        case 15:
            v1_7 |= (("abcd"[0] / (v1_0 | 1)) >> (1));
            break;
        case 21:
            {
                int _f5;
                for (_f5 = 0; _f5 < 1; _f5++) {
                    v1_2 += (v1_0 < v1_6);
                }
            }
            break;
        default:
            {
                int _d6;
                _d6 = 0;
                do {
                    _d6++;
                    v1_6 += (v1_3[4] % (v1_7 | 1));
                } while (_d6 < 4);
            }
            break;
        }
        break;
    }
    v1_6 *= (f0((((int)sizeof(char) + 0) == f0("fooX"[3], v1_0, v1_1[6], v1_2)), ((-27 > '{') ? ('f', 1) : ('s', 16)), f0((v1_6 & v1_2), ("hello"[2] < 39), (g0 != v1_0), (v1_6, -2)), (f0(0, v1_1[12], '!', (int)sizeof(unsigned int)) ? ((int)sizeof(unsigned char) < (int)sizeof(int)) : ((int)sizeof(int) + v1_6))) - (((v1_3[0] != '$') | (')' || 30)) ^ ((v1_2 == v1_7) ? (-30 != v1_2) : (v1_7 / (v1_2 | 1)))));
    if (((f0('x', v1_6, "wxyz"[0], 46) % ((v1_3[3], 247) | 1)) ? ((v1_6 ? g0 : -35) % ((1 << (27)) | 1)) : (((int)sizeof(long) || '|') > (-35 ? v1_1[4] : v1_7)))) {
        v1_4 = &v1_6;
        *v1_4 = (((g0 + 0) & ('$' ? v1_6 : -44)) / ((("abc123"[0] * v1_6) | (-38 < "wxyz"[0])) | 1));
        {
            int _d7;
            _d7 = 0;
            do {
                _d7++;
                g0 %= ((("abcd"[3] ? v1_6 : 0) >> (30)) | 1);
            } while (_d7 < 10);
        }
    } else {
        v1_7 = (((v1_0, "fooX"[0]) < (v1_3[1] && v1_6)) || ((v1_7 ^ 45) ? (v1_3[5] ^ 0) : (v1_0 || v1_6)));
    }
    v1_2 -= ((((v1_2 / ((int)sizeof(int) | 1)), f0(g0, v1_0, v1_2, 61)) + ((v1_6 ^ "world"[0]) >> (12))) ? ((("barY"[0] ? "barY"[0] : v1_7) ^ (v1_7 >> (23))) << (0)) : (((g0 | "hello"[1]) - (0 < v1_0)) ^ f0(((int)sizeof(long) / (68 | 1)), (0 == 3), (24 == v1_1[0]), (4106 << (18)))));
    g0 = f0((f0(f0(6543, g0, 27, 84), (v1_0 ? "barY"[2] : v1_1[5]), f0('_', "barY"[2], v1_3[2], v1_7), (56 ^ 5037)), (f0((int)sizeof(char), 'i', 1, v1_2) * (7157 ^ v1_2))), (((v1_2 ^ g0) ? (0 % ((int)sizeof(unsigned char) | 1)) : ('x' | v1_1[10])) ^ ((1 ? g0 : v1_0) ? (v1_2 | v1_0) : f0(v1_1[9], v1_0, 'M', "test"[0]))), (((v1_2 * v1_3[6]) * (v1_0 > v1_1[3])) % (((v1_7, "fooX"[2]) * ('g' + v1_3[6])) | 1)), (((v1_3[6], 1) * (v1_3[3], "fooX"[3])) == f0(f0((int)sizeof(int), 109, v1_0, v1_7), f0(v1_7, 0, -3, (int)sizeof(unsigned long)), ('Z' & "abcd"[1]), (1 + 0))));
    v1_7 = ((((1 | v1_7) + f0(91, 4382, (int)sizeof(long), v1_1[8])) >> (30)) + (((4874 ? v1_0 : 1) >> (25)) ? ((v1_3[5] > g0) & (1 ? 'G' : 22)) : (("world"[2] > v1_3[1]), (0 >> (26)))));
    switch ((((g0, (int)sizeof(unsigned long)) & (v1_6 == v1_7)) ^ ((-40 ^ v1_1[9]), f0(0, g0, 1, 48)))) {
    case 3:
        {
            int _f8;
            for (_f8 = 0; _f8 < 6; _f8++) {
                {
                    int _w9;
                    _w9 = 0;
                    while (_w9 < 5) {
                        _w9++;
                        v1_6 /= ((v1_6 > -25) | 1);
                    }
                }
                {
                    g0 |= f0(v1_0, v1_6, v1_7, 0);
                    v1_7 %= (((int)sizeof(int) ? 3019 : v1_2) | 1);
                    v1_6 -= (v1_1[13] ? (int)sizeof(int) : v1_1[1]);
                    v1_7 /= ((-35 % (v1_1[2] | 1)) | 1);
                }
                {
                    int _d10;
                    _d10 = 0;
                    do {
                        _d10++;
                        if ('$') {
                            v1_2 *= "fooX"[1];
                        } else {
                            g0 -= v1_0;
                            g0 += 'r';
                        }
                    } while (_d10 < 2);
                }
            }
        }
        break;
    case 9:
        v1_4 = &v1_6;
        break;
    case 10:
        {
            int _f11;
            for (_f11 = 0; _f11 < 3; _f11++) {
                {
                    int _f12;
                    for (_f12 = 0; _f12 < 4; _f12++) {
                        v1_2 %= ((0 && 9) | 1);
                    }
                }
                v1_6 %= (((58 < v1_7) ? (v1_3[2] / (g0 | 1)) : ('}' ? "test"[3] : '8')) | 1);
            }
        }
        break;
    case 18:
        {
            int _d13;
            _d13 = 0;
            do {
                _d13++;
                v1_2 %= (((v1_1[1], v1_7) < (v1_2, 'j')) | 1);
                (('B' && 26), ("abcd"[3] + 66));
            } while (_d13 < 9);
        }
        v1_7 %= (f0(f0((1 & v1_3[1]), f0((int)sizeof(char), 46, v1_7, "world"[1]), (v1_2 || v1_6), ("test"[2] ^ 926)), (("hello"[3] - v1_7) >> (25)), ((v1_0 & v1_0) > (1940 ^ v1_7)), ((2619 || v1_6) ? (0 > 0) : f0(g0, -8, v1_6, v1_7))) | 1);
        break;
    }
    return (v1_6);
}

int main(void)
{
    int result;
    struct S0 m0;
    char m1[12];
    unsigned int m2;
    int m3[6];
    result = 0;
    m0.m0 = 0;
    m0.m1 = -35;
    m0.m2 = -26;
    m0.m3 = -11;
    m1[0] = 89;
    m2 = 3877;
    m3[0] = 1;

    m2 *= f0(f0((("fooX"[0] | 1) << (3)), f0(f1(), (-42 < (int)sizeof(unsigned int)), (m2 > "test"[2]), ((int)sizeof(long) < "world"[0])), f0(((int)sizeof(unsigned int) & m2), (-25 * m2), ((int)sizeof(unsigned long) ^ g0), (result || g0)), ((g0 | g0) << (18))), (((-29 != "world"[0]) | (6093 << (19))) != ((205 + 1) ? ((int)sizeof(unsigned long) > 0) : f1())), (((89 >> (5)) < f0(g0, m1[9], 1, g0)) - ((-17 % (g0 | 1)) >> (3))), f1());
    m2 = ((((m2 >> (12)), (m1[4] * 'E')), ((g0 / (m2 | 1)) ? ((int)sizeof(int) | 0) : ((int)sizeof(unsigned char), result))) ? (((-45 ? m2 : m2), ("hello"[2] ? g0 : g0)) || ((0 != result) == f0(1, (int)sizeof(unsigned char), 0, g0))) : (f1() & f1()));
    result %= (((((result && (int)sizeof(char)) % ((m1[11] ^ "hello"[2]) | 1)) ? (f0(1, m2, -38, g0) == (0 | m3[3])) : ((141 == 1) || (118 ? m2 : m2))) ? (((m2 == m2) ? (g0 || m1[7]) : (g0 != m2)) - ((result * result) << (20))) : ((f1() > f0((int)sizeof(unsigned int), g0, 103, 121)), ((64, -35) % ((m2 ^ result) | 1)))) | 1);
    result += (((('|' % (result | 1)) ? (193 ^ g0) : (5, g0)) << (8)) % (((("abcd"[3] ? m2 : g0) - ((int)sizeof(char) + '`')) | ((result && 'A') ? ((int)sizeof(char) | 0) : (87 ^ 1))) | 1));
    m0.m1 = f1();

    result = 0;
    result += (int)(m2);
    result += (int)(m2);
    result += (int)f1();

    return (result >= 0 ? result : -result) & 255;
}
