/* Generated by cgen, seed=445 */

struct S0 {
    int m0;
    char m1;
    unsigned char m2;
};

struct S1 {
    unsigned long m0;
    long m1;
    long m2;
    long m3;
    unsigned long m4;
};

struct S2 {
    int m0;
    long m1;
    unsigned long m2;
    int m3;
};

struct S3 {
    long m0;
    int m1;
    int m2;
    unsigned int m3;
    unsigned long m4;
};

struct S4 {
    char m0;
    char m1;
};

struct S5 {
    int m0;
    char m1;
};

unsigned long g0 = 60;
char g1;
unsigned long g2 = 1;
int g3[4];
struct S4 gs4;
int g5 = 0;
unsigned long g6;
struct S4 gs7;
int g8[11];
unsigned long g9;

char f0(void);
unsigned int f1(unsigned long p0, unsigned long p1);
long f2(unsigned char p0, unsigned int p1, int p2, int p3);
unsigned long f3(unsigned int p0, int p1, int p2);
unsigned char f4(long p0);
long f5(int p0);
int f6(unsigned int p0, long p1, int p2, char p3, unsigned int p4);

char f0(void)
{
    int * v0_0;
    v0_0 = 0;

    g2 -= ((((81 | -46) ? (g6 & g5) : (g8[8] * (int)sizeof(unsigned long))) | ((9194 * g9) * ("abcd"[1], g6))), (((g3[0], 'w') && (1 % (1 | 1))) ^ ((g8[0] || "hello"[1]) / (("test"[1] || g1) | 1))));
    return (g1);
}

unsigned int f1(unsigned long p0, unsigned long p1)
{
    int v1_0;
    v1_0 = -9;

    {
        {
            int _d0;
            _d0 = 0;
            do {
                _d0++;
                g0 &= ((79 ? g2 : g8[7]) - (g8[10] > g5));
            } while (_d0 < 6);
        }
        g6 -= ((("barY"[1] > '@') && ("world"[0] ? -49 : g2)) != ((g3[0] - 107) < f0()));
    }
    {
        int _d1;
        _d1 = 0;
        do {
            _d1++;
            goto _lbl2;
            _lbl2:
            g5 -= (((21 ^ g6) ? (g3[3] == g9) : f0()), ((g1 / (g9 | 1)) | ((int)sizeof(unsigned char), v1_0)));
        } while (_d1 < 3);
    }
    return (g2);
}

long f2(unsigned char p0, unsigned int p1, int p2, int p3)
{
    long v2_0;
    v2_0 = 0;

    goto _lbl3;
    _lbl3:
    {
        int _w4;
        _w4 = 0;
        while (_w4 < 5) {
            _w4++;
            {
                int _f5;
                for (_f5 = 0; _f5 < 4; _f5++) {
                    switch (((int)sizeof(int), g6)) {
                    case 3:
                        g6 *= (5411 - "abcd"[2]);
                        break;
                    case 6:
                        p0 -= (g8[4] || 0);
                        break;
                    case 11:
                        g2 -= ((int)sizeof(unsigned int) > g8[6]);
                        break;
                    }
                }
            }
        }
    }
    {
        int _d6;
        _d6 = 0;
        do {
            _d6++;
            {
                int _w7;
                _w7 = 0;
                while (_w7 < 6) {
                    _w7++;
                    p1 = ((70 << (30)) % (('a' ^ v2_0) | 1));
                    {
                        int _f8;
                        for (_f8 = 0; _f8 < 3; _f8++) {
                            g6 /= (f0() | 1);
                        }
                    }
                }
            }
        } while (_d6 < 8);
    }
    return (g6);
}

unsigned long f3(unsigned int p0, int p1, int p2)
{
    char * v3_0;
    int * v3_1;
    int * v3_2;
    int v3_3;
    v3_0 = 0;
    v3_1 = 0;
    v3_2 = 0;
    v3_3 = 1;

    g6 &= ((((1 ^ g8[7]) % ((27, -14) | 1)) || ((v3_3 ? "fooX"[0] : 7854) ? (g1 ^ (int)sizeof(unsigned int)) : f0())) / (((((int)sizeof(unsigned long) >> (23)) || (g0 != (int)sizeof(unsigned long))) | (f1(p0, 6), ((int)sizeof(long) || g2))) | 1));
    goto _lbl9;
    _lbl9:
    v3_1 = &v3_3;
    v3_2 = &v3_3;
    *v3_2 = ((f0() && f0()) / ((((89 > 4442) ? (1 || 33) : (p0, (int)sizeof(int))) ? (("hello"[2] ? 'A' : g5) * ('C' == '0')) : (f2(g6, g3[3], g0, g1) << (24))) | 1));
    {
        p2 &= (((p2 >> (16)) | (5432 ? g6 : 23)), f1((g9 ? p2 : p2), ('.' / ("test"[1] | 1))));
    }
    g2 += (f2(((110 << (8)) | (225 / (g9 | 1))), f0(), ((101, g9) < f2(23, 'P', (int)sizeof(unsigned int), g9)), (('v' ? p0 : 4693) != (v3_3 >> (4)))) ? f2((("hello"[2] >> (13)) ? (v3_3, g5) : (p1 ? g6 : 0)), ((g9 - 1) == (1 ^ (int)sizeof(unsigned int))), ((p0 ? "test"[3] : p1), (-47 | (int)sizeof(unsigned char))), (f0() && ('v' * 'x'))) : (((g8[0] & p1) % ((1 - "test"[1]) | 1)) & (f1(g8[4], p0) << (15))));
    g6 -= ((((-21 >> (1)) & f1("abcd"[0], p1)) ? ((77 > g2) / (('~' + 48) | 1)) : ((g2 >> (29)) - (220 % (p1 | 1)))) ? ((('i' > g2) / ((g9 + "hello"[0]) | 1)) && f2((g1 && (int)sizeof(long)), f0(), (g1 ? p0 : 'C'), (75 % (g2 | 1)))) : ((f0() < (p2 ? 1403 : g0)) | ((g9 | 'h') / ((1 != -36) | 1))));
    if (f1(((g3[0] / (g9 | 1)) > (254 ? 'v' : 9038)), ((g0 < "wxyz"[3]) ? (63 != 5551) : (p0 / (g0 | 1))))) {
        goto _lbl10;
        _lbl10:
        p0 = (((1 - g6) - f0()) + ((p0 || g6) + (9427, v3_3)));
    } else {
        g9 -= (((v3_3 && g3[2]) < (g2 / (p0 | 1))) ^ ((1 & "world"[3]) | (1 << (20))));
    }
    g6 = f0();
    g9 %= ((((f1(-40, (int)sizeof(unsigned long)) < (1 * g3[0])) && f0()) | f1((((int)sizeof(unsigned char) == 1) % ((g8[8] ? -36 : (int)sizeof(int)) | 1)), f2((g0 ? p1 : p1), (g6 ? "barY"[0] : g0), (g8[7] && g0), ('Z' ^ g0)))) | 1);
    return (p0);
}

unsigned char f4(long p0)
{
    long v4_0;
    int * v4_1;
    int v4_2;
    int v4_3;
    char * v4_4;
    char v4_5[14];
    int v4_6;
    v4_0 = 1;
    v4_1 = 0;
    v4_2 = 4855;
    v4_3 = -4;
    v4_4 = 0;
    v4_5[0] = 127;
    v4_6 = 3709;

    v4_3 |= ((((g0 | g8[7]) | (v4_6 >> (16))) >> (11)) < (f1((v4_2 ^ v4_2), (p0 || g6)) % ((('a' - v4_0) ? f1(g3[2], "hello"[0]) : ('y' >> (1))) | 1)));
    ((((v4_5[8] << (29)) && (g3[2] / (g9 | 1))) > ((p0 | 255) ^ (16, 'a'))) ? ((f3(g1, v4_5[4], g8[4]) ? f1(v4_3, 136) : f0()) ^ ((g2 | -26) > ('/' >> (27)))) : (((0 ^ g3[1]) < (p0, 'X')) ? (((int)sizeof(char) * "wxyz"[1]) > (v4_6 < 85)) : ((1 % (v4_5[8] | 1)) << (22))));
    v4_0 = f0();
    return (p0);
}

long f5(int p0)
{
    unsigned long v5_0;
    v5_0 = 60;

    switch ((f1((308 ^ '8'), ('T', g2)) ? f4(((int)sizeof(unsigned int) + (int)sizeof(unsigned int))) : (("test"[1] ? 1 : p0), ((int)sizeof(unsigned char) >> (7))))) {
    case 4:
        switch ((("fooX"[2] << (22)) >> (19))) {
        case 4:
            g0 += (('7' > g5) ? ("abc123"[2] < 247) : ((int)sizeof(int) > 1));
            switch ((p0 ? 95 : 18)) {
            case 1:
                g9 += ((int)sizeof(long) + "hello"[0]);
                break;
            case 9:
                switch (1) {
                case 2:
                    v5_0 += g1;
                    break;
                case 8:
                    g1 %= ('Z' | 1);
                    break;
                }
                break;
            case 12:
                v5_0 = (995 | g8[10]);
                break;
            case 17:
                if (g9) {
                    v5_0 &= 86;
                    g9 &= 1;
                } else {
                    g1 -= 1;
                }
                break;
            }
            break;
        case 7:
            if ((4276, g8[5])) {
                g6 |= (-28 / (1 | 1));
            }
            break;
        case 13:
            ((g8[1], (int)sizeof(char)) != f4('}'));
            break;
        case 15:
            gs7.m0 = ((g3[2] / (v5_0 | 1)) + (-26 | -18));
            break;
        default:
            {
                v5_0 &= (g3[1] >> (13));
                g6 /= (('R' || 207) | 1);
            }
            break;
        }
        break;
    case 5:
        g5 &= ((f1("abc123"[2], 0) ? ("barY"[3] ? v5_0 : g1) : (g8[10] + "abc123"[2])) == (("abc123"[1] % (0 | 1)) / (((int)sizeof(char) << (27)) | 1)));
        break;
    }
    v5_0 -= (((f0() << (14)) ? f1(("abcd"[3] < '8'), (p0 ? '|' : -23)) : ((g0 ? g8[10] : g2) != (g2 > g2))) - ((((int)sizeof(unsigned long) ? 0 : v5_0) | (48 + g3[0])) >> (22)));
    return (v5_0);
}

int f6(unsigned int p0, long p1, int p2, char p3, unsigned int p4)
{
    unsigned int v6_0;
    int v6_1;
    struct S0 v6_2;
    char v6_3[4];
    int v6_4;
    v6_0 = 65;
    v6_1 = -43;
    v6_2.m0 = 1;
    v6_2.m1 = -37;
    v6_2.m2 = -8;
    v6_3[0] = 1;
    v6_4 = 184;

    g2 |= (f0() && (((-25, 'O') ? (g3[2] ? g1 : p2) : (v6_3[0] | "world"[0])) > ((0 % (g2 | 1)) ? (g1, p3) : f3(1, 62, g6))));
    gs4.m0 = (((('a' ? p2 : (int)sizeof(unsigned long)) << (18)) / (((v6_0, p2) && (-49 ^ g8[0])) | 1)) || (f0() >> (13)));
    {
        {
            int _f11;
            for (_f11 = 0; _f11 < 3; _f11++) {
                {
                    p4 |= (p0 / ((int)sizeof(unsigned long) | 1));
                }
            }
        }
    }
    return (v6_0);
}

int main(void)
{
    int result;
    char m0;
    result = 0;
    m0 = -40;

    g6 |= ((((g1 * g1) + (g5 | 1)) ? ((1 >> (23)) && (g0 ? g8[2] : g3[2])) : ((1 * (int)sizeof(long)), (12 / (g8[7] | 1)))), (((3106 - "world"[2]) || (0 % (g3[2] | 1))) << (13)));
    {
        int _w12;
        _w12 = 0;
        while (_w12 < 5) {
            _w12++;
            result += (((14, "barY"[3]) - f1("wxyz"[0], 8285)) * (('q' ^ g9) ? (44 ? g9 : g2) : ("fooX"[1] + 6034)));
        }
    }
    g5 %= ((f1(((g2 % ("test"[3] | 1)) ? (g8[5] && g9) : ('w' != g5)), ((result < g3[2]) && (0 || g0))), ((('_' << (21)) && ((int)sizeof(unsigned long) ^ -11)) != f3(('s' < g9), (g9 ? g3[2] : 'x'), (g9 < "world"[1])))) | 1);
    if ((((g3[3] + g3[2]) | (9 ^ 0)) / ((("barY"[0] < 7845) ? ("fooX"[2] == m0) : ((int)sizeof(unsigned char) ? 46 : 6060)) | 1))) {
        g5 /= ((f3((0 & m0), f4(97), (43 / ((int)sizeof(char) | 1))), ((g1 < g8[8]) < (g9 / ("abc123"[1] | 1)))) | 1);
        {
            {
                int _d13;
                _d13 = 0;
                do {
                    _d13++;
                    g9 = (85 == g0);
                } while (_d13 < 2);
            }
            {
                g1 %= (f4(-41) | 1);
                g0 |= ("barY"[0] ^ (int)sizeof(unsigned char));
            }
            g1 /= (((g8[8] / (0 | 1)) & ((int)sizeof(long) ^ result)) | 1);
        }
    } else {
        gs7.m1 = (((result, g9) % (('S' ? "hello"[3] : "barY"[1]) | 1)) || f1((g2 << (17)), (result, 'k')));
    }
    {
        int _w14;
        _w14 = 0;
        while (_w14 < 8) {
            _w14++;
            {
                g3[1] = (('$' / ("wxyz"[1] | 1)) ? (g3[2] || -33) : (5681 & g6));
            }
        }
    }
    goto _lbl15;
    _lbl15:
    g0 = ((f3((1 != 83), ('I' >> (4)), (g9 << (6))) == ((g3[1] >> (10)) > (248 / ((int)sizeof(unsigned char) | 1)))) / (((((int)sizeof(unsigned char) - 228), ("wxyz"[2] | 'R')) + (f4(97) * (1 + g8[5]))) | 1));
    g8[2] = f6((((g2 && 0) | (46 ? g0 : m0)), f4((1 | g6))), (((g5, g8[1]) + (0 > g9)) ? ((-18, -30) * (g6 ? "fooX"[2] : g9)) : f5((m0 - g9))), (f0(), (((int)sizeof(unsigned int) ^ "abcd"[2]) == ("world"[1] | 1807))), (((result == g0), f2(g0, 1, 75, g0)) ? f4((1 - 31)) : ((g0, "fooX"[1]) > f4('<'))), ((('w' ^ g8[9]), (-35 * '4')) || (f5(-18) << (9))));
    g8[3] = (f6(((g9 & 58) < ((int)sizeof(int) && 0)), ((227 - g3[3]), ('E' >> (10))), ((g6 < g1) >> (3)), (('w', result) << (12)), (f3(g0, 61, g1) && (g5 && -9))) >> (5));

    result = 0;
    result += (int)(m0);
    result += (int)(m0);
    result += (int)(g5);
    result += (int)f2(((-46 ^ g5) ^ f5('!')), ((g8[0] != 2492) ^ f6('g', result, 1, '6', m0)), ((')' < m0) || f0()), (('*' ? 1 : g0), f0()));
    result += (int)f3(f0(), (((int)sizeof(unsigned char) ? result : g0) - ("abc123"[1] - 142)), ((-42 != -21) + (g9 ? (int)sizeof(unsigned int) : 'U')));
    result += (int)f5(((-36 == g6) % (f4(g1) | 1)));

    return (result >= 0 ? result : -result) & 255;
}
