/* Generated by cgen, seed=299 */

struct S0 {
    unsigned long m0;
    int m1;
    long m2;
    int m3;
    long m4;
};

unsigned char g0 = 79;
int g1 = -15;
int g2 = 1;
unsigned int g3 = -20;
long g4;
unsigned long g5;
unsigned int g6 = -13;

char f0(void);
unsigned int f1(unsigned long p0, unsigned char p1, unsigned int p2);

char f0(void)
{
    struct S0 v0_0;
    char v0_1;
    int v0_2[14];
    struct S0 v0_3;
    int v0_4;
    v0_0.m0 = 8;
    v0_0.m1 = 5454;
    v0_0.m2 = -38;
    v0_0.m3 = -27;
    v0_0.m4 = 235;
    v0_1 = 45;
    v0_2[0] = 36;
    v0_3.m0 = -36;
    v0_3.m1 = 1;
    v0_3.m2 = 144;
    v0_3.m3 = -34;
    v0_3.m4 = 242;
    v0_4 = -42;

    v0_3.m2 = ((((1 * v0_4) + ((int)sizeof(unsigned int) ? g2 : -47)), ((0 > g5) ? (-18 == 58) : (235 || "fooX"[2]))) >> (28));
    return (g0);
}

unsigned int f1(unsigned long p0, unsigned char p1, unsigned int p2)
{
    unsigned char v1_0;
    unsigned long v1_1;
    v1_0 = 1;
    v1_1 = 5788;

    v1_0 |= (f0() ? (((-4 ^ g0) + (p2 ? 23 : 8191)) % ((f0() & (v1_0 >> (12))) | 1)) : (((0 ^ -50), ("hello"[1] * "abc123"[4])) != ((p1 | -38) ^ (p2 ? 85 : 'N'))));
    return (p2);
}

int main(void)
{
    int result;
    int m0;
    int m1;
    unsigned char m2;
    result = 0;
    m0 = 0;
    m1 = 41;
    m2 = 1;

    {
        int _d0;
        _d0 = 0;
        do {
            _d0++;
            {
                int _w1;
                _w1 = 0;
                while (_w1 < 8) {
                    _w1++;
                    {
                        int _f2;
                        for (_f2 = 0; _f2 < 3; _f2++) {
                            m2 &= (g1 >> (30));
                            result -= (g2 >> (16));
                        }
                    }
                    {
                        g4 -= ('A', g2);
                    }
                    m0 += ((1 || g0) < (31, 56));
                }
            }
        } while (_d0 < 4);
    }
    g3 = ((((g4 >> (28)) ? (1, -41) : (g6 & g0)) ? ((g0 ? -21 : 1) / ((0 < "barY"[3]) | 1)) : ((1 && "test"[1]) << (5))) - (((m2 - g3), f0()) | ((-11 & 896) * (1 & g5))));
    m1 += (f0() / ((((-23, g4) ? (-5 >> (26)) : (1 * (int)sizeof(char))), (("fooX"[2] > 97) ? (g6, "hello"[2]) : f1(g2, -25, 1496))) | 1));
    {
        int _f3;
        for (_f3 = 0; _f3 < 8; _f3++) {
            g1 *= ((("hello"[4] / (g1 | 1)) | ("fooX"[0] % (137 | 1))), ((0 ^ g5), f1(m1, g5, "abc123"[3])));
            {
                g4 = ((g0 << (11)) ? (g6 >> (17)) : (result / ('o' | 1)));
                {
                    int _w4;
                    _w4 = 0;
                    while (_w4 < 5) {
                        _w4++;
                        g5 += f1("barY"[2], g3, m2);
                    }
                }
                ((-15 | result) + ("wxyz"[1] != '{'));
            }
        }
    }
    {
        int _d5;
        _d5 = 0;
        do {
            _d5++;
            {
                int _w6;
                _w6 = 0;
                while (_w6 < 7) {
                    _w6++;
                    m0 *= f1((6596 * g1), (g4 << (9)), f0());
                }
            }
        } while (_d5 < 6);
    }
    {
        int _f7;
        for (_f7 = 0; _f7 < 7; _f7++) {
            g3 -= ((f1(-7, 61, g4) / ((g1 < 'z') | 1)), ((m0 || 2904) | ("abcd"[0] / (m2 | 1))));
        }
    }
    g1 = (((("barY"[2], 5541) != (0 ^ (int)sizeof(unsigned char))) << (6)) < (((5527 ? 0 : g6) << (6)), (("wxyz"[0] - 37) || (g0 >> (20)))));
    {
        (((47, g2) + (g3, 1)) ? ((g3 * 54) || (m2 != (int)sizeof(int))) : ((g3 & g1) >> (26)));
    }
    if (((f0(), ("barY"[3] > (int)sizeof(long))) * f1(("fooX"[0] ? (int)sizeof(char) : 28), (8734 + 0), (74, (int)sizeof(long))))) {
        if (((g2 ? 1 : 80) * ('w' || 15))) {
            g0 &= ((g5 < 8738) ^ ((int)sizeof(unsigned long), g4));
        }
    } else {
        goto _lbl8;
        _lbl8:
        g3 |= f0();
    }
    g4 &= ((((-33 ^ 123) ? (m1 == g3) : (g3 == m1)) || (f0(), (6967 < 28))) ? ((f0() ? f1(g2, -42, '8') : ('^' % (g2 | 1))) << (5)) : ((('T' + (int)sizeof(unsigned char)) / (("hello"[0] << (8)) | 1)) ? f1((-9 + m2), (0 < g5), (0 ^ 0)) : ((23 & g0) & (49 > g1))));
    {
        int _d9;
        _d9 = 0;
        do {
            _d9++;
            result /= ((((0 && 5016) - (1 ? g2 : 0)), ((-14 ? (int)sizeof(long) : -14), (-48 << (16)))) | 1);
        } while (_d9 < 4);
    }
    {
        g3 -= ((('z' - g5) ^ (g3 ? 'Q' : 24)) & (f0() | f0()));
        (((g5 != -14) | (92 & 8)) & f0());
        g4 = ((f1(g5, (int)sizeof(unsigned int), (int)sizeof(unsigned long)) ^ (7789 || "abc123"[1])) + f0());
        g1 -= (f0() ? ((g4 ? 'r' : m0) * (m2 & g4)) : ((g3 && '3') % ((g5 << (9)) | 1)));
    }

    result = 0;
    result += (int)(g2);
    result += (int)(m2);
    result += (int)(m0);
    result += (int)f0();
    result += (int)f0();
    result += (int)f1(f1(f1(g0, 125, 0), ((int)sizeof(unsigned char), g1), ((int)sizeof(unsigned int) == result)), ((0 << (21)) && (1 ? 0 : 7599)), ((0 ? "world"[2] : 183) / ((135 & "abc123"[5]) | 1)));

    return (result >= 0 ? result : -result) & 255;
}
