/* Generated by cgen, seed=425 */

struct S0 {
    int m0;
    char m1;
    unsigned char m2;
    long m3;
    unsigned long m4;
    long m5;
};

struct S1 {
    unsigned int m0;
    int m1;
    int m2;
    unsigned int m3;
    unsigned char m4;
    unsigned int m5;
};

unsigned char g0 = -44;
unsigned long g1 = 3807;
int g2[8];
int g3[15];
int g4 = 47;
int g5[8];
int g6[5];
unsigned int g7 = -35;

char f0(unsigned char p0, char p1, unsigned int p2, char p3);
char f1(unsigned long p0, char p1, unsigned long p2, unsigned long p3);
char f2(long p0, char p1, int p2, unsigned int p3, char p4);

char f0(unsigned char p0, char p1, unsigned int p2, char p3)
{
    long v0_0;
    v0_0 = 5291;

    p1 += (((("hello"[3] > g3[11]) == ((int)sizeof(char) < "world"[4])) - ((-27 ? 59 : 2341) || ("barY"[0] < 8452))) == ((("abc123"[1] << (20)) ? (g4 < "barY"[3]) : (p0 / (0 | 1))) / (((v0_0 * p0) ? (g7 ? 0 : g4) : (p0 | v0_0)) | 1)));
    return (v0_0);
}

char f1(unsigned long p0, char p1, unsigned long p2, unsigned long p3)
{
    long v1_0;
    long v1_1;
    struct S0 v1_2;
    struct S1 v1_3;
    long v1_4;
    struct S1 v1_5;
    v1_0 = -35;
    v1_1 = 0;
    v1_2.m0 = 0;
    v1_2.m1 = -16;
    v1_2.m2 = 26;
    v1_2.m3 = 0;
    v1_2.m4 = 82;
    v1_2.m5 = 174;
    v1_3.m0 = 1041;
    v1_3.m1 = 0;
    v1_3.m2 = 57;
    v1_3.m3 = 76;
    v1_3.m4 = 0;
    v1_3.m5 = 1;
    v1_4 = 515;
    v1_5.m0 = 253;
    v1_5.m1 = 21;
    v1_5.m2 = 5294;
    v1_5.m3 = -24;
    v1_5.m4 = 1;
    v1_5.m5 = 1;

    {
        int _d0;
        _d0 = 0;
        do {
            _d0++;
            goto _lbl1;
            _lbl1:
            g1 %= ((((p1 | p0) << (9)), (('C' && 1) == (g7 != (int)sizeof(char)))) | 1);
        } while (_d0 < 10);
    }
    {
        {
            int _f2;
            for (_f2 = 0; _f2 < 9; _f2++) {
                p3 -= f0((0 - p0), (g1 != v1_0), f0(g7, 0, (int)sizeof(unsigned char), ':'), ("abc123"[3] & g5[2]));
            }
        }
    }
    if (((('+' / (v1_0 | 1)), f0(p1, "test"[0], 5717, g4)) ? (("fooX"[3] == 1) | (g4 >> (30))) : ((82 % ((int)sizeof(long) | 1)) > ("barY"[0] ^ (int)sizeof(unsigned int))))) {
        v1_4 += (((g2[3], g0) > (g7, g2[7])) != (("abc123"[4] + 'y') != (46 ? 2149 : v1_4)));
    } else {
        {
            g1 %= ((((int)sizeof(unsigned int), 'z') == (4663 ? 0 : (int)sizeof(int))) | 1);
            v1_2.m3 = f0(((int)sizeof(int) != g4), f0(g7, v1_0, p0, "abc123"[1]), ((int)sizeof(unsigned char) == "world"[4]), ('J' ^ v1_4));
        }
    }
    return (v1_4);
}

char f2(long p0, char p1, int p2, unsigned int p3, char p4)
{
    unsigned int v2_0;
    struct S1 v2_1;
    int v2_2;
    v2_0 = 1;
    v2_1.m0 = 0;
    v2_1.m1 = -46;
    v2_1.m2 = -27;
    v2_1.m3 = 100;
    v2_1.m4 = 0;
    v2_1.m5 = 1;
    v2_2 = 0;

    {
        int _f3;
        for (_f3 = 0; _f3 < 10; _f3++) {
            {
                int _w4;
                _w4 = 0;
                while (_w4 < 5) {
                    _w4++;
                    f0((g3[13] || p0), (5165 + 1), (5887 != "abc123"[0]), (g4 == 16));
                }
            }
        }
    }
    if (((((int)sizeof(unsigned long) / ((int)sizeof(unsigned char) | 1)) == (p4 < 0)) && (('`' * -19) / (("test"[3] ? 6639 : -41) | 1)))) {
        {
            int _f5;
            for (_f5 = 0; _f5 < 10; _f5++) {
                p3 = ((p4 + g3[5]), f0(249, v2_0, g2[1], g0));
                g7 = ((p1 | p1) | (g5[4], (int)sizeof(char)));
                p1 *= (((int)sizeof(unsigned long) | g3[1]) / ((1, "fooX"[2]) | 1));
            }
        }
    } else {
        g4 |= (((g1 > g6[2]), (500 == g5[0])) && (("fooX"[3] / (g2[4] | 1)), ((int)sizeof(int) > v2_0)));
    }
    p1 |= (((f1(3037, 9463, -12, 8010) ? (g7 > "abcd"[2]) : ("hello"[3] && g3[3])) == (("hello"[0] - p2), (p2 + "test"[0]))), (((p1 - p0) > ("fooX"[1] > v2_2)) || (f1(-2, v2_2, (int)sizeof(long), 8118) >> (4))));
    {
        int _w6;
        _w6 = 0;
        while (_w6 < 3) {
            _w6++;
            g5[6] = ((f0('v', (int)sizeof(int), 6982, 1) << (1)), ((g7, p3) / (f1(g6[3], "hello"[4], (int)sizeof(unsigned char), 'A') | 1)));
        }
    }
    g1 /= ((((f0("barY"[2], g5[7], -23, p1) < (p2 && -16)) / (f1(('0' == 4801), (p2 ^ (int)sizeof(int)), (p1 != (int)sizeof(unsigned char)), ("abc123"[0] << (14))) | 1)) && (((g2[2] == g0) || (v2_0, 'Z')), ((61 << (7)) ? f0('#', 0, 5, p1) : ("barY"[3] == "hello"[3])))) | 1);
    {
        int _d7;
        _d7 = 0;
        do {
            _d7++;
            p0 *= (((3266 * g3[4]) ? (-20 > 0) : ('V' || (int)sizeof(long))) ^ ((p1 ^ "abc123"[2]) < (g5[5] % (3596 | 1))));
        } while (_d7 < 9);
    }
    switch (f1((("wxyz"[2] ? -23 : g7) >> (19)), ((0 ? (int)sizeof(int) : p0) & (g7 - "fooX"[0])), f1((p3 < 'e'), ((int)sizeof(long) ? v2_2 : "test"[3]), (g7 + p2), ('-' % (g5[7] | 1))), ((p1 ? 8920 : 0) ? f1(g6[4], g7, 6, v2_2) : (1 > g5[1])))) {
    case 2:
        v2_1.m5 = f0(((32 - 58) * ('|' + "test"[1])), (('O' == "abc123"[1]) & (94 != 0)), ((39 << (23)) + (29 | "barY"[2])), ((g6[4] & 49) + f0(23, 1, (int)sizeof(unsigned long), "abcd"[2])));
        break;
    case 6:
        {
            int _w8;
            _w8 = 0;
            while (_w8 < 9) {
                _w8++;
                {
                    int _d9;
                    _d9 = 0;
                    do {
                        _d9++;
                        v2_0 -= ("hello"[1] % (g2[0] | 1));
                    } while (_d9 < 1);
                }
            }
        }
        break;
    case 14:
        v2_2 = (((g1 / ((int)sizeof(unsigned long) | 1)) >> (26)) > ((0 << (9)) || f0(p4, p3, 1, 'V')));
        {
            v2_2 *= (((int)sizeof(unsigned long) ? 1 : 9117) % ((95 * g4) | 1));
            p1 /= (((6582 ^ p1) ? (p1 / ("barY"[1] | 1)) : (g6[1] ? g2[0] : 0)) | 1);
            {
                int _d10;
                _d10 = 0;
                do {
                    _d10++;
                    v2_2 *= (g0, v2_0);
                } while (_d10 < 5);
            }
            {
                int _w11;
                _w11 = 0;
                while (_w11 < 3) {
                    _w11++;
                    p2 /= ((g4 ^ "wxyz"[0]) | 1);
                    v2_2 *= (v2_0 > g6[1]);
                    if (p0) {
                        g4 += 'Y';
                        g7 |= p0;
                        g0 -= "abcd"[2];
                    }
                }
            }
        }
        break;
    case 16:
        (((g4 * v2_0) == ('|' * g1)) % (((p1 ? 'f' : g7) != f0(0, g7, g6[0], g4)) | 1));
        g7 = f0(((g5[6] < p1) || ((int)sizeof(long) ? 29 : "abcd"[1])), ((g2[6] ? g0 : 35) < (25 != (int)sizeof(int))), f0(f1((int)sizeof(unsigned int), 1, 9079, 24), ('B', 27), (g7 ? g0 : 1), (p4 ? 109 : g5[3])), f1((p0 | "abc123"[1]), (0, g3[11]), (-20 + p2), (90 >> (25))));
        break;
    case 23:
        switch (((g3[4] << (25)) & ((int)sizeof(unsigned long) * -16))) {
        case 2:
            g1 &= f1(f1("wxyz"[2], g7, 39, p3), ('y' ? g2[5] : p2), (0 != g4), ("abcd"[3] >> (7)));
            break;
        case 7:
            {
                int _d12;
                _d12 = 0;
                do {
                    _d12++;
                    p1 *= (p4 >> (28));
                } while (_d12 < 2);
            }
            p3 = (('7' ? g0 : p0) % ((g4, "fooX"[1]) | 1));
            break;
        case 11:
            g1 %= ((('4' != "abc123"[4]) ? ('(' && p4) : (1 != -39)) | 1);
            break;
        default:
            g3[7] = ((p2 != p2) || (g2[3] ? g0 : g5[1]));
            break;
        }
        break;
    }
    g3[5] = (((("wxyz"[1] * 't') * f0('&', 'm', (int)sizeof(int), v2_0)) / (((p4 > 'Z') >> (8)) | 1)) | ((((int)sizeof(char) && (int)sizeof(unsigned int)) + (148 + "hello"[4])), ((-32 ? (int)sizeof(unsigned char) : g0) && (0 / ('[' | 1)))));
    return (v2_2);
}

int main(void)
{
    int result;
    char * m0;
    struct S0 m1;
    struct S1 m2;
    result = 0;
    m0 = 0;
    m1.m0 = -30;
    m1.m1 = 135;
    m1.m2 = 52;
    m1.m3 = 58;
    m1.m4 = 0;
    m1.m5 = 3269;
    m2.m0 = 1;
    m2.m1 = -8;
    m2.m2 = -18;
    m2.m3 = -38;
    m2.m4 = 60;
    m2.m5 = 1;

    result += ((((g1 != g0) + (g0 ? g0 : g0)) ? ((g1 | 'n') ? ("test"[2] * (int)sizeof(unsigned long)) : f2(g1, g0, "abcd"[2], result, (int)sizeof(long))) : ((g4 || g0) * ((int)sizeof(int) % (g6[2] | 1)))) ? ((f0(g1, 4790, result, 6229) != (5927 != (int)sizeof(unsigned char))), ((g4 && 7958) != f2(4573, g7, 5112, "abc123"[2], (int)sizeof(unsigned long)))) : f2(((4 - -32) ? f2(g6[3], g1, (int)sizeof(int), g0, g7) : f2((int)sizeof(char), '5', 5372, 'V', 8930)), (f1(g7, g6[3], (int)sizeof(char), '=') - f1(g1, "abcd"[3], (int)sizeof(unsigned long), "world"[0])), (("abc123"[3], 20) > ((int)sizeof(unsigned int) ? -44 : 4903)), ((40 * g1) ? ("fooX"[2] << (22)) : (g4 + 0)), (((int)sizeof(unsigned long), g6[0]) || f0(result, g7, g7, 'A'))));
    m0 = &result;
    g7 += ((f1(((int)sizeof(unsigned long) || g6[1]), (0 < "fooX"[2]), ("barY"[3] || g4), (61 ? "world"[4] : g6[1])) == (f2(g0, 1, 30, g0, 0) >> (17))) + f0(((result >> (27)) ^ ("barY"[0] > (int)sizeof(char))), f0(("abcd"[2] ? "hello"[2] : g0), (result % (g7 | 1)), (50 << (0)), (',', ')')), ((g7 ? "world"[2] : (int)sizeof(long)) ? ("wxyz"[0], g0) : (g5[1], g4)), ((g7, "barY"[2]) && ((int)sizeof(char) * '~'))));
    goto _lbl13;
    _lbl13:
    {
        int _f14;
        for (_f14 = 0; _f14 < 2; _f14++) {
            m0 = &g0;
            *m0 = (((45 & 0) << (13)) && ((result || '~') | (50 << (5))));
        }
    }

    result = 0;
    result += (int)(g1);
    result += (int)(g0);
    result += (int)(g7);
    result += (int)f1((f2(g0, g4, g7, (int)sizeof(long), -5) ? (0 & '@') : (g6[0] + -9)), (((int)sizeof(unsigned long) / ("hello"[3] | 1)) || (g1 > g1)), ((g6[3] ? g4 : '^') ? (1 ? (int)sizeof(char) : g6[2]) : (1 + 0)), ((g7 * g3[10]) * ("fooX"[1] && 65)));
    result += (int)f0(((g6[3], "hello"[1]) ? (g1 / ("test"[2] | 1)) : ("test"[0], g0)), (f0("barY"[2], g7, g6[0], g4) >> (4)), ((g0 ? 485 : "world"[3]) != (g2[3] * -11)), (f0(3796, result, g1, 29) > (result - 21)));
    result += (int)f0((f2("abc123"[5], 0, g0, 985, g0) ? f2(result, g4, result, 1, 492) : (g2[5] + "abcd"[2])), ((g1 ? 0 : g3[8]) % (('b' % (g2[5] | 1)) | 1)), (((int)sizeof(char) ? (int)sizeof(char) : (int)sizeof(long)) | (0 >> (26))), ((result / (result | 1)) ? f2(g1, 0, 49, (int)sizeof(long), -44) : (-50 % (g7 | 1))));

    return (result >= 0 ? result : -result) & 255;
}
