/* Generated by cgen, seed=491 */

int g0;
unsigned char g1;
unsigned int g2;
int g3[2];
char g4 = 0;
unsigned long g5;
int g6 = 0;
unsigned int g7 = -6;
unsigned char g8 = 47;

unsigned long f0(unsigned long p0, unsigned int p1, int p2);

unsigned long f0(unsigned long p0, unsigned int p1, int p2)
{
    unsigned long v0_0;
    v0_0 = 249;

    if (((((int)sizeof(long) | g8) & (0 ? 150 : "wxyz"[0])) % ((('-' << (3)), (g7 == (int)sizeof(char))) | 1))) {
        switch (((g0 >> (13)) > ((int)sizeof(unsigned char) && g3[1]))) {
        case 2:
            g8 /= (((g8 ? 55 : 'r') ? (g5 ? g3[1] : 32) : (v0_0, p0)) | 1);
            break;
        case 6:
            if (("hello"[4] < (int)sizeof(int))) {
                g1 = (2198 || 0);
                g6 *= (g2 != g5);
            }
            g2 &= ((g3[1] > 1) * ('b' + 'N'));
            break;
        case 13:
            g6 &= ((9 / ("abcd"[2] | 1)) / (("wxyz"[0] ? 0 : -28) | 1));
            break;
        case 18:
            g5 /= (((1 - g4) >> (28)) | 1);
            break;
        case 24:
            g4 /= ((((int)sizeof(char) / ((int)sizeof(unsigned long) | 1)) % ((g6 ? g2 : g3[1]) | 1)) | 1);
            break;
        }
    } else {
        p1 &= (((g0 ^ g4) / ((g8 < g3[1]) | 1)) ? ((1 | g0) ? (0, g6) : (g3[0] - g3[0])) : (('B' >> (6)) ? ((int)sizeof(char) << (27)) : ("world"[1], 23)));
        if (((v0_0 - "fooX"[0]) & ("wxyz"[1] >> (10)))) {
            g8 |= (('I' - (int)sizeof(unsigned int)) < (g3[0] ^ (int)sizeof(long)));
        } else {
            g2 %= (((g2 << (24)) / (((int)sizeof(char) > '*') | 1)) | 1);
            {
                int _d0;
                _d0 = 0;
                do {
                    _d0++;
                    p0 -= (g7 ^ 804);
                } while (_d0 < 5);
            }
        }
        ((("abcd"[2] ? g1 : g4) << (12)) % (((1 << (12)), (g4 & g2)) | 1));
    }
    ((((g3[0] ? p1 : 7301) ? ((int)sizeof(unsigned int) == g2) : (g1 == "hello"[4])) && ((g7, 5007) - (g7 % ("fooX"[0] | 1)))) ? ((((int)sizeof(int) << (4)) ? (9744 | (int)sizeof(unsigned long)) : (g7 << (0))) || ((p1 == g3[1]) & (g3[1], 5491))) : (((g3[0], 'u') > ('f' ? 237 : (int)sizeof(unsigned long))) / ((("fooX"[1] * "fooX"[3]) > ("wxyz"[2] > g6)) | 1)));
    {
        int _f1;
        for (_f1 = 0; _f1 < 2; _f1++) {
            g8 &= (((p0 > g0) | ('^', 1)) ? ((0, 0) ? (g0 == '!') : ("abcd"[0] / (v0_0 | 1))) : (((int)sizeof(unsigned long) ? (int)sizeof(char) : p1) * ('R' ? g8 : p2)));
        }
    }
    g6 /= (((((106 ? -36 : 129) % ((95 ^ g3[1]) | 1)) ? ((p1 - p2) || ((int)sizeof(unsigned int) & '*')) : ((g2 + g4) ? ('C' / (v0_0 | 1)) : (p0 % (g7 | 1)))) | (((g3[1] ? g5 : 0) >> (28)) ? ((p1 % (p1 | 1)) && (g6 * 4384)) : ((g7 > 40), ("hello"[0] % (g3[0] | 1))))) | 1);
    goto _lbl2;
    _lbl2:
    {
        int _f3;
        for (_f3 = 0; _f3 < 1; _f3++) {
            switch (((g2 * "barY"[0]) ? ('=', 1) : (g2 | '5'))) {
            case 4:
                g6 += (("abcd"[1], p2) ^ (g2 >> (9)));
                break;
            case 9:
                {
                    int _d4;
                    _d4 = 0;
                    do {
                        _d4++;
                        g7 = (g8 || 1);
                    } while (_d4 < 1);
                }
                break;
            case 10:
                g6 = ((1 > p2) ^ (38 ? 36 : "hello"[3]));
                break;
            case 19:
                goto _lbl5;
                _lbl5:
                break;
            }
        }
    }
    ((((-18 | 1) | (g8 >> (30))) & ((59 == 69), (-38 / (g4 | 1)))) ? (((g5 << (22)), ((int)sizeof(unsigned long) < g6)) || ((g3[0], "hello"[2]) ? (v0_0, 76) : ("abc123"[2] + ' '))) : ((("wxyz"[0], g2) | (g8 ? 1 : 5213)) && ((1 | g0) ? (g7 % ((int)sizeof(unsigned long) | 1)) : ("fooX"[3] ? 6461 : p2))));
    {
        int _f6;
        for (_f6 = 0; _f6 < 8; _f6++) {
            {
                int _d7;
                _d7 = 0;
                do {
                    _d7++;
                    if ((g1 / (1 | 1))) {
                        p2 *= (1686 < g7);
                    }
                } while (_d7 < 9);
            }
            {
                int _f8;
                for (_f8 = 0; _f8 < 8; _f8++) {
                    g3[0] = (((int)sizeof(unsigned long) || g1) ^ (-8 ? g2 : g8));
                }
            }
            g1 += (((g1 ? 'R' : p0) < (g0 && '|')) == ((1 ? "world"[3] : 16) < ((int)sizeof(unsigned char) < (int)sizeof(unsigned long))));
        }
    }
    {
        int _d9;
        _d9 = 0;
        do {
            _d9++;
            {
                int _d10;
                _d10 = 0;
                do {
                    _d10++;
                    goto _lbl11;
                    _lbl11:
                    g8 |= ((77 << (24)) + (p0 - g3[0]));
                } while (_d10 < 8);
            }
        } while (_d9 < 5);
    }
    return (p0);
}

int main(void)
{
    int result;
    long m0;
    int m1[8];
    char m2;
    char m3[15];
    long m4;
    char m5;
    unsigned char m6;
    unsigned int m7;
    result = 0;
    m0 = 1;
    m1[0] = 95;
    m2 = 0;
    m3[0] = 0;
    m4 = 1;
    m5 = 1;
    m6 = 46;
    m7 = 0;

    ((((-47 + -8), (g4 << (4))), ((4891 | m0) >> (17))) * f0(f0((m2, g7), (m3[9] > m1[6]), f0('R', g0, g6)), (f0(0, g8, g8) && (1 < g1)), ((g6 >> (25)), (m6 & m6))));
    m1[3] = ((((2422 + "fooX"[3]) && (-30, 1)) ? (f0(g4, g1, 1) + (result > 1)) : (('J' == "wxyz"[2]), ("abc123"[3] & m7))) / (f0(((m1[0] ? 1 : 89), f0(8714, 1, m3[7])), ((m6 & g8) || ((int)sizeof(unsigned long) * m1[5])), ((m5 | (int)sizeof(int)) ? f0('%', m0, (int)sizeof(int)) : f0(708, m5, m3[12]))) | 1));

    result = 0;
    result += (int)(m5);
    result += (int)(g1);
    result += (int)(g1);
    result += (int)f0((f0(m5, m2, 'A') || (m1[5] ? m4 : m3[3])), (('5' & g2) < (m0 > 57)), (("world"[4] + "abcd"[3]), ("abc123"[5] ? m4 : g3[1])));
    result += (int)f0(((m1[4] & m1[4]) << (18)), ((g8 ^ "barY"[1]) * (g7 < 85)), (f0(12, g4, g5) / ((g6 & 55) | 1)));
    result += (int)f0((((int)sizeof(int) * g8) && (g5 % (g3[0] | 1))), ((g4 < 95) + (m4, 57)), ((1 << (18)), (-9 >> (9))));

    return (result >= 0 ? result : -result) & 255;
}
