/* Generated by cgen, seed=450 */

struct S0 {
    unsigned long m0;
    unsigned int m1;
};

int g0[5];
unsigned int g1 = -49;
unsigned int g2;
int g3[2];
struct S0 gs4;
int g5[13];
long g6;
long g7;
unsigned long g8;
char g9 = -24;

unsigned char f0(void);
int f1(void);

unsigned char f0(void)
{
    char v0_0;
    unsigned int v0_1;
    int * v0_2;
    v0_0 = 18;
    v0_1 = 24;
    v0_2 = 0;

    ((((',' == 0) << (26)) ? ((99 ? (int)sizeof(unsigned char) : "abc123"[1]), (v0_0 >> (23))) : ((g6 < 'e') + ('A' > 755))) > (((1 ? g5[4] : ']') < (g9 >> (7))) * ((v0_0 && "hello"[0]) || (g6 ? g9 : g3[1]))));
    return (g8);
}

int f1(void)
{
    unsigned long v1_0;
    v1_0 = 1;

    g8 = (((f0() + ((int)sizeof(unsigned char) ? g1 : 242)) < (((int)sizeof(char) >> (28)) / (((int)sizeof(long) - g8) | 1))) * ((f0() > (9035 - "abcd"[3])) / ((f0() ? (-6 % (9329 | 1)) : (-23 ? g2 : g1)) | 1)));
    v1_0 *= ((f0() != (("abc123"[5] || 166) - f0())) == ((f0() > (g2 ? "abcd"[3] : '~')) > f0()));
    ((((g9 & g7) - (g6, g0[3])) < ((g2, "abc123"[3]) ? (v1_0 * g5[3]) : (g6, g1))) == ((((int)sizeof(int) | g1) && (g8 < 'g')) > f0()));
    g2 /= (((((g8 == 246) >> (16)) && (f0() & (1 ^ g8))) < (((g9 ? g6 : "test"[2]) < (134 > (int)sizeof(char))) & ((-14 - (int)sizeof(int)) || ('v' >> (2))))) | 1);
    if ((((159 | 21) & f0()) < (('U' ^ "hello"[3]) < f0()))) {
        g7 %= (((('r' >> (24)) ? ("world"[0] || (int)sizeof(unsigned char)) : ('S' ? 0 : 'S')) ? ((142 + '_'), (g1 ? 5 : g8)) : ((-27 ? "hello"[3] : g9) ? ("barY"[1] | "world"[2]) : ((int)sizeof(unsigned char) * g6))) | 1);
        if (((1 ? g7 : (int)sizeof(char)) > (g5[11] || "hello"[0]))) {
            v1_0 = ((',' ^ 0) == (g0[1] ? v1_0 : (int)sizeof(int)));
        }
        {
            int _w0;
            _w0 = 0;
            while (_w0 < 3) {
                _w0++;
                switch ((1 ? "barY"[2] : g5[3])) {
                case 1:
                    g2 %= (('g' != ')') | 1);
                    if (g5[2]) {
                        g7 |= '#';
                    } else {
                        g6 %= (8 | 1);
                    }
                    break;
                case 5:
                    g7 += (g1 | g8);
                    break;
                case 14:
                    v1_0 %= ((8308 - g7) | 1);
                    break;
                case 19:
                    g6 = (v1_0 % (714 | 1));
                    break;
                case 21:
                    g6 /= ((g0[1], g7) | 1);
                    g2 = (242 % ("barY"[2] | 1));
                    break;
                default:
                    g6 &= f0();
                    g9 += ("fooX"[0] - 234);
                    break;
                }
                {
                    int _w1;
                    _w1 = 0;
                    while (_w1 < 5) {
                        _w1++;
                        g6 *= f0();
                    }
                }
            }
        }
    }
    return (g1);
}

int main(void)
{
    int result;
    char * m0;
    char * m1;
    int m2[6];
    unsigned int m3;
    long m4;
    char * m5;
    int m6;
    result = 0;
    m0 = 0;
    m1 = 0;
    m2[0] = 0;
    m3 = 1991;
    m4 = 135;
    m5 = 0;
    m6 = 0;

    m6 |= (((('v' < (int)sizeof(long)), (g0[2] - (int)sizeof(unsigned int))) >> (10)), f1());
    switch ((((m3 || g6), (g8 ? g0[1] : m3)), (((int)sizeof(unsigned int) | (int)sizeof(int)) ? (98 || g2) : ((int)sizeof(long) < m6)))) {
    case 4:
        if ((f0() == (g8 * 20))) {
            {
                int _d2;
                _d2 = 0;
                do {
                    _d2++;
                    m6 *= f1();
                } while (_d2 < 3);
            }
        } else {
            m4 -= (f1() - (8346 ? result : g3[1]));
            g1 += (((int)sizeof(unsigned int) + (int)sizeof(long)) > (m6 + "barY"[2]));
        }
        break;
    case 8:
        gs4.m1 = ((f0() || (']' && 'I')) ? ((g0[1] * (int)sizeof(unsigned long)) % (('k' != 57) | 1)) : (("abcd"[1] != (int)sizeof(long)) % (("abc123"[4] * m4) | 1)));
        break;
    case 13:
        g8 *= ((('6' ? (int)sizeof(char) : g9) + (g9 * 0)) ^ ((result, 0) ? (0 << (30)) : f0()));
        {
            int _d3;
            _d3 = 0;
            do {
                _d3++;
                g8 %= (f0() | 1);
            } while (_d3 < 5);
        }
        break;
    case 17:
        {
            int _d4;
            _d4 = 0;
            do {
                _d4++;
                {
                    int _d5;
                    _d5 = 0;
                    do {
                        _d5++;
                        result |= (-39, 44);
                    } while (_d5 < 2);
                }
            } while (_d4 < 2);
        }
        break;
    default:
        m3 /= ((((m3 | g8), ("test"[3] << (27))) ^ f1()) | 1);
        break;
    }

    result = 0;
    result += (int)(m3);
    result += (int)(g2);
    result += (int)(g8);
    result += (int)(g2);
    result += (int)(g9);
    result += (int)f0();

    return (result >= 0 ? result : -result) & 255;
}
