/* Generated by cgen, seed=39 */

struct S0 {
    unsigned char m0;
    long m1;
    char m2;
    long m3;
    long m4;
};

struct S1 {
    long m0;
    int m1;
};

struct S2 {
    long m0;
    int m1;
    char m2;
};

struct S3 {
    unsigned long m0;
    unsigned long m1;
    unsigned char m2;
};

struct S4 {
    unsigned long m0;
    unsigned long m1;
};

struct S5 {
    unsigned int m0;
    unsigned char m1;
    char m2;
    char m3;
};

struct S6 {
    unsigned char m0;
    unsigned long m1;
    char m2;
    long m3;
    char m4;
};

long g0;
unsigned long g1 = 5864;
struct S3 gs2;
int g3[14];
unsigned int g4;
unsigned int g5 = -5;
unsigned long g6 = 0;
long g7;
long g8;

int f0(int p0, char p1, unsigned char p2, long p3, unsigned int p4);
int f1(unsigned char p0, int p1, char p2);
char f2(unsigned long p0, unsigned int p1, long p2, unsigned char p3, char p4);
unsigned int f3(long p0, unsigned long p1, unsigned long p2, unsigned char p3, long p4);
int f4(unsigned int p0, char p1, char p2);
unsigned long f5(unsigned long p0, unsigned long p1, unsigned int p2);
int f6(unsigned int p0, unsigned long p1, unsigned char p2);
unsigned long f7(int p0, unsigned char p1, char p2, unsigned long p3, char p4);

int f0(int p0, char p1, unsigned char p2, long p3, unsigned int p4)
{
    int v0_0;
    v0_0 = 387;

    p1 += ((((g7 << (10)) ? (p0 ? "abcd"[2] : g0) : ((int)sizeof(long) >> (0))) % (((g6 ? 52 : (int)sizeof(unsigned int)) / ((33 >> (9)) | 1)) | 1)) || (((g3[4] / (g3[12] | 1)) && (g3[12], "hello"[4])) || ((4387 < p0) << (3))));
    g6 |= ((((p2 >> (1)) % ((0 + g4) | 1)) | ((g3[0] ? 14 : 'h') ? (p1 == -35) : (14 | g1))) & ((('2' - (int)sizeof(char)), (p1 ? p3 : 'y')) << (15)));
    return (g5);
}

int f1(unsigned char p0, int p1, char p2)
{
    int v1_0;
    unsigned char v1_1;
    char v1_2;
    v1_0 = 215;
    v1_1 = 43;
    v1_2 = 38;

    {
        v1_2 /= ((((v1_0 < 1), (172 / (p2 | 1))) == (f0((int)sizeof(char), "test"[2], g1, 'V', g3[0]) % ((72, (int)sizeof(long)) | 1))) | 1);
    }
    return (g8);
}

char f2(unsigned long p0, unsigned int p1, long p2, unsigned char p3, char p4)
{
    char v2_0[4];
    v2_0[0] = 21;

    {
        int _d0;
        _d0 = 0;
        do {
            _d0++;
            switch ((('`' * (int)sizeof(int)) ? ('q' ^ p4) : (g3[9] > g4))) {
            case 4:
                g4 = f0((1 + 0), (g6 < v2_0[2]), (p2 << (23)), f1(0, -21, -44), (g0 || (int)sizeof(unsigned int)));
                break;
            case 9:
                p3 %= (((g8 != g7), f0(g4, g8, p4, '-', p0)) | 1);
                break;
            case 12:
                goto _lbl1;
                _lbl1:
                break;
            case 15:
                v2_0[1] = ((p2 + (int)sizeof(char)) || (g0 >> (12)));
                break;
            }
            g1 = (((-15 % (v2_0[0] | 1)), ("test"[3] * p0)) ? ((33 & (int)sizeof(int)) && (g3[11] * g1)) : ((41, 31), (g4 ^ (int)sizeof(unsigned int))));
        } while (_d0 < 2);
    }
    return (p0);
}

unsigned int f3(long p0, unsigned long p1, unsigned long p2, unsigned char p3, long p4)
{
    int v3_0;
    unsigned int v3_1;
    unsigned long v3_2;
    int v3_3;
    v3_0 = -32;
    v3_1 = 24;
    v3_2 = -31;
    v3_3 = 221;

    p1 *= ((((g7 | "barY"[1]) + ('?' >> (6))) > ((v3_3 + 1) > f1(0, "abcd"[0], 0))) << (23));
    return (p3);
}

int f4(unsigned int p0, char p1, char p2)
{
    char v4_0;
    unsigned int v4_1;
    int v4_2;
    char v4_3[14];
    v4_0 = 1;
    v4_1 = 146;
    v4_2 = 7408;
    v4_3[0] = 59;

    switch ((((v4_2 == v4_0) || ("hello"[3] ? '8' : 'Q')) - ((g3[2] > g7) | f0(g3[11], p1, 0, (int)sizeof(unsigned int), (int)sizeof(unsigned long))))) {
    case 3:
        gs2.m0 = f0(f1(((int)sizeof(long) - "wxyz"[3]), (g3[13] != g8), (-34 * 0)), f3((v4_2 > "abcd"[0]), f2(0, g8, g8, (int)sizeof(char), 75), (20 * g8), (')' / (13 | 1)), ("abcd"[0] ? p0 : g0)), ((0 ? '^' : g7) * (g4 ? v4_1 : 'R')), f3((p2 << (4)), (v4_1 + "fooX"[3]), ("barY"[3] % (p0 | 1)), (g0 == g6), (1 * g1)), f1((p2 + g7), (g4, '9'), (p0, -43)));
        break;
    default:
        g5 = (((1 > 1) > ((int)sizeof(long) ? g0 : (int)sizeof(long))) == ((p2 < 4453), (g8 ? g7 : v4_0)));
        break;
    }
    switch ((((v4_2 ? g4 : 0) != (p2 || -18)) << (11))) {
    case 1:
        if ((((int)sizeof(unsigned long) ? 0 : (int)sizeof(int)) - (254 * -13))) {
            if ((-31, g0)) {
                v4_2 /= (((int)sizeof(unsigned int) ? p2 : v4_2) | 1);
            }
            if ((g5 && v4_2)) {
                switch (g7) {
                case 4:
                    v4_1 += (int)sizeof(int);
                    v4_1 -= v4_1;
                    break;
                case 8:
                    p2 &= p0;
                    break;
                case 12:
                    g4 += 0;
                    break;
                default:
                    v4_2 -= g4;
                    break;
                }
                g1 %= ((v4_0, v4_2) | 1);
            }
        } else {
            ((v4_2, 186) < (p1, "barY"[3]));
            if ((v4_1, g8)) {
                v4_0 *= (g3[6] != '`');
            } else {
                g4 %= ((134, 116) | 1);
            }
        }
        break;
    case 7:
        ((('U' < "barY"[2]) ? (v4_1 & 'y') : f3(1, v4_1, 4118, g3[13], g8)), ((0 ? g5 : 172), (1 || v4_1)));
        break;
    default:
        p0 &= (((g0 % (p2 | 1)) * f3(p0, g5, (int)sizeof(unsigned long), 180, 1)) ? ((9919 && -5) || (v4_0 ^ 51)) : (f1(1, 1, 1) ? ("abcd"[3] + (int)sizeof(long)) : (-16 | -16)));
        break;
    }
    v4_0 /= (((((g1 % (0 | 1)), f3(g8, (int)sizeof(int), v4_3[5], g0, (int)sizeof(int))) ^ ((1748 & p0) >> (18))) ? ((('T' >> (16)) * (g0 ? "world"[3] : '#')) / (((v4_2 < 127) * (g7 & 'd')) | 1)) : ((('4' == (int)sizeof(unsigned int)) == (g4 + 0)) & f1(("abcd"[1], v4_3[5]), (v4_0 || (int)sizeof(long)), ('T' | 60)))) | 1);
    return (g4);
}

unsigned long f5(unsigned long p0, unsigned long p1, unsigned int p2)
{
    unsigned int v5_0;
    int v5_1[2];
    char v5_2[2];
    unsigned long v5_3;
    unsigned int v5_4;
    v5_0 = -6;
    v5_1[0] = 25;
    v5_2[0] = -22;
    v5_3 = -9;
    v5_4 = 4149;

    v5_3 = ((((g7 / (p0 | 1)) * (g4 ? g6 : 35)) ^ (((int)sizeof(unsigned char) < v5_0) != ((int)sizeof(int) ? 1 : 50))), ((('Y' << (18)) < (1 != g1)) << (22)));
    if (((((int)sizeof(char) | g0) < (v5_2[0] > 25)) % (((g7 || 'm') || (g7 | v5_1[1])) | 1))) {
        {
            int _w2;
            _w2 = 0;
            while (_w2 < 6) {
                _w2++;
                {
                    int _d3;
                    _d3 = 0;
                    do {
                        _d3++;
                        v5_3 %= (("hello"[1] * g6) | 1);
                    } while (_d3 < 1);
                }
                p0 &= ((1 % (95 | 1)), f1(g6, g1, g4));
                p0 /= ((f2(v5_0, ' ', g0, g0, 1174), ((int)sizeof(unsigned int) / (v5_4 | 1))) | 1);
            }
        }
        v5_1[1] = (((24 | p0) ^ f2("world"[3], g0, g7, 'P', 1)) / (f0((213 ? p1 : 0), (4761 || v5_1[0]), (v5_1[0] || -27), ('O', 5698), f4(-18, 7063, (int)sizeof(long))) | 1));
    }
    {
        {
            int _w4;
            _w4 = 0;
            while (_w4 < 1) {
                _w4++;
                v5_4 *= ((1229 && g7) / ((78 >> (7)) | 1));
            }
        }
        {
            int _f5;
            for (_f5 = 0; _f5 < 7; _f5++) {
                {
                    int _f6;
                    for (_f6 = 0; _f6 < 4; _f6++) {
                        v5_4 -= f4(v5_4, (int)sizeof(int), 1);
                        g1 += (0 ? g8 : v5_4);
                    }
                }
            }
        }
    }
    g5 *= ((((83 ? 0 : 4942) && (g3[13] + (int)sizeof(int))) ? ((v5_2[0] - "wxyz"[1]), (g7 | 1)) : ((g3[8] + g7) ? (g3[3] >> (3)) : (-27 && p0))) && (((g5 >> (23)) || f1(96, g0, "test"[1])) * ((g3[5] == (int)sizeof(unsigned long)) % ((g3[0] < -36) | 1))));
    if (((f3(g5, 1, "test"[3], 66, 1) % (((int)sizeof(long) / (v5_0 | 1)) | 1)) != (f4(v5_4, v5_3, "world"[1]) > ('`' ^ g5)))) {
        v5_2[0] = (((871, (int)sizeof(char)) % ((v5_1[0] + "barY"[3]) | 1)) ^ f1((v5_2[1] + 'A'), ((int)sizeof(int) * 1), ((int)sizeof(unsigned char) > "world"[2])));
    }
    v5_1[0] = ((((g3[1] | p0), (v5_2[0] % (g1 | 1))) != ((g8 && (int)sizeof(unsigned int)), (p0 >> (1)))) % (((((int)sizeof(int) / (49 | 1)) | (629 * (int)sizeof(unsigned char))) < ((g3[10] == 8757) | (0 ? v5_0 : 1))) | 1));
    ((((g1 ? "abc123"[2] : g0) && (-12 % (43 | 1))), ((g5 | v5_0) || (-45 != 0))) - (((6614 / ('E' | 1)) / ((p1 != v5_3) | 1)) | (("test"[1] > (int)sizeof(unsigned char)) ? (v5_2[1] == p1) : (g7 != (int)sizeof(unsigned int)))));
    {
        p0 /= ((((61 << (14)), (g4 % ('A' | 1))) * (((int)sizeof(unsigned int) ? (int)sizeof(char) : 'R'), (v5_3 ? "abcd"[3] : p0))) | 1);
        g8 += ((f0(1910, g8, (int)sizeof(char), 0, g6) >> (16)) & ((-29 * (int)sizeof(unsigned long)) ? f3(7408, g1, "abc123"[5], '1', g6) : ((int)sizeof(unsigned int) != "hello"[0])));
        goto _lbl7;
        _lbl7:
        {
            int _w8;
            _w8 = 0;
            while (_w8 < 5) {
                _w8++;
                {
                    int _d9;
                    _d9 = 0;
                    do {
                        _d9++;
                        g5 = ((int)sizeof(int) | p2);
                    } while (_d9 < 1);
                }
                g6 += (f2(v5_2[1], g8, -16, 'i', v5_2[0]), (v5_1[1] - 71));
                {
                    int _d10;
                    _d10 = 0;
                    do {
                        _d10++;
                        g7 |= ((int)sizeof(unsigned long) == "hello"[4]);
                    } while (_d10 < 4);
                }
            }
        }
    }
    v5_3 |= ((((g6 == (int)sizeof(int)) ? ("barY"[2] || g5) : ((int)sizeof(int), p1)) - ((g5 == p0), (1 | 1))) < (((29, 0), (g4, p1)) << (25)));
    g0 -= (((('L' < (int)sizeof(long)) ? (g5 < "abcd"[3]) : (4501 % (g6 | 1))) / ((f4(g8, '3', 1) ? ('!' == 954) : (v5_3 * 78)) | 1)) || (f1((0 | p2), (v5_0 ? "abc123"[0] : 0), ("hello"[4] != (int)sizeof(unsigned char))) & ((v5_2[0], g3[11]) > (g6, 5722))));
    return (v5_4);
}

int f6(unsigned int p0, unsigned long p1, unsigned char p2)
{
    unsigned int v6_0;
    char * v6_1;
    v6_0 = 1;
    v6_1 = 0;

    if ((((g3[1] % (g7 | 1)) * ('}' || -39)) / (((-24 + '='), (g7 == 'w')) | 1))) {
        (((g1 + p0) != (27 >> (21))) ? ((46 && -32) == (32 > 1)) : ((72 * p1) ? ((int)sizeof(long) ? g1 : 212) : (0 | -30)));
    } else {
        p1 |= (((84 | 95) > (2 ? 293 : (int)sizeof(long))) | ((1, "hello"[4]) >> (13)));
    }
    g0 &= (((("fooX"[0] > 5401) || (g4 << (17))) ? ((g4 != ' ') == (g3[3] | 9652)) : (f3(-15, v6_0, 'z', g5, p0), (g5 ? g4 : p2))) == ((((int)sizeof(long) > g6) ? ("fooX"[3] != "fooX"[2]) : ("wxyz"[3] / ("hello"[4] | 1))), ((g3[2] * 1) - (1 % (g3[3] | 1)))));
    g7 -= ((((g6 | g5), f0('(', 1, -50, "test"[2], 1)) >> (11)) != (((g8 - (int)sizeof(unsigned char)) && (g6 ? p1 : "test"[1])) || f4(('m' | (int)sizeof(char)), ((int)sizeof(unsigned char), 1), (0 != (int)sizeof(int)))));
    if ((((g8 | (int)sizeof(unsigned char)) >> (15)) << (1))) {
        p2 |= (((g3[3] ? 233 : g0) & (g8 | 53)), ((g3[0] * 'a') ? (0 - 1) : f1(p2, 68, 0)));
    } else {
        {
            int _w11;
            _w11 = 0;
            while (_w11 < 9) {
                _w11++;
                g8 *= ((g3[6] ? '2' : g0) / (("fooX"[0] | -23) | 1));
            }
        }
        g0 |= f5(((g5 / (-48 | 1)) < (g3[4] || p2)), ((249 >> (14)), (p1 ? g3[10] : g4)), (('Q' ? g3[13] : g6) > (g3[2] - p2)));
    }
    v6_1 = &g5;
    *v6_1 = (((("world"[0] - p1) * (159 > 'f')) || ((g3[13] == (int)sizeof(char)) ? (v6_0 ^ p2) : (185 ? 0 : 89))) & (((p0 ? p0 : 3519) ? (g6 & p2) : (40 - g8)) ? ((v6_0 ? 'A' : 0), (p0 < p2)) : ((-41 ? g4 : ';') + f5(g3[4], v6_0, g1))));
    v6_1 = &p1;
    *v6_1 = (((f5(0, 0, p2) >> (4)) * (f4(p2, g1, g5) < ("world"[1] ? (int)sizeof(char) : g7))) / ((((g0 | 1) || (g4 != g3[3])) * ((g5 | "wxyz"[2]), ('W' && g3[9]))) | 1));
    {
        int _w12;
        _w12 = 0;
        while (_w12 < 7) {
            _w12++;
            switch ((("abc123"[3], '<') * (g8 / ((int)sizeof(unsigned char) | 1)))) {
            case 2:
                {
                    g8 /= ((g6 << (4)) | 1);
                }
                break;
            case 6:
                ((0 ^ g3[8]) << (27));
                break;
            case 14:
                gs2.m1 = ((1 % (-41 | 1)), f4(g7, (int)sizeof(int), "abcd"[1]));
                {
                    int _w13;
                    _w13 = 0;
                    while (_w13 < 4) {
                        _w13++;
                        g6 |= (78 | p0);
                        g7 = f2(g7, 3831, g8, 0, g3[2]);
                    }
                }
                break;
            case 16:
                {
                    int _f14;
                    for (_f14 = 0; _f14 < 4; _f14++) {
                        g7 /= ((1 >> (2)) | 1);
                    }
                }
                break;
            case 22:
                g7 /= ((('t' ^ 89) || (g4 >> (15))) | 1);
                {
                    int _w15;
                    _w15 = 0;
                    while (_w15 < 2) {
                        _w15++;
                        p1 %= ((0 - (int)sizeof(char)) | 1);
                    }
                }
                break;
            }
        }
    }
    {
        p0 = (((g7 * g3[10]) == (12 > g0)), f3(("wxyz"[0] - 61), (g4, 1), (g1 * "abcd"[1]), (' ' > g0), (1 & "abc123"[1])));
    }
    if ((((p1 ^ 174) >> (12)) - ((g1 ^ 'K'), ('Y', g5)))) {
        gs2.m1 = (((1 || (int)sizeof(long)) * (1 & (int)sizeof(int))) < ((g6 | g7) % ((p2 ? g0 : -28) | 1)));
        {
            g3[12] = (((int)sizeof(char) < 0) % ((150 + g7) | 1));
        }
    }
    {
        int _w16;
        _w16 = 0;
        while (_w16 < 1) {
            _w16++;
            if (((60, g0), ("test"[1] ? g8 : g8))) {
                g6 %= (((-50 & g1) / (('5' ? g6 : 'C') | 1)) | 1);
                gs2.m2 = (('9' && ']') != f3((int)sizeof(unsigned long), -35, g8, "fooX"[0], "abc123"[1]));
                g8 += ((g8, 1), (0 >> (29)));
            } else {
                g7 = ((23 > 1) * (-26 ? g3[6] : 1));
            }
            if (((p2 % (v6_0 | 1)) ? ((int)sizeof(long) || 't') : (g3[11], -17))) {
                g0 %= (f4((g5 ? 1 : 4730), ((int)sizeof(int) % (p2 | 1)), (1 && v6_0)) | 1);
            } else {
                if ((g4 & g8)) {
                    g8 &= (81 && 6380);
                }
            }
        }
    }
    v6_1 = &v6_0;
    *v6_1 = ((((196 > 0) + (g7 > 2067)) != ((g3[1] > "fooX"[0]) + (v6_0 ? g7 : 'm'))) % ((((g0 ^ (int)sizeof(unsigned int)) ? (p2 - g5) : (p0 < 'A')) ? (("abcd"[3] * g7) ? ("hello"[2] << (12)) : ("fooX"[3] ? g1 : g4)) : ((p1 > g4) ? (1 == (int)sizeof(unsigned long)) : (g8 + 23))) | 1));
    switch (f2((f0(v6_0, g3[7], p2, g7, g4) >> (11)), ((0 ? g4 : g0) * (111 & "test"[0])), (("test"[3] & p0) & (0 && 0)), ((-50 > 11) * ((int)sizeof(char) >> (30))), ((33, p1) * ((int)sizeof(unsigned int), g3[0])))) {
    case 0:
        {
            int _f17;
            for (_f17 = 0; _f17 < 9; _f17++) {
                g0 %= (((0 << (19)) + (g4 & 'f')) | 1);
            }
        }
        break;
    case 7:
        {
            int _f18;
            for (_f18 = 0; _f18 < 9; _f18++) {
                g5 %= (((110 & 1) + (g5 + v6_0)) | 1);
            }
        }
        switch (((p1 & 0) * (51, (int)sizeof(unsigned long)))) {
        case 0:
            ((g1 ? g6 : 1281) == f3(g6, '&', -2, v6_0, 65));
            goto _lbl19;
            _lbl19:
            break;
        case 8:
            ((0 + g7) ? f4("abc123"[4], 1, 0) : (243 || g3[11]));
            {
                switch (g8) {
                case 0:
                    g7 &= "world"[2];
                    g6 = p1;
                    break;
                case 8:
                    g0 += 1031;
                    break;
                case 13:
                    p0 |= g3[3];
                    break;
                case 16:
                    p1 += "abcd"[3];
                    break;
                case 23:
                    g8 = g3[7];
                    break;
                default:
                    g5 /= (0 | 1);
                    break;
                }
                switch (g6) {
                case 3:
                    g4 |= (int)sizeof(unsigned int);
                    break;
                default:
                    g6 = "wxyz"[3];
                    p2 |= (int)sizeof(unsigned char);
                    break;
                }
                v6_0 = ((int)sizeof(long) > 17);
            }
            break;
        case 10:
            {
                int _d20;
                _d20 = 0;
                do {
                    _d20++;
                    g1 &= (g6 ^ 43);
                    p2 = ((int)sizeof(unsigned long) != 6832);
                } while (_d20 < 3);
            }
            break;
        default:
            if ((g3[12] ? 184 : '|')) {
                p0 = f1(g4, (int)sizeof(unsigned int), "test"[3]);
            } else {
                g0 %= ((-42 * 1) | 1);
                g0 += (g3[13] + (int)sizeof(unsigned char));
            }
            g4 /= (((g6 == (int)sizeof(int)) >> (17)) | 1);
            break;
        }
        break;
    case 14:
        goto _lbl21;
        _lbl21:
        break;
    default:
        switch ((f2(208, g4, "hello"[0], 5140, g6) != f1(g0, 64, "abcd"[1]))) {
        case 3:
            {
                int _w22;
                _w22 = 0;
                while (_w22 < 4) {
                    _w22++;
                    p1 &= (p2 + v6_0);
                }
            }
            break;
        case 6:
            g6 = f5((5 + g8), (71 ? g5 : 4), ('7' - g0));
            break;
        case 14:
            g7 %= (((g5 && g1) ? ((int)sizeof(unsigned long) || 'g') : (9 < (int)sizeof(int))) | 1);
            {
                g8 = (6758 | "abcd"[2]);
                g8 -= (g1 & "world"[1]);
            }
            break;
        case 15:
            g1 /= (((g0 >> (14)) < (-27 ? g7 : -29)) | 1);
            break;
        case 23:
            p0 -= ((5047 - g5) >> (28));
            break;
        default:
            {
                int _f23;
                for (_f23 = 0; _f23 < 3; _f23++) {
                    p2 += (g3[10] ^ p0);
                }
            }
            p1 /= (((g4 & '9') / (('(' & 93) | 1)) | 1);
            break;
        }
        break;
    }
    return (v6_0);
}

unsigned long f7(int p0, unsigned char p1, char p2, unsigned long p3, char p4)
{
    unsigned long v7_0;
    int v7_1;
    v7_0 = 46;
    v7_1 = 60;

    g8 &= ((((1 ? "world"[4] : p3) ^ (134 ^ 838)) - (((int)sizeof(long) % (p2 | 1)), (0 < g0))) & (((g8 ^ "abc123"[4]) && ('>' & (int)sizeof(unsigned long))) >> (15)));
    v7_1 &= (((f6(9598, 181, g8) % ((89 < p4) | 1)) == ((g3[3] - -43), ((int)sizeof(unsigned long) ? g3[6] : 43))) % ((((g3[3] != 1) && f0(1, g3[10], "abc123"[2], 74, "world"[1])) && ((g5 ? g3[13] : g0) & (g3[5] ? 34 : g5))) | 1));
    {
        int _w24;
        _w24 = 0;
        while (_w24 < 6) {
            _w24++;
            g7 /= ((f0((g5 ? p4 : g6), (v7_0 >> (3)), f4(g7, g1, -24), ('d', -42), (71 != (int)sizeof(char))) ? ((g3[10] != 1) & ("world"[0] != 't')) : ((51 / (g8 | 1)) != ('c' << (26)))) | 1);
        }
    }
    return (g1);
}

int main(void)
{
    int result;
    struct S4 m0;
    unsigned int m1;
    result = 0;
    m0.m0 = -37;
    m0.m1 = 9930;
    m1 = 0;

    if (((('L' == 1) ? ((int)sizeof(unsigned long) << (24)) : ((int)sizeof(int) != 0)) == f7(("fooX"[0] | 'H'), (g8 >> (18)), ("world"[2] ? g0 : "world"[3]), ("abc123"[4] << (13)), ("wxyz"[1] % ("hello"[4] | 1))))) {
        {
            int _w25;
            _w25 = 0;
            while (_w25 < 1) {
                _w25++;
                {
                    g1 |= (g3[1] < g1);
                }
            }
        }
    } else {
        m1 -= (((g4, (int)sizeof(char)) ? (m1 || g7) : (49 * '5')), ((5748 + 162) - (0 + g3[5])));
    }
    g8 -= (((("wxyz"[2] / (g3[10] | 1)) + (0, -38)) == ((g7 >> (27)) * ('7' ? 'o' : m1))) == (f3((g0 >> (22)), (g0 ? g4 : g0), (m1 ? g5 : (int)sizeof(unsigned int)), (98 && g1), (g6 && result)) || f1(((int)sizeof(char), g0), ((int)sizeof(unsigned long) ? (int)sizeof(unsigned int) : g0), (-42 << (0)))));
    {
        int _f26;
        for (_f26 = 0; _f26 < 7; _f26++) {
            switch ((("test"[3] == 'u'), (24 % (1 | 1)))) {
            case 2:
                {
                    int _d27;
                    _d27 = 0;
                    do {
                        _d27++;
                        g5 -= f0(g3[2], '`', g0, result, "test"[1]);
                    } while (_d27 < 2);
                }
                g5 -= ((52 > 177) == ("abcd"[3] / (0 | 1)));
                break;
            case 5:
                g7 /= ((('N' ? (int)sizeof(char) : g3[1]) + (34 % (48 | 1))) | 1);
                goto _lbl28;
                _lbl28:
                break;
            case 12:
                goto _lbl29;
                _lbl29:
                break;
            default:
                goto _lbl30;
                _lbl30:
                break;
            }
            g0 |= (((g6 | 10) ^ (-26 * g8)) * ((g5 ? 3931 : "test"[2]) / ((g3[13] % (g3[6] | 1)) | 1)));
        }
    }
    {
        int _w31;
        _w31 = 0;
        while (_w31 < 2) {
            _w31++;
            result /= (f3((((int)sizeof(unsigned int) ? g0 : 'E') < (m1 > 233)), ((0 + -26) > (216 << (16))), ((g3[10] - 1) | f3(result, g7, 0, g7, g0)), (f0(211, 6, m1, 173, "fooX"[0]) > (g5 ? "barY"[2] : g3[1])), ((g0 + (int)sizeof(char)) << (6))) | 1);
        }
    }

    result = 0;
    result += (int)(g0);
    result += (int)(g4);
    result += (int)(g6);
    result += (int)f4(((73 ? m1 : '~') & (30 ? g8 : g1)), ((g6 < 1) / ((g0 != 46) | 1)), f4((16 ? -13 : '#'), (g6 - g7), (g5 / ('*' | 1))));
    result += (int)f6(f1((g0 && 3900), f1('b', 'V', 100), ('+' ? 44 : 1)), (((int)sizeof(int) << (24)) != f0('S', g0, (int)sizeof(unsigned long), "barY"[3], "barY"[2])), (("abc123"[3] ? -47 : 'g') || (-39 % (g7 | 1))));
    result += (int)f2(((194 ? 0 : "wxyz"[3]) & (16 % ("wxyz"[3] | 1))), (f5((int)sizeof(unsigned char), 8647, g0) ^ (1 < g5)), f7((-37 % (g5 | 1)), (g5, 0), (5340 ? g5 : 'w'), (g7, "hello"[0]), ('o', g1)), ((m1 / ('d' | 1)) / (("barY"[0], g7) | 1)), (f5(240, 3015, "wxyz"[1]) ? ('j' != 1) : (g4 << (14))));

    return (result >= 0 ? result : -result) & 255;
}
