/* Generated by cgen, seed=117 */

struct S0 {
    unsigned long m0;
    long m1;
    char m2;
};

struct S1 {
    unsigned long m0;
    unsigned char m1;
    char m2;
    unsigned int m3;
};

struct S2 {
    unsigned long m0;
    unsigned char m1;
    unsigned char m2;
    unsigned char m3;
    char m4;
    unsigned char m5;
};

struct S3 {
    char m0;
    unsigned int m1;
    unsigned char m2;
    unsigned long m3;
    unsigned char m4;
    int m5;
};

struct S4 {
    long m0;
    int m1;
    unsigned long m2;
    int m3;
};

int g0[12];
int g1 = 38;
int g2[14];
int g3[15];
unsigned int g4;
int g5[8];

unsigned int f0(int p0, unsigned char p1, unsigned int p2);
long f1(unsigned char p0, long p1, char p2, unsigned int p3, unsigned long p4);
long f2(int p0, int p1, unsigned long p2);
long f3(void);
int f4(unsigned long p0, unsigned int p1, char p2);
unsigned long f5(char p0, unsigned char p1, int p2, int p3);

unsigned int f0(int p0, unsigned char p1, unsigned int p2)
{
    char v0_0[11];
    char v0_1;
    int v0_2;
    long v0_3;
    char v0_4;
    int * v0_5;
    int * v0_6;
    unsigned long v0_7;
    v0_0[0] = 205;
    v0_1 = 0;
    v0_2 = 0;
    v0_3 = 45;
    v0_4 = 1;
    v0_5 = 0;
    v0_6 = 0;
    v0_7 = 1;

    ((((4545 % (15 | 1)), (v0_2 != v0_2)) - ((v0_1 ? 7833 : -41) | (v0_0[7] != '='))) != (((41 != g5[6]) > ('Z' ^ g2[13])) != ((v0_7 / (0 | 1)) && (v0_3 & "hello"[0]))));
    p2 = ((((p1 ? v0_3 : g5[0]) != (g4 || g3[6])) ? ((v0_2 ? g0[9] : "wxyz"[1]) == ("abcd"[1] | g0[9])) : ((g5[6] < (int)sizeof(long)) << (1))) > ((("abcd"[1] != 209) / (("fooX"[0] - p1) | 1)) ? ((p0 ? g2[2] : v0_1) < ("abcd"[0] / (v0_7 | 1))) : ((v0_7 ? 1 : g1) != (1 / (p0 | 1)))));
    return (p1);
}

long f1(unsigned char p0, long p1, char p2, unsigned int p3, unsigned long p4)
{
    int v1_0;
    char v1_1;
    char v1_2;
    unsigned char v1_3;
    v1_0 = 1;
    v1_1 = 203;
    v1_2 = 93;
    v1_3 = -14;

    {
        int _d0;
        _d0 = 0;
        do {
            _d0++;
            v1_1 %= ((((34 * 8939), f0(189, 1, 23)) * (f0(v1_0, g2[6], 1) + (31 ? -4 : '('))) | 1);
        } while (_d0 < 7);
    }
    p4 = f0(((("test"[3] ? p3 : v1_0) != ("wxyz"[1] + (int)sizeof(int))) << (10)), (((p1 ? (int)sizeof(unsigned char) : 0), (v1_2 % (1 | 1))) * (('=' > p4) | ((int)sizeof(unsigned char), -2))), (((g4 >> (17)) || (v1_3 & -31)) >> (8)));
    switch (((('k' ? (int)sizeof(unsigned long) : 62) ? (g4, g1) : ('q', 'l')) ? ((0 > 'A') ? ("barY"[0] / (1 | 1)) : ((int)sizeof(unsigned int) != g4)) : ((v1_2 < p2) << (10)))) {
    case 1:
        p4 /= ((((g4 / (g2[4] | 1)) < ((int)sizeof(unsigned char) ? g1 : (int)sizeof(unsigned long))) != ((g4 != 0) * (g0[11] != 1))) | 1);
        break;
    case 8:
        switch (((172 >> (19)) < f0(p3, v1_3, 0))) {
        case 4:
            (((int)sizeof(unsigned int) ^ (int)sizeof(char)) % ((v1_3, "hello"[2]) | 1));
            break;
        case 8:
            g1 |= (((int)sizeof(unsigned long), v1_2) == ((int)sizeof(long) ? g1 : -15));
            {
                int _d1;
                _d1 = 0;
                do {
                    _d1++;
                    if (p2) {
                        p4 *= 49;
                    } else {
                        v1_2 += '_';
                        g1 %= (-21 | 1);
                    }
                } while (_d1 < 3);
            }
            break;
        }
        {
            int _w2;
            _w2 = 0;
            while (_w2 < 6) {
                _w2++;
                if ((p0, "hello"[4])) {
                    g4 -= (g2[9] - '$');
                }
            }
        }
        break;
    case 13:
        {
            int _d3;
            _d3 = 0;
            do {
                _d3++;
                f0(f0(90, 6, 1), (p3 ? 'q' : "abcd"[3]), (v1_2 / (p2 | 1)));
                p1 /= (f0(f0(p0, 't', 7943), ("abc123"[5] ? p4 : g2[12]), ('7' > g4)) | 1);
            } while (_d3 < 3);
        }
        break;
    default:
        p0 |= (((56, (int)sizeof(int)) & (v1_2 | g2[5])), ((0 % (0 | 1)) - ('(' && (int)sizeof(int))));
        break;
    }
    p2 -= ((((v1_1 != p1) - (g0[9] | "fooX"[1])) ? ((-5 == g1) ? (g2[8] != p2) : (p4 < -37)) : ((p1 ? -21 : g3[9]) && (v1_3 > 34))) != (((168 * v1_3) | (13 ? '?' : v1_2)) + ((0 * 0) + ("abc123"[0] ? -25 : 1))));
    {
        int _d4;
        _d4 = 0;
        do {
            _d4++;
            {
                int _w5;
                _w5 = 0;
                while (_w5 < 9) {
                    _w5++;
                    {
                        int _w6;
                        _w6 = 0;
                        while (_w6 < 3) {
                            _w6++;
                            p2 |= (g5[1] ? 1 : ' ');
                            p2 *= ((int)sizeof(unsigned int) == g1);
                        }
                    }
                }
            }
        } while (_d4 < 10);
    }
    return (p2);
}

long f2(int p0, int p1, unsigned long p2)
{
    char * v2_0;
    int v2_1;
    int v2_2;
    v2_0 = 0;
    v2_1 = 1;
    v2_2 = 1908;

    if ((((p1 + 6684) + f0('i', p2, 0)) ? f0((v2_1, g1), ((int)sizeof(char) % (p2 | 1)), ('e' ^ (int)sizeof(unsigned int))) : ((1 ? 51 : (int)sizeof(long)) == (g5[7] * p1)))) {
        v2_2 &= ((("abc123"[4] ? (int)sizeof(unsigned int) : p2) % (((int)sizeof(int) ^ p0) | 1)) ? ((g1 != "test"[0]), (1 << (27))) : (((int)sizeof(char) || p2) > (5106 < 51)));
    } else {
        {
            g1 |= ((121 | (int)sizeof(int)) + ((int)sizeof(unsigned char) * g4));
            v2_0 = &g4;
        }
    }
    g1 |= ((((v2_1 || "hello"[1]) << (24)) & (f1(g4, v2_1, p1, 25, "barY"[3]) >> (6))) != (((-45 ? 'A' : g4) ? (p0, 1) : (-20 && 5098)) ^ ((p2 ^ g5[4]) > ('l' || p1))));
    ((((g1 * 9283) && f1(1, 5, "hello"[2], g4, "wxyz"[0])) != ((p0 & "test"[3]) || (g1 - p0))), (((p0 ? g1 : 21) ^ (v2_1 & v2_1)), (("test"[1] / (p0 | 1)) | f1(g4, "test"[2], 's', "abcd"[2], 5))));
    p2 += f0((f0((p1 + 124), (230 && p0), f0(g1, g5[6], v2_1)) ? ((g4 ? 3514 : (int)sizeof(long)) ^ (p1 != (int)sizeof(unsigned long))) : ((p1 % (p1 | 1)) >> (17))), (((1856 == g1) == (v2_2 ? p1 : "abc123"[1])) > ((-37 << (29)) % (('g' ? "barY"[0] : "world"[0]) | 1))), ((((int)sizeof(unsigned char) >> (18)), (g1 ? p2 : g1)) ? ((149 / (g1 | 1)) % ((-42 || p0) | 1)) : ((g5[0] & 11) && (0 < 1))));
    g1 += (((("abc123"[4] ? 1 : 7) * f1(g0[10], g5[6], "barY"[2], 62, p2)) || ((-24 >> (5)) ^ ((int)sizeof(int) + 94))) || ((((int)sizeof(unsigned char) ^ v2_1) << (0)) < (((int)sizeof(int) < 1945) >> (12))));
    switch (((f0(6465, "barY"[3], g4) ? (-41, 23) : ('[' >> (8))) * ((v2_2 * p0) & (g2[1] / ('e' | 1))))) {
    case 4:
        p0 /= ((((g2[9] - p0) + ((int)sizeof(char) || g2[6])) && ((1 | g1) ? (1 && v2_2) : (-24 ? v2_1 : v2_2))) | 1);
        switch (f0((65 < v2_2), (p1 ? (int)sizeof(int) : 0), ('L' * 'H'))) {
        case 1:
            {
                int _w7;
                _w7 = 0;
                while (_w7 < 5) {
                    _w7++;
                    switch (80) {
                    case 3:
                        p0 /= (p2 | 1);
                        break;
                    case 9:
                        p0 -= (int)sizeof(int);
                        break;
                    case 11:
                        g4 /= (0 | 1);
                        break;
                    default:
                        p2 %= ('o' | 1);
                        break;
                    }
                    p2 = (-39, p2);
                }
            }
            break;
        case 6:
            g4 *= ((g3[7] / (103 | 1)) | ("abc123"[2], (int)sizeof(unsigned long)));
            break;
        case 11:
            p0 |= ((g5[6] || p0) & (p2 ? g1 : g1));
            break;
        case 15:
            g4 = ((g1 ? 13 : g3[1]) % (("world"[0] << (7)) | 1));
            break;
        case 24:
            g1 &= ((7026 - v2_2) ? ("hello"[0] ? 'V' : 125) : f1(3, 75, p0, g5[7], g5[3]));
            break;
        default:
            if ((6098 << (4))) {
                if ("barY"[3]) {
                    p2 %= (1 | 1);
                } else {
                    p2 &= p1;
                    p1 += 35;
                    v2_2 &= p0;
                }
            } else {
                if ('V') {
                    p1 %= (g2[1] | 1);
                } else {
                    p1 -= v2_2;
                }
                g1 %= ((210 < p0) | 1);
                v2_2 -= ((int)sizeof(unsigned int) * g4);
            }
            break;
        }
        break;
    case 6:
        {
            int _f8;
            for (_f8 = 0; _f8 < 1; _f8++) {
                {
                    int _w9;
                    _w9 = 0;
                    while (_w9 < 2) {
                        _w9++;
                        switch (g1) {
                        case 3:
                            g1 *= (int)sizeof(unsigned long);
                            g1 |= p2;
                            break;
                        case 6:
                            p1 |= 0;
                            break;
                        case 13:
                            p0 += p2;
                            break;
                        case 19:
                            g4 -= 1;
                            break;
                        case 20:
                            v2_1 = p0;
                            break;
                        }
                    }
                }
            }
        }
        v2_0 = &p1;
        *v2_0 = (((141 || "fooX"[3]) ^ (v2_2 | g0[2])) ? ((v2_1 != p0) && (v2_2 >> (11))) : ((p0 & g4) * (p2 * p2)));
        break;
    case 12:
        switch (((150 % (-6 | 1)) ? (1 || 0) : (g1, (int)sizeof(char)))) {
        case 1:
            {
                int _f10;
                for (_f10 = 0; _f10 < 1; _f10++) {
                    p2 *= (0 + g5[2]);
                    if (g0[7]) {
                        g1 |= g5[7];
                    }
                }
            }
            break;
        case 5:
            {
                v2_1 |= (p0 ? g4 : 'U');
            }
            if (("barY"[2] >> (4))) {
                v2_1 /= (((int)sizeof(unsigned long) | g4) | 1);
                v2_1 %= ((g4, v2_1) | 1);
            }
            break;
        default:
            {
                int _w11;
                _w11 = 0;
                while (_w11 < 5) {
                    _w11++;
                    g4 -= (p0 || '.');
                    v2_2 |= (v2_1 | p0);
                    if (v2_2) {
                        g1 = 1037;
                    }
                }
            }
            break;
        }
        break;
    case 18:
        (f1(("hello"[4] << (13)), ((int)sizeof(unsigned long) < (int)sizeof(unsigned int)), (p1 ? p0 : p1), ((int)sizeof(unsigned int) ? g4 : g5[7]), ((int)sizeof(unsigned long) == p1)) + ((g4 >> (13)) - f1(81, g5[6], 1, 6988, 306)));
        break;
    }
    return (p0);
}

long f3(void)
{
    char v3_0[5];
    v3_0[0] = 3367;

    g2[9] = (((((int)sizeof(unsigned int) ? 2677 : g3[14]) - (g4 < 0)) << (8)) % ((((g4 ? "wxyz"[2] : 0) - ((int)sizeof(unsigned char) & 'O')) > f1((14 ? g4 : "world"[3]), ('<' ? g1 : 0), (g4, g1), ("fooX"[2] ^ g1), (g4, g1))) | 1));
    return (g1);
}

int f4(unsigned long p0, unsigned int p1, char p2)
{
    unsigned char v4_0;
    int v4_1;
    int v4_2[10];
    v4_0 = -24;
    v4_1 = -22;
    v4_2[0] = 73;

    {
        int _f12;
        for (_f12 = 0; _f12 < 8; _f12++) {
            v4_0 += (f3() && (f2((int)sizeof(unsigned long), p2, g0[2]) == (g1 ? 65 : 0)));
        }
    }
    v4_0 %= (((((1927, g4) - (g1 - 82)) | f0((g0[8], g3[11]), f3(), f1(p2, p1, p2, v4_2[8], p2))) ? (((g1 << (14)) != (p1 ? (int)sizeof(long) : (int)sizeof(unsigned long))) || ((0 / (p0 | 1)) || (0 == g1))) : ((((int)sizeof(unsigned long) + p0) | (p1 << (20))) & ((g4 + (int)sizeof(char)) != f2("abcd"[1], 77, g3[4])))) | 1);
    return (p0);
}

unsigned long f5(char p0, unsigned char p1, int p2, int p3)
{
    struct S0 v5_0;
    char v5_1;
    struct S0 v5_2;
    long v5_3;
    long v5_4;
    v5_0.m0 = 585;
    v5_0.m1 = 1;
    v5_0.m2 = 1166;
    v5_1 = 5;
    v5_2.m0 = 1;
    v5_2.m1 = 8568;
    v5_2.m2 = -13;
    v5_3 = 226;
    v5_4 = 1;

    {
        int _d13;
        _d13 = 0;
        do {
            _d13++;
            p0 -= ((((int)sizeof(char) ? p2 : v5_3) || (v5_4 ? 'A' : v5_3)) > (('Z' ? p1 : 1) ^ ('*' << (0))));
        } while (_d13 < 3);
    }
    v5_0.m0 = ((((1 ? 2516 : "abcd"[0]) % ((g2[3] * p1) | 1)), ((3418 ? (int)sizeof(char) : (int)sizeof(unsigned long)) ^ ('i' + ';'))) * (((p2 ? p1 : 1) && (g4 ? g4 : 9986)) < ((v5_1 % (v5_4 | 1)) ^ ("test"[3], (int)sizeof(long)))));
    v5_4 %= ((((("test"[1] && (int)sizeof(long)) / ((g0[4] ^ 0) | 1)) && f4((p2 > -40), f2('3', v5_4, p2), (v5_1 % ((int)sizeof(long) | 1)))) ? (((g1 & "abc123"[3]) ? (1 < 41) : (v5_3, (int)sizeof(unsigned int))) | (('!', g4) && (v5_1 % ('S' | 1)))) : f4(((1 ^ (int)sizeof(int)) || ("fooX"[2] >> (13))), ((v5_3 * p0) ? f0((int)sizeof(unsigned int), g4, (int)sizeof(char)) : ((int)sizeof(int), g3[3])), f4((p1 % (0 | 1)), (',' > 3146), f4("world"[0], g1, 75)))) | 1);
    ((((538 < p1) && ("abcd"[3], -21)) & ((p3 > 0), ((int)sizeof(unsigned int) << (26)))) || f2(((3643, 186) >> (28)), (f4("hello"[4], g1, p1) + ((int)sizeof(unsigned long), p1)), (f1("abc123"[4], p1, 'v', v5_3, 0) - (g2[8] ^ 19))));
    v5_3 += (f0(((g5[6] != '6') & ((int)sizeof(int) ? v5_1 : p2)), f3(), (f3() < (96 ^ -8))) != (((14 ? -12 : p3) ? (g1 && g4) : ('h', v5_1)) - ((89 ? (int)sizeof(char) : (int)sizeof(long)) < (-35, "hello"[4]))));
    return (g1);
}

int main(void)
{
    int result;
    char m0[4];
    int * m1;
    result = 0;
    m0[0] = 0;
    m1 = 0;

    result -= ((((-45, -9) ? (result - 156) : f5(g4, result, g4, 1)) + ((1 ? g5[3] : (int)sizeof(unsigned long)) % ((1 < (int)sizeof(int)) | 1))) % ((((g4 != 0) % ((g1 % (result | 1)) | 1)) + (("test"[2] * g4) + (-29 * 5382))) | 1));
    g1 += (f4(((0 | -39) + (-24, g0[11])), (((int)sizeof(char), g1) << (2)), ((1046 * -18) + (77 != g1))), (((g2[13] ? g1 : "abc123"[3]) != ('g' != 20)) + (f4(243, 'P', g4) % ((1 & g4) | 1))));
    g1 /= (((f3() / (((g0[10], g1) - (result > 'd')) | 1)) % (((((int)sizeof(char) != (int)sizeof(unsigned int)) ? f4(1, (int)sizeof(unsigned char), result) : ((int)sizeof(unsigned int) > "barY"[0])) ? ((g2[5] + 0) ? ((int)sizeof(unsigned int) == "world"[3]) : ("abcd"[0], 2272)) : ((g4 - result) < (g1 + result))) | 1)) | 1);

    result = 0;
    result += (int)(g1);
    result += (int)(g4);
    result += (int)(g4);
    result += (int)f5((((int)sizeof(long) ? g1 : 'b') % (((int)sizeof(unsigned char) | (int)sizeof(long)) | 1)), (("abcd"[1] & "world"[2]) ? (g1 ? 1 : 75) : (1 && g1)), (((int)sizeof(char) || result), (',' | 0)), ((g4, "abc123"[1]) + (1 ^ 126)));
    result += (int)f2((('*' ? result : g1), (1244 < ' ')), ((g1 ? g2[9] : (int)sizeof(unsigned long)) / ((m0[2] ? result : g3[11]) | 1)), ((g4, (int)sizeof(char)) << (29)));
    result += (int)f0(((result | 57) ^ f4((int)sizeof(long), result, "test"[1])), ((113 | result), (g1 << (22))), (f4(result, 7305, 173), (g4 ? 0 : g1)));

    return (result >= 0 ? result : -result) & 255;
}
