/* Generated by cgen, seed=135 */

struct S0 {
    char m0;
    unsigned int m1;
};

struct S1 {
    long m0;
    long m1;
    long m2;
};

struct S2 {
    long m0;
    int m1;
};

struct S3 {
    unsigned long m0;
    unsigned int m1;
};

struct S4 {
    char m0;
    int m1;
    unsigned int m2;
    int m3;
    long m4;
    unsigned int m5;
};

struct S5 {
    unsigned long m0;
    unsigned char m1;
};

unsigned long g0 = -33;
unsigned long g1;
struct S4 gs2;
unsigned int g3 = 1;
unsigned long g4 = -2;

long f0(int p0, unsigned long p1, int p2, int p3);
unsigned char f1(long p0, unsigned long p1, char p2);
char f2(long p0);
int f3(unsigned int p0);
char f4(unsigned int p0, int p1);
unsigned long f5(int p0, long p1, unsigned long p2);
long f6(char p0, long p1, unsigned long p2, unsigned int p3);

long f0(int p0, unsigned long p1, int p2, int p3)
{
    int v0_0;
    char v0_1[11];
    int v0_2;
    v0_0 = 5172;
    v0_1[0] = 1;
    v0_2 = 28;

    p1 = ((((-22 % ((int)sizeof(unsigned long) | 1)) > (41 || v0_1[9])) ? ((-28 | '$') || (p3, p0)) : (("fooX"[1] || v0_1[4]) ? (p3, (int)sizeof(unsigned int)) : (p1 ? p2 : g3))) * (((v0_0 * g3) ? ("abcd"[2] < v0_1[0]) : ('#' ? g3 : 0)) ^ (('t' ? 1 : p0) / ((g3 == g0) | 1))));
    v0_2 %= ((((("fooX"[0] % (p1 | 1)) - (-1 || v0_2)) && ((p3 ^ (int)sizeof(long)) >> (17))), (((1939 ? 'C' : ':') + (v0_1[8], v0_1[6])), ((p1 == "abcd"[2]) == (v0_1[3] >> (2))))) | 1);
    gs2.m5 = (((("test"[0] - p0) >> (27)) ? ((114 && v0_1[1]) || ((int)sizeof(long) + g0)) : ((v0_1[0] || 'G') ? (0 << (1)) : (p3 ^ v0_0))) ? (((0 == g4) << (7)) ? ((p1 ^ p3) && (p1 & 'I')) : ((v0_0, v0_2) && ('"' < p0))) : (((-31 & v0_1[9]), (4528 != g1)) + ((p0 || p3) + (v0_1[4] << (6)))));
    {
        p3 /= ((((58 ? 'q' : (int)sizeof(unsigned char)) | ((int)sizeof(long) << (29))) && (("world"[4] << (11)) - ((int)sizeof(unsigned int) / (p3 | 1)))) | 1);
    }
    return (p3);
}

unsigned char f1(long p0, unsigned long p1, char p2)
{
    char * v1_0;
    int v1_1[16];
    v1_0 = 0;
    v1_1[0] = 3217;

    g3 /= ((((f0(p2, '#', 127, 1) & (g1 | 1)) - (f0((int)sizeof(int), 82, g1, g3) && ((int)sizeof(unsigned int), g3))), (((g4 * 8) < (109, g4)) ? ((119 / ((int)sizeof(unsigned long) | 1)) % ((40 ? g0 : 36) | 1)) : ((232 % (g1 | 1)), (-6 ? p1 : g3)))) | 1);
    {
        int _d0;
        _d0 = 0;
        do {
            _d0++;
            {
                int _w1;
                _w1 = 0;
                while (_w1 < 5) {
                    _w1++;
                    g1 %= ((("test"[1], (int)sizeof(unsigned char)) - ((int)sizeof(unsigned long) ? "hello"[3] : g3)) | 1);
                    switch ((-9 / (p1 | 1))) {
                    case 2:
                        if (6096) {
                            g3 -= "hello"[0];
                            g3 *= g1;
                        } else {
                            p1 |= 1;
                        }
                        break;
                    case 6:
                        g4 /= (((int)sizeof(unsigned long) * v1_1[6]) | 1);
                        break;
                    case 10:
                        g0 *= (85 > (int)sizeof(long));
                        break;
                    case 18:
                        p0 %= ((g0 + ',') | 1);
                        p2 *= ('2' == 'G');
                        break;
                    }
                }
            }
        } while (_d0 < 8);
    }
    (f0(((p2 ? g1 : g1) * f0(p2, p1, 1, v1_1[13])), ((g4, 6910), ("hello"[2] || g3)), ((g1 | v1_1[15]) - (70 % (63 | 1))), (('q' % (2669 | 1)) - f0("fooX"[0], "abcd"[0], '}', g1))) == (((1 + g1) * (0 >> (5))) + ((p2 + -45) && (0, v1_1[14]))));
    if ((f0(f0((int)sizeof(unsigned char), 238, g0, (int)sizeof(unsigned int)), ((int)sizeof(unsigned char) && g0), f0((int)sizeof(unsigned long), 87, 1, p1), ("test"[3] && 56)) == ((16 ? p0 : 'z') & (1 + "world"[2])))) {
        switch (((p1 > p1) - (p1 ? g0 : 0))) {
        case 0:
            v1_1[12] = ((g1 && -16) - (p0 && g4));
            break;
        case 5:
            goto _lbl2;
            _lbl2:
            break;
        case 10:
            p2 %= ((("world"[0] ? 0 : 29) == (p0 * -26)) | 1);
            break;
        case 16:
            (f0(p1, g4, 7769, 0) >> (10));
            break;
        default:
            ((1, v1_1[1]), (0, 'Y'));
            {
                int _w3;
                _w3 = 0;
                while (_w3 < 3) {
                    _w3++;
                    g4 *= (p1 % (222 | 1));
                }
            }
            break;
        }
        p0 = (((21 > 7057), (v1_1[12] * -35)) + (((int)sizeof(unsigned long) > (int)sizeof(unsigned int)), (-5 == -3)));
    }
    return (g1);
}

char f2(long p0)
{
    int v2_0;
    char v2_1[10];
    v2_0 = 45;
    v2_1[0] = 40;

    v2_0 %= ((((f0(g1, '7', "test"[2], g4) % ((p0 ? g0 : 57) | 1)), f1((v2_1[6] ^ 1), (25, -36), (v2_1[4] == 'S'))), (((v2_0, g1) ? (g1 & p0) : ((int)sizeof(unsigned int) + v2_0)) | ((' ' << (15)) + (v2_1[6] | -7)))) | 1);
    goto _lbl4;
    _lbl4:
    g1 -= (f1((f0("world"[1], 0, 'H', 5276) + (0 ? 28 : 67)), (f1(4916, (int)sizeof(int), v2_1[5]) / ((v2_0 == -28) | 1)), (f0('m', (int)sizeof(unsigned long), g0, p0) ? f1((int)sizeof(unsigned int), "fooX"[2], 35) : f1(g4, v2_1[6], g4))) << (9));
    {
        int _f5;
        for (_f5 = 0; _f5 < 5; _f5++) {
            g3 = ((("test"[3] & 0) << (13)) ? f1((g3, v2_1[1]), f1("abcd"[0], ' ', g4), f1(8, '0', 90)) : (('m' ? 'q' : '&') - ("world"[0], 1)));
            {
                if ((-31 + 72)) {
                    if (v2_1[0]) {
                        g4 -= 7005;
                        g4 *= v2_1[6];
                    }
                }
                g4 |= f0(f0(0, g1, p0, g0), ((int)sizeof(int) && -47), f0(v2_0, -46, g1, (int)sizeof(unsigned int)), (0 && g1));
                v2_0 -= (((int)sizeof(char) ? g3 : v2_1[9]) >> (13));
            }
            {
                int _d6;
                _d6 = 0;
                do {
                    _d6++;
                    (("hello"[2] < "fooX"[1]) << (28));
                    (("abc123"[3] * v2_1[0]) > (v2_0, p0));
                } while (_d6 < 5);
            }
        }
    }
    {
        int _f7;
        for (_f7 = 0; _f7 < 1; _f7++) {
            v2_0 += (((v2_0, g3), (g0 ? v2_1[4] : p0)) + f0((v2_1[1] | v2_1[9]), ('P' ? 'f' : v2_1[4]), (g1 ? (int)sizeof(unsigned long) : v2_0), ((int)sizeof(unsigned long), p0)));
        }
    }
    g1 &= (((f1(1, 1, v2_0), (g4 && "fooX"[0])) % (((g3 || "abc123"[5]) ? (g1 ? (int)sizeof(int) : 76) : (p0 && 1)) | 1)) - (((g3 ? g4 : g3), ((int)sizeof(long) | (int)sizeof(unsigned long))) / (((g1 << (16)) == ((int)sizeof(int) ^ g0)) | 1)));
    switch ((f0((30 / (p0 | 1)), (g3 < v2_0), f0(g0, g4, g4, (int)sizeof(unsigned int)), (g1 > v2_1[3])) != ((38 - 13) || (v2_1[9] | p0)))) {
    case 1:
        g4 &= (f1((g3 / (g1 | 1)), (-29 == v2_0), (p0 / (7245 | 1))) || (("fooX"[0] != (int)sizeof(long)) != (2685 || g1)));
        break;
    case 5:
        p0 += (((v2_0 * 43) & (1 < 0)), (f1(p0, g0, 2151) ^ (178 | p0)));
        break;
    }
    ((((v2_1[5] == p0), f0(1, g0, 'K', v2_1[5])) << (10)) << (1));
    g1 /= (((((g0 ? p0 : (int)sizeof(char)) > ((int)sizeof(char) / (-45 | 1))) < ((0 ? 'm' : (int)sizeof(unsigned int)), ('A' == 'h'))) < (f1((g1 ? '<' : "abc123"[4]), (1 & g3), (v2_0 ? 'O' : v2_0)) ^ (('U' * 6050) >> (20)))) | 1);
    g3 |= ((((1 - 4580) % (f0(78, 228, v2_1[8], g3) | 1)) && ((g1 + "barY"[3]) >> (9))) ? (f0(f0(g4, 7794, g3, v2_0), (p0 < g4), (v2_0, -18), (v2_1[1] && "fooX"[2])) ? (f1((int)sizeof(unsigned int), 145, g3) & (g3 ? v2_0 : v2_0)) : (((int)sizeof(unsigned char) || 0) ? (v2_1[1] && v2_0) : (v2_1[7] + (int)sizeof(char)))) : (((g0 / (0 | 1)) > (g3 ? v2_1[3] : (int)sizeof(unsigned int))) < ((v2_1[4] ? g3 : p0) || (v2_1[3] ? 71 : p0))));
    v2_0 -= ((((g0 ^ "wxyz"[0]) | (g0 > g1)), ((g0 << (14)) | (p0 ? 1 : 'S'))) ? (((1 & 0) ? (g3, 1) : (-17, '8')) << (21)) : ((((int)sizeof(int) != g1) && ((int)sizeof(unsigned long) / ('*' | 1))) * (("fooX"[0] + v2_0) > (18 ? g0 : g0))));
    v2_1[5] = ((((g1, v2_1[5]) ? f1((int)sizeof(long), -15, 7542) : (0 != 93)) > (((int)sizeof(int) | 'D') | f0(g3, p0, 1, g4))), (((g1, g4), ((int)sizeof(unsigned long) - (int)sizeof(char))) | f1((g4, g4), f1((int)sizeof(char), v2_1[8], (int)sizeof(long)), (1 - 0))));
    p0 = (((f0(v2_1[4], g0, g4, p0) / ((g0 + v2_1[5]) | 1)) >> (8)) + ((("hello"[4] + v2_0) ? ("abcd"[1] ? "abc123"[4] : g0) : f0((int)sizeof(unsigned int), g4, 77, g3)) << (15)));
    goto _lbl8;
    _lbl8:
    return (g1);
}

int f3(unsigned int p0)
{
    char v3_0[14];
    int v3_1[15];
    unsigned char v3_2;
    v3_0[0] = 0;
    v3_1[0] = 91;
    v3_2 = 8526;

    {
        int _f9;
        for (_f9 = 0; _f9 < 7; _f9++) {
            {
                ((6007 * 'A') * (v3_1[5] < 0));
            }
        }
    }
    if ((((-10 * 0) > ("fooX"[2] - g3)) > (('F' / (50 | 1)) % ((g4 / (1 | 1)) | 1)))) {
        v3_1[1] = f0(((1 << (4)) ? (6572 ^ (int)sizeof(unsigned int)) : (v3_0[8] ? '6' : (int)sizeof(long))), ((1 / ("hello"[0] | 1)) / (f0(g0, 2983, 174, 8) | 1)), (((int)sizeof(unsigned int) ^ v3_1[10]) & (g1 * 0)), f0((248, -42), (g4 - "abc123"[2]), (1 | 1), ((int)sizeof(unsigned char) | (int)sizeof(unsigned int))));
    } else {
        {
            int _w10;
            _w10 = 0;
            while (_w10 < 8) {
                _w10++;
                goto _lbl11;
                _lbl11:
                {
                    int _d12;
                    _d12 = 0;
                    do {
                        _d12++;
                        switch (248) {
                        case 1:
                            g0 = p0;
                            g0 = 0;
                            break;
                        case 5:
                            g0 /= (g4 | 1);
                            break;
                        }
                    } while (_d12 < 3);
                }
            }
        }
    }
    {
        int _f13;
        for (_f13 = 0; _f13 < 3; _f13++) {
            goto _lbl14;
            _lbl14:
            g1 -= ((((int)sizeof(unsigned long) - 82), (p0 / ((int)sizeof(long) | 1))) > (((int)sizeof(long), "abcd"[1]), (v3_0[6] % (p0 | 1))));
        }
    }
    {
        p0 /= (((f0('a', p0, g3, v3_2) && (g0 ? v3_1[2] : 'Q')) >> (24)) | 1);
        gs2.m1 = ((((int)sizeof(char) || v3_2) >> (29)) < f0((g3 - g4), (v3_1[8] ? g3 : g1), (v3_1[5], 'b'), f2(g0)));
    }
    v3_1[14] = (((((int)sizeof(unsigned long) + 34) % (("abcd"[3] && 1) | 1)) < ((v3_1[14] > v3_2) | f1(g4, p0, g1))), (((g0 == -40) && ((int)sizeof(unsigned long) < 437)) * ((89 & v3_1[10]) ^ (5 < 208))));
    g3 %= ((f1((((int)sizeof(unsigned char) << (19)) ^ f2(v3_1[10])), (("test"[2] < v3_2) * (8170 < (int)sizeof(char))), (("test"[3] - '>') & ("world"[4] < 1))) << (10)) | 1);
    return (p0);
}

char f4(unsigned int p0, int p1)
{
    unsigned char v4_0;
    char v4_1;
    unsigned long v4_2;
    v4_0 = -17;
    v4_1 = -23;
    v4_2 = 87;

    {
        p1 &= (((g3, v4_1), (p1 ? '2' : (int)sizeof(unsigned long))) ? (('Q' | p0) ? ("hello"[4] / ((int)sizeof(char) | 1)) : ((int)sizeof(unsigned int) ? p0 : v4_2)) : ((g1 ? p1 : g3) ? (g3 > 0) : (48 == g4)));
    }
    goto _lbl15;
    _lbl15:
    switch (f3(f0((g1 || "barY"[3]), (g1 == 'O'), (85 + "barY"[2]), (g1 < '!')))) {
    case 2:
        g3 &= (((g4 & 1025) - ((int)sizeof(long) - 1)) ^ ((v4_0 ^ g1) > (1 | 80)));
        break;
    case 9:
        goto _lbl16;
        _lbl16:
        break;
    case 14:
        p1 -= f0(((g0 == '4') < f3(v4_1)), ((g0, v4_0) ? (p0 + (int)sizeof(char)) : f3(v4_2)), ((3481 && '[') | (0, 53)), ((219 ^ g1) % ((g1 ^ v4_0) | 1)));
        break;
    case 17:
        {
            v4_2 -= ((v4_1 || "test"[0]) - f2("test"[0]));
        }
        (((g3 ? 222 : 0) ? ("hello"[2] ^ (int)sizeof(unsigned char)) : (0 ? "test"[1] : 'W')) != ((7832 ? 91 : '7') && (-16, g3)));
        break;
    default:
        g4 |= (((1934 || v4_2), ((int)sizeof(unsigned long) || 1)) * f1(('C' - g0), ('v' - v4_0), f2(82)));
        break;
    }
    switch ((((0 * 'B') != ("hello"[1] >> (1))) ? (('&' < '[') & (p0 || 0)) : (((int)sizeof(unsigned long) && p1) | (p0 ? p0 : v4_2)))) {
    case 2:
        if (((10 || 46) > (1, v4_2))) {
            p0 = (f0(g0, v4_2, g1, (int)sizeof(int)) - (80, g3));
        } else {
            goto _lbl17;
            _lbl17:
            {
                int _d18;
                _d18 = 0;
                do {
                    _d18++;
                    p1 += f0(-43, p0, -13, g0);
                } while (_d18 < 3);
            }
        }
        break;
    case 9:
        g0 /= (f3(((1703 & '8') & (g4 < 26))) | 1);
        break;
    case 14:
        p0 &= (((80 ? g4 : p1) ? ((int)sizeof(unsigned int) & "abc123"[0]) : (71 | 7470)), ((25 ? 54 : g4) & (g4 << (26))));
        break;
    case 15:
        if (((g3 || 1) > (g3, v4_0))) {
            p0 *= ((1 >> (1)) / (((int)sizeof(int) ^ "abcd"[2]) | 1));
        }
        break;
    case 24:
        g1 += (((3489 / (46 | 1)) ? f2(v4_0) : (1 && 1)), ((v4_0 / (0 | 1)) >> (24)));
        break;
    }
    p0 *= f3((((88 ? (int)sizeof(unsigned long) : 0) > ('+' | 0)) != ((0 & 135) << (18))));
    g1 = ((f1(((int)sizeof(unsigned long) ? 5656 : "barY"[3]), (g0 << (20)), (p0 ? 8 : p0)) << (17)) && (f3((-23, 0)) || (("fooX"[0] ? (int)sizeof(char) : "test"[3]) ? f2(p1) : f2('9'))));
    p0 &= (((f2("wxyz"[2]) / ((0 || 112) | 1)) > ((147 & 40) || (g3 ? g3 : v4_0))) && ((("abcd"[1] ? 56 : 7542) || (-6 << (21))) ? ((0 ^ (int)sizeof(long)) ? (p1 < 'j') : ('H', "world"[4])) : f0((v4_0 & p1), (p0 + p1), f2(g1), (14 % (67 | 1)))));
    goto _lbl19;
    _lbl19:
    v4_0 -= (((('N' && -46) + ('y' | 1915)) + ((60 > v4_2) - f0((int)sizeof(int), 'u', 41, 12))) % ((((g0 ? 0 : 252) / ((1 ? "test"[3] : 0) | 1)), ((p0 ? p1 : (int)sizeof(char)) >> (28))) | 1));
    return (v4_2);
}

unsigned long f5(int p0, long p1, unsigned long p2)
{
    char v5_0;
    int v5_1;
    char v5_2;
    v5_0 = 61;
    v5_1 = 14;
    v5_2 = 0;

    g3 += f4(((((int)sizeof(int) ? 8102 : -14) - (1 ^ (int)sizeof(int))), (f4(21, 154) ^ (-15 && -41))), (((v5_1 > g3) + (g0, v5_2)) - ((-18 < v5_0) ? (g1 - p1) : (v5_0 < 'd'))));
    {
        int _d20;
        _d20 = 0;
        do {
            _d20++;
            {
                int _d21;
                _d21 = 0;
                do {
                    _d21++;
                    v5_2 += f1((p0 | 1), (p2 < 1), f0(1, 'u', g4, g4));
                } while (_d21 < 3);
            }
            gs2.m0 = ((f3(22) < (242 ^ g1)) | ((g4 & v5_2) > (81 & 1)));
        } while (_d20 < 9);
    }
    {
        int _w22;
        _w22 = 0;
        while (_w22 < 4) {
            _w22++;
            gs2.m1 = ((f1(1, p1, g3) ? f2(g4) : (p2 & '@')), (f1(-32, -19, 37) << (30)));
        }
    }
    switch ((((v5_0 >> (27)) || (-47 >> (11))) << (22))) {
    case 3:
        g4 |= (((96 & -29), (1903 ? 'M' : g0)) ? ((g3 && -37) < (p0 - 42)) : ((v5_1 == v5_1), (-8 | "test"[1])));
        break;
    case 7:
        {
            {
                int _d23;
                _d23 = 0;
                do {
                    _d23++;
                    if (g0) {
                        g0 %= (42 | 1);
                        p1 -= (int)sizeof(long);
                    } else {
                        g4 = 'R';
                    }
                } while (_d23 < 1);
            }
        }
        v5_0 &= ((f2(185) == (0 > g3)) || ((g3 < (int)sizeof(long)) - f2((int)sizeof(unsigned int))));
        break;
    case 12:
        g4 |= (((35 ? -33 : 1), (41 * 45)), (f4(v5_1, g3) >> (27)));
        break;
    case 17:
        g4 /= ((((1974 ? "wxyz"[2] : -45) ? ("abc123"[4] ^ 57) : ('j' * 1471)) < (f4('L', 0) != ('j' % ("barY"[2] | 1)))) | 1);
        break;
    case 20:
        p2 &= (f0((0, v5_1), (1 & p2), f0('A', 11, 8959, 69), (26 && 239)) != ((v5_0 == (int)sizeof(unsigned char)) ? ('A' ? v5_2 : (int)sizeof(unsigned int)) : (0 + "abc123"[1])));
        break;
    }
    switch (((((int)sizeof(unsigned int) << (24)) ? (g3 * -47) : ((int)sizeof(unsigned int) == 1)) ? (("barY"[3] == g0), ('~', g3)) : f1(("world"[0] ? v5_2 : "abcd"[1]), f1((int)sizeof(unsigned char), 80, 0), (g0 && p1)))) {
    case 2:
        {
            int _w24;
            _w24 = 0;
            while (_w24 < 7) {
                _w24++;
                f2((p2, -18));
            }
        }
        break;
    case 6:
        {
            {
                int _d25;
                _d25 = 0;
                do {
                    _d25++;
                    v5_1 &= f2(v5_2);
                } while (_d25 < 4);
            }
            {
                p1 = ((int)sizeof(unsigned long) > 3048);
            }
        }
        break;
    case 12:
        {
            int _d26;
            _d26 = 0;
            do {
                _d26++;
                g3 *= (f1(g1, 0, v5_2) | (g3 % (203 | 1)));
            } while (_d26 < 7);
        }
        break;
    case 17:
        g4 %= (((((int)sizeof(int) << (30)) ? ((int)sizeof(unsigned int) == v5_2) : f2(0)), (('o' - 938) - (0 ? v5_0 : 1))) | 1);
        break;
    case 23:
        {
            int _w27;
            _w27 = 0;
            while (_w27 < 10) {
                _w27++;
                gs2.m0 = f3((v5_1, g1));
            }
        }
        ((f1("test"[2], (int)sizeof(unsigned long), 1) || f2(v5_2)) ? f0((65 ? 0 : 3508), f2(188), (g3 ^ 105), ('y' == v5_2)) : f2((1 > -40)));
        break;
    }
    return (v5_0);
}

long f6(char p0, long p1, unsigned long p2, unsigned int p3)
{
    char v6_0[7];
    char v6_1[7];
    char * v6_2;
    int v6_3;
    v6_0[0] = 0;
    v6_1[0] = 0;
    v6_2 = 0;
    v6_3 = -3;

    switch (((((int)sizeof(char), g4) & (g4 * v6_3)) % (((1 + v6_3) >> (0)) | 1))) {
    case 3:
        {
            int _f28;
            for (_f28 = 0; _f28 < 7; _f28++) {
                {
                    p3 += f5(0, -31, p1);
                    p2 = (0, g3);
                    switch (p3) {
                    case 4:
                        p3 /= (p1 | 1);
                        break;
                    case 9:
                        g4 = "wxyz"[1];
                        break;
                    case 10:
                        g0 *= p0;
                        break;
                    case 18:
                        g3 |= p0;
                        break;
                    }
                }
            }
        }
        break;
    case 8:
        {
            ((g3 ? v6_0[3] : 1) ? ('^' ^ v6_1[0]) : (g1 ? g1 : 0));
            p0 &= (f4(p3, v6_0[5]) || (p0 ? v6_1[1] : 0));
        }
        break;
    case 13:
        {
            int _w29;
            _w29 = 0;
            while (_w29 < 2) {
                _w29++;
                p3 |= ((']' / (-47 | 1)) || (p0 - g4));
            }
        }
        break;
    }
    goto _lbl30;
    _lbl30:
    return (g4);
}

int main(void)
{
    int result;
    int m0;
    int m1;
    char * m2;
    int m3[13];
    result = 0;
    m0 = 1;
    m1 = 0;
    m2 = 0;
    m3[0] = 1;

    goto _lbl31;
    _lbl31:

    result = 0;
    result += (int)(g4);
    result += (int)(m0);
    result += (int)(m1);
    result += (int)f6(((-12 != g1) || (4823 != '|')), ((m3[5] / ("barY"[3] | 1)) || (6682 > 64)), (('}' | 70) * f1(m3[9], 55, g3)), ((91 ? m0 : 1) | (-45 || g0)));

    return (result >= 0 ? result : -result) & 255;
}
