/* Generated by cgen, seed=30 */

struct S0 {
    long m0;
    int m1;
};

struct S1 {
    unsigned long m0;
    unsigned int m1;
    unsigned int m2;
    long m3;
    char m4;
    long m5;
};

struct S2 {
    long m0;
    long m1;
};

struct S3 {
    char m0;
    unsigned int m1;
    long m2;
    unsigned int m3;
    unsigned long m4;
};

struct S4 {
    long m0;
    unsigned char m1;
    unsigned int m2;
    unsigned long m3;
};

struct S5 {
    unsigned int m0;
    unsigned char m1;
};

int g0[3];
long g1;
unsigned long g2;
struct S2 gs3;

long f0(unsigned char p0, int p1);
unsigned int f1(void);
unsigned long f2(long p0);
char f3(unsigned int p0, int p1, long p2);
unsigned int f4(unsigned long p0);
int f5(int p0, unsigned char p1, int p2, int p3, long p4);
int f6(int p0, unsigned long p1, int p2, long p3);

long f0(unsigned char p0, int p1)
{
    int v0_0;
    unsigned long v0_1;
    v0_0 = 6092;
    v0_1 = -26;

    v0_0 &= ((((p1 * (int)sizeof(unsigned char)) ? (v0_1 % (p0 | 1)) : (g1 % ('P' | 1))) << (19)) ? (((g1 ? g0[0] : p0) < (g1 / (p1 | 1))) << (18)) : (((v0_0 * v0_0) ? (g0[2] ? g1 : 77) : ("abcd"[0] ? -48 : 65)), ((-34 + '/') < ((int)sizeof(unsigned int) == "test"[3]))));
    {
        switch (((v0_0 ? g0[0] : g0[1]) | (-49, (int)sizeof(char)))) {
        case 1:
            switch ((g0[0] ? p0 : g1)) {
            case 1:
                g2 |= (g1 ? v0_1 : v0_0);
                break;
            default:
                g2 += ('f' != 14);
                break;
            }
            {
                int _d0;
                _d0 = 0;
                do {
                    _d0++;
                    g1 |= (-32 ^ (int)sizeof(unsigned char));
                    g2 |= ("hello"[1] ? "abcd"[0] : 69);
                } while (_d0 < 5);
            }
            break;
        case 8:
            gs3.m1 = ((-16 & 'S') != (p0 ? v0_1 : g1));
            if ((0 >> (24))) {
                p1 *= (0 >> (4));
                v0_0 &= (g1 | 'F');
            } else {
                p0 -= ('s' | 'B');
            }
            break;
        case 12:
            g0[2] = ((5749 ? 1 : 1) ? ((int)sizeof(unsigned long) && g2) : ('-' == p1));
            break;
        }
    }
    g0[0] = ((((g1, v0_1) & (-27, v0_1)) == ((0 ? 1 : p1) + ((int)sizeof(long) >> (2)))) << (11));
    p0 |= ((((g2 || g0[0]) == ('X' != "wxyz"[2])) * ((v0_1 == v0_0) == ((int)sizeof(long) < (int)sizeof(unsigned long)))) && (((p0 || p0) << (13)) & ((v0_1 ? g2 : "abc123"[4]) - (p0 && 's'))));
    {
        {
            int _d1;
            _d1 = 0;
            do {
                _d1++;
                {
                    v0_0 %= ((v0_0 > '_') | 1);
                }
                v0_1 *= ((1 || -10) < (-3 ^ p1));
            } while (_d1 < 2);
        }
    }
    return (g1);
}

unsigned int f1(void)
{
    int v1_0;
    int v1_1[2];
    char v1_2;
    v1_0 = 16;
    v1_1[0] = -47;
    v1_2 = 53;

    gs3.m1 = ((((g0[0] ? g1 : v1_2) / ((51 * v1_1[0]) | 1)), ((v1_2 ? v1_2 : v1_2) ? (g0[0] & v1_0) : ("wxyz"[3] * '0'))) ? (((g1 ? g2 : g0[2]) * (g1 && g1)) * ((4414 + v1_1[1]) ^ (g0[1] ? g1 : v1_1[0]))) : ((f0(g0[1], 1) << (13)) != ((g1 && 1) >> (24))));
    {
        int _d2;
        _d2 = 0;
        do {
            _d2++;
            {
                int _d3;
                _d3 = 0;
                do {
                    _d3++;
                    g1 *= ((1 || (int)sizeof(unsigned long)) | ("world"[3] | "wxyz"[2]));
                } while (_d3 < 4);
            }
            v1_1[1] = (((v1_2, "test"[2]) >> (1)) != (((int)sizeof(int) * "hello"[1]) >> (28)));
        } while (_d2 < 1);
    }
    return (v1_0);
}

unsigned long f2(long p0)
{
    char v2_0[6];
    v2_0[0] = 0;

    g2 -= f0((((g2 || 1) ? ('Q' & "world"[2]) : (g2 ? '.' : '/')) * ((g2 << (5)) ? (1, 1) : (g1 && g1))), ((("barY"[0] * 0) << (4)) ? ((0 * v2_0[3]), ((int)sizeof(unsigned int) & g2)) : ((237 != (int)sizeof(unsigned char)) % ((2379 ? p0 : 'R') | 1))));
    goto _lbl4;
    _lbl4:
    return (g2);
}

char f3(unsigned int p0, int p1, long p2)
{
    int v3_0;
    v3_0 = -7;

    gs3.m0 = ((((1, 5779) | f1()) ? (((int)sizeof(unsigned int) / (p2 | 1)) * (-43 & g0[1])) : ((v3_0 + p2) != (p0 ? g1 : (int)sizeof(int)))) / ((((g1 && 19) << (25)) % ((('T' % ('C' | 1)) & (v3_0 ^ 1)) | 1)) | 1));
    return (g1);
}

unsigned int f4(unsigned long p0)
{
    long v4_0;
    unsigned char v4_1;
    char * v4_2;
    unsigned long v4_3;
    v4_0 = 68;
    v4_1 = 141;
    v4_2 = 0;
    v4_3 = 98;

    g1 |= ((f1(), f1()) ? (f0(("world"[1] != (int)sizeof(unsigned int)), ('$' >> (11))) >> (17)) : (((-29 | p0) == f0('t', (int)sizeof(long))) ? (f2((int)sizeof(unsigned long)) ^ (g2 - 0)) : ((g1, v4_1) == (29 / (p0 | 1)))));
    if ((((v4_3 * 'q') != (p0 > p0)) > f0((g2 ? v4_3 : g1), (g0[2] ? p0 : v4_3)))) {
        {
            g2 += ((-35 < 0) << (5));
        }
        {
            int _d5;
            _d5 = 0;
            do {
                _d5++;
                p0 |= f0((3659 << (26)), (g0[2] ? g2 : 0));
                {
                    int _w6;
                    _w6 = 0;
                    while (_w6 < 3) {
                        _w6++;
                        v4_0 |= ("test"[1] ? ']' : -49);
                    }
                }
            } while (_d5 < 10);
        }
    } else {
        v4_2 = &v4_0;
        *v4_2 = (f0(f2(g2), (v4_1 > 2219)) * ((v4_0 << (16)) - (0 ? 1 : 84)));
    }
    return (v4_1);
}

int f5(int p0, unsigned char p1, int p2, int p3, long p4)
{
    int v5_0;
    v5_0 = 33;

    g2 += (((("barY"[0] > v5_0) ? (3613 || 'W') : (g1 > g0[2])) + ((p0 % ('"' | 1)) / (("hello"[0] != g2) | 1))) && (((p0 ? p4 : "hello"[4]) != ('A' / ("abc123"[0] | 1))) >> (14)));
    return (p1);
}

int f6(int p0, unsigned long p1, int p2, long p3)
{
    int v6_0[12];
    struct S1 v6_1;
    char * v6_2;
    v6_0[0] = 176;
    v6_1.m0 = 1;
    v6_1.m1 = 0;
    v6_1.m2 = 0;
    v6_1.m3 = -40;
    v6_1.m4 = 1;
    v6_1.m5 = 1;
    v6_2 = 0;

    v6_0[7] = ((((g0[0] - '-') || (p1 | 31)) + ((p1 || -31), ('^' / (g2 | 1)))) / (((((int)sizeof(long) ? (int)sizeof(unsigned long) : p1) > (0 != 1)) << (28)) | 1));
    return (p1);
}

int main(void)
{
    int result;
    unsigned long m0;
    int m1[4];
    int m2[4];
    int * m3;
    int * m4;
    unsigned int m5;
    int m6;
    struct S0 m7;
    result = 0;
    m0 = 233;
    m1[0] = 0;
    m2[0] = 26;
    m3 = 0;
    m4 = 0;
    m5 = -20;
    m6 = 83;
    m7.m0 = 0;
    m7.m1 = -39;

    gs3.m0 = ((((3861 | -38) && (g1 < m2[0])) && (f6(g0[0], g1, m1[0], (int)sizeof(char)) % ((1 << (24)) | 1))) ? (((m6 + 18) - (49, g2)) ^ ((28 < (int)sizeof(unsigned char)), (4928 || 5123))) : (((m1[2] < result) / ((1 + "world"[2]) | 1)) ? f0((2174 >> (1)), (25 * 1)) : ((3023 > g1) ? (g1 < (int)sizeof(char)) : (241 ^ 0))));
    m3 = &m5;
    *m3 = (((("abc123"[4] ^ 'Q') == (g2 ? 31 : 6633)) ? f6((m5 >> (2)), f6('P', 0, 8200, 89), (m5 > result), (m5 - m5)) : ((g1 ? 'F' : 'c') / ((1 / (m6 | 1)) | 1))) * f4(((m6, (int)sizeof(unsigned long)) > f2(m5))));
    {
        int _d7;
        _d7 = 0;
        do {
            _d7++;
            g1 *= ((("world"[0] + "abc123"[0]) ? (m5 && '"') : (m6 - g2)) + ((g2, m0) ? ('z' > 139) : ((int)sizeof(unsigned long) != 231)));
            switch (((g1 * 'P') ? (88 > "wxyz"[3]) : (g1 != g1))) {
            case 2:
                {
                    g1 &= (227 < 182);
                    switch (5502) {
                    case 4:
                        g1 /= (g1 | 1);
                        break;
                    case 8:
                        g2 %= ((int)sizeof(long) | 1);
                        break;
                    case 14:
                        g1 /= ((int)sizeof(unsigned long) | 1);
                        break;
                    case 15:
                        g2 -= (int)sizeof(long);
                        break;
                    case 22:
                        g1 |= 177;
                        m5 *= 'n';
                        break;
                    }
                }
                break;
            case 9:
                goto _lbl8;
                _lbl8:
                (("barY"[1] ? "wxyz"[0] : -7) || f4(203));
                break;
            case 10:
                result %= (((g2 >> (28)) & ((int)sizeof(unsigned int) ? 1 : 1)) | 1);
                break;
            }
        } while (_d7 < 8);
    }
    {
        goto _lbl9;
        _lbl9:
        m2[1] = (((result & m2[2]) || (result == m0)) * ((m0 & m6), ((int)sizeof(int) || 0)));
    }

    result = 0;
    result += (int)(g2);
    result += (int)(g1);
    result += (int)(m5);
    result += (int)(m5);
    result += (int)(m5);
    result += (int)f3(((m0 < 31), (g2 + g1)), ((m1[3] ? "wxyz"[0] : result) & ((int)sizeof(unsigned int), m1[1])), f6((60 & m6), (m0 ? m5 : m2[3]), (m1[3] * ';'), f2(0)));

    return (result >= 0 ? result : -result) & 255;
}
