/* Generated by cgen, seed=357 */

struct S0 {
    long m0;
    unsigned int m1;
    unsigned char m2;
    char m3;
};

struct S1 {
    char m0;
    unsigned char m1;
    unsigned int m2;
    unsigned int m3;
};

struct S2 {
    long m0;
    int m1;
    unsigned long m2;
};

struct S3 {
    char m0;
    unsigned long m1;
    unsigned char m2;
};

struct S4 {
    long m0;
    unsigned int m1;
    int m2;
    unsigned char m3;
    int m4;
};

struct S5 {
    char m0;
    unsigned long m1;
    unsigned char m2;
    unsigned long m3;
    long m4;
    int m5;
};

struct S6 {
    int m0;
    long m1;
};

unsigned long g0;
long g1;
unsigned char g2 = 9664;
unsigned char g3 = -36;

unsigned long f0(int p0);
unsigned long f1(char p0);
unsigned long f2(unsigned char p0, long p1, unsigned char p2, char p3);
unsigned char f3(unsigned long p0, unsigned char p1, int p2, unsigned char p3, long p4);
int f4(int p0, unsigned char p1);
int f5(int p0, char p1, unsigned long p2);
long f6(char p0, unsigned long p1, unsigned long p2, unsigned char p3);
unsigned char f7(char p0, char p1, unsigned int p2, long p3);

unsigned long f0(int p0)
{
    long v0_0;
    v0_0 = 82;

    switch (((((int)sizeof(unsigned char) + -21) ? (g2 & 28) : (p0 ^ g0)) % (((-3 ? 250 : g1) & ("test"[1] / (190 | 1))) | 1))) {
    case 2:
        switch (((g3 * v0_0) || (v0_0 ? 165 : v0_0))) {
        case 2:
            g2 -= ((v0_0 || v0_0) * (g2, v0_0));
            {
                g2 %= ((g0, 1) | 1);
            }
            break;
        }
        g3 -= (((1 >> (15)) + (-13 << (3))) ? (("barY"[1] * 106) * (g3 ? 0 : (int)sizeof(int))) : ((g3 ? g3 : g2), (g1 ^ -7)));
        break;
    case 9:
        switch (((g3 == -26) || (g0 ? 'Y' : g2))) {
        case 0:
            g0 += ((g1 + g3) & (1 ? 179 : g2));
            break;
        }
        break;
    }
    g2 &= ((((g0 | 0) ^ ((int)sizeof(int), -36)) >> (25)) && ((('-' < g0) || ('Y' ^ g2)) ? ((126 ? g1 : 36) ^ (-9 == g2)) : (("abcd"[1] == "test"[3]) >> (2))));
    g0 /= ((((((int)sizeof(char) || 0) - (8086 + (int)sizeof(int))) > ((0 % ((int)sizeof(unsigned char) | 1)) ? (g1 == 'f') : (7339 + 1))) ? (((5570 != p0) ? (2710 ? ')' : '[') : ('e' < p0)) ^ ((0 % (p0 | 1)) ^ (-50 < "abcd"[2]))) : (((0 - g2) >> (15)) && ((g2 ? g2 : g3) / ((v0_0 / (g0 | 1)) | 1)))) | 1);
    if ((((0 / (26 | 1)), (57 % (g0 | 1))) & ((164, p0) | (0 ? (int)sizeof(char) : 56)))) {
        g0 *= (((g3, v0_0), (v0_0, 35)) | (("fooX"[0] << (0)) * (g2 ? (int)sizeof(long) : 235)));
    } else {
        {
            int _w0;
            _w0 = 0;
            while (_w0 < 8) {
                _w0++;
                switch (('1' ^ (int)sizeof(long))) {
                case 3:
                    p0 /= ((g1 ? "world"[4] : (int)sizeof(char)) | 1);
                    break;
                case 7:
                    g1 = (g3 | g1);
                    break;
                case 14:
                    g1 %= ((5138 > 87) | 1);
                    break;
                default:
                    g2 /= ((v0_0 / ("hello"[4] | 1)) | 1);
                    break;
                }
            }
        }
    }
    return (g3);
}

unsigned long f1(char p0)
{
    char v1_0[14];
    v1_0[0] = 1;

    g3 /= (((((37 == 43) | f0(g2)), ((1, g3) < (g3 ^ g3))) >> (15)) | 1);
    return (p0);
}

unsigned long f2(unsigned char p0, long p1, unsigned char p2, char p3)
{
    int v2_0;
    v2_0 = 57;

    g2 += (f0(((p2 ? g0 : (int)sizeof(unsigned long)) << (27))) == (f1(("abcd"[0] % ('_' | 1))) ? (('w' < p0) ? (-30 ? p1 : -16) : (p2 > v2_0)) : ((-29 << (6)) - (g3 | 'W'))));
    {
        g1 = (((p1 & g1) < (g0 || p0)) == ((g1 * (int)sizeof(long)) ? (p2 < p2) : (85 < "wxyz"[3])));
        if (((1 == g0) & (p3 && 't'))) {
            p0 += ((g0 - (int)sizeof(long)), (g1 & 192));
            switch ((g3 << (30))) {
            case 0:
                p1 &= (1 + 218);
                break;
            case 6:
                v2_0 += f1(g3);
                break;
            case 14:
                g3 -= (g0 == p0);
                break;
            case 17:
                switch ('%') {
                case 2:
                    v2_0 *= g1;
                    break;
                case 9:
                    g3 *= 0;
                    break;
                case 14:
                    g3 *= 1;
                    break;
                case 18:
                    g3 %= ("abcd"[1] | 1);
                    p2 %= (0 | 1);
                    break;
                case 21:
                    g1 &= g3;
                    break;
                }
                break;
            }
        }
        v2_0 %= ((((0, '.') & ((int)sizeof(int) < g0)) - (('O', g2), (-39 || '.'))) | 1);
    }
    if (((("abcd"[3] ? 23 : 0), (g3 + "barY"[3])) ? ((v2_0 && 14) & (130 < -11)) : ((p2 == -32) % ((g0 && g0) | 1)))) {
        {
            int _w1;
            _w1 = 0;
            while (_w1 < 6) {
                _w1++;
                ((1 | v2_0) ? ((int)sizeof(long) > p3) : (p2 ? g2 : "wxyz"[3]));
                if ((p1, '#')) {
                    switch (0) {
                    case 2:
                        g3 -= g2;
                        break;
                    case 6:
                        v2_0 |= p3;
                        break;
                    case 10:
                        v2_0 *= p2;
                        g3 /= (0 | 1);
                        break;
                    default:
                        p0 -= -7;
                        p3 = 100;
                        break;
                    }
                    switch (40) {
                    case 3:
                        g0 = 127;
                        break;
                    case 9:
                        g2 = "hello"[2];
                        break;
                    default:
                        v2_0 = 81;
                        break;
                    }
                } else {
                    g0 %= (('k', p0) | 1);
                }
            }
        }
        p3 *= (f0((g2, "fooX"[1])) & ((p3 + 42), (g1 & -20)));
    } else {
        (((0 < 9506) * ("test"[0] > '`')) ? ((g2 == p0), (0 | "abc123"[1])) : ((0 && (int)sizeof(unsigned int)), (1 ? 81 : 178)));
    }
    return (g1);
}

unsigned char f3(unsigned long p0, unsigned char p1, int p2, unsigned char p3, long p4)
{
    char v3_0[12];
    int v3_1;
    int v3_2[15];
    v3_0[0] = 1;
    v3_1 = 187;
    v3_2[0] = 146;

    {
        int _w2;
        _w2 = 0;
        while (_w2 < 1) {
            _w2++;
            switch (((p0 < g2) ? ((int)sizeof(int) ? p1 : v3_0[10]) : (p3, v3_2[7]))) {
            case 3:
                {
                    int _f3;
                    for (_f3 = 0; _f3 < 5; _f3++) {
                        g2 = (g1, (int)sizeof(unsigned char));
                    }
                }
                break;
            case 9:
                {
                    int _w4;
                    _w4 = 0;
                    while (_w4 < 4) {
                        _w4++;
                        p0 &= ("wxyz"[2] >> (15));
                        g1 |= (v3_1, (int)sizeof(unsigned char));
                    }
                }
                break;
            case 13:
                if ((v3_0[5] == (int)sizeof(long))) {
                    g2 -= ('4' ? -38 : 7022);
                }
                break;
            case 16:
                {
                    g3 += (-23, 1);
                    p0 %= ((p0 + v3_1) | 1);
                }
                break;
            case 24:
                g2 %= (((p2 && 2004) || (-9 ? v3_2[2] : g3)) | 1);
                break;
            }
            switch ((((int)sizeof(int) ? 0 : p3) | f2("abc123"[2], 50, 83, 56))) {
            case 4:
                g3 = (("test"[1] && "wxyz"[2]) - ((int)sizeof(unsigned char) && g3));
                break;
            case 9:
                g0 /= (((g3 && p4) == (p2 + 45)) | 1);
                g2 /= ((((int)sizeof(char) ? g1 : 0) < f0((int)sizeof(char))) | 1);
                break;
            case 12:
                p2 |= ((49 ? (int)sizeof(unsigned char) : (int)sizeof(char)), (1 << (10)));
                break;
            case 18:
                {
                    int _w5;
                    _w5 = 0;
                    while (_w5 < 4) {
                        _w5++;
                        g1 -= ('Q' << (26));
                        switch (13) {
                        case 1:
                            p2 /= (1 | 1);
                            break;
                        case 8:
                            p3 = 8;
                            break;
                        case 11:
                            v3_1 /= (39 | 1);
                            break;
                        default:
                            g0 += "abcd"[1];
                            g1 /= (93 | 1);
                            break;
                        }
                    }
                }
                break;
            case 21:
                g3 += ((-21 ^ p1), (3468 ? -46 : (int)sizeof(char)));
                break;
            }
        }
    }
    goto _lbl6;
    _lbl6:
    g3 /= (((f2((g3 | g3), (v3_2[14] || v3_0[8]), (-3 & (int)sizeof(char)), (p4 >> (14))) && ((216, v3_1) >> (1))) ? f2(((4 || 105) && (-8 * g1)), ((')' >> (8)) ? (83 ? v3_2[6] : 0) : ('x' >> (5))), ((p4 / (-4 | 1)), (p0 ? p0 : 0)), ((4660 ? p3 : -38) >> (9))) : (((129 ? 1 : "wxyz"[0]) - (600, g2)) % ((('Y' & g1), ('>' & 48)) | 1))) | 1);
    return (g3);
}

int f4(int p0, unsigned char p1)
{
    struct S3 v4_0;
    unsigned int v4_1;
    int v4_2;
    unsigned long v4_3;
    unsigned int v4_4;
    v4_0.m0 = 5852;
    v4_0.m1 = 156;
    v4_0.m2 = 8409;
    v4_1 = 1;
    v4_2 = 6;
    v4_3 = 11;
    v4_4 = 8522;

    g3 |= ((((g1 != "abcd"[2]) & (v4_1 >> (6))) % (((3104 || g1) != (1 & g1)) | 1)) || (((44 > '%') > f1((int)sizeof(long))) ? f0(('4' < p0)) : (("barY"[2], p0) ? (-35 - v4_1) : ('(' == p0))));
    goto _lbl7;
    _lbl7:
    return (v4_1);
}

int f5(int p0, char p1, unsigned long p2)
{
    struct S3 v5_0;
    v5_0.m0 = 0;
    v5_0.m1 = -37;
    v5_0.m2 = 7654;

    g3 /= ((((f2(0, g0, (int)sizeof(char), '/') ^ (g0 ? 'r' : 1)) % (((13 != 1) ? f3(-10, p0, p0, p0, p2) : (g1 << (21))) | 1)) ? (f3((g1, p0), (-26 - (int)sizeof(unsigned char)), f4("barY"[0], 4091), ("hello"[0] || '7'), f2("test"[2], 54, g0, p1)) || ((p1 & p1) * ("test"[1] | p1))) : (((g2 ? 0 : g0) << (6)) || f0(('t' || p0)))) | 1);
    return (g3);
}

long f6(char p0, unsigned long p1, unsigned long p2, unsigned char p3)
{
    int v6_0;
    v6_0 = 143;

    {
        int _f8;
        for (_f8 = 0; _f8 < 5; _f8++) {
            g0 /= ((((4754 ^ 249) ^ ("hello"[0] ^ 0)), f1(((int)sizeof(unsigned long) - (int)sizeof(unsigned long)))) | 1);
        }
    }
    return (p2);
}

unsigned char f7(char p0, char p1, unsigned int p2, long p3)
{
    int v7_0;
    v7_0 = 35;

    {
        int _f9;
        for (_f9 = 0; _f9 < 7; _f9++) {
            g1 &= (((2866 == g3) % ((p1 & (int)sizeof(char)) | 1)) / (((1 == p3) + (g2 ? (int)sizeof(int) : g1)) | 1));
            {
                int _f10;
                for (_f10 = 0; _f10 < 10; _f10++) {
                    if ((v7_0 ? p1 : "world"[3])) {
                        p1 *= (v7_0 ? -17 : p0);
                        if (g2) {
                            g1 &= "hello"[0];
                        }
                    }
                    ((p3 && (int)sizeof(unsigned long)) && f6(1, v7_0, 'E', 0));
                }
            }
        }
    }
    v7_0 %= (f5(((('b' * (int)sizeof(int)) && (-47 ? 329 : p3)) ? f3((1607 < p2), (g0 != g3), ((int)sizeof(unsigned int), "wxyz"[0]), (g2 - g3), f3(39, g3, 1, v7_0, 1)) : ((35 || p0) + (9842 / (g0 | 1)))), ((f5(0, (int)sizeof(unsigned int), (int)sizeof(unsigned int)) & (v7_0 > 9179)) * (f4(1, 8) != (30 && g3))), ((((int)sizeof(char) ? g1 : 270) ^ (p0 ? -47 : p2)) - (("world"[1] - 2331) ? ("wxyz"[0] ? 32 : (int)sizeof(unsigned int)) : (46 ? "world"[4] : g2)))) | 1);
    g3 /= ((((("abcd"[2] && -31) << (14)) * (('[' ? '_' : g0), (91 ? 'A' : 146))), (f6((64 - (int)sizeof(unsigned int)), (1 ? p1 : g0), (p3 - (int)sizeof(int)), ('e', (int)sizeof(int))) | ((5485, 1) ? ('l' - 160) : ((int)sizeof(long) > g0)))) | 1);
    return (p0);
}

int main(void)
{
    int result;
    int m0;
    unsigned char m1;
    unsigned char m2;
    char m3;
    int m4;
    unsigned char m5;
    char m6;
    unsigned int m7;
    result = 0;
    m0 = 1;
    m1 = 0;
    m2 = 25;
    m3 = 1799;
    m4 = 16;
    m5 = 0;
    m6 = -37;
    m7 = 0;

    m0 = (((f0(m5) | ((int)sizeof(int) != "test"[3])) ? (f5(m0, "world"[4], (int)sizeof(unsigned char)) >> (24)) : (f0((int)sizeof(unsigned int)) != f4(m1, -48))) < f6((f5(-21, 0, m0) || (196 << (7))), (((int)sizeof(char) < m7) % ((g0 != "world"[3]) | 1)), ((1 - m1) >> (13)), ((1 * 19) >> (11))));
    g1 %= ((f6(((m4 ? 1 : m2) ? (-9, (int)sizeof(long)) : ("wxyz"[1] != 0)), ((m0 << (27)) != (m2 % (0 | 1))), ((m6, g0) ? f2("world"[3], m1, "wxyz"[2], g2) : ("hello"[2] % (m6 | 1))), f1((1 < -46))) * ((((int)sizeof(unsigned long) ? g3 : '_') ? (m2 / (73 | 1)) : f1(1)) || f2(f1('}'), (35 ^ m1), ('H' ? -30 : 52), f7(-28, 38, m0, "abc123"[3])))) | 1);
    {
        int _d11;
        _d11 = 0;
        do {
            _d11++;
            {
                m3 |= ((1 || 1) ? (219 && m7) : (40, g0));
                m0 &= ((m6 ? g1 : 240), f6(m0, "wxyz"[0], m7, "wxyz"[2]));
            }
        } while (_d11 < 8);
    }
    {
        int _d12;
        _d12 = 0;
        do {
            _d12++;
            g1 = ((("test"[0] ? m0 : '@'), ((int)sizeof(unsigned int) | m3)) << (9));
        } while (_d12 < 2);
    }

    result = 0;
    result += (int)(m1);
    result += (int)(g1);
    result += (int)(m6);
    result += (int)(g3);
    result += (int)(m4);
    result += (int)f6((("barY"[0] | 0) < (123 != '1')), ((m0 ^ 0) % ((g1 >> (5)) | 1)), f4(f2(m3, result, (int)sizeof(long), m0), (result ? result : m4)), ((8, (int)sizeof(char)) / ((g3 * 0) | 1)));

    return (result >= 0 ? result : -result) & 255;
}
