/* Generated by cgen, seed=148 */

struct S0 {
    char m0;
    unsigned char m1;
    char m2;
};

struct S1 {
    unsigned long m0;
    unsigned long m1;
    unsigned int m2;
    char m3;
    unsigned long m4;
    char m5;
};

struct S2 {
    char m0;
    char m1;
};

struct S3 {
    char m0;
    unsigned long m1;
    int m2;
    unsigned char m3;
    unsigned char m4;
    char m5;
};

struct S4 {
    int m0;
    unsigned long m1;
    long m2;
    int m3;
};

struct S4 gs0;
int g1 = -46;
int g2[10];

char f0(void);
int f1(unsigned long p0);
unsigned int f2(unsigned int p0, long p1, long p2, char p3);
char f3(unsigned int p0);
unsigned long f4(unsigned long p0, int p1);
unsigned long f5(unsigned char p0);

char f0(void)
{
    int v0_0;
    long v0_1;
    int v0_2;
    unsigned long v0_3;
    unsigned char v0_4;
    long v0_5;
    int v0_6;
    int v0_7;
    v0_0 = 4;
    v0_1 = 0;
    v0_2 = 1;
    v0_3 = 5762;
    v0_4 = 34;
    v0_5 = 95;
    v0_6 = -40;
    v0_7 = 1;

    {
        int _w0;
        _w0 = 0;
        while (_w0 < 2) {
            _w0++;
            (((g2[9] || "abc123"[5]) < (20 >> (9))) / (((g1 && (int)sizeof(unsigned long)), ("abc123"[4] == v0_4)) | 1));
            v0_1 %= ((((150 + v0_4) || (0 < v0_1)) ? (('y', g2[5]) >> (21)) : (('k' < 1) ? (g2[1] / (v0_7 | 1)) : (g1 / (g1 | 1)))) | 1);
            gs0.m1 = (((g1 << (28)) && (26 * "barY"[3])) ? (('9' ? "hello"[4] : '=') / ((151 / (86 | 1)) | 1)) : (((int)sizeof(long) != (int)sizeof(char)) + (-30, 13)));
        }
    }
    (((((int)sizeof(char) == -50) * ("hello"[2] & v0_0)) - (('<' - 0) != (v0_3, "abcd"[3]))) == (((g1 || g1) % ((1 ^ 0) | 1)) ? ((82 ? g2[4] : v0_2) << (7)) : ((-34 % (v0_4 | 1)) >> (29))));
    v0_4 &= ((((g1 ? (int)sizeof(unsigned char) : "wxyz"[2]) - ("fooX"[1] ? v0_7 : 'c')) | ((0 / ("abc123"[3] | 1)), (-47, 'A'))) | ((((int)sizeof(long) != 1404) < (4498 % (v0_7 | 1))) < ((v0_4 ? 0 : 84), (g2[7] * g1))));
    switch (((("abc123"[0] == g1) && (g2[1] + 149)) || (((int)sizeof(int) ? 100 : g2[9]) || (1 < 65)))) {
    case 4:
        {
            {
                v0_7 += (0 || '2');
                if (0) {
                    v0_5 += -10;
                }
            }
        }
        v0_3 |= (((g2[1] - 'P') << (2)) << (0));
        break;
    case 7:
        {
            int _w1;
            _w1 = 0;
            while (_w1 < 4) {
                _w1++;
                g1 /= (((v0_1, (int)sizeof(unsigned long)) ? ((int)sizeof(long) - (int)sizeof(unsigned long)) : ('~' > g2[7])) | 1);
            }
        }
        v0_4 *= (((v0_3 & g2[2]) ? ((int)sizeof(unsigned char) >> (25)) : ('(' ? 1 : 8896)) | ((v0_7 || '`') > (212, v0_7)));
        break;
    case 12:
        gs0.m3 = (((g1 == ';') >> (14)) ? ((1 ? g2[1] : 8024) < (v0_4, v0_2)) : ((g2[6] ? (int)sizeof(unsigned int) : 0) != (1 != g2[5])));
        break;
    case 18:
        switch (((90 >> (1)), (v0_0 < 81))) {
        case 1:
            if (("abcd"[1] ? 3261 : -18)) {
                g1 %= ((v0_4 ? v0_6 : v0_6) | 1);
                if (v0_3) {
                    v0_7 *= g2[8];
                }
            } else {
                if (66) {
                    v0_1 |= 1;
                    v0_3 %= (27 | 1);
                    g1 -= "hello"[3];
                }
            }
            break;
        case 9:
            v0_5 &= ((87 - (int)sizeof(int)) > (v0_5, 'i'));
            g1 |= (("hello"[2] / ("wxyz"[2] | 1)) % ((v0_5 - g2[8]) | 1));
            break;
        }
        break;
    default:
        gs0.m3 = (((0 || 0) > ("abc123"[2] != v0_7)) ? (((int)sizeof(unsigned char) > v0_1) > ((int)sizeof(int) < (int)sizeof(long))) : ((1 * g1) + (4475 % (v0_3 | 1))));
        break;
    }
    {
        int _d2;
        _d2 = 0;
        do {
            _d2++;
            switch (((v0_2 + "abcd"[3]) * ("abcd"[2] ^ g2[3]))) {
            case 4:
                v0_0 *= (("world"[0] == (int)sizeof(int)) & (v0_0 << (21)));
                break;
            case 5:
                v0_6 += (((int)sizeof(long) * 122) || ("abc123"[4] == 152));
                break;
            case 11:
                {
                    int _d3;
                    _d3 = 0;
                    do {
                        _d3++;
                        v0_1 += (0 * v0_3);
                    } while (_d3 < 2);
                }
                break;
            case 15:
                gs0.m2 = ((v0_1 & -41) - (v0_7 << (3)));
                break;
            case 20:
                v0_6 %= ((("abc123"[3] - 86) ^ (v0_0 + '#')) | 1);
                break;
            }
            gs0.m3 = ((((int)sizeof(long) + v0_4) & (v0_3 ? (int)sizeof(unsigned char) : 8106)) / (((v0_2 ? -22 : v0_4) ? (1 / (v0_0 | 1)) : (1 ? (int)sizeof(unsigned int) : v0_0)) | 1));
        } while (_d2 < 1);
    }
    v0_0 = ((((v0_5, 66), (v0_6 == v0_1)) ? ((0 % (v0_5 | 1)) & (54 || g2[5])) : (((int)sizeof(unsigned int) < v0_3) / ((g1, v0_6) | 1))) / (((("world"[1] < "world"[0]) ? (-41, (int)sizeof(long)) : ("abc123"[2] << (7))) + (("abc123"[0] % (14 | 1)) << (10))) | 1));
    gs0.m3 = (((('~' * 'X') * ("world"[0] ^ g2[0])) | (((int)sizeof(unsigned int), "world"[0]) ^ (g2[2] && "abcd"[0]))), ((("hello"[1], -23) - ('e' & v0_7)) ? ((78 ? v0_6 : v0_5) || (35 * g1)) : (("world"[0] ? 1 : (int)sizeof(int)) ? ((int)sizeof(unsigned long) * (int)sizeof(long)) : ('(' < v0_0))));
    goto _lbl4;
    _lbl4:
    v0_7 |= (((((int)sizeof(char) & '^') << (9)) && (((int)sizeof(int) && v0_0) ? ("barY"[3] ? v0_5 : v0_0) : (1 == '('))) != (((g2[4] / ((int)sizeof(char) | 1)) % ((v0_4 ? v0_5 : 18) | 1)), ((7295 % (44 | 1)) ? (v0_1 / (v0_3 | 1)) : (v0_5 << (23)))));
    {
        int _f5;
        for (_f5 = 0; _f5 < 9; _f5++) {
            (((-40 || v0_7) ? (-28 && "fooX"[3]) : ((int)sizeof(long) ? v0_4 : "barY"[0])) != (((int)sizeof(unsigned char) || v0_3) / (('n', v0_0) | 1)));
        }
    }
    v0_2 += ((((v0_2 & (int)sizeof(unsigned int)) < (g2[6] ? v0_2 : -40)) / (((193 - (int)sizeof(unsigned char)) && ('{' > 'P')) | 1)) - (((163 ? -46 : "test"[2]) && ("world"[4] + 249)) ? ((71 || g2[3]) % ((v0_3 ? 8854 : g2[3]) | 1)) : ((v0_2 == (int)sizeof(int)) ^ (g1 == 33))));
    return (v0_6);
}

int f1(unsigned long p0)
{
    struct S0 v1_0;
    char v1_1[2];
    char v1_2[3];
    v1_0.m0 = 0;
    v1_0.m1 = 1305;
    v1_0.m2 = 158;
    v1_1[0] = 7126;
    v1_2[0] = 1;

    p0 += (f0(), ((((int)sizeof(char) > (int)sizeof(int)) & (g1 - 'h')), (("test"[1] < p0) - (40 ? -3 : (int)sizeof(int)))));
    return (g1);
}

unsigned int f2(unsigned int p0, long p1, long p2, char p3)
{
    int v2_0[9];
    v2_0[0] = -45;

    p1 *= ((f1((g2[7] << (7))) < ((p2 == g2[7]) ^ ("barY"[0] + v2_0[6]))) | (((3234 ^ p2) * ((int)sizeof(unsigned long) ? (int)sizeof(unsigned char) : p0)) % (f1(((int)sizeof(unsigned long) < 0)) | 1)));
    (f1(((p1 ? 1 : (int)sizeof(unsigned long)) < (g1 ? g1 : g2[8]))) ? f1((f0() ? ("hello"[4] % (4650 | 1)) : (-30, g1))) : (((p0 ? p3 : v2_0[2]), ('Z' + 'B')) ? ((4159 || 'w') ? ('7' / (v2_0[5] | 1)) : (v2_0[5], '*')) : ((p3 / ('s' | 1)) * (p2 || 763))));
    gs0.m1 = f1((((v2_0[2] & p3) & (g1 - p0)) - ((p2 * 1) % (((int)sizeof(int) ? p1 : v2_0[7]) | 1))));
    {
        (((g1 << (21)) ? (g1 ^ p0) : ("fooX"[0], g1)) || ((0 != p2), ((int)sizeof(int) > 'U')));
        switch (((-22 > p0) > (p2 + p1))) {
        case 4:
            g1 = ((120, (int)sizeof(unsigned char)) ? ('Q' ? "hello"[3] : '0') : (204 < g2[7]));
            gs0.m0 = ((p0 ? p3 : 0) < (p0 ? 1 : 'K'));
            break;
        case 9:
            gs0.m0 = (((int)sizeof(long) * p0) > (-9 / (-32 | 1)));
            break;
        }
        p2 -= (f1((p2 ? 0 : p1)) / (((-18 < g1) == (g2[0] + 0)) | 1));
    }
    if ((((1 >> (29)) << (17)) - (((int)sizeof(long) * p2) << (25)))) {
        p1 %= ((((g1 ^ 0) / ((0 % (149 | 1)) | 1)) & f1((-11 / (0 | 1)))) | 1);
    }
    p3 *= ((((0 && p0), ((int)sizeof(char) ? 0 : p1)) << (4)) ? (((p0, 194) << (12)) > ((v2_0[1] == (int)sizeof(int)), f0())) : f0());
    p3 %= ((((("hello"[2], p0) * ((int)sizeof(char) ? "wxyz"[0] : v2_0[3])) - f1((p1 - "world"[1]))) - f0()) | 1);
    {
        int _f6;
        for (_f6 = 0; _f6 < 6; _f6++) {
            g1 /= (((('V' ? p0 : -2) * ('J' ? (int)sizeof(unsigned long) : -45)) && ((p2 != 'R') ? f0() : (1, p1))) | 1);
        }
    }
    gs0.m1 = (((('U' - 1) ? (0 < (int)sizeof(unsigned int)) : ("barY"[0], 'z')) && ((0 && (int)sizeof(long)) / ((144 - p1) | 1))) < ((((int)sizeof(int) != (int)sizeof(char)) | (p1 && 1620)) ? (f1(p1) + ("fooX"[0] < g2[5])) : (f1(p2), (p1 != (int)sizeof(char)))));
    return (p1);
}

char f3(unsigned int p0)
{
    int v3_0[4];
    int v3_1;
    v3_0[0] = 0;
    v3_1 = 0;

    {
        int _w7;
        _w7 = 0;
        while (_w7 < 4) {
            _w7++;
            g1 -= (((v3_1 + g1) ? (8910 && 1) : (7724 == p0)) - (f0() ? (g1, 71) : (g1, 57)));
        }
    }
    g1 = ((((p0 || 1694) >> (2)) ? (f1('h') ? (144 - g1) : (v3_1, v3_1)) : ((60 | (int)sizeof(char)) % ((p0 >> (28)) | 1))) - (((1 > g1) ? (p0 ? g1 : -1) : (93 + v3_1)) % (f0() | 1)));
    v3_1 = f1((((85 < v3_1) > ('}' ? 1 : "hello"[3])) * (f1(g1), ((int)sizeof(unsigned int) < g1))));
    p0 -= ((f2((58, 0), (g1 != -7), (47 || (int)sizeof(long)), ((int)sizeof(int) * v3_0[1])) ? (f1((int)sizeof(unsigned int)) ^ ('X' | 125)) : f1((v3_1 < (int)sizeof(int)))), (((v3_0[1] ^ v3_1) % ((p0 % (6703 | 1)) | 1)) % (((0 != 0) | (1 >> (14))) | 1)));
    ((((-28 * 4937) & (g1 + 'y')) ? ((230 << (13)) ? (p0 & 7150) : (p0 + v3_1)) : (('R' | v3_1), (v3_1 ? v3_1 : v3_0[0]))) ? (((g1 ? p0 : g1) != (-46 < 6723)), ((p0 % (g1 | 1)) || ("test"[1] | 2939))) : (((g1 ? 219 : p0) > f0()), ((22 ^ 149), (g1 == v3_0[3]))));
    ((((v3_0[3] / ('#' | 1)) > (v3_1 + p0)) < (((int)sizeof(long) || p0) % ((-37 != "test"[1]) | 1))), ((f1(-36) & f1(p0)), (((int)sizeof(int) == "barY"[0]) < (v3_1 * p0))));
    switch (((f2(1, v3_1, g1, g1) ? (48 ? v3_0[3] : "test"[3]) : ('n' ^ "abc123"[5])) == ((v3_1 ? "wxyz"[3] : 'Z') - ("world"[1] ? -21 : (int)sizeof(unsigned long))))) {
    case 4:
        (((g1 / ('/' | 1)) && (g1 * 'G')) > f2((8609 ? '7' : 1), ("world"[2] != '?'), (g1 + "abc123"[3]), (p0 << (20))));
        break;
    }
    p0 &= ((((v3_1 > -23) << (0)) ^ (f0() ? f0() : (v3_1 ? "wxyz"[3] : v3_1))) - ((("test"[3] ? v3_0[1] : g1) ^ (g2[0] || (int)sizeof(int))) ? f1((v3_0[1] >> (0))) : (("world"[1] / ((int)sizeof(long) | 1)) << (26))));
    return (v3_1);
}

unsigned long f4(unsigned long p0, int p1)
{
    long v4_0;
    int v4_1;
    char v4_2;
    char v4_3;
    v4_0 = 1740;
    v4_1 = 1;
    v4_2 = 8705;
    v4_3 = 13;

    {
        int _d8;
        _d8 = 0;
        do {
            _d8++;
            p1 = f3(f2(((int)sizeof(unsigned long) + -31), f2('h', g1, p1, 174), f3(v4_2), (p0 > v4_1)));
        } while (_d8 < 1);
    }
    {
        int _f9;
        for (_f9 = 0; _f9 < 8; _f9++) {
            switch (((v4_1 * (int)sizeof(long)) - (p1 != (int)sizeof(unsigned int)))) {
            case 3:
                switch (("wxyz"[0] + g2[7])) {
                case 2:
                    switch (g1) {
                    case 3:
                        v4_3 += (int)sizeof(long);
                        break;
                    case 6:
                        v4_1 -= g1;
                        break;
                    case 12:
                        p0 *= 'K';
                        break;
                    }
                    if (g1) {
                        v4_1 = 83;
                        g1 *= 1;
                        v4_1 |= (int)sizeof(unsigned int);
                    }
                    break;
                case 9:
                    p1 *= (115 & p0);
                    break;
                }
                break;
            default:
                {
                    int _w10;
                    _w10 = 0;
                    while (_w10 < 4) {
                        _w10++;
                        v4_1 %= ((-39 && 0) | 1);
                    }
                }
                break;
            }
        }
    }
    g1 += ((((38, "abcd"[1]) + (v4_3 | 0)) < (('x' && (int)sizeof(unsigned int)) ? ("abcd"[1] ^ v4_0) : (3 * 0))) * ((((int)sizeof(long) * 'o') * f1(1)) ^ ((v4_3 && 'Z') - ('T' != g1))));
    v4_3 %= ((((f2((int)sizeof(unsigned long), p0, v4_3, "abc123"[4]), f3(g2[4])) << (5)) << (28)) | 1);
    {
        int _w11;
        _w11 = 0;
        while (_w11 < 9) {
            _w11++;
            goto _lbl12;
            _lbl12:
            {
                int _d13;
                _d13 = 0;
                do {
                    _d13++;
                    (("world"[2] / (235 | 1)), (g2[3] & p0));
                    v4_0 &= ((g2[7] / (p0 | 1)) ? ((int)sizeof(int) / (v4_0 | 1)) : (0 ? v4_0 : g2[5]));
                } while (_d13 < 6);
            }
            gs0.m3 = ((f1(v4_3) * (2840 < 0)) + ((g2[1] | g2[4]) & ((int)sizeof(unsigned char) ? 175 : 46)));
        }
    }
    {
        int _d14;
        _d14 = 0;
        do {
            _d14++;
            goto _lbl15;
            _lbl15:
            p1 -= ((f2(51, (int)sizeof(long), "abc123"[4], v4_0) >> (25)) >> (24));
        } while (_d14 < 2);
    }
    v4_1 *= ((f1(("abc123"[4] & v4_0)) >> (23)) & (f1((99 && p0)), (('_' + "wxyz"[3]), (32 ? 'S' : 9835))));
    v4_1 |= ((((g2[0] >> (13)) < (0 & 31)) != ((218 & 't') == (-43 << (18)))) ? (f2((1 || v4_1), (v4_1 || "test"[2]), f3(p0), f1(v4_1)), f3(((int)sizeof(int) >> (15)))) : (((115 >> (9)) & (1 / (16 | 1))) >> (9)));
    {
        int _w16;
        _w16 = 0;
        while (_w16 < 8) {
            _w16++;
            {
                int _d17;
                _d17 = 0;
                do {
                    _d17++;
                    {
                        int _f18;
                        for (_f18 = 0; _f18 < 2; _f18++) {
                            if (g2[4]) {
                                v4_1 -= v4_3;
                            }
                            v4_3 %= (('u' ? 63 : -15) | 1);
                            p0 |= (v4_3 >> (26));
                        }
                    }
                } while (_d17 < 8);
            }
        }
    }
    {
        int _w19;
        _w19 = 0;
        while (_w19 < 7) {
            _w19++;
            v4_2 |= f1(f2(('f' == -23), ((int)sizeof(unsigned int) << (23)), (v4_0 ^ v4_2), f2(g2[8], v4_2, '|', "fooX"[1])));
            (((5 == p0), ("world"[4] == 0)) | (('C' ? 1 : 53) || f3(g2[4])));
        }
    }
    goto _lbl20;
    _lbl20:
    gs0.m2 = ((f1(((int)sizeof(unsigned int) - "fooX"[2])) + (((int)sizeof(unsigned int) | 8830) < (p0 != -20))) ^ ((('d' ? (int)sizeof(unsigned int) : 'x') > (g1 | (int)sizeof(int))) - f0()));
    v4_3 &= (f3(f2((6368 != -49), ((int)sizeof(unsigned int) >> (16)), (v4_0 % (3445 | 1)), (p1 | g1))), ((("test"[2] != g2[3]) > (4457 ? "hello"[1] : g2[3])) * ((157 && v4_0), ("wxyz"[2] >> (8)))));
    g2[5] = f0();
    return (v4_0);
}

unsigned long f5(unsigned char p0)
{
    struct S1 v5_0;
    char * v5_1;
    int * v5_2;
    v5_0.m0 = 0;
    v5_0.m1 = 81;
    v5_0.m2 = 0;
    v5_0.m3 = 5268;
    v5_0.m4 = 0;
    v5_0.m5 = 0;
    v5_1 = 0;
    v5_2 = 0;

    ((f4(f3(p0), (2628 != p0)) == f4((-18 || "abcd"[3]), (p0 % ('W' | 1)))) == ((('/' / (5956 | 1)) && (p0 == 67)) == ((0 == p0) + (p0 ? (int)sizeof(unsigned long) : g2[2]))));
    g1 -= (f2(((6112 << (16)) % ((49 % (p0 | 1)) | 1)), ((0 & p0) - (p0 << (10))), (((int)sizeof(char) == p0) != (-40 & 6)), f4((-35 == g1), (2990 ? (int)sizeof(char) : ':'))) - (f2((573 == ' '), f0(), ("wxyz"[3] << (8)), f1(1)) || ((g1, g1) * (g1 > g1))));
    gs0.m2 = ((((g1, (int)sizeof(unsigned char)) == (p0 ? "wxyz"[2] : "barY"[3])) ? ((g1 && 21) ^ ((int)sizeof(unsigned int) ? -45 : p0)) : ((g1 << (13)) > f0())) / (f4((((int)sizeof(char) ? 59 : p0) != f1(p0)), ((g2[9] > (int)sizeof(unsigned long)) ? f2(p0, (int)sizeof(unsigned long), g1, 'T') : ('/' & 0))) | 1));
    g2[5] = (((f1(g1), (p0 - g1)) >> (23)) == f1(((g1 ? p0 : "barY"[0]) ? (p0 ^ 'P') : f3(1))));
    g2[7] = ((f0() < f0()), f1(((g1 ? g2[0] : 36) ^ (p0 ^ 'o'))));
    {
        v5_2 = &p0;
        *v5_2 = f4(((197 != "world"[4]) + (g1 >> (17))), (f1(g1) % ((p0 > "barY"[0]) | 1)));
    }
    g2[1] = ((((g1 | p0) & f0()) * ((p0 << (22)) / ((p0 || g2[8]) | 1))) != (((g1, p0) - (p0 + 229)) ? f4((g2[3], 0), ("test"[0] & g1)) : (f3(g1), (g2[7], p0))));
    {
        int _w21;
        _w21 = 0;
        while (_w21 < 8) {
            _w21++;
            if ((f3(-40), (1, 'B'))) {
                v5_1 = &g1;
                *v5_1 = ((p0 ^ "barY"[3]) << (12));
            } else {
                goto _lbl22;
                _lbl22:
                f2((1 ? g1 : 11), (g1 - "abc123"[2]), ((int)sizeof(long) && g1), (71 ? 166 : g1));
                {
                    int _w23;
                    _w23 = 0;
                    while (_w23 < 4) {
                        _w23++;
                        p0 %= (('o' % (6 | 1)) | 1);
                        g1 = (p0 - "hello"[4]);
                    }
                }
            }
            f1((('g' || "test"[3]) ? (g1 > (int)sizeof(char)) : f0()));
        }
    }
    return (g1);
}

int main(void)
{
    int result;
    char * m0;
    char m1[4];
    unsigned long m2;
    result = 0;
    m0 = 0;
    m1[0] = -12;
    m2 = -44;

    {
        int _w24;
        _w24 = 0;
        while (_w24 < 8) {
            _w24++;
            result |= ((('y' != m2) ? (g1 ? 'A' : g2[2]) : (33 || 's')) - (("world"[0] ? "abc123"[5] : 46) & (m2, result)));
        }
    }
    m1[3] = (f4(((0 ? (int)sizeof(long) : m1[2]) & (result || result)), ((g1 / ("hello"[2] | 1)) ? (g1 | '?') : (result - result))) >> (7));

    result = 0;
    result += (int)(m2);
    result += (int)f3((('l' ? 77 : 35) && ('r' / ((int)sizeof(long) | 1))));

    return (result >= 0 ? result : -result) & 255;
}
