/* Generated by cgen, seed=145 */

char g0;
int g1;
int g2;
char g3 = 2129;
int g4;
int g5 = -30;

char f0(unsigned int p0, long p1);

char f0(unsigned int p0, long p1)
{
    int * v0_0;
    v0_0 = 0;

    if ((((0 < p0) * (g0 << (14))) == ((1 != 1) != (3406 > "world"[2])))) {
        p0 %= ((((8226 ? g5 : (int)sizeof(unsigned char)) ? (4917 & -17) : (1 | g4)) == (('n' > p1) ? (60 / (p0 | 1)) : ((int)sizeof(long) < (int)sizeof(char)))) | 1);
        {
            int _w0;
            _w0 = 0;
            while (_w0 < 4) {
                _w0++;
                p1 &= ((g3 + "abc123"[1]) | (p0 ? g3 : 1));
                if ((p1 - g4)) {
                    g2 /= (('A' || 'g') | 1);
                    p0 &= (p1 >> (29));
                    p1 *= ("wxyz"[2] | p1);
                } else {
                    g2 -= ((int)sizeof(long), "abcd"[2]);
                    p0 /= (("abc123"[5] - g5) | 1);
                }
            }
        }
    } else {
        g5 += (((g3 && 8075) >> (8)), ((1, (int)sizeof(unsigned int)) - ((int)sizeof(unsigned int) / ((int)sizeof(long) | 1))));
    }
    if ((((g0 == g4) * (g0 ? 0 : p0)) >> (16))) {
        g3 |= (((-28 && 0) || ('~' >> (16))) + ((0 / ((int)sizeof(int) | 1)) > (g5 != p0)));
    } else {
        {
            int _d1;
            _d1 = 0;
            do {
                _d1++;
                goto _lbl2;
                _lbl2:
                {
                    int _d3;
                    _d3 = 0;
                    do {
                        _d3++;
                        g0 /= (('K' ? 220 : g2) | 1);
                        p0 |= (g2, -32);
                    } while (_d3 < 3);
                }
            } while (_d1 < 2);
        }
    }
    return (g1);
}

int main(void)
{
    int result;
    char m0;
    int m1[6];
    unsigned long m2;
    int m3;
    int m4;
    unsigned char m5;
    char m6[15];
    result = 0;
    m0 = -1;
    m1[0] = 3485;
    m2 = 183;
    m3 = 31;
    m4 = 100;
    m5 = -5;
    m6[0] = 191;

    goto _lbl4;
    _lbl4:
    {
        int _w5;
        _w5 = 0;
        while (_w5 < 3) {
            _w5++;
            {
                int _d6;
                _d6 = 0;
                do {
                    _d6++;
                    g1 &= ((122 + g5) + (g4 & (int)sizeof(unsigned long)));
                } while (_d6 < 9);
            }
        }
    }
    m2 %= ((((((int)sizeof(char) >> (1)), ("abcd"[1] / ('.' | 1))) * ((g1 | 'C') && (0 ^ result))) % (((('~' && m6[2]) && ('y' || 'L')) << (29)) | 1)) | 1);
    m2 /= ((f0(((g0 > result) ? (28 ^ g2) : ("world"[0], g1)), (((int)sizeof(unsigned int) ? 'q' : g2) != (1 + m4))) & (((m6[8] || 'x') << (17)) | ((g5 & 'j') >> (28)))) | 1);
    {
        int _w7;
        _w7 = 0;
        while (_w7 < 6) {
            _w7++;
            ((f0(m2, "abcd"[3]), (1 < m1[2])) > (("test"[3] << (22)) & ((int)sizeof(unsigned int) >> (12))));
            {
                m2 |= ((99 * g5) ^ (g3 < 4422));
                m4 %= (((g1 >> (11)) % (f0(m3, m5) | 1)) | 1);
            }
        }
    }
    {
        {
            int _f8;
            for (_f8 = 0; _f8 < 10; _f8++) {
                {
                    result |= ((int)sizeof(unsigned long) << (1));
                    m4 |= (m5 ? 'l' : m3);
                }
                g1 |= f0((g3 < -29), (m3 != "wxyz"[3]));
            }
        }
        {
            int _d9;
            _d9 = 0;
            do {
                _d9++;
                {
                    int _d10;
                    _d10 = 0;
                    do {
                        _d10++;
                        g1 /= ((1 << (1)) | 1);
                    } while (_d10 < 5);
                }
            } while (_d9 < 3);
        }
    }
    goto _lbl11;
    _lbl11:
    g2 |= ((((g2, "wxyz"[2]), ('>' * m6[8])), ((m6[4] ? g3 : 18) ^ ('Y' ^ g4))) == (((g4 ? (int)sizeof(unsigned char) : (int)sizeof(unsigned int)) < (0 && g0)) > (("fooX"[2] / (0 | 1)) != (m6[0] / ('!' | 1)))));
    ((((8506 % (0 | 1)) >> (21)) + (("wxyz"[0], 'b') ^ f0(g1, "fooX"[0]))) & (((g0 > 'n') ^ ("test"[1] != g3)) / (((g1 == 220) << (13)) | 1)));

    result = 0;
    result += (int)(g1);
    result += (int)(g5);
    result += (int)(g5);
    result += (int)f0((("barY"[2] || 'p') ? (m4 > -27) : f0(g5, 0)), ((g5 & 'E'), (-45 > (int)sizeof(int))));
    result += (int)f0((("hello"[2] % ((int)sizeof(char) | 1)) * f0(0, 'm')), f0((g0 - g3), (m5 ? "test"[3] : 'k')));

    return (result >= 0 ? result : -result) & 255;
}
