/* Generated by cgen, seed=384 */

struct S0 {
    char m0;
    unsigned char m1;
};

struct S1 {
    char m0;
    int m1;
    int m2;
};

struct S2 {
    int m0;
    char m1;
    unsigned int m2;
    int m3;
    unsigned long m4;
    unsigned long m5;
};

int g0 = 96;
int g1;
unsigned char g2 = 7;

char f0(long p0, long p1, unsigned long p2);
int f1(int p0, unsigned long p1, char p2, long p3);
unsigned int f2(unsigned long p0);
unsigned int f3(long p0, unsigned char p1, unsigned char p2, int p3, unsigned int p4);

char f0(long p0, long p1, unsigned long p2)
{
    int v0_0;
    unsigned char v0_1;
    v0_0 = 52;
    v0_1 = 2763;

    g2 /= (((((-48 || g0) == (v0_1 / (196 | 1))) - ((p2 ? v0_1 : "world"[2]) << (14))) ^ (((p2 & -10) < (g1 < 55)) >> (12))) | 1);
    switch (((((int)sizeof(int) - g1) >> (28)) > ((v0_1 / ('U' | 1)) != (-13 == g2)))) {
    case 0:
        v0_1 -= (((1 < 1) << (11)) ? ((p1 | g1) * ('y', p1)) : ((p0 & v0_1) ? (p0 + 1) : (v0_1 ? (int)sizeof(unsigned char) : 9181)));
        break;
    case 8:
        (((p0, (int)sizeof(long)) * (g0 ? v0_0 : v0_1)) && (("wxyz"[0] ? v0_0 : 68) ? (54 || p2) : (60 >> (27))));
        (((42 && "wxyz"[3]) == ('n' * p0)), ((v0_1 % (41 | 1)) ? ((int)sizeof(char) ? "world"[2] : 12) : (3375 ? 0 : "fooX"[1])));
        break;
    case 14:
        g0 &= (((0 ^ g0) / (((int)sizeof(unsigned char) >> (7)) | 1)) == ((-46 - 'j') == (p1 & g2)));
        break;
    case 17:
        {
            int _w0;
            _w0 = 0;
            while (_w0 < 7) {
                _w0++;
                {
                    int _d1;
                    _d1 = 0;
                    do {
                        _d1++;
                        p1 /= ((v0_0, 140) | 1);
                    } while (_d1 < 4);
                }
            }
        }
        {
            int _d2;
            _d2 = 0;
            do {
                _d2++;
                g2 %= (((g1 % (91 | 1)) & ('0' || (int)sizeof(char))) | 1);
            } while (_d2 < 2);
        }
        break;
    default:
        g0 += (((p0 - (int)sizeof(long)) % ((p1 & g2) | 1)) < ((v0_1, 0) - (p0 | v0_1)));
        g2 /= ((((v0_1, 'E'), (g0 ? v0_0 : p2)) % ((((int)sizeof(unsigned char) == 'c') * (4429, g1)) | 1)) | 1);
        break;
    }
    p1 += ((((7 ? p0 : 1) - ((int)sizeof(char) / ('u' | 1))) << (23)) && (((g1 < 1) ? (g0, 80) : (179 ? g1 : -7)) >> (23)));
    g2 %= (((((76 || p0) << (24)) || ((g2 / (p0 | 1)) ? ('"' % (83 | 1)) : (54, -29))) ? ((((int)sizeof(unsigned char) ? (int)sizeof(char) : 91), (1, "wxyz"[0])) ? (((int)sizeof(unsigned int) && p1) && (v0_1 ? 38 : "wxyz"[0])) : (('C' + 4983) != (p0 == -33))) : (((g2, 1) < (p2 / (p0 | 1))) + ((p1, '$') / (('#' ? 0 : (int)sizeof(unsigned char)) | 1)))) | 1);
    p0 -= ((((209 / ((int)sizeof(unsigned int) | 1)) | (p2 << (11))) && ((96 ? 'I' : (int)sizeof(int)) + (p0 == "world"[0]))), (((1892 ^ "test"[2]) != (1 > -14)) % (((v0_0 | (int)sizeof(long)) ? ("wxyz"[1] + p1) : (g2 << (9))) | 1)));
    return (p1);
}

int f1(int p0, unsigned long p1, char p2, long p3)
{
    long v1_0;
    v1_0 = -40;

    switch ((((1 / ("hello"[3] | 1)) == ("abc123"[2] ? p1 : 6703)) ^ (('A' ? g0 : p2) & (1 & p2)))) {
    case 4:
        g2 += (((99 ^ 2863) % ((p3 % ((int)sizeof(unsigned long) | 1)) | 1)), ((4062 ^ 74), (p0 != (int)sizeof(int))));
        break;
    case 7:
        {
            int _w3;
            _w3 = 0;
            while (_w3 < 2) {
                _w3++;
                if ((961 * 0)) {
                    p3 = (p1 << (24));
                }
                g2 &= ((65 / (g2 | 1)) ? (g2 && 'v') : (p1 && '/'));
            }
        }
        break;
    }
    if ((((g2 ^ 1) == ((int)sizeof(int) + p2)) > ((v1_0 % (p1 | 1)) / (("test"[0] - 193) | 1)))) {
        {
            int _d4;
            _d4 = 0;
            do {
                _d4++;
                {
                    int _f5;
                    for (_f5 = 0; _f5 < 3; _f5++) {
                        p2 += ('A' != p3);
                    }
                }
                v1_0 += (f0(7831, (int)sizeof(unsigned long), 0) % ((2101 ? 231 : (int)sizeof(unsigned int)) | 1));
            } while (_d4 < 10);
        }
    } else {
        if (((9932, "fooX"[3]) << (8))) {
            p2 = (f0(80, v1_0, p2) ? ("hello"[2] >> (6)) : ("world"[4] >> (30)));
        }
    }
    p3 /= ((((f0(0, p0, "test"[1]) < f0(7, "hello"[2], "barY"[2])) > (('J' + p1) % ((2335 & 'z') | 1))) & (((p2 / (p0 | 1)) | ('>', v1_0)) || (("world"[1] | p1) > f0((int)sizeof(unsigned int), v1_0, p3)))) | 1);
    v1_0 *= (((('K' + p0) * (-46 ? '|' : ' ')) < ((1 * 1) ? (v1_0 ? 1 : p2) : (41 * (int)sizeof(int)))) > (((0 != 42) + ('v' > 1)) | f0((9207 ? 23 : -24), f0(-2, 43, v1_0), (67 % (v1_0 | 1)))));
    return (p3);
}

unsigned int f2(unsigned long p0)
{
    int * v2_0;
    unsigned int v2_1;
    char v2_2[10];
    int v2_3[9];
    unsigned long v2_4;
    char v2_5[5];
    int v2_6;
    v2_0 = 0;
    v2_1 = 1;
    v2_2[0] = 1;
    v2_3[0] = 82;
    v2_4 = 0;
    v2_5[0] = 1;
    v2_6 = 0;

    v2_2[6] = ((((v2_1 >> (25)) ? ((int)sizeof(int) ? 1215 : v2_1) : (v2_2[0] | v2_5[1])) != ((110 << (9)), (p0 ? (int)sizeof(unsigned long) : g1))) + ((("abcd"[1] >> (21)) ? (33 ? v2_3[4] : (int)sizeof(int)) : (86 ? v2_1 : 15)) >> (24)));
    return (p0);
}

unsigned int f3(long p0, unsigned char p1, unsigned char p2, int p3, unsigned int p4)
{
    int v3_0;
    unsigned int v3_1;
    int * v3_2;
    v3_0 = 125;
    v3_1 = 9752;
    v3_2 = 0;

    g0 *= ((((p2 >> (15)) | ('1' ^ p3)) ^ ((p2, p0) >> (26))) / ((((g1 ? 0 : g0) > ('.' || -34)) ? (("fooX"[3] | 30) || (p0 + 1)) : ((0 ? 201 : p2) & (v3_0 ? 0 : -22))) | 1));
    switch ((f0(("wxyz"[2], -29), (p4 == 1), (1 != g1)) / (((p3 || '3') != ((int)sizeof(char) == -23)) | 1))) {
    case 4:
        if (((v3_1 ? "hello"[1] : 6963) & (v3_0 / (38 | 1)))) {
            p4 &= (f1(163, 176, 'N', -40) != ("test"[3] != g2));
            g0 %= (((-1 - 0), (63 ? '"' : 1)) | 1);
        } else {
            (((int)sizeof(unsigned char) % (p1 | 1)), (1628 < g0));
        }
        p0 %= ((((v3_0 ? "fooX"[2] : 24) | (133 && 1)) - ((92, 'K') > ("hello"[2] % (328 | 1)))) | 1);
        break;
    case 8:
        p3 |= (((p0 | 'Z') ? (p4 ^ "wxyz"[3]) : (32 * p0)), ((p3 / ("fooX"[2] | 1)), (1, (int)sizeof(unsigned char))));
        break;
    case 12:
        g2 -= (f1(f1((int)sizeof(unsigned int), "abc123"[0], -12, 'b'), f1(20, p1, v3_0, g2), f2(150), ('7' ? p0 : -46)) || ((v3_1 && (int)sizeof(int)) + (1 ? g0 : v3_1)));
        break;
    case 17:
        g2 &= (((p1 != 0) / (((int)sizeof(int) ^ 8629) | 1)) == (("world"[0] - 4) == ('H' & "abcd"[3])));
        break;
    }
    v3_2 = &g2;
    *v3_2 = ((((g1 + 37) ? (g1 && g2) : (p2 | v3_0)) && ((p3 ^ 0) / ((-49 ? g1 : p2) | 1))) + (((0, g0) % ((-8, p4) | 1)) ? (('K' / (p0 | 1)) + ("barY"[0] != 'r')) : (('b', 75) || (v3_1 ^ (int)sizeof(long)))));
    {
        int _f6;
        for (_f6 = 0; _f6 < 3; _f6++) {
            (f0((g0, g0), ('?' ^ p2), ('/' || p1)) / (((0 > 1) / ((-18 == '+') | 1)) | 1));
        }
    }
    if ((((248 ? '#' : -48) ? f1('~', "hello"[1], p1, 9379) : (p0 - 1)) & ((p3 < 1) ? (g2 ? (int)sizeof(unsigned int) : p4) : (9475 ? 0 : '|')))) {
        g0 = f2((f1(1, 'O', p2, -9) < (p0 << (30))));
        {
            int _d7;
            _d7 = 0;
            do {
                _d7++;
                {
                    if ('u') {
                        p3 *= p2;
                        v3_1 %= (48 | 1);
                        p1 |= g0;
                    } else {
                        g0 = 0;
                    }
                    switch (g1) {
                    case 3:
                        p3 |= p1;
                        break;
                    case 8:
                        v3_0 |= v3_0;
                        break;
                    case 12:
                        g2 += p0;
                        break;
                    case 17:
                        g2 *= 1;
                        break;
                    }
                }
            } while (_d7 < 3);
        }
        g2 |= (f1(f1(p2, 27, g1, "barY"[2]), (457 + 7874), (p3 & '>'), (v3_0 % (g1 | 1))), f0(('`' ? 'c' : 0), ('B' || g0), (8462 ? 8428 : 0)));
    }
    p3 -= ((f0((g0 >> (13)), ("abc123"[4] << (4)), ("test"[2] ? 221 : v3_1)) + (((int)sizeof(unsigned char) >> (20)) | (181 > "abc123"[3]))) << (3));
    {
        p0 |= (((0 % (']' | 1)) * ((int)sizeof(long) ? 0 : 'M')) != (f2(g1) & (0 & p3)));
        p1 -= (((g1 | p4) ? f1(v3_1, (int)sizeof(long), 0, -50) : (p4, 80)) || f0((50 + 139), (v3_1 ^ 52), (p2 ? p0 : p1)));
        switch ((f1(3884, 0, p3, '7'), f2((int)sizeof(long)))) {
        case 0:
            p0 |= ((p4 || '%') < (p3 << (27)));
            {
                if (v3_1) {
                    p1 = '%';
                }
                g2 &= (0 && "test"[3]);
                g0 |= (p1 < 1);
            }
            break;
        default:
            goto _lbl8;
            _lbl8:
            break;
        }
    }
    return (p2);
}

int main(void)
{
    int result;
    char m0;
    char m1;
    int m2[2];
    char * m3;
    int * m4;
    int * m5;
    result = 0;
    m0 = 115;
    m1 = -7;
    m2[0] = 9965;
    m3 = 0;
    m4 = 0;
    m5 = 0;

    g0 &= (f0(f0((1 >> (25)), (m1 || (int)sizeof(long)), (58 << (3))), (('!' > 0) | (result & g0)), ((result && (int)sizeof(char)) ? ((int)sizeof(unsigned int) > m1) : (-11 | result))) ? (((0 >> (28)) && (m2[1] != 1958)) ? ((m1 ^ 'e') ? (result ? 'v' : m2[0]) : f3(m1, 1, 2, m2[1], m1)) : ((m2[1] | '>') & (m2[1] ? 95 : -25))) : (((1 ^ g2) | ('e', 1)) & f3((-7 == 1), ('O' != g2), ((int)sizeof(long) / (m1 | 1)), (93 - (int)sizeof(long)), (m2[0] & m2[1]))));
    g0 += (((((int)sizeof(int), 1) ? (g0 - "world"[2]) : ('u' & 0)) ? ((-35 | -12) - f3(0, g1, result, m2[1], m0)) : ((-36 & m0) ? (78 && "abc123"[3]) : f3(21, -24, m1, 'd', g2))) || (((m1 | 0) >> (26)), ((-18 + 2654) & (g0 != g1))));
    goto _lbl9;
    _lbl9:
    {
        int _d10;
        _d10 = 0;
        do {
            _d10++;
            m1 += (((g1 || m0) == (42 + m2[1])) ? ((result ^ m1) > (result ? m0 : -13)) : (f2(-31) >> (8)));
        } while (_d10 < 7);
    }

    result = 0;
    result += (int)(m0);
    result += (int)(m1);
    result += (int)(m0);
    result += (int)f1(((m2[1] < g0) < ("hello"[4] || 2893)), ((g0 + 26) || (6 ? g0 : m0)), ((g1 ? 60 : m2[0]), f3(-17, result, 0, '+', m0)), (f2(0) ? (3045, m1) : f0(m1, "barY"[3], 32)));
    result += (int)f0((f2("abc123"[5]) * ((int)sizeof(long) | result)), ((m1 || m2[1]), f2("abc123"[0])), ((1, g0) * (m2[1] ? 232 : m1)));
    result += (int)f0(((m1 ? m1 : "test"[0]) ^ ("abc123"[1] | result)), ((result >> (18)) + (m1 >> (10))), f1(("hello"[0] * 0), (m1 >> (7)), (1 | result), (result ? 0 : "wxyz"[3])));

    return (result >= 0 ? result : -result) & 255;
}
