/* Generated by cgen, seed=176 */

struct S0 {
    long m0;
    int m1;
    int m2;
    long m3;
};

int g0[2];
int g1 = -44;
int g2 = 3527;
int g3[13];
int g4[12];
int g5;
int g6[6];
int g7[12];
unsigned char g8 = 55;

long f0(void);
char f1(int p0, unsigned long p1, char p2, unsigned int p3, int p4);

long f0(void)
{
    char * v0_0;
    v0_0 = 0;

    g5 *= ((((g2 && g1) || (97, g4[4])) << (11)) && (((15 * '(') * ((int)sizeof(int) - "abc123"[2])) & ((72, -16) == (g7[8] < g2))));
    {
        int _f0;
        for (_f0 = 0; _f0 < 5; _f0++) {
            g5 &= ((((int)sizeof(long) - 2581) < (0 ^ g1)) && ((g2, g2) * (g8 && (int)sizeof(long))));
        }
    }
    g0[0] = (((('m' | g2), (g1 * g5)) == ((g2 ^ g0[1]), (0 / (0 | 1)))) ? ((((int)sizeof(int) | (int)sizeof(unsigned int)) / ((g2 + g1) | 1)), ((g8 + (int)sizeof(unsigned char)) < (g8, g8))) : (((25 * g1) ^ (-30 * "abcd"[3])) && (("barY"[0], 9608) + (2963 ^ g1))));
    ((((g7[0] + 0) < ('a' / (g5 | 1))) && ((0 + 1) | (g5 & g1))) - (((g5, (int)sizeof(unsigned char)) ? ("wxyz"[0] ? 194 : ')') : (1, g5)) / (((0 - g1) >> (10)) | 1)));
    switch ((((']' - (int)sizeof(unsigned long)) == (-3 * g2)) ? ((g5 < g1) % (('J' | 1) | 1)) : ((g5, "abc123"[1]) << (15)))) {
    case 3:
        {
            switch (('a', g2)) {
            case 3:
                g2 -= (g8 & "test"[3]);
                g1 = (g5, (int)sizeof(unsigned long));
                break;
            case 8:
                g1 *= (')' - g8);
                break;
            case 14:
                g2 = ((int)sizeof(char) + g2);
                break;
            }
            v0_0 = &g5;
        }
        break;
    case 8:
        g6[0] = (((0, g3[8]) & ((int)sizeof(unsigned char) || (int)sizeof(unsigned char))) ^ (("fooX"[0] > 208), ('G' / (9931 | 1))));
        break;
    case 13:
        {
            int _d1;
            _d1 = 0;
            do {
                _d1++;
                {
                    int _d2;
                    _d2 = 0;
                    do {
                        _d2++;
                        g2 = (170 ? "barY"[2] : "world"[1]);
                    } while (_d2 < 2);
                }
            } while (_d1 < 1);
        }
        break;
    case 16:
        g8 |= (((160 >> (10)) / ((',', g1) | 1)) < ((-16 << (21)) & (5467, 72)));
        break;
    case 22:
        {
            int _d3;
            _d3 = 0;
            do {
                _d3++;
                g4[2] = ((0 || (int)sizeof(unsigned long)) + (g1 + g8));
            } while (_d3 < 1);
        }
        break;
    default:
        {
            int _w4;
            _w4 = 0;
            while (_w4 < 2) {
                _w4++;
                g5 -= (('m' > g5) == (6163 / ('R' | 1)));
                g1 = ((1 >> (14)) < (g5 | g5));
            }
        }
        break;
    }
    g7[11] = (((('!' ^ (int)sizeof(char)) && (g8 | g7[7])) + ((38 ? '%' : 'U') && (2459 ? 38 : g2))) < (((g2 - g8) ? (-31 % (77 | 1)) : (229 & g5)) - (((int)sizeof(int) << (7)) * (0 ? "wxyz"[3] : "test"[3]))));
    g6[2] = ((((g2 < 1), ('p' == 'R')), ((g2 << (19)) >> (4))) / ((((g0[1] & 71) & (g5, (int)sizeof(unsigned int))) << (2)) | 1));
    g1 *= ((((2562 ^ g8) / ((g2 | g4[9]) | 1)) % ((("test"[1], g3[8]) ? (g5 ? 1 : -50) : (g1 & g7[6])) | 1)) < (((g2 || g8) ? ('_' / (76 | 1)) : ('V' & g2)) < ((15 ? g1 : g5) || (1 % ("fooX"[0] | 1)))));
    ((((g2 / ('{' | 1)) ? (1 && g4[7]) : (g7[2] || g8)) > ((193 % ('{' | 1)) >> (19))) > (((g2 + g1) % ((g8 * 0) | 1)) ? ((g1 > 70), (g1 / (g1 | 1))) : (('2', g0[0]) < (7815, g1))));
    g5 &= ((((g5 % ('%' | 1)) * (1 - (int)sizeof(char))) < (((int)sizeof(unsigned long) - 1040) && (g1 || 0))) < (((1 & g2) | (-23 + g5)), ((g4[11] && g1) && ("barY"[0] || g8))));
    switch ((((g8, g8) ? ('y' || g6[1]) : (g1 & (int)sizeof(int))) << (10))) {
    case 0:
        g8 |= (((247 & "fooX"[1]) ? ('*' - g8) : (g8 * g5)) + ((1 ? g1 : g5) / ((1 && (int)sizeof(char)) | 1)));
        if ((("abc123"[5], 253) - (-20 || '0'))) {
            ((g7[0], 'P') ^ (6499 > 0));
            g2 %= (((g0[0] != 187) * ('*' >> (26))) | 1);
        }
        break;
    }
    g2 -= ((((g2 == g8) + (g2, (int)sizeof(unsigned char))) << (18)) ? (((g5 << (28)) == (g5, g8)) ^ ((';', 0) ^ (g1 > '{'))) : (((g8 + "barY"[0]) << (20)) == ((-28 ^ 'B') & (g2 & '*'))));
    return (g1);
}

char f1(int p0, unsigned long p1, char p2, unsigned int p3, int p4)
{
    int * v1_0;
    v1_0 = 0;

    p1 %= (((f0() ? ((g2 * ')') < f0()) : ((p4 < 0) ? (g8 & g6[2]) : (0 ? p1 : g8))) < f0()) | 1);
    {
        int _w5;
        _w5 = 0;
        while (_w5 < 9) {
            _w5++;
            {
                int _f6;
                for (_f6 = 0; _f6 < 4; _f6++) {
                    {
                        int _d7;
                        _d7 = 0;
                        do {
                            _d7++;
                            g2 *= (g2 > (int)sizeof(unsigned char));
                        } while (_d7 < 4);
                    }
                }
            }
        }
    }
    {
        int _w8;
        _w8 = 0;
        while (_w8 < 8) {
            _w8++;
            {
                int _f9;
                for (_f9 = 0; _f9 < 6; _f9++) {
                    p0 &= ((1 % ("fooX"[2] | 1)) && (p1 == 'J'));
                }
            }
        }
    }
    p2 |= f0();
    {
        int _w10;
        _w10 = 0;
        while (_w10 < 6) {
            _w10++;
            {
                p2 = (f0() && f0());
            }
        }
    }
    {
        int _w11;
        _w11 = 0;
        while (_w11 < 5) {
            _w11++;
            {
                int _d12;
                _d12 = 0;
                do {
                    _d12++;
                    switch (('j' << (27))) {
                    case 0:
                        g2 += (153 ? 29 : "wxyz"[0]);
                        break;
                    case 5:
                        p4 |= (-35 - g4[8]);
                        g2 = (1 ^ 1);
                        break;
                    case 13:
                        p1 = (p0, 10);
                        p2 += ('<' * 1);
                        break;
                    case 18:
                        g8 = (p1 << (2));
                        break;
                    default:
                        g2 = (p3 != p4);
                        break;
                    }
                } while (_d12 < 1);
            }
        }
    }
    p0 += ((((g5 & (int)sizeof(char)) << (29)) - (f0() < (19 ? '_' : p1))) < (((1 << (9)) != (-10 / (33 | 1))), ((6037 ? g5 : 4986) != ((int)sizeof(int) + g2))));
    {
        int _f13;
        for (_f13 = 0; _f13 < 4; _f13++) {
            p2 %= ((((p3 > -29), f0()) ? ((p3 * (int)sizeof(char)) * f0()) : f0()) | 1);
        }
    }
    p1 *= (((f0() ? (p0 >> (2)) : (-20 < 68)) > (f0() ? (g5 ? p3 : g2) : (-20 - g3[7]))), ((("barY"[3] ^ g0[0]) - (g7[1] == 0)), (f0() ? (22 >> (30)) : (g1 ? (int)sizeof(long) : 131))));
    f0();
    ((((g6[0] * g1), (g8, 97)) ? ((1, p1) && (g2 ? "barY"[3] : -5)) : (f0(), (p3, p2))) == ((f0() & (g0[1], p0)) - (f0() ^ ("barY"[2] ? (int)sizeof(int) : 58))));
    goto _lbl14;
    _lbl14:
    g1 -= f0();
    return (p1);
}

int main(void)
{
    int result;
    char m0[14];
    long m1;
    unsigned char m2;
    char m3[3];
    struct S0 m4;
    unsigned long m5;
    long m6;
    result = 0;
    m0[0] = -37;
    m1 = 1;
    m2 = 198;
    m3[0] = 1;
    m4.m0 = 0;
    m4.m1 = -15;
    m4.m2 = -5;
    m4.m3 = 12;
    m5 = 0;
    m6 = 75;

    g2 &= ((((g8 ? g2 : "wxyz"[1]) ? ((int)sizeof(char) % (m1 | 1)) : ("hello"[0] >> (9))) ? (f1(0, 4585, m1, -35, result) & (-13 ? 1 : '+')) : ((g0[1] >> (19)) >> (23))) << (26));
    switch ((((0 & m3[1]) >> (24)) == ((7440 ? "abc123"[3] : g2) ? (1 - (int)sizeof(long)) : ((int)sizeof(long) / (g5 | 1))))) {
    case 0:
        {
            int _d15;
            _d15 = 0;
            do {
                _d15++;
                result /= (((g0[0] ? 4 : "abcd"[0]) ? ('h' + g5) : ('8' ? 8 : g5)) | 1);
                if ((m5, g1)) {
                    m2 |= (m6 ? 40 : 1);
                    m6 %= ((2585 < g0[1]) | 1);
                    m1 -= (']' / (m6 | 1));
                } else {
                    g1 /= (((int)sizeof(unsigned long) ? 141 : m5) | 1);
                }
            } while (_d15 < 7);
        }
        break;
    case 7:
        {
            int _d16;
            _d16 = 0;
            do {
                _d16++;
                if ((m1 << (18))) {
                    g1 /= ((7929 % (g8 | 1)) | 1);
                    g8 = ("test"[0] ? ',' : g8);
                }
            } while (_d16 < 5);
        }
        break;
    case 14:
        {
            int _w17;
            _w17 = 0;
            while (_w17 < 4) {
                _w17++;
                m1 &= (((int)sizeof(unsigned int) / (g2 | 1)) ? (m5 ^ g7[6]) : (m2 ? 'x' : 'Z'));
            }
        }
        break;
    case 18:
        m4.m2 = (f0() && ((m5, m2) ? ((int)sizeof(unsigned int), "hello"[2]) : (m2 << (24))));
        {
            int _w18;
            _w18 = 0;
            while (_w18 < 5) {
                _w18++;
                g1 += ((m2 == "world"[2]) ^ (239 < 96));
                if ((g1 - 214)) {
                    if (g4[9]) {
                        m5 -= '[';
                    }
                } else {
                    result &= (m5 != g8);
                    g5 &= (m2 >> (14));
                    m2 |= (m6 / ('-' | 1));
                }
            }
        }
        break;
    }

    result = 0;
    result += (int)(m6);
    result += (int)(g8);
    result += (int)f1((f1(g5, 57, 61, (int)sizeof(long), "test"[0]), ("hello"[2] - m1)), (f1(result, g1, 'I', (int)sizeof(int), 3371) < (g8 && "abcd"[2])), (f1(-41, 87, 'A', '%', 'R') ? f1(m6, 1, 79, g5, m1) : (76 | 0)), ((m1 ? "wxyz"[0] : 97) | (m5 % (m0[1] | 1))), ((0 ? m1 : g1) || (m2 ? m0[12] : 0)));

    return (result >= 0 ? result : -result) & 255;
}
