/* Generated by cgen, seed=344 */

struct S0 {
    unsigned long m0;
    long m1;
    unsigned int m2;
};

struct S1 {
    char m0;
    char m1;
    unsigned char m2;
};

struct S1 gs0;
int g1 = 3881;
int g2[5];
unsigned int g3 = 240;
unsigned int g4;

unsigned long f0(char p0);
unsigned long f1(unsigned char p0, long p1, unsigned int p2);
unsigned char f2(int p0, long p1, unsigned char p2);

unsigned long f0(char p0)
{
    int v0_0;
    struct S0 v0_1;
    char v0_2[6];
    v0_0 = 206;
    v0_1.m0 = 1;
    v0_1.m1 = 9147;
    v0_1.m2 = 0;
    v0_2[0] = 37;

    {
        int _d0;
        _d0 = 0;
        do {
            _d0++;
            {
                int _f1;
                for (_f1 = 0; _f1 < 7; _f1++) {
                    {
                        g3 += (g4 % (p0 | 1));
                    }
                    (((int)sizeof(int) != "abc123"[0]) > (g1 | g2[2]));
                }
            }
            if (((g2[1] ? 98 : g4) < (g3, g4))) {
                switch ((1 / (7385 | 1))) {
                case 0:
                    p0 += (204, "world"[4]);
                    g1 = (p0 + 0);
                    break;
                case 6:
                    g4 &= ("abc123"[3] < "barY"[1]);
                    break;
                case 11:
                    p0 &= (v0_0 != g4);
                    break;
                case 17:
                    g1 &= (g3 / (57 | 1));
                    break;
                case 21:
                    if ('=') {
                        p0 /= ("barY"[2] | 1);
                    } else {
                        v0_0 += g2[0];
                        v0_0 += g4;
                    }
                    v0_0 *= (v0_2[5] * v0_0);
                    break;
                }
            } else {
                g4 &= ((v0_0 || 3911) && (p0 | p0));
            }
        } while (_d0 < 9);
    }
    (((("world"[4] || g1), ("abcd"[3] * "fooX"[0])) + ((g1 % (p0 | 1)) ? (g3 << (22)) : (g1 | 75))) ^ ((((int)sizeof(char) ^ v0_2[3]) && ("barY"[3] ^ g4)) ? ((g4 ? v0_0 : g2[4]) >> (0)) : ((g4 - -22) / ((p0 >> (22)) | 1))));
    ((((1 & g4) / ((p0 < v0_0) | 1)), ((0 ^ g4) * (3571 & g3))), ((("fooX"[0] > (int)sizeof(int)) << (13)) || ((p0 % (g1 | 1)) ? ("test"[2] * -39) : (p0 - "abcd"[2]))));
    return (g1);
}

unsigned long f1(unsigned char p0, long p1, unsigned int p2)
{
    char v1_0;
    v1_0 = -50;

    switch ((((0 && 1) > (p1 | 28)) >> (3))) {
    case 3:
        {
            int _d2;
            _d2 = 0;
            do {
                _d2++;
                g1 *= (f0(g1) / ((7 ? g2[1] : -48) | 1));
                {
                    int _f3;
                    for (_f3 = 0; _f3 < 3; _f3++) {
                        if (g2[4]) {
                            g3 -= g2[2];
                            p0 %= (p0 | 1);
                        }
                    }
                }
            } while (_d2 < 2);
        }
        break;
    case 5:
        switch ((((int)sizeof(long), 23) != (g3 && p2))) {
        case 3:
            if ((p1 || "fooX"[1])) {
                g3 += (-4 || (int)sizeof(unsigned long));
                p2 |= (p0 * g4);
                if (-12) {
                    g3 %= (5 | 1);
                    g3 %= (p0 | 1);
                }
            }
            break;
        case 8:
            {
                int _w4;
                _w4 = 0;
                while (_w4 < 1) {
                    _w4++;
                    v1_0 /= ((p2 / (-26 | 1)) | 1);
                }
            }
            break;
        }
        break;
    case 13:
        {
            int _w5;
            _w5 = 0;
            while (_w5 < 6) {
                _w5++;
                {
                    int _f6;
                    for (_f6 = 0; _f6 < 4; _f6++) {
                        g4 |= (g2[3] << (9));
                        if (g3) {
                            g4 += g2[3];
                            p1 = 6;
                        }
                    }
                }
                p2 += (f0(g2[3]), f0('3'));
                g1 += ((v1_0 | 1) || ((int)sizeof(unsigned long) | p0));
            }
        }
        break;
    default:
        g3 = ((f0(-15) ? (81 || p1) : f0(65)) * (f0(p0) | f0(g3)));
        break;
    }
    return (v1_0);
}

unsigned char f2(int p0, long p1, unsigned char p2)
{
    unsigned long v2_0;
    unsigned char v2_1;
    unsigned char v2_2;
    unsigned long v2_3;
    int * v2_4;
    char v2_5[12];
    int v2_6;
    v2_0 = 1;
    v2_1 = 75;
    v2_2 = 224;
    v2_3 = 3811;
    v2_4 = 0;
    v2_5[0] = -11;
    v2_6 = 1;

    v2_6 -= (f1(((v2_1 < "abc123"[5]) ? ((int)sizeof(unsigned int) >> (27)) : ("abc123"[2] >> (18))), (("test"[1] == v2_3) || (g3 != v2_1)), ((p1 ? g1 : 53) > (g1 > p0))) + (((g4 ? '*' : "wxyz"[2]) ^ (9 | 5184)) ^ (f1(p1, (int)sizeof(unsigned int), v2_2) != ((int)sizeof(long) >> (1)))));
    g4 -= (((f0(p2) << (28)) + ((p0, 4295) ? (v2_1 ^ p2) : f0(g3))) && f0(f1((g1 < 86), f0(8307), (p0 / ('!' | 1)))));
    v2_5[1] = (((f1(p2, (int)sizeof(unsigned long), g4) > (v2_0 < v2_6)), ((v2_0 - '@') != (v2_3, '6'))) ^ (((v2_2 | -7) ? (73, v2_5[4]) : ('/' != 205)) & ((1 % (v2_3 | 1)) / (f1(p2, "hello"[3], p2) | 1))));
    v2_3 &= f1((((251 ? g4 : p0) == (g3 || v2_3)) ? ((p0 ? 2797 : 0) & (g3 ? '5' : "abc123"[3])) : (f1(-37, v2_3, v2_2) / ((1 | v2_5[2]) | 1))), (((v2_6 & (int)sizeof(unsigned int)) >> (26)) || ((v2_3 + -46) ^ f1(55, p0, 2401))), ((f0(211) ? f0(p1) : ((int)sizeof(unsigned int) << (14))), ((0 | '-') - f1(v2_0, 'D', 0))));
    {
        int _f7;
        for (_f7 = 0; _f7 < 3; _f7++) {
            v2_5[4] = (((v2_1 < p1) > (v2_3 ^ v2_2)) ? ((26 - 1), (v2_1 + 10)) : ((403 << (26)) * (-44 << (6))));
            v2_1 %= (((f1((int)sizeof(int), g3, 194) < (v2_1 << (16))) << (23)) | 1);
        }
    }
    {
        int _d8;
        _d8 = 0;
        do {
            _d8++;
            switch (((0, "hello"[4]) && (g3 >> (24)))) {
            case 0:
                goto _lbl9;
                _lbl9:
                switch (((int)sizeof(unsigned int) + g1)) {
                case 0:
                    p1 -= (v2_0 << (27));
                    break;
                case 8:
                    v2_6 |= (-24 * g2[4]);
                    break;
                case 11:
                    p0 &= (2488 + v2_2);
                    p0 |= (v2_0 & 1);
                    break;
                case 18:
                    p1 /= (f1((int)sizeof(int), g4, p0) | 1);
                    break;
                case 22:
                    v2_0 += (g1 ? 86 : 59);
                    v2_3 &= (v2_1 / (v2_3 | 1));
                    break;
                }
                break;
            case 9:
                v2_1 = f1(((int)sizeof(char) % ('(' | 1)), ('(' == 9095), ('m' - "wxyz"[1]));
                v2_0 |= (("abcd"[2] | g3) | ("test"[2], 1));
                break;
            case 14:
                {
                    v2_6 &= f1("fooX"[3], v2_6, p0);
                    v2_6 %= ((4436 ? g2[3] : v2_0) | 1);
                    v2_0 = (g3 ? v2_1 : v2_5[0]);
                }
                break;
            }
        } while (_d8 < 4);
    }
    return (v2_3);
}

int main(void)
{
    int result;
    int m0;
    result = 0;
    m0 = 13;

    goto _lbl10;
    _lbl10:
    if ((f2(((int)sizeof(char) && g2[4]), ("hello"[4] < 50), (g3 & "test"[3])), (f1(g1, 3821, g4) | ((int)sizeof(unsigned int) < g3)))) {
        g4 -= f2((f2("abc123"[5], g4, g1) != (g4, g1)), f1(((int)sizeof(long) | (int)sizeof(unsigned long)), (1 >> (19)), (g4 == 90)), ((g4 + g3) | ((int)sizeof(long) | m0)));
    } else {
        m0 *= (f2(((int)sizeof(unsigned int) ? -12 : g1), (' ' == g1), (g2[0] ? g3 : 20)) && ((1 > g1) != (g2[1], result)));
    }
    {
        g1 -= f2(((91 ? 'Z' : g4) != ((int)sizeof(int), (int)sizeof(char))), ((m0 % (0 | 1)) ? ((int)sizeof(unsigned char) ? g4 : '6') : (61, 'D')), (((int)sizeof(unsigned long) ^ "barY"[1]) + (m0 / ('G' | 1))));
        g3 |= (((1708 / (-46 | 1)) && ("barY"[3] != g3)) / ((("barY"[0], result) || (g2[4] | -1)) | 1));
        m0 += (f0((m0 % ("fooX"[1] | 1))), ((g3, result), (result != 528)));
    }
    {
        g1 -= ((f2(g2[1], '|', 157) / ((8746 / (g4 | 1)) | 1)), f2(('=' - "wxyz"[2]), (g1 != g1), (g4 - ' ')));
        {
            int _f11;
            for (_f11 = 0; _f11 < 3; _f11++) {
                {
                    int _f12;
                    for (_f12 = 0; _f12 < 4; _f12++) {
                        g1 = (g4, "wxyz"[3]);
                    }
                }
            }
        }
        g1 -= (f2((m0 > g1), ((int)sizeof(char) ? g3 : 11), ('c' && g4)) ^ (f0((int)sizeof(unsigned long)) / ((g3 + m0) | 1)));
    }
    switch ((((0 ? g4 : g2[0]) << (8)) - ((g1 - (int)sizeof(long)) && (g3 || 0)))) {
    case 1:
        {
            g2[3] = (f1((int)sizeof(long), 0, m0) & ("test"[0], m0));
            g2[0] = (f0((int)sizeof(char)) && (136 ? g2[2] : "barY"[1]));
            if (('x' % (g4 | 1))) {
                result |= (m0 ? 1 : 74);
            }
        }
        break;
    case 8:
        g4 /= ((((253 * g1) | f1('$', result, result)) ? ((192 % ("abcd"[3] | 1)) >> (16)) : ((1 - -30), (g4 + result))) | 1);
        break;
    case 11:
        g1 += f0(((g2[2] | g4) != (1 % (m0 | 1))));
        break;
    case 15:
        switch ((f0(result), f2(g4, 4153, "hello"[3]))) {
        case 2:
            m0 *= ((0 || '6') < (2360 | 0));
            break;
        case 6:
            {
                int _f13;
                for (_f13 = 0; _f13 < 1; _f13++) {
                    g3 &= f0(0);
                }
            }
            break;
        }
        break;
    case 24:
        g2[2] = ((f2(3499, m0, result) / ((g2[0] ? m0 : g3) | 1)) + f1(((int)sizeof(long) % ((int)sizeof(long) | 1)), f0(m0), (0 / (result | 1))));
        break;
    default:
        if (((27 << (8)) & (result ? 163 : g1))) {
            g2[1] = f2((m0 ? 'O' : 0), (result ? 'i' : (int)sizeof(int)), f0(m0));
        }
        break;
    }
    {
        g1 += ((("fooX"[0] - -23) > ('q' / (-27 | 1))) < ((result ? m0 : 75) >> (9)));
    }
    g3 += (((("barY"[0] << (13)) / (f1(g4, 1, 9244) | 1)) * (('G' * g3), ('F', g3))) / ((((m0, g1) >> (8)) != (f1((int)sizeof(unsigned long), g4, "hello"[4]) / (f1(g4, 23, 16) | 1))) | 1));

    result = 0;
    result += (int)(m0);
    result += (int)(g4);
    result += (int)(m0);
    result += (int)f0((('S', g4) ? (1 | g4) : ((int)sizeof(long) % ((int)sizeof(long) | 1))));

    return (result >= 0 ? result : -result) & 255;
}
