/* Generated by cgen, seed=53 */

struct S0 {
    unsigned long m0;
    unsigned char m1;
    unsigned long m2;
    int m3;
};

struct S1 {
    long m0;
    char m1;
    unsigned char m2;
    unsigned int m3;
    unsigned int m4;
};

struct S2 {
    unsigned char m0;
    char m1;
    unsigned long m2;
    unsigned int m3;
    unsigned char m4;
    int m5;
};

struct S3 {
    int m0;
    unsigned int m1;
    unsigned long m2;
};

struct S4 {
    unsigned int m0;
    unsigned long m1;
    unsigned long m2;
};

unsigned char g0 = -2;
int g1[2];
unsigned char g2 = 60;
unsigned char g3 = 73;
int g4[4];
struct S1 gs5;

unsigned int f0(int p0, unsigned int p1, unsigned int p2);
int f1(unsigned long p0, int p1, unsigned char p2, unsigned int p3, unsigned char p4);
unsigned int f2(unsigned long p0, char p1, unsigned int p2, long p3);
unsigned long f3(long p0, unsigned long p1, unsigned long p2, long p3, int p4);
int f4(void);
unsigned char f5(void);

unsigned int f0(int p0, unsigned int p1, unsigned int p2)
{
    unsigned int v0_0;
    struct S4 v0_1;
    v0_0 = 4792;
    v0_1.m0 = 122;
    v0_1.m1 = 94;
    v0_1.m2 = 1;

    g2 *= ((((g2 < '4') && ((int)sizeof(char) ? g0 : (int)sizeof(int))), ((5928 ? p0 : g4[2]) ? ((int)sizeof(unsigned char) ? 15 : g2) : (g1[1] % (p0 | 1)))) + (((1 != 'S') - (2378 | "barY"[1])) * ((g0 - p2), (8024 ? '8' : p0))));
    g2 *= ((((1 | 'Q') ? ((int)sizeof(unsigned long) / (v0_0 | 1)) : (v0_0 || p0)) * ((p2 == 1) || (0 * 0))) != (((187 && 'n') ? (190 * -25) : ((int)sizeof(int) + g3)) ^ ((g1[1] % ("world"[3] | 1)) << (11))));
    return (g0);
}

int f1(unsigned long p0, int p1, unsigned char p2, unsigned int p3, unsigned char p4)
{
    int * v1_0;
    int v1_1;
    char v1_2[16];
    int v1_3;
    unsigned int v1_4;
    unsigned char v1_5;
    long v1_6;
    v1_0 = 0;
    v1_1 = 4392;
    v1_2[0] = 0;
    v1_3 = 1115;
    v1_4 = 1;
    v1_5 = 8400;
    v1_6 = 0;

    {
        int _w0;
        _w0 = 0;
        while (_w0 < 3) {
            _w0++;
            p3 -= (((p4 == v1_6) | (g0 * 11)), f0(("barY"[0] | p4), (g4[0] == -2), ('f' || p2)));
        }
    }
    goto _lbl1;
    _lbl1:
    g2 |= (((((int)sizeof(unsigned int) & 41) ? (3226, "fooX"[2]) : (v1_2[13], 24)), ((5820 ? p0 : "barY"[2]) != (p3 & g4[2]))), (((77 - g1[1]) > (v1_2[8] & 30)) << (10)));
    ((((p0 ? v1_6 : p3) != ((int)sizeof(int) | v1_5)) == (((int)sizeof(unsigned int) ? v1_5 : "test"[1]), f0((int)sizeof(long), 0, 11))) | ((('w' || 4346) ? (p4 | 0) : (v1_4 > 0)) ? ((v1_1 % (g3 | 1)) / ((v1_1 && 1) | 1)) : ((v1_6 - g4[1]) | (-20, 31))));
    v1_0 = &g3;
    v1_0 = &g2;
    *v1_0 = ((((g2 != g0) != ('q' ^ 7696)) == ((p4 != 'K') ? (v1_6 ? (int)sizeof(unsigned char) : "abc123"[0]) : (v1_2[5] ? g4[3] : v1_6))) * ((('"' && -31) << (12)) / (((p0 - v1_5) >> (9)) | 1)));
    {
        int _w2;
        _w2 = 0;
        while (_w2 < 7) {
            _w2++;
            v1_1 *= ((((int)sizeof(unsigned char) > 35) || (g2 & p4)) * ((1 ? 0 : 'W') ? (g1[1] != -12) : f0(0, v1_4, '`')));
        }
    }
    {
        g2 |= (((64 ? 1 : 80) == ((int)sizeof(char) * 1)) ? ((v1_5, p2) ? ((int)sizeof(unsigned int) % (v1_5 | 1)) : f0(7913, g1[1], v1_1)) : (f0('C', g1[0], "abc123"[2]) & (p3 ? p3 : 94)));
    }
    return (p0);
}

unsigned int f2(unsigned long p0, char p1, unsigned int p2, long p3)
{
    char * v2_0;
    v2_0 = 0;

    g1[0] = (((("barY"[3] == "hello"[1]) == (936 >> (14))) - f0(((int)sizeof(long) != 1), (g3 & (int)sizeof(int)), ("hello"[4] ? 4937 : p1))) ? (((1 % (0 | 1)) ? ((int)sizeof(int) ? (int)sizeof(int) : 1589) : (g1[1] && 222)) | (((int)sizeof(int) ? 'q' : "wxyz"[1]) << (19))) : (((98 < "abc123"[5]) & (p3 && g2)) != (((int)sizeof(int) ? p0 : g3) > (p0 / (p1 | 1)))));
    p1 += f0(((f0(65, g1[0], g3) + ("abc123"[5] < 1)) > ((p0 ? 1 : p1) && f1('w', g0, 27, p2, -41))), f1((f1(p3, "abc123"[2], (int)sizeof(long), 23, g2) / ((g1[1] << (23)) | 1)), f1((0 || "world"[4]), ("test"[2] >> (24)), (1 >> (24)), (7251 < p2), ((int)sizeof(int) < p3)), (f0((int)sizeof(unsigned char), p3, g1[1]) ? (g4[1] * '-') : (g4[1] > 1)), ((90 * "hello"[0]) != (9793 ? "wxyz"[2] : p2)), (((int)sizeof(unsigned char) ? 4 : p0) == (g4[3] * g4[3]))), (((g3 ? g2 : p3) | (g0 > 1)) && (f1(99, p3, (int)sizeof(unsigned long), '6', g2) / (("wxyz"[2] << (22)) | 1))));
    v2_0 = &p2;
    g0 *= ((((185 && 236) ^ (g4[1] ? g0 : g0)) + ((g3 || 1) ? (g0 ^ p0) : (g2 >> (18)))) | (((p2 / (81 | 1)) > f0(g1[0], 31, -32)) == (("abc123"[2] | -31) & f0(p0, "abcd"[0], 100))));
    return (p2);
}

unsigned long f3(long p0, unsigned long p1, unsigned long p2, long p3, int p4)
{
    struct S0 v3_0;
    int v3_1;
    int * v3_2;
    v3_0.m0 = 1;
    v3_0.m1 = -5;
    v3_0.m2 = 18;
    v3_0.m3 = 574;
    v3_1 = -19;
    v3_2 = 0;

    gs5.m2 = ((((p1 - "fooX"[2]) % ((p0 || 52) | 1)), ((p0 && p3) / ((g0 && p0) | 1))) ? (f0((1 ^ v3_1), (p3 ^ g0), (1 > p2)) % (f2((g3 ? g2 : g2), (1 | p2), (144 < (int)sizeof(char)), f1((int)sizeof(unsigned int), (int)sizeof(unsigned char), (int)sizeof(unsigned int), -35, -41)) | 1)) : (((p2 ? (int)sizeof(int) : "wxyz"[3]) != (78 + (int)sizeof(unsigned char))) * (("fooX"[1] ? 0 : (int)sizeof(unsigned int)) != (p1 >> (19)))));
    {
        int _d3;
        _d3 = 0;
        do {
            _d3++;
            p1 *= f1(f2((g4[2] % ("abcd"[3] | 1)), f1('5', "abc123"[1], p0, 1, 1), (p3 % (p4 | 1)), (77 == g4[0])), (((int)sizeof(char) || g1[1]) < (g3 != p3)), (("abc123"[3], 21), ((int)sizeof(unsigned long) << (11))), ((g0, 1) ? (g2 && "test"[0]) : (p3, 1)), ((5778 ? "test"[2] : g3) && (0, 82)));
            {
                int _w4;
                _w4 = 0;
                while (_w4 < 4) {
                    _w4++;
                    {
                        switch (170) {
                        case 1:
                            p1 *= g2;
                            break;
                        case 6:
                            v3_1 |= 'q';
                            p2 |= 51;
                            break;
                        default:
                            p1 /= ('u' | 1);
                            break;
                        }
                        g2 = f0('g', p2, "abc123"[3]);
                        g3 |= (p4 > p3);
                    }
                }
            }
        } while (_d3 < 3);
    }
    switch ((((6492 * (int)sizeof(char)) ^ ('p' - "barY"[0])) < (((int)sizeof(unsigned char), "wxyz"[3]) < f1(p0, p4, 0, p3, g4[0])))) {
    case 0:
        ((f2(39, (int)sizeof(unsigned long), 'A', "test"[1]) << (2)) > ((g0 ^ 53) * (p3 == g3)));
        break;
    case 5:
        switch ((f1(1, 1, "barY"[3], g2, 0) < ((int)sizeof(unsigned char) / (']' | 1)))) {
        case 4:
            {
                int _w5;
                _w5 = 0;
                while (_w5 < 5) {
                    _w5++;
                    g3 = (g2, (int)sizeof(int));
                }
            }
            g1[0] = (((int)sizeof(unsigned char) << (3)) != (g2 * 'x'));
            break;
        case 9:
            g3 = f2((p0 && g1[1]), (g0 == -43), (g3 > 0), f0(76, (int)sizeof(char), p1));
            break;
        case 12:
            {
                int _d6;
                _d6 = 0;
                do {
                    _d6++;
                    p0 |= (g0 != g2);
                } while (_d6 < 4);
            }
            break;
        }
        break;
    case 11:
        goto _lbl7;
        _lbl7:
        break;
    case 19:
        switch (((p3, p4) ? (g3 & p1) : (p2 & g3))) {
        case 2:
            g1[0] = (((int)sizeof(unsigned int) << (1)) ^ (6885 < v3_1));
            break;
        case 7:
            goto _lbl8;
            _lbl8:
            break;
        case 14:
            gs5.m0 = f0(f1(g2, p4, v3_1, p3, 78), (p4 ? p2 : g0), (0 < 'T'));
            break;
        default:
            v3_0.m0 = ((p0 | p0) >> (2));
            break;
        }
        break;
    case 23:
        g1[1] = f2(((1 ? p2 : 0) & (g3 < p2)), (f1(0, 0, p2, v3_1, 26) - (g3 / (168 | 1))), ((p4 ^ p1) ? ("hello"[3] > p1) : (v3_1 ? p3 : 95)), ((g0 >> (28)) - (p0 * p2)));
        break;
    }
    switch ((((g1[0] & 72) == (2740 != (int)sizeof(int))), ((g0 ? 'X' : "barY"[1]) & (p0 < p3)))) {
    case 4:
        g4[3] = ((('=' ? (int)sizeof(unsigned long) : '|') == (-32 >> (15))) ? (('v' < 7889) != (g4[1] / (p0 | 1))) : ((p1 >> (14)) || (g3 || g4[3])));
        goto _lbl9;
        _lbl9:
        break;
    case 7:
        v3_2 = &g3;
        {
            int _w10;
            _w10 = 0;
            while (_w10 < 8) {
                _w10++;
                v3_2 = &p2;
                *v3_2 = f2((g4[0] != 6332), f0((int)sizeof(long), 0, 7565), (g3 >> (5)), (g4[3] / (4 | 1)));
            }
        }
        break;
    case 10:
        g0 %= ((((60 % (1 | 1)) ? (g3 / (p1 | 1)) : (g1[0] + g0)) != ((g1[0] || 5854) == (p3 > '3'))) | 1);
        break;
    case 17:
        g0 *= (((p2 + p1) % ((118, 91) | 1)) > (('f' || 149) - (p4 ? g0 : "barY"[3])));
        break;
    case 22:
        gs5.m3 = (((p0, p3) ? (3098 && v3_1) : (p0 + g1[0])), ((v3_1 ^ (int)sizeof(unsigned long)) ^ ('i' % ("wxyz"[0] | 1))));
        p0 %= (f2((('b' % (v3_1 | 1)) << (17)), ((1 ? p3 : "test"[3]) - f2(0, "abc123"[1], p3, (int)sizeof(char))), ((g0 | 30), ("barY"[0] == "abcd"[1])), ((p3 % (9 | 1)) / ((v3_1 ? 60 : p2) | 1))) | 1);
        break;
    default:
        v3_2 = &p0;
        break;
    }
    return (p4);
}

int f4(void)
{
    unsigned int v4_0;
    char * v4_1;
    v4_0 = 75;
    v4_1 = 0;

    v4_0 += ((((g4[3] < 1) >> (18)) ? f1((-6 / (138 | 1)), (1, 5002), (g4[3] ? g3 : g3), (1 || v4_0), ((int)sizeof(int) ? 0 : '.')) : ((-31 & 'n'), (g2, -33))) ^ f0(((3896 * -4), (g0 * 4864)), ((g4[3] >> (3)), (3630 == g1[0])), ((v4_0 * 8053) != f1(g0, g1[1], g2, v4_0, 1))));
    {
        int _d11;
        _d11 = 0;
        do {
            _d11++;
            {
                int _d12;
                _d12 = 0;
                do {
                    _d12++;
                    g4[0] = ((g3 ? (int)sizeof(unsigned int) : g2), (v4_0, g4[0]));
                    {
                        int _w13;
                        _w13 = 0;
                        while (_w13 < 2) {
                            _w13++;
                            g2 *= (g0 || '@');
                        }
                    }
                } while (_d12 < 7);
            }
        } while (_d11 < 8);
    }
    {
        int _f14;
        for (_f14 = 0; _f14 < 10; _f14++) {
            g2 /= ((((1, g0) > ((int)sizeof(unsigned char) != 206)) > ((g0 || 44) > (g1[1] < 0))) | 1);
        }
    }
    if ((((g4[2], 726), ("barY"[1] + g3)) != (((int)sizeof(int) | v4_0) ^ (g0 % (g3 | 1))))) {
        {
            int _d15;
            _d15 = 0;
            do {
                _d15++;
                g4[1] = ((g2 == "hello"[1]), ((int)sizeof(char) || v4_0));
            } while (_d15 < 4);
        }
    }
    switch (((("hello"[2] << (23)) & (g1[1] - g1[1])) - ((71 || (int)sizeof(int)) & (g3 / (8810 | 1))))) {
    case 4:
        g3 /= (((('[' / (g3 | 1)) >> (17)) - (('e' < g3) || (v4_0 == 2270))) | 1);
        g2 %= ((f0((g0 * 1), (g2 ? g2 : v4_0), ((int)sizeof(char) & 0)) < f0((v4_0 ? v4_0 : (int)sizeof(char)), ((int)sizeof(char) + g3), (1 % ('A' | 1)))) | 1);
        break;
    case 8:
        g4[2] = (f1(('+' != g3), (0 || g1[1]), (89 << (1)), ((int)sizeof(unsigned char) && g1[1]), ("world"[1] > v4_0)) & ((83 % (1526 | 1)) || ('r', 'y')));
        g2 = (((g0 - 186), (-15 ? v4_0 : (int)sizeof(long))) ? f0(('D' ^ 233), (4201 > 1), (g2 % ("test"[1] | 1))) : f3(((int)sizeof(int) ^ "abcd"[1]), (0 << (18)), (-43 && 1), ("test"[1] ^ g4[0]), f1(g2, g4[2], 837, g2, 17)));
        break;
    case 11:
        g2 *= f0(((0 ^ (int)sizeof(char)), (v4_0 >> (8))), ((6303, '4') >> (3)), ((7602 >> (0)), (234 != g0)));
        break;
    case 19:
        g0 |= (((g3 ? g2 : (int)sizeof(unsigned int)) ^ (312 || g4[0])) | f3((v4_0, g3), ((int)sizeof(unsigned char), 6), (38 ? 73 : g2), (0 >> (14)), (g2, 2)));
        break;
    case 24:
        goto _lbl16;
        _lbl16:
        break;
    default:
        g0 &= ((f2(g2, g3, (int)sizeof(unsigned long), g3) != ("test"[1] & ']')) - ((g0 * (int)sizeof(int)) & ((int)sizeof(int) % ('m' | 1))));
        break;
    }
    v4_0 %= ((((('&' - g3) ^ (g3, g0)) ? f1((g0 ? 9480 : g0), (g3 | v4_0), (50 * g3), (v4_0 << (21)), ((int)sizeof(char) != "world"[1])) : ((-8 ? '6' : "fooX"[2]), ((int)sizeof(long) == "fooX"[1]))) ? (((g2 - 3706) * (v4_0, g4[2])) ? ((g4[2] ? g2 : g3) || (g4[1] << (29))) : ((92, g3) && (199 ? 6733 : "hello"[3]))) : (f2((g3 ? g0 : (int)sizeof(int)), (1, g3), f0('Y', 0, 0), (0 ? 1 : 0)) == (f1("fooX"[0], 5557, 0, -42, g2) < (g1[0] > 0)))) | 1);
    {
        int _w17;
        _w17 = 0;
        while (_w17 < 8) {
            _w17++;
            g0 /= ((((g0 || 113) ? (-26 ? v4_0 : (int)sizeof(unsigned int)) : (58, 1)) == ((120 ? g0 : 75) < ((int)sizeof(unsigned int) ? (int)sizeof(unsigned char) : g4[1]))) | 1);
        }
    }
    ((((g4[3] / (0 | 1)) ? (g1[0] ? g3 : (int)sizeof(long)) : (g2, '/')) % ((((int)sizeof(int) ? g4[3] : "abcd"[1]) ? (9038 != 2970) : ('J' != (int)sizeof(unsigned char))) | 1)) < (f3(f2('/', 51, g1[0], '9'), (g3 || g1[0]), (-45 << (15)), (g3 ? g2 : g3), (g3 ? g0 : g3)) ? ((237 % (g1[0] | 1)), (v4_0 / (g2 | 1))) : (("hello"[1] != g1[0]) ^ (v4_0 ? g3 : g2))));
    ((((g2 | 3165) == ('B', g1[1])) ? (('O' - g0) - (g3 ? g3 : g0)) : ((5793 || 69), (-37 / (g3 | 1)))) ^ (f2((1, -23), (g0 ? '8' : g3), (g3 != g3), f2('B', "wxyz"[1], 236, '5')) && ((123 ? g0 : 1) < ("test"[0] * 'z'))));
    return (g2);
}

unsigned char f5(void)
{
    int v5_0;
    v5_0 = -32;

    g4[3] = f2(f4(), ((("world"[4] % ("world"[2] | 1)) < f2(132, g2, g2, 1)) - ((g3 ? (int)sizeof(long) : g3) ? ('E' ^ -34) : (v5_0 % ('}' | 1)))), (((g2 ^ 71) / ((g0 == g0) | 1)), ((137 != g4[3]) ^ (g3, '*'))), (f0(("world"[2] ? 19 : 1), (g1[0] == ' '), (0, g1[1])) >> (24)));
    g0 /= ((((("test"[2] ^ g2) ? (g3 % (v5_0 | 1)) : (g3 ? g1[0] : 4)) / (((-20 >> (10)), (g4[1] > g4[1])) | 1)) && (((g3 ^ 25) || ((int)sizeof(unsigned char) - (int)sizeof(unsigned char))) && f3(((int)sizeof(unsigned long), g2), (g1[0] != g2), (1 * 29), f2(g2, (int)sizeof(int), (int)sizeof(char), 1), f1(g0, 3286, g2, 'B', 1)))) | 1);
    return (g0);
}

int main(void)
{
    int result;
    int m0;
    result = 0;
    m0 = 1;

    {
        g0 = (((g0 || (int)sizeof(unsigned long)) ? (0 || 7943) : f3(g2, g2, 145, "abcd"[1], m0)) - f5());
    }
    g1[1] = (f5() ? (((0 - g0) << (25)) ? (((int)sizeof(int) | "abcd"[1]), (g2, m0)) : ((g1[1] != 'C') + ((int)sizeof(long) ? (int)sizeof(int) : (int)sizeof(unsigned int)))) : ((("abcd"[2], g2) % (('=' && "abc123"[4]) | 1)), ((g2 == "test"[0]) ^ f1("world"[1], -48, (int)sizeof(unsigned char), '=', 10))));
    {
        {
            int _w18;
            _w18 = 0;
            while (_w18 < 3) {
                _w18++;
                g1[1] = ((g1[1] + 'x') != (g0 >> (28)));
            }
        }
    }
    {
        {
            int _d19;
            _d19 = 0;
            do {
                _d19++;
                g0 += (f0("world"[2], -40, "abc123"[2]) | (g0 > result));
            } while (_d19 < 9);
        }
    }
    g4[0] = (((("hello"[3] >> (25)) >> (1)) || ((220 ? 54 : -21) ? (13 * m0) : (14 << (12)))) != (((37 << (11)) || ("hello"[2] ? result : g1[0])) & (("wxyz"[0] != (int)sizeof(unsigned int)) || (0 || 89))));
    g2 |= f5();
    g2 |= ((((1 == (int)sizeof(unsigned long)) % (f5() | 1)) | f2(('n' + g2), ("wxyz"[0] | g0), (g1[1], g2), ('b' < "hello"[4]))), ((f0(m0, 0, 91), (g4[0] ? 89 : (int)sizeof(char))) >> (2)));

    result = 0;
    result += (int)(g2);
    result += (int)f4();

    return (result >= 0 ? result : -result) & 255;
}
