/* Generated by cgen, seed=456 */

struct S0 {
    unsigned int m0;
    unsigned int m1;
    char m2;
    unsigned long m3;
    long m4;
};

struct S1 {
    unsigned long m0;
    unsigned long m1;
    unsigned char m2;
    int m3;
};

struct S2 {
    unsigned char m0;
    char m1;
    unsigned long m2;
    long m3;
};

unsigned long g0 = 1466;
char g1 = 0;
unsigned char g2;
char g3;
int g4 = -15;
unsigned long g5;
unsigned long g6 = 142;
long g7;
int g8 = 9450;

int f0(void);
int f1(unsigned long p0, long p1, char p2);
int f2(unsigned int p0, char p1);
int f3(unsigned long p0);

int f0(void)
{
    long v0_0;
    char v0_1;
    long v0_2;
    v0_0 = 0;
    v0_1 = -17;
    v0_2 = 0;

    g1 %= ((((("barY"[0] != g1) == ((int)sizeof(unsigned char) & g0)) & ((72 ? "test"[0] : g8) == (g1 || g2))) ? (((-50 / (-17 | 1)) || (0 >> (19))), (('`', "world"[1]) > (g2 << (8)))) : (((g5, -25) ? (g4 | ',') : (-24, g1)), ((0 == g0) ? (g1 & 8289) : (g0 + -23)))) | 1);
    g8 |= ((((g6 << (5)) ^ ('I' >> (18))), ((g4 != g5) + (92 ? g1 : -38))) - ((((int)sizeof(unsigned int), 'q') << (13)) > ((g5, v0_0) >> (3))));
    v0_1 |= ((((v0_1 | g2), (97 == -29)) != ((g3 ^ 8312) && (g3 + (int)sizeof(unsigned char)))) > (((58 < 48) < (-30 < 21)) + ((g0, '(') - ("test"[1] < g5))));
    if (((((int)sizeof(unsigned char) * 9379) / (((int)sizeof(long) << (24)) | 1)) >> (21))) {
        {
            g6 *= (("hello"[0] ^ 1) >> (3));
        }
    } else {
        g2 %= ((((0 >> (21)) > ((int)sizeof(int) | g1)) / ((((int)sizeof(unsigned long) >> (12)) || ((int)sizeof(unsigned long) >> (27))) | 1)) | 1);
    }
    g8 /= (((((v0_0 & 't') % ((v0_2 < 2952) | 1)) ? ((v0_0 & 0), (g3 & 87)) : ((v0_1 >> (21)) | (v0_2 * (int)sizeof(unsigned long)))) + (((g7 == g0) | (1 - g2)), ((g5 & g8) | (g0 > v0_1)))) | 1);
    return (g4);
}

int f1(unsigned long p0, long p1, char p2)
{
    struct S1 v1_0;
    v1_0.m0 = 1675;
    v1_0.m1 = 26;
    v1_0.m2 = 0;
    v1_0.m3 = -7;

    p0 &= (f0() && f0());
    g6 |= ((f0() ? f0() : (f0() != (44 || 13))) ? ((f0() ? ((int)sizeof(unsigned char) ? g1 : g2) : (g8 / (4794 | 1))) < f0()) : (((p0, 'b'), f0()) == (("test"[0] && g6) > (4087 ? "abcd"[0] : 3739))));
    return (g0);
}

int f2(unsigned int p0, char p1)
{
    char v2_0;
    int * v2_1;
    unsigned long v2_2;
    v2_0 = 0;
    v2_1 = 0;
    v2_2 = -29;

    g4 = ((((p1 | g5) / ((g8 ? (int)sizeof(long) : 'N') | 1)), ((0 != 6652) + (g4, 'f'))) / ((((g3 / (g0 | 1)) > ('m' || 174)) != ((-50 ? g5 : 1) && f1(g2, v2_2, 73))) | 1));
    goto _lbl0;
    _lbl0:
    return (p0);
}

int f3(unsigned long p0)
{
    long v3_0;
    v3_0 = 1;

    g4 = f2(((((int)sizeof(char) ? g3 : g2) ? ('W' ? "abcd"[1] : g5) : (4795 && g3)) > (('A' && 'u') ? (g3 ? g0 : 1) : (-28, g3))), (((g0 * 0) | f1(g0, g2, p0)) ? f1(((int)sizeof(int) >> (14)), f0(), (-30 * 134)) : (('`' == (int)sizeof(unsigned long)) ? f1(1, -8, "abcd"[1]) : (1 || "abcd"[1]))));
    return (g2);
}

int main(void)
{
    int result;
    unsigned int m0;
    int m1;
    unsigned char m2;
    int m3;
    result = 0;
    m0 = 4635;
    m1 = 5775;
    m2 = 1;
    m3 = 22;

    g0 = ((((-33 == 0) != (-41 ? 'Z' : g3)) != (('^' ^ 22) - ("wxyz"[1] & 200))), (((m1 ? 240 : m0) ? (g3 ^ (int)sizeof(char)) : ('`' % (g8 | 1))) ^ (("barY"[2] + -12) != ("world"[0] != 34))));

    result = 0;
    result += (int)(g8);
    result += (int)(m0);
    result += (int)(g3);
    result += (int)(g5);
    result += (int)(g8);
    result += (int)f0();

    return (result >= 0 ? result : -result) & 255;
}
