/* Generated by cgen, seed=339 */

struct S0 {
    long m0;
    unsigned int m1;
    char m2;
    long m3;
    char m4;
    long m5;
};

unsigned char g0;
unsigned int g1;
int g2 = 3881;
unsigned char g3 = -48;
unsigned long g4;

int f0(long p0, unsigned long p1, char p2);
unsigned char f1(long p0, char p1, int p2, char p3, unsigned long p4);

int f0(long p0, unsigned long p1, char p2)
{
    unsigned int v0_0;
    int v0_1;
    unsigned char v0_2;
    unsigned char v0_3;
    v0_0 = 3743;
    v0_1 = -2;
    v0_2 = 5522;
    v0_3 = 0;

    switch (((("barY"[2] ? "abcd"[1] : -50) < (v0_2 == 164)) * (('F' && p2), ('}' % (g3 | 1))))) {
    case 4:
        {
            int _d0;
            _d0 = 0;
            do {
                _d0++;
                p2 &= (('H' > g3) ? ('s' == 0) : ((int)sizeof(unsigned int) ? 59 : 'A'));
            } while (_d0 < 1);
        }
        break;
    case 8:
        p1 &= (((203, "abcd"[1]) ? (0 + p2) : (v0_2, -48)) * ((g0 != g3), (47 << (29))));
        break;
    case 14:
        switch (((p1 + 1), (g3 ^ "test"[2]))) {
        case 4:
            v0_2 -= ((p1 != 5869), ((int)sizeof(unsigned char) ? 255 : 0));
            break;
        case 9:
            g2 = (('A' ? g2 : "wxyz"[3]) != (v0_0 < v0_1));
            break;
        default:
            v0_1 &= ((3084 ? g1 : 1) - ((int)sizeof(int), v0_0));
            break;
        }
        v0_1 |= (((1 | 0) < ((int)sizeof(unsigned char) + p1)) != ((g3 ? p2 : -27) & (-33 & 155)));
        break;
    case 16:
        p0 |= (((1, 67) ^ (75 || "test"[3])) % (((p0 ? p1 : 1) * ('B' < 0)) | 1));
        break;
    default:
        v0_2 %= (((("abc123"[0] == v0_3) & (v0_0 >> (28))) ? ((182, '|') == ((int)sizeof(long) ? g2 : "fooX"[2])) : ((1 ? "world"[1] : "abc123"[5]), (4433 & 'g'))) | 1);
        break;
    }
    if ((((p0 < v0_3), (181 || 24)) ^ ((g4 ? 167 : g1) * (0 | -7)))) {
        g2 *= (((p1 / (g3 | 1)) % ((88 ? "world"[3] : 'U') | 1)) - ((0 / (197 | 1)) & ((int)sizeof(char) < v0_1)));
    }
    {
        int _d1;
        _d1 = 0;
        do {
            _d1++;
            g2 -= (((-8 != 1) < (6372 ^ ',')) != ((v0_3, '!') > (7527 >> (7))));
        } while (_d1 < 7);
    }
    v0_1 = ((((v0_0 ? v0_3 : p1) ? ((int)sizeof(unsigned char) > -36) : (132 && (int)sizeof(int))) ? ((169 != -12), (1, 76)) : ((g2 % (672 | 1)) ? ('x' ? 1149 : g3) : (0 % ((int)sizeof(long) | 1)))), (((g0 - g3) << (3)) >> (16)));
    return (g3);
}

unsigned char f1(long p0, char p1, int p2, char p3, unsigned long p4)
{
    int v1_0;
    unsigned long v1_1;
    char v1_2;
    int v1_3;
    int v1_4[4];
    unsigned char v1_5;
    char * v1_6;
    v1_0 = 1;
    v1_1 = 49;
    v1_2 = 54;
    v1_3 = 0;
    v1_4[0] = 1;
    v1_5 = 206;
    v1_6 = 0;

    g3 = ((f0((v1_5 - (int)sizeof(long)), f0(3403, 0, 0), f0(p2, p2, g4)) && (('D' ? 1 : '"') / ((v1_1 && p3) | 1))) && (((g2 + 74), (21 * 'b')) | ((v1_4[1] > 46) / (('A' + 124) | 1))));
    {
        int _d2;
        _d2 = 0;
        do {
            _d2++;
            v1_4[0] = (f0((v1_3 < 1), ("abc123"[1] && 96), ((int)sizeof(unsigned long) * -20)) > ((v1_3 < -43) | (v1_4[2] | p1)));
        } while (_d2 < 9);
    }
    v1_3 /= (((((32 != "wxyz"[2]) + ((int)sizeof(unsigned long) < 9195)) << (6)) ? (((4614 ? -10 : 's') + f0(0, p1, v1_5)), ((p1 > p2) > (v1_5 >> (2)))) : ((("barY"[0] > p0) > (g0 | "wxyz"[1])) % (((g0 && 1) - (g1 != p2)) | 1))) | 1);
    g0 -= ((f0((9009 ^ g2), (v1_2 < 1286), (p0 >> (13))) < ((g2 ^ '|') ^ f0("barY"[2], g0, g2))) && (((v1_5, 9239) * (v1_5 || (int)sizeof(unsigned int))) < ((99 ? g2 : "hello"[2]) + (g3 + 0))));
    goto _lbl3;
    _lbl3:
    goto _lbl4;
    _lbl4:
    p3 &= ((((226 ? v1_5 : 10) | (0 * g3)) * ((p0 ? '[' : 6793) + (121 ? v1_0 : v1_4[3]))) + f0(f0(f0(70, p4, "wxyz"[2]), ("wxyz"[0] / (153 | 1)), (';' & g2)), (f0(0, g2, v1_4[0]) && (v1_3 == 118)), (f0(v1_3, p1, 51) || ('Z' != "world"[4]))));
    g1 += ((((g1 - 46) > f0(1, '`', 0)) << (25)) | ((('!' + (int)sizeof(unsigned int)) / ((g2 && v1_4[1]) | 1)) ? ((v1_0 - '1') + (-4 | 9838)) : ((1 | v1_4[1]) / ((p4 & "fooX"[2]) | 1))));
    p4 &= ((((v1_4[2] ? p0 : 8286) != (p3 && 1)) % ((f0(v1_4[3], 1, '?') || ("barY"[1] % (v1_4[3] | 1))) | 1)) || (((v1_0, (int)sizeof(unsigned int)) && ('*' == "abc123"[0])) == ((1 / (5341 | 1)) ? (99 < 0) : (g2 && (int)sizeof(unsigned char)))));
    return (p1);
}

int main(void)
{
    int result;
    int m0;
    unsigned int m1;
    int m2[14];
    unsigned int m3;
    char m4[10];
    unsigned long m5;
    int m6[6];
    unsigned char m7;
    result = 0;
    m0 = 0;
    m1 = 0;
    m2[0] = 118;
    m3 = 73;
    m4[0] = -4;
    m5 = -49;
    m6[0] = 17;
    m7 = 4087;

    m0 += (((((int)sizeof(long) != g0) - f1(14, (int)sizeof(unsigned long), 1, (int)sizeof(unsigned long), (int)sizeof(long))) == ((1 ^ g1) == (24 || g3))) + (f0(((int)sizeof(char) != g2), ((int)sizeof(char) - 30), ("wxyz"[1] ? g0 : 66)) ? ((g2 ? result : m1) << (5)) : ((m2[2] * 100) ^ (result ? 's' : g3))));
    {
        int _f5;
        for (_f5 = 0; _f5 < 7; _f5++) {
            if ((f1(m4[5], m2[10], g1, 42, m3) / ((g1 & (int)sizeof(unsigned char)) | 1))) {
                g2 %= ((f0((int)sizeof(unsigned int), "abc123"[0], 9184) / ((g4 & 105) | 1)) | 1);
                m5 += ((m3 ? "barY"[2] : 9534) ^ ('x' ? (int)sizeof(long) : result));
                {
                    int _f6;
                    for (_f6 = 0; _f6 < 5; _f6++) {
                        g3 += (3408 - m5);
                        if ((int)sizeof(unsigned long)) {
                            g4 /= (m1 | 1);
                        } else {
                            g3 *= 1;
                        }
                    }
                }
            } else {
                ((75 ? "hello"[4] : m0) * f1((int)sizeof(long), g1, (int)sizeof(int), (int)sizeof(char), 598));
            }
        }
    }
    g1 &= f1((((g3 ? "barY"[3] : m3) * (m1 & 1)) % (((g3 / ("abcd"[1] | 1)) | (g2, m6[3])) | 1)), (f0((m0 ? g3 : 239), ('[' < result), (m6[0] != m1)) ? ((1 != g2) % ((g2 > m6[2]) | 1)) : ((m4[8] + (int)sizeof(int)) ? (1 ? m7 : m5) : (result - m3))), (f0(f0(m7, 178, 3286), (14 / (9093 | 1)), (m3 + m3)) ^ ((m4[5] ^ m6[1]) - (g4 << (8)))), ((f0(g0, m5, result), ('c' % (255 | 1))), ((-17 * 8601) - (95 / (-21 | 1)))), (((m1 != -16) - (m5 ? m6[3] : 1)) >> (12)));
    m0 = (f0((f1('G', (int)sizeof(unsigned int), m5, m2[11], g1) | f0(0, 16, m7)), ((m4[2] - 1) - ('6' * m5)), ((-29, "abc123"[3]) ^ (m7, "abcd"[1]))) ? f1(((result ^ (int)sizeof(int)) + ("test"[2] ? 73 : g3)), ((241 > 69) / ((g2 | m2[9]) | 1)), (('Z' & (int)sizeof(char)) ? (-32 ? m3 : "wxyz"[3]) : (m4[2] % ("abc123"[3] | 1))), (("test"[2] && m1) % ((m6[0] | "barY"[0]) | 1)), ((m4[5] - 'r') & (g0 && g2))) : (((result + m4[9]) != (0 << (8))) % ((((int)sizeof(char) + (int)sizeof(unsigned int)) != (43 - 0)) | 1)));
    m0 = f1(((f0("barY"[2], g4, m5) * (g1, (int)sizeof(char))) ? ((0 || 19) % ((14 + 'a') | 1)) : f0((1 / (m3 | 1)), (40, m0), f0(result, "barY"[3], (int)sizeof(unsigned int)))), (((m2[9] && "hello"[1]) > ("wxyz"[2] | g0)) ? (((int)sizeof(unsigned int) / ((int)sizeof(int) | 1)) == (0 + m6[3])) : ((7942 ? (int)sizeof(char) : g3), (-14 + '2'))), (((m7 * (int)sizeof(unsigned int)) | (m1 ? m6[4] : m0)) ? (("barY"[1] ? "world"[2] : (int)sizeof(unsigned long)) + ((int)sizeof(unsigned long) || g2)) : f1((g4 == (int)sizeof(unsigned int)), (m2[1] ? m3 : "world"[4]), (1 ? 19 : 'v'), (m6[0] / (result | 1)), (g4 < 0))), (((m3 ? "fooX"[1] : 0) - (-7 / (-11 | 1))) ? ((23 ? (int)sizeof(int) : 9930) ? ('P' || 6257) : f0('}', m3, g2)) : (f1('D', 45, "world"[2], m4[6], 1787) || f1(6648, result, (int)sizeof(long), (int)sizeof(char), 187))), ((('~' << (22)) ? ("barY"[1] || "test"[1]) : ("barY"[2] << (10))) != ((result ? ']' : 'O') >> (16))));
    {
        int _d7;
        _d7 = 0;
        do {
            _d7++;
            goto _lbl8;
            _lbl8:
            g3 %= ((((m4[2], m0) == ("fooX"[3] ^ "fooX"[2])) | ((m4[0] != m6[3]) < ((int)sizeof(unsigned long) == m4[2]))) | 1);
        } while (_d7 < 9);
    }
    m2[7] = (((f1(1, m6[4], result, 59, -11) >> (10)) % ((((int)sizeof(unsigned long) + (int)sizeof(unsigned long)) == (g3, 'd')) | 1)) % ((((g3 || '3') ^ (44 ? 1 : '^')) || ((m0 ? (int)sizeof(unsigned long) : "abc123"[2]) | ((int)sizeof(long) + -25))) | 1));
    m2[6] = (((('x' * m7) / ((17 > (int)sizeof(char)) | 1)), ((m1 ? "wxyz"[0] : m7), (m6[5] > g0))) << (2));
    if (((((int)sizeof(char) / (result | 1)), (121 ^ 9017)) % ((("abcd"[1] ^ ':'), f0(-32, -41, (int)sizeof(unsigned long))) | 1))) {
        {
            switch (('H', '8')) {
            case 4:
                g0 += (m0 * '0');
                break;
            case 7:
                if (2941) {
                    m5 *= m7;
                } else {
                    m3 = m1;
                }
                break;
            case 12:
                g0 /= ((g2 == -2) | 1);
                result |= f0(m2[12], m2[0], "abc123"[0]);
                break;
            case 15:
                g3 = (m6[1] ? g0 : result);
                break;
            }
        }
    }

    result = 0;
    result += (int)(g4);
    result += (int)(g2);
    result += (int)(g0);
    result += (int)f1(((-39 % (m4[4] | 1)) ? (result ? m5 : m2[4]) : f0(g2, m3, 'U')), (f1(m3, m4[9], 1, m0, result), (m6[2], g1)), ((g0 ? 'V' : g3) < f0(0, m6[4], 1)), ((0 >> (12)) ^ f1(g0, g0, 'E', m0, m4[6])), ((g3 | g2) + ("barY"[1] > m0)));
    result += (int)f0(((m7 ^ m4[0]) >> (23)), ((m4[1] || g4) && (51, 'c')), (('*' >> (13)) > (1 << (16))));
    result += (int)f0(((g1 % (m1 | 1)) & (55 || m7)), ((g3 | g1), (m1 >> (17))), ((m5 | 15), (4 & 11)));

    return (result >= 0 ? result : -result) & 255;
}
