/* Generated by cgen, seed=347 */

struct S0 {
    int m0;
    unsigned char m1;
    char m2;
    unsigned char m3;
    int m4;
    long m5;
};

int g0 = 168;
struct S0 gs1;
int g2[8];
int g3;
int g4[13];
int g5[13];
char g6 = -15;
unsigned int g7 = 4157;
unsigned long g8 = 0;

long f0(unsigned long p0, long p1, unsigned long p2);
long f1(long p0);

long f0(unsigned long p0, long p1, unsigned long p2)
{
    char v0_0[6];
    unsigned int v0_1;
    int v0_2;
    char v0_3;
    v0_0[0] = 92;
    v0_1 = 1;
    v0_2 = 5439;
    v0_3 = 1;

    g0 -= ((((p1 == -8) != (72 ? g3 : (int)sizeof(unsigned int))) && (((int)sizeof(unsigned long) & 0) ? (g6 | '+') : (g3 ^ "test"[0]))) | (((g5[4] == p1) / ((22 & 1) | 1)) << (8)));
    return (g6);
}

long f1(long p0)
{
    int * v1_0;
    char v1_1;
    long v1_2;
    int * v1_3;
    int v1_4;
    int v1_5;
    int * v1_6;
    v1_0 = 0;
    v1_1 = 0;
    v1_2 = 19;
    v1_3 = 0;
    v1_4 = 54;
    v1_5 = 87;
    v1_6 = 0;

    v1_3 = &v1_2;
    *v1_3 = (((f0(g4[12], "abcd"[3], -31) > (v1_2 > 96)), f0((g6, g0), (1 < v1_5), ((int)sizeof(long) == g7))) ? (((g3 & g6) == (g6 >> (4))) < ((v1_2 ? g5[2] : g4[8]) ? (g7 ? '/' : g0) : (g0 * g5[10]))) : (((253 ? g6 : 1) | (1 == "barY"[2])) == (f0((int)sizeof(char), 'V', "hello"[3]), (v1_2 / (-48 | 1)))));
    return (g3);
}

int main(void)
{
    int result;
    long m0;
    char m1;
    int m2;
    int m3[6];
    long m4;
    result = 0;
    m0 = 95;
    m1 = -4;
    m2 = -49;
    m3[0] = 170;
    m4 = -27;

    {
        int _w0;
        _w0 = 0;
        while (_w0 < 5) {
            _w0++;
            result /= ((((g7 == "hello"[0]) | ("abc123"[2] ? 1 : 1)) - (f1(m0) ? f1(g4[8]) : (m1 / (39 | 1)))) | 1);
            if (((g3 < (int)sizeof(unsigned char)), f1('w'))) {
                g5[4] = ((g5[8], 92) != f0(m0, (int)sizeof(char), 0));
                {
                    int _f1;
                    for (_f1 = 0; _f1 < 3; _f1++) {
                        g8 -= (g6 && (int)sizeof(int));
                    }
                }
                {
                    int _w2;
                    _w2 = 0;
                    while (_w2 < 5) {
                        _w2++;
                        g3 = (g6 ^ 1);
                        result |= (result == 250);
                        switch (g6) {
                        case 0:
                            g3 |= g0;
                            break;
                        case 5:
                            g0 += 1;
                            g7 |= "abc123"[4];
                            break;
                        }
                    }
                }
            }
            if ((('n' == 1) ? (m0 || g8) : (result & g7))) {
                m2 = ((m1 | g8) != (g6 ? "test"[2] : g7));
                m4 += ((6688 != '6') % ((m3[4] / ('r' | 1)) | 1));
            } else {
                g3 *= f1(((int)sizeof(unsigned long) || 'D'));
            }
        }
    }
    g0 += (((((int)sizeof(unsigned char) != g6) & (25, 'z')) % (((1 >> (10)) ? (':' - "test"[2]) : f1(1)) | 1)) == ((((int)sizeof(long) * 225) - (g0 & g6)) << (29)));
    goto _lbl3;
    _lbl3:

    result = 0;
    result += (int)(m2);
    result += (int)(m4);
    result += (int)(g3);
    result += (int)f0(((g8 % ((int)sizeof(long) | 1)) || (g7 && 213)), ((201 * g5[6]) ? (m2 ^ g0) : (g8 / (';' | 1))), (f1(3968) > (m3[4] < g3)));
    result += (int)f1(f0(("abc123"[0] ? ' ' : g8), (47 * g8), (g3 == "abcd"[2])));

    return (result >= 0 ? result : -result) & 255;
}
