/* Generated by cgen, seed=362 */

long g0 = 1;
int g1;

int f0(void);

int f0(void)
{
    long v0_0;
    char v0_1;
    int v0_2[5];
    v0_0 = 1272;
    v0_1 = -25;
    v0_2[0] = 1845;

    goto _lbl0;
    _lbl0:
    {
        int _f1;
        for (_f1 = 0; _f1 < 8; _f1++) {
            if ((("barY"[3] == v0_1) == (v0_1 < g1))) {
                {
                    int _d2;
                    _d2 = 0;
                    do {
                        _d2++;
                        g0 &= (0 && v0_1);
                    } while (_d2 < 2);
                }
            }
            {
                int _f3;
                for (_f3 = 0; _f3 < 8; _f3++) {
                    {
                        int _d4;
                        _d4 = 0;
                        do {
                            _d4++;
                            if (v0_0) {
                                v0_0 &= (int)sizeof(int);
                            } else {
                                g1 &= v0_2[4];
                            }
                        } while (_d4 < 1);
                    }
                }
            }
        }
    }
    return (v0_0);
}

int main(void)
{
    int result;
    char * m0;
    char * m1;
    int m2[15];
    unsigned char m3;
    result = 0;
    m0 = 0;
    m1 = 0;
    m2[0] = 0;
    m3 = 35;

    {
        int _d5;
        _d5 = 0;
        do {
            _d5++;
            {
                int _w6;
                _w6 = 0;
                while (_w6 < 4) {
                    _w6++;
                    m1 = &m3;
                    switch ((g1, 1916)) {
                    case 2:
                        switch (-38) {
                        case 3:
                            result %= (g1 | 1);
                            break;
                        case 9:
                            g0 += "test"[3];
                            break;
                        case 13:
                            g0 *= '/';
                            g0 %= (result | 1);
                            break;
                        default:
                            g1 -= 73;
                            m3 *= m3;
                            break;
                        }
                        break;
                    case 9:
                        g0 |= (1 >> (22));
                        break;
                    case 13:
                        switch ("abc123"[2]) {
                        case 3:
                            m3 = 7893;
                            break;
                        case 6:
                            g0 *= 61;
                            break;
                        case 11:
                            g0 |= "barY"[2];
                            g0 = "barY"[2];
                            break;
                        case 19:
                            m3 = -48;
                            m3 &= m3;
                            break;
                        }
                        break;
                    case 15:
                        if ((int)sizeof(unsigned long)) {
                            m3 += 'n';
                            result *= "test"[0];
                        }
                        break;
                    case 23:
                        g1 %= ((119, '.') | 1);
                        break;
                    }
                }
            }
        } while (_d5 < 2);
    }
    result /= (((((result == '$') && (result << (7))) < ((0 << (10)) ? (m3 >> (26)) : (g0 + m3))) != (((432 ? (int)sizeof(int) : m3), f0()) | ((143 ^ g0) >> (10)))) | 1);
    result /= (f0() | 1);
    switch (((f0() ? f0() : f0()) * (('(', m3) / ((474 >> (29)) | 1)))) {
    case 3:
        m2[13] = (((result * 0) != f0()) == ((m3 >> (17)) || (m2[5], g1)));
        m2[6] = ((f0() > f0()) % ((('J' ? g1 : g1) && (7117 || g1)) | 1));
        break;
    case 6:
        switch (((result ? 'X' : "barY"[1]) + (5671 == 55))) {
        case 4:
            {
                int _f7;
                for (_f7 = 0; _f7 < 5; _f7++) {
                    g1 = (-10, m3);
                }
            }
            switch (((int)sizeof(unsigned long) ^ ';')) {
            case 3:
                result /= ((g0 == 0) | 1);
                break;
            }
            break;
        case 6:
            {
                int _w8;
                _w8 = 0;
                while (_w8 < 5) {
                    _w8++;
                    switch ((int)sizeof(long)) {
                    case 1:
                        result |= m2[2];
                        result = (int)sizeof(unsigned int);
                        break;
                    default:
                        g0 *= 'M';
                        break;
                    }
                }
            }
            break;
        case 11:
            g0 = (('s' | g1) || (26 ? 54 : m3));
            m0 = &m3;
            *m0 = ((1 ? result : (int)sizeof(unsigned int)) && (0 ? m3 : (int)sizeof(char)));
            break;
        case 17:
            g1 += ((g1 < 1) ^ ('P' / ('/' | 1)));
            break;
        default:
            {
                int _f9;
                for (_f9 = 0; _f9 < 3; _f9++) {
                    g1 %= ((m2[8] < m2[1]) | 1);
                }
            }
            if ((1 ? g0 : g0)) {
                result |= ((int)sizeof(unsigned char) == "abcd"[2]);
                g1 += (27 > 0);
            } else {
                switch ("wxyz"[1]) {
                case 4:
                    m3 &= m2[14];
                    break;
                default:
                    result *= 1;
                    break;
                }
                g1 += (g0 ? "fooX"[2] : g1);
            }
            break;
        }
        {
            {
                switch (g0) {
                case 4:
                    result = "fooX"[0];
                    break;
                case 5:
                    result *= (int)sizeof(unsigned int);
                    break;
                case 13:
                    g1 *= m2[2];
                    g1 *= m2[3];
                    break;
                }
            }
        }
        break;
    case 12:
        {
            int _d10;
            _d10 = 0;
            do {
                _d10++;
                {
                    int _f11;
                    for (_f11 = 0; _f11 < 4; _f11++) {
                        g0 /= ((result ^ 74) | 1);
                    }
                }
                m3 -= (((int)sizeof(unsigned long), g0) > (m3 & 0));
            } while (_d10 < 7);
        }
        break;
    case 15:
        g1 *= (((94 % (':' | 1)) && ((int)sizeof(char) + (int)sizeof(int))) & ((result ? m3 : 1) % (f0() | 1)));
        break;
    default:
        {
            {
                m3 = (0 - g1);
                result += f0();
            }
        }
        break;
    }
    {
        result &= (((m3 & m3) ? ('t' == "barY"[0]) : (g1 / (-37 | 1))), ((1105 / ("abc123"[1] | 1)) << (29)));
        result &= (((result && -29) << (17)) == ((m2[7] | g1) ? (g1 < g0) : (-40 << (3))));
    }
    {
        int _f12;
        for (_f12 = 0; _f12 < 2; _f12++) {
            g1 += (((4426 || -23) == ((int)sizeof(char) == g0)) ? ((result, 1) || (m2[14] * result)) : ((g1 < 0) << (22)));
        }
    }
    if ((((88 / (g1 | 1)) < ("abc123"[3] ^ "fooX"[0])) < ((m2[9] ? 50 : 0) ? (g1 / (result | 1)) : ((int)sizeof(char) >> (10))))) {
        g0 |= (((m2[11] && m2[6]) & (result || -43)) != ((0 + g1) + (m2[12] >> (29))));
        m3 |= (((g0 ? g0 : result) & (5129 < 69)) ^ ((-27 < g0) < (g0 ? 100 : (int)sizeof(unsigned long))));
        g0 -= (f0() | (f0() ? ((int)sizeof(long) - 53) : ('-' || 32)));
    }

    result = 0;
    result += (int)(m3);
    result += (int)(g1);
    result += (int)f0();
    result += (int)f0();
    result += (int)f0();

    return (result >= 0 ? result : -result) & 255;
}
