/* Generated by cgen, seed=402 */

struct S0 {
    int m0;
    long m1;
    char m2;
    char m3;
    unsigned char m4;
    char m5;
};

unsigned char g0;
char g1;
int g2[14];
unsigned long g3;
struct S0 gs4;
unsigned long g5;
unsigned char g6 = -25;
char g7 = -37;

unsigned char f0(unsigned long p0, unsigned long p1, long p2);
unsigned int f1(int p0);

unsigned char f0(unsigned long p0, unsigned long p1, long p2)
{
    long v0_0;
    int * v0_1;
    int v0_2;
    v0_0 = 1;
    v0_1 = 0;
    v0_2 = 0;

    g0 |= (((("fooX"[1] * 'N') != (1 + g7)) > ((1538 + g3) != (v0_0 & "fooX"[2]))) | (((1 != g5) > (1 != (int)sizeof(int))), ((p0 ? g0 : -50) | ('Q' ? '|' : (int)sizeof(unsigned long)))));
    gs4.m3 = (((((int)sizeof(long) ^ v0_0) == ((int)sizeof(int) ? 44 : 0)) ? ((g2[10] != g3) > (g0 ? g5 : g2[8])) : ((g3 ^ 'p') != (96 % ("hello"[1] | 1)))) - (((g6 ? v0_0 : v0_2), (9286 - g3)), ((g3 + 0) | (v0_0 | g3))));
    ((((g2[7], g6) ? (v0_0 ? v0_0 : v0_0) : ('A' ? p0 : g2[10])) ? (("wxyz"[3] << (11)) ? ('u' ? p0 : 0) : (p2 - "wxyz"[0])) : ((-22 || (int)sizeof(int)) & ('U' & g7))), (((55 / (p0 | 1)) ? (1 - g5) : (g6, 't')) != ((1 && 9768) ? (172 ? p2 : (int)sizeof(unsigned int)) : (1 / ((int)sizeof(int) | 1)))));
    v0_2 /= (((((g6 ? p1 : p2) ? (0 ? p2 : "world"[4]) : (p0 & '4')), ((7103 + g7) + (g2[9] - (int)sizeof(int)))) - (((184 >> (9)) ? (1809 >> (17)) : ((int)sizeof(char), g6)) ^ (("barY"[0] == (int)sizeof(char)) - (g7 != g2[5])))) | 1);
    switch ((((g7 ? v0_2 : g0) & (g2[10] ? "abc123"[1] : g3)) & ((g2[9] ? v0_2 : g0) ? ('K' * g2[12]) : (-17 || g0)))) {
    case 1:
        (((g0 | (int)sizeof(int)), (g6 && g5)) ? ((g0 ? -12 : 0) > ('H' * 98)) : ((g0 > g5) != (g1 + (int)sizeof(unsigned long))));
        break;
    }
    v0_1 = &g5;
    *v0_1 = ((((g1 < "wxyz"[2]) ? (g2[3], g1) : (p0 - g7)) % (((-46 ? p0 : 69) / ((v0_2 + p1) | 1)) | 1)) + (((g6, 83) & (g1 % (p2 | 1))) & (("wxyz"[0] | 'd') != (g6 ? g3 : g6))));
    {
        int _w0;
        _w0 = 0;
        while (_w0 < 9) {
            _w0++;
            g6 %= ((((g6, g2[0]) ? (v0_2 > v0_2) : (92 / (p2 | 1))), (('z' || '=') > (p2 & 'm'))) | 1);
        }
    }
    p2 *= ((((-21 ? 2575 : g2[3]) & (64 * 129)) ? ((g0, p2) ? ("test"[1] >> (9)) : ('Q', -35)) : (('l' ? p1 : 3611) | (p1 & 7))) / ((((p1 == g1) & (v0_0 ? -41 : p1)) + ((10 ? 18 : 59) ? (1765 != "barY"[2]) : (0 % (0 | 1)))) | 1));
    return (v0_2);
}

unsigned int f1(int p0)
{
    struct S0 v1_0;
    int v1_1[5];
    v1_0.m0 = 57;
    v1_0.m1 = 36;
    v1_0.m2 = 36;
    v1_0.m3 = 90;
    v1_0.m4 = 181;
    v1_0.m5 = 86;
    v1_1[0] = -29;

    g1 = ((((-48 ? g3 : g1) || (v1_1[4] ? p0 : g0)), (f0("abc123"[3], "barY"[1], g0) ? (g5 ? 74 : 'f') : ((int)sizeof(unsigned long) || 'w'))) ? f0((((int)sizeof(unsigned long) ? 6 : 0) || (p0 > g1)), (f0("abcd"[0], g2[0], g6) ? ("abc123"[2] & 'K') : (g2[7] >> (6))), ((126 ? 1 : 1) ? (g6 ^ g2[13]) : (g6 & v1_1[3]))) : (((-7 == v1_1[1]) || (g3 ? p0 : 1)) && f0((g6 >> (22)), f0(g2[11], g2[1], 'G'), (8726 * g3))));
    return (g7);
}

int main(void)
{
    int result;
    int m0;
    int m1;
    unsigned long m2;
    struct S0 m3;
    unsigned long m4;
    int m5[13];
    unsigned long m6;
    int * m7;
    result = 0;
    m0 = -45;
    m1 = 85;
    m2 = 1;
    m3.m0 = -38;
    m3.m1 = 0;
    m3.m2 = 6401;
    m3.m3 = -30;
    m3.m4 = 8282;
    m3.m5 = -26;
    m4 = 8515;
    m5[0] = 139;
    m6 = 25;
    m7 = 0;

    result /= (f1((((-48 == 0) || ((int)sizeof(unsigned int) || m1)) - ((-45 ? g5 : 0) || ('*' ? -25 : g1)))) | 1);
    {
        int _w1;
        _w1 = 0;
        while (_w1 < 9) {
            _w1++;
            goto _lbl2;
            _lbl2:
            result *= f1((((int)sizeof(unsigned long) ? g3 : -47) % (f0('+', '7', 8) | 1)));
            m1 %= (f0(((4646 >> (26)), (g1 * g5)), (('3' & 3312) + (g3 ^ "wxyz"[3])), ((m2 && (int)sizeof(long)) | f0((int)sizeof(int), (int)sizeof(char), (int)sizeof(unsigned char)))) | 1);
        }
    }

    result = 0;
    result += (int)(g5);
    result += (int)f1((((int)sizeof(unsigned int) << (5)), (g2[4] ? g3 : "abc123"[3])));
    result += (int)f0((('u' ? g7 : m0) * (m5[6], 28)), ((8796 - result) ? (0 ? (int)sizeof(unsigned char) : result) : ((int)sizeof(unsigned int) != 0)), f0((2657 >> (10)), (221, 57), (g6 > m1)));

    return (result >= 0 ? result : -result) & 255;
}
