/* generated by free-cc */
	.arch armv8-a

	.section .rodata

	.text

	.global main
	.type main, %function
	.p2align 2
main:
	/* prologue */
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	sub sp, sp, #16
	/* addr of local 'x' [fp, #-4] */
	sub x0, x29, #4
	str x0, [sp, #-16]!
	mov x0, #2
	ldr x1, [sp], #16
	str w0, [x1]
	/* addr of local 'x' [fp, #-4] */
	sub x0, x29, #4
	ldrsw x0, [x0]
	mov x9, x0
	cmp x9, #1
	b.eq .L.case.1
	cmp x9, #2
	b.eq .L.case.2
	b .L.case.3
.L.case.1:
	mov x0, #1
	b .L.return.main
.L.case.2:
	mov x0, #42
	b .L.return.main
.L.case.3:
	mov x0, #0
	b .L.return.main
.L.break.0:
.L.return.main:
	/* epilogue */
	mov sp, x29
	ldp x29, x30, [sp], #16
	ret
	.size main, .-main

	.section .note.GNU-stack,"",%progbits
